src/rpmostree-compose-builtin-tree.c
src/rpmostree-treepkgdiff.c
src/rpmostree-treepkgdiff.h

Print goal

---

src/rpmostree-builtin-rebase.c

This is what `upgrade` does.  Otherwise we end up not printing a
newline, and the next line gets glommed on, and we look silly.

rebase: Also end status line after pull is complete

---

src/app/rpmostree-compose-builtin-tree.c

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

compose: honor --proxy again

---

Makefile-tests.am

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

Makefile-tests.am: clean generated files

---

src/app/rpmostree-libbuiltin.c

Fix version number output on upgrade/rollback.

---

src/app/rpmostree-compose-builtin-tree.c

This is being friendly for configuration errors.  The failure mode
here of not finding repos and silently continuing was quite bad.

compose: Error out if specified repositories aren't found

---

src/libpriv/rpmostree-postprocess.c

This should help to generate the same initrd when the files didn't
change.
Newer versions of gzip (or pigz when available) can generate rsync
friendly files and if present, Dracut already takes advantage of it.
Also use --reproducible, to instruct Dracut to generate CPIO
reproducible files.  It is required a version of GNU CPIO that
has support for it.
Check that Dracut has --reproducible in its --help output before
setting it.
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

postprocess: provide --gzip and --reproducible to dracut if supported

---

src/libpriv/rpmostree-postprocess.c

This has been long useless because we now disable history writing in
libhif.

postprocess: Delete dead code relating to yumdb

---

src/app/rpmostree-compose-builtin-tree.c
src/libpriv/rpmostree-hif.c
src/libpriv/rpmostree-hif.h

Two nits noticed in review that I accidentally ignored before pushing.
https://github.com/projectatomic/rpm-ostree/pull/202

Honor --proxy again, tweak internal libhif API

---

doc/treefile.md

Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

There is no support for comps groups at this moment

---

Makefile-tests.am
tests/libtest.sh
tests/setup-session.sh.in

Fix up libtest.sh and add testenv helper

---

src/app/rpmostree-builtin-status.c

A few cherry-picks from my package-layering branch.

Small `rpm-ostree status` output fixups

---

src/app/rpmostree-dbus-helpers.c

libgsystem has long been deprecated, so this is a small step for man,
and not really a gigantic leap at all for anyone but hey, at least I
changed something in git today.

app: Use libglnx console API

---

.cci.jenkinsfile
.papr.yml
ci/msrv.sh

Just split it out into a separate script for easier sharing.

ci: Also bump MSRV to 1.37.0 for CCI Jenkins

---

rust/src/lockfile.rs
rust/src/treefile.rs
rust/src/utils.rs

Fixes #1904
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

rust/lockfile: Add YAML support

---

.papr.yml

It's currently covered by the Jenkins job.

ci/papr: Drop cosa build

---

configure.ac
packaging/rpm-ostree.spec.in

Not the biggest release, but there are some decent targeted fixes and
enhancements and it's been a while.

Release 2019.7

---

.cci.jenkinsfile
rust/Cargo.lock

We haven't done one of these in a while.

rust: cargo update

---

src/libpriv/rpmostree-importer.c
tests/vmcheck/test-layering-basic-1.sh

This way we handle filenames with spaces in `/var` in general,
like `/var/app/foo bar`, but *also* the special `/opt/foo bar`
translation bits.
I saw this bug and thought "oh that'd be easy".  But hoo boy
did it take me down a rat's nest.  The first thing was verifying
that `systemd-tmpfiles` supports any kind of quotation/escaping; it does.
The next thing was figuring out *exactly* what the syntax for that
is and how it works, as it's obviously not widely used.
I debated just using `g_shell_quote()` for this but that *always*
quotes the argument, which is a bit of an eyesore.  So I ended up
changing things so we only do it if necessary.
And then this raised the whole question of *other* characters
beyond spaces, like `"` characters themselves, etc.  It looks
to me like the Rust …

importer: Quote filenames with spaces for tmpfiles.d

---

.cci.jenkinsfile

Noticed in https://github.com/coreos/rpm-ostree/pull/2052#issuecomment-613694719

ci: Actually run kola tests

---

.cci.jenkinsfile

See https://github.com/coreos/coreos-assembler/pull/1379

ci: Explicitly fetch before build

---

Makefile.am
tests/kola/nondestructive/misc.sh
tests/runkola
tests/vmcheck/test-misc-1.sh

A few small testing patches, continuing the momentum to update our test framework to use coreos-assembler.

More kola ext

---

tests/common/libtest.sh

The main goal here is to get `assert_jq()` usable in
kola tests.
This was forked from ostree long ago but we aren't
using most of it.  I want to try to move this into kola where
we're just using `tests/common` but this code references
`tests/gpghome` which we weren't using.
Only a few things here reference `SRCDIR` - change those
to fail for now if it's not set, since we're not running
those tests in kola yet.  I will eventually try to
clean that up later.

tests: Trim out dead code from libtest.sh, rework SRCDIR

---

tests/kola/nondestructive/misc.sh
tests/vmcheck/test-misc-1.sh

tests: Move more code to kola

---

src/libpriv/rpmostree-rojig-build.c

I have no idea why I came up with the previous code instead
of just expanding `%_isa`.  The old code blew up for me
trying to use rojig w/silverblue because of the `abi` in:
```
$ rpm -q --provides gawk | grep \(
gawk(abi) = 3.0
gawk(x86-64) = 5.0.1-5.fc31
$
```
We can definitely assume that we have the same value of `_isa`
at rojig build time as for the target.

rojig-build: Just expand %_isa

---

packaging/rpm-ostree.spec.in

Upstreamed from https://src.fedoraproject.org/rpms/rpm-ostree/c/dea1d3a82f542c4cccff9f2d73ca8c830b99efcb?branch=master.

spec: Disable LTO

---

configure.ac
packaging/rpm-ostree.spec.in

A few goodies, but mostly to get #2221 out.

Release 2020.5

---

src/daemon/rpmostreed-transaction.c

Had this file open for other work, decided to port to new
style on general principle.

transaction: Port to declare-and-initialize style

---

src/app/rpmostree-dbus-helpers.c

Part of looking at
https://bugzilla.redhat.com/show_bug.cgi?id=1865839
https://github.com/coreos/rpm-ostree/pull/2255/
Basically the transaction can be lifecycle bound to the
DBus connection.  We hold that connection open even
after we get a success response and then call back into the
daemon again to do a reload.
Rework the client code here so that all of the txn
stuff is in a method itself, and move the reload outside
of it.  That way the bus connection will have been closed
reliably by autocleanups before we reload.

client: Close DBus connection before calling reload

---

src/daemon/rpmostreed-transaction.c

Today we unlock in the finalize path, which means that
the unlock can be delayed if something is referencing
the gobject for the transaction, even after it's done.
Worse, we do `g_clear_object (&priv->sysroot)` in the dispose
handler which means that if something calls dispose before
the last unref, we will never unlock!
Fix all this by unlocking when the transaction is done
executing.  At that point we aren't going to do any
further modifications, so there's no reason to hold the lock.
This should be much more reliable.
While we're here also track the locked state via an explicit
boolean rather than keying off whether we happen to have
a sysroot object.
Closes: https://github.com/coreos/rpm-ostree/issues/1692

transaction: Unlock more reliably at txn finish

---

src/daemon/rpmostreed-sysroot.c

I suspect that having two DBus connections involved
is part of potential races in
https://bugzilla.redhat.com/show_bug.cgi?id=1865839
https://github.com/coreos/rpm-ostree/pull/2255
Right now the client calls Reload when done - by
having the daemon defer it to an idle, we help ensure
that any other pending events (fd close,
transaction completions) are processed before
we even start the reload.

daemon: Defer reload to an idle

---

configure.ac
packaging/rpm-ostree.spec.in

We have the 32 bit fix, the new initramfs command, and various
other cleanups.  I also want to see if this fixes https://bugzilla.redhat.com/show_bug.cgi?id=1865839
so let's get a release out.

Release 2020.6

---

OWNERS

Add more people from the CoreOS updates&remoting team.

OWNERS: extend/reorder approvers section

---

src/libpriv/rpmostree-scripts.c

Everyone who hits this really just wants to see the GH issue.

scripts: Link to lua issue on error

---

src/app/rpmostree-compose-builtin-tree.c

This allows us to fix RHCOS builds with coreos-assembler
after https://github.com/coreos/coreos-assembler/pull/1800/commits/e76b2701985529334168a64931bba9d9cdde43d1
That broke change detection.
We need to explicitly provide the previous commit.  This is
very similar to `--parent`, and arguably we should
have made `--parent` have change detection semantics too
at the time.

compose: Add --previous-commit

---

.cci.jenkinsfile
configure.ac
packaging/rpm-ostree.spec.in

This mainly has two build-side fixes for coreos-assembler.

Release 2020.8

---

Makefile-libpriv.am
Makefile-rpm-ostree.am
src/app/rpmostree-dbus-helpers.cxx
src/app/rpmostree-dbus-helpers.h
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-importer.c
src/libpriv/rpmostree-postprocess.cxx

I think this is going to work, see https://github.com/coreos/rpm-ostree/pull/2336#issuecomment-739556744

More C++ porting

---

configure.ac
packaging/rpm-ostree.spec.in

A lot of stuff here; new livefs is a big one.  Plus a lot
of internal cleanups, the introduction of C++ and
the 32 bit package script fix etc.

Release 2020.9

---

configure.ac
packaging/rpm-ostree.spec.in

Now should build from vendored sources too!

Release 2020.10

---

Makefile-rpm-ostree.am
src/app/main.cxx

Also here, catch C++ exceptions and convert to GError.

main: Convert to C++

---

Makefile-daemon.am
src/daemon/rpmostree-sysroot-core.cxx
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-os.cxx
src/daemon/rpmostreed-transaction-types.cxx

I'm targeting the files that use `RpmOstreeOrigin`  so I can revive the oxidation code in https://github.com/cgwalters/rpm-ostree/commit/44ace540e901c96382591e14aa3d0f3ba70c103d

More C++, round 3

---

src/app/rpmostree-builtin-ex.c
src/app/rpmostree-builtin-livefs.c
tests/vmcheck/test-livefs.sh

- Rename `ex livefs` to `ex apply-live`
- apply-live: Print a success message

Rename `ex livefs` to `ex apply-live` and print on success

---

rust/src/cxx_bridge_gobject.rs
rust/src/initramfs.rs
rust/src/lib.rs
src/daemon/rpmostree-sysroot-upgrader.cxx
src/libpriv/rpmostree-cxxrs-prelude.h
src/libpriv/rpmostree-util.h

Also adds support for passing through `GCancellable`.

Port initramfs Rust code to cxx-rs

---

rust/src/composepost.rs
rust/src/lib.rs
src/libpriv/rpmostree-postprocess.cxx

Port composepost to cxx-rs

---

rust/src/lib.rs
rust/src/testutils.rs
src/app/rpmostree-builtin-testutils.cxx

Another easy port like cliwrap.

testutils: Port to cxx-rs

---

Cargo.lock
Cargo.toml
rust/src/lib.rs
rust/src/utils.rs
src/app/rpmostree-builtin-shlib-backend.cxx

Prep for other code using memfds.

Add a Rust helper to create a sealed memfd, use in shlib backend

---

mkdocs.yml

Was used for Read the Docs website.

Remove now unused mkdocs.yml

---

rust/src/lib.rs
rust/src/progress.rs
src/app/rpmostree-dbus-helpers.cxx
src/libpriv/rpmostree-output.cxx

Only slightly tricky thing here was double checking which
places pass "optional &str" (represented as empty strings)
and which don't.

rust: Port progress.rs to cxx-rs

---

configure.ac
packaging/rpm-ostree.spec.in

Release 2021.1

---

src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostree-sysroot-upgrader.h
src/daemon/rpmostreed-daemon.cxx
src/daemon/rpmostreed-daemon.h
src/daemon/rpmostreed-transaction-types.cxx
src/daemon/rpmostreed-transaction.cxx
src/daemon/rpmostreed-transaction.h
tests/vmcheck/test-misc-2.sh

daemon: Record agent's systemd service

---

src/app/libmain.cxx

Prep for reworking our binary entrypoint to be Rust and not C++.
We need to split up main into sub-pieces; but before we do
that let's avoid `goto out` and rework into declare-and-initialize
style which cleans things up here.

libmain: Avoid use of goto out

---

src/daemon/rpmostreed-daemon.cxx

Registration through `RegisterClient` is not mandatory today; for
example, Zincati does not register itself. In functions where we
might want to access info about the client, gather that info on
demand if the client is not registered.

daemon/rpmostreed-daemon: Look up systemd unit if caller not registered

---

rust/src/passwd.rs
src/libpriv/rpmostree-postprocess.cxx

Followup to https://github.com/coreos/rpm-ostree/pull/2510.

rust/passwd: minor cleanup, use write_file_with_sync

---

ci/build-check.sh
ci/installdeps.sh

Prep for https://github.com/openshift/release/pull/15461

Two small CI patches

---

src/app/rpmostree-builtin-status.cxx
tests/vmcheck/test-misc-2.sh

If update driver is a service unit, look up its StatusText DBus
property and display it.

app/status: Show update driver's status

---

.cci.jenkinsfile
ci/build.sh
ci/commit-validation.sh

ci: Add a commit validation entrypoint
---
Also export PATH here
Prow job is running this one directly.
We really need to clean this up...

Two more small CI patches

---

Makefile-rpm-ostree.am
Makefile.am

Makefiles: Fix setting of `cargo_target_dir` and some other tweaks

---

src/libpriv/rpmostree-postprocess.cxx

This removes all goto statements in the postprocess module,
replacing them with an exception catcher instead.

libpriv/postprocess: get rid of goto statements

---

docs/compose-server.md
docs/index.md

- Link to osbuild blog
- Drop CentOS 7 stuff
- clarify goals a bit

Misc doc tweaks/cleanups

---

rust/src/lockfile.rs

We should really have safety comments around our use of `.unwrap()`.
This Google kubernetes rpm-md repo appears to use microseconds-since-epoch.
We could try to detect that, probably best done in libdnf.
I think it'd be better to get them to match the informal schema
for this actually though instead.
For now let's just log an error and not crash.
Closes: https://github.com/coreos/rpm-ostree/issues/2600
---

lockfile: Be robust to non-seconds-since-epoch repodata

---

docs/HACKING.md

In particular describe the cxx tools trap.

docs/HACKING.md: Various updates

---

src/daemon/rpmostreed-deployment-utils.cxx

I was looking at a different problem and noticed a spam of
```
Feb 24 23:06:37 cosa-devsh rpm-ostree[1099]: g_variant_dict_ref: assertion 'is_valid_heap_dict (dict)' failed
Feb 24 23:06:37 cosa-devsh rpm-ostree[1099]: g_variant_dict_unref: assertion 'is_valid_heap_dict (dict)' failed
Feb 24 23:06:37 cosa-devsh rpm-ostree[1099]: g_variant_dict_ref: assertion 'is_valid_heap_dict (dict)' failed
Feb 24 23:06:37 cosa-devsh rpm-ostree[1099]: g_variant_dict_unref: assertion 'is_valid_heap_dict (dict)' failed
```
in the journal.  It turns out that the Rust bindings try to call
`g_variant_ref()`, but that's (understandably) not allowed on
a stack allocated instance.
Since we heap allocate a *ton* here, let's just heap allocate
the dict too.
Now, we also along the way stopped using the bits to …

daemon: Heap allocate GVariantDict to pass to Rust

---

tests/vmcheck/test-apply-live.sh

Came up on `#fedora-iot` channel, some people are hitting
"No packages in transaction".  I believe we have a bug,
but I didn't hit it with at least this simple test case.
It may be related to layering while doing this too, going to
test that next.

tests/apply-live: Upgrade+liveapply no-package changes

---

rust/src/cxxrsutil.rs

This generalizes our binding macro, so we can trivially e.g.
add `Variant` into the entry of bound glib types.

cxxrsutil: Generalize cxxrs_bind! macro

---

rust/rpmostree-client/src/lib.rs

Zincati wants this and it's a friendly thing to do.

rust/client: derive(Debug, Clone)

---

rust/src/cliwrap.rs
rust/src/cliwrap/cliutil.rs
rust/src/cliwrap/dracut.rs
rust/src/countme.rs
rust/src/countme/cookie.rs
rust/src/countme/repo.rs
rust/src/history.rs

Explicit sign-off-by from authors:
Signed-off-by: Timothée Ravier <travier@redhat.com>

rust: Relicense some GPL-2.0-or-later to Apache-2.0 OR MIT

---

rust/src/passwd.rs
src/app/rpmostree-compose-builtin-tree.cxx

This contains a couple of minor code cleanups, left over from previous
reviews.

passwd: minor cleanups

---

rust/src/treefile.rs

This tweaks the data and types parsed from `check-passwd` and
`check-groups`, so that it can be more easily iterated and
consumed by passwd-handling logic.

treefile: tweak check-passwd/check-groups data

---

src/libpriv/rpmostree-kernel.cxx

Prep for porting rpmostree-bwrap.cxx to Rust; cxx-rs doesn't
expose passing a function pointer from C++ to Rust.  There's
a simpler API for this anyways.

kernel: Avoid using bwrap child setup

---

.cci.jenkinsfile

Matching https://github.com/coreos/ignition/pull/1182
and discussion in https://github.com/coreos/fedora-coreos-tracker/issues/764

ci: Update to use new buildroot pod

---

rust/src/origin.rs
rust/src/treefile.rs

There's a lot more of this in the code, just decided to do a little
bit more in treefile.rs mostly.

rust: More usage of indoc

---

docs/architecture-daemon.md

To help new contributors trying to understand how it all fits together.

docs: Add page about the daemon interface

---

rust/src/cxxrsutil.rs
rust/src/passwd.rs

This updates all bridged functions in order to return CxxResult in
a uniform way.

passwd: align all bridged functions to return CxxResult

---

ci/prow/Dockerfile

ci/prow: Update to use new buildroot image

---

rust/src/composepost.rs

This aligns the result types and visibility for all post-processing
functions that are bridged to C++.

composepost: uniform results and visibility for cxxbridge

---

rust/src/treefile.rs
src/app/rpmostree-composeutil.cxx

More prep for removing treespec.

compose: Move repos/lockfile-repos validation to Rust

---

rust/src/composepost.rs

`syncfs()` isn't going to do anything on e.g. `tmpfs` and even
if it did wouldn't fix any race conditions because that's about
synchronizing in memory changes to disk, but won't change
what system calls return.
Some investigation turned up
https://stackoverflow.com/questions/14392975/timestamp-accuracy-on-ext4-sub-millsecond
and `current_fs_time` is now:
https://www.kernel.org/doc/html/v5.12/core-api/timekeeping.html
Basically there's a "coarse" time that might only update once every 10ms
for example.
Let's just sleep 100ms for now.
I think we should be using the inode versions, but we can investigate
that separately.

composepost: Fix race condition in timestamp checking

---

tests/vmcheck/test-misc-2.sh
tests/vmcheck/test-override-kernel.sh

This adds support for Fedora 34.

tests/override-kernel: add f34 kernel

---

rust/src/treefile.rs

This isn't important at all, but I am just trying to up my
"Rust iterator and mapping" skills.  Here:
- In this case we always want to go from `Option<Some(T)>` to `Option<Some(T)>`,
so instead of destructuring `Some()` back to another `Some()`
we can use `as_mut()` to manipulate the inner vector directly.
- Now instead of destroying the inner `Vec<>` we need to use `drain()`
instead
- And then we can just `extend()` with a reversed iterator from
our explicit temporary

treefile: Minor cleanup of handle_repo_packages_overrides()

---

src/app/rpmostree-builtin-kargs.cxx
src/daemon/rpmostreed-transaction-types.cxx
tests/vmcheck/test-kernel-args.sh

The new switch will rise an exit code 77 if kernel args are unchanged 

kargs: Add CLI switch --unchanged-exit-77

---

.cci.jenkinsfile
docs/CONTRIBUTING.md
docs/administrator-handbook.md
tests/common/libtest.cxx
tests/common/libtest.h

To apply on top of https://github.com/coreos/rpm-ostree/pull/2815
Hold until cutover.

*: rename master branch to main (for external projects)

---

src/libpriv/rpmostree-importer.cxx

This reworks the special-case handling of `/var/lib/rpm`, in order
to make it uniform across codepaths and outside of auto-tmpfiles logic.
It prepares for further oxidation and auto-tmpfiles codepaths unification.

importer: align /var/lib/rpm handling

---

man/rpm-ostree.xml

man/rpm-ostree: Document `install --idempotent`

---

src/libpriv/rpmostree-importer.cxx

This was only used for the code that was removed in
https://github.com/coreos/rpm-ostree/pull/2344 and
https://github.com/coreos/rpm-ostree/pull/2410

importer: Remove traces of unprivileged import

---

packaging/rpm-ostree.spec.in

This contains minor cleanups to re-sync with Fedora and CentOS.

packaging/spec: misc cleanups

---

docs/HACKING.md
rust/src/main.rs

This should be helpful to new contributors.

HACKING: Add section about using GDB with rpm-ostree

---

tests/compose/test-installroot.sh

osbuild is hitting issues where `/var/lib/rpm` is showing
up in the target ostree commit.  I am not reproducing it
right now, but let's validate it isn't happening in our CI.
Also while we're here, add a check that we're not using fuse
for `/var/tmp` (as happens in `toolbox` by default) because
that breaks us trying to set `security.selinux` xattrs.

test-installroot: Validate we don't have /var/lib/rpm

---

rust/rpmostree-client/src/lib.rs
rust/src/bwrap.rs
rust/src/composepost.rs
rust/src/main.rs
rust/src/passwd.rs
rust/src/treefile.rs

Will try to add clippy to main CI at some point, but it's
entangled with the buildroot.

rust: Fix misc clippy lints

---

rust/src/composepost.rs

This tweaks the macro injection logic (newline ending, umask hardening)
and adds basic tests for it.

composepost: minor cleanups and tests for dbpath macro injection

---

configure.ac
packaging/rpm-ostree.spec.in

No major new (stable) features, but some notable fixes around dbpath,
openssl 3.0 compat, etc.

Release 2021.6

---

src/libpriv/rpmostree-importer.cxx

This adds some comments and notes to clarify the semantics of
internal data structures. It also adds a few assertions matching
those properties.

libpriv/importer: clarify semantics of some internal structures

---

src/libpriv/rpmostree-core.cxx

The `rpmostree_context_assemble` function is huge.  Factor
out the rpmdb writing in prep for further work.

core: Factor out rpmdb writing function

---

src/app/rpmostree-compose-builtin-tree.cxx

To help debug https://github.com/openshift/os/issues/594

compose: Add error prefixing for local pull

---

rust/src/daemon.rs
rust/src/live.rs
rust/src/modularity.rs
rust/src/utils.rs
rust/src/variant_utils.rs

From here on let's try to submit PRs for any APIs we need.

rust: Almost entirely empty out our variant_utils.rs

---

rust/src/client.rs
rust/src/lib.rs
src/app/rpmostree-clientlib.cxx

This progresses general oxidation.  But the main goal here
is actually to have this be an API callable from the daemon
side too.

Oxidize transaction progress rendering

---

rust/src/client.rs
rust/src/lib.rs
src/app/rpmostree-override-builtins.cxx
src/daemon/org.projectatomic.rpmostree1.xml
src/daemon/rpmostreed-os-experimental.cxx
tests/kolainst/destructive/override-pinning
tests/kolainst/kolainst-build.sh

override replace query enabled repost for the lastest version

override replace: fetch from enabled repos

---

src/daemon/rpmostreed-transaction.cxx

This week I don't have a real Internet connection at my house,
so I'm tethering through my phone which is now data capped at 128k/s.
I was noticing that FCOS upgrades are...slow.  And the thing is,
zincati doesn't display the download progress from the CLI, and neither does
the daemon anywhere in `rpm-ostree status`.
So I initially spent some time debugging thinking things were
stuck, but it was actually just slow downloading.
For now, let's log the transaction progress periodically
to the journal.
A next step will be rendering this in `rpm-ostree status` too.
---

daemon: Emit transaction progress to journal every 15s (if changed)

---

configure.ac
packaging/rpm-ostree.spec.in

Time for a new release, lots of stuff here.

Release 2021.8

---

rust/rpmostree-client/src/lib.rs
rust/src/composepost.rs
rust/src/daemon.rs
rust/src/lib.rs
rust/src/origin.rs
rust/src/passwd.rs
rust/src/utils.rs

There's a ton here, so we need to be incremental.

rust: Fix some clippy lints

---

configure.ac
packaging/rpm-ostree.spec.in

A few fixes, but mainly want to get the new ostree-container
code out.

Release 2021.11

---

docs/architecture-daemon.md

docs: fix hyperlinks in architecture-daemon.md

---

rust/src/normalization.rs

Procedural note: Since you wrote all of this nice code, and all I am doing is a minor shuffling around, I went ahead and listed you as patch author, and me as `Co-authored-by` - that way credit (and blame :grin: ) in `git annotate` still points to you.
---
The normalization code is deeply nested, and I think having
separate functions helps readability and manage complexity.
A key bit in this code motion is we can drop the "bare open block"
(i.e. the `{ ... }` on its own}) which is currently ensuring all
I/O is complete before we recompute the checksum.
Co-authored-by: Colin Walters <walters@verbum.org>

normalization: Factor out core loop code into function

---

rust/src/main.rs

I realized after submitting the PR yesterday it's silly
to copy the arguments twice.

main: Remove pointless copy of arguments

---

docs/container.md
docs/experimental.md

docs: Add docs for `ex-container`

---

configure.ac
packaging/rpm-ostree.spec.in

Various bugfixes, a few important, plus the major container
update.

Release 2021.14

---

man/rpm-ostree.xml

man/rpm-ostree: update docs for kargs and override parameters

---

rust/src/main.rs

This adds the initial logic for detecting and dispatching multicall
execution through specific `argv[0]` callnames.
It is primarily meant to support `ostree` CLI extensions, and
currently it re-exports ostree-rs-ext container logic in that way.
Ref: https://github.com/ostreedev/ostree/issues/2480
Closes: https://github.com/coreos/rpm-ostree/issues/3277

main: add support for multicall binaries

---

Cargo.lock
rust/src/client.rs
rust/src/lib.rs
src/app/libmain.cxx
src/app/rpmostree-pkg-builtins.cxx

Depends on: https://github.com/ostreedev/ostree-rs-ext/pull/193

rust/src/client: check for ostree structure using ostree_ext api

---

src/daemon/rpmostreed-os-experimental.cxx

This drops a bunch of goto codepaths from the DBus live-fs handler.

dbus/live-fs: remove some goto statements

---

src/daemon/rpmostreed-os.cxx

This drops a bunch of goto codepaths from the `GetCachedDeployRpmDiff`
DBus handler.

dbus: remove some goto statements

---

docs/layering.md

Using the FCOS tutorial as base, this document should guide someone through the steps of using the new layering feature of rpm-ostree.

docs/layering: Tutorial on using the rpm-ostree layering feature

---

src/libpriv/rpmostree-core.cxx

I am hitting a strange issue in coreos-assembler when trying to use
`overrides/rpm`; it generates a lockfile, but then `cosa build`
fails to find the RPM that's clearly there.
Let's print out other packages which match the name and arch.
I don't know what the bug is yet, but this already helped me
debug that the problem is we're somehow missing the overrides
rpm-md repo.

core: When we fail to find a locked package, also print non-matches

---

rust/src/composepost.rs
rust/src/extensions.rs
rust/src/lib.rs
rust/src/passwd.rs
rust/src/treefile.rs
src/libpriv/rpmostree-core-private.h
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h
tests/compose/test-basic-unified.sh

Split out of #3340. See individual commit messages.

Prep patches for #3340

---

rust/src/lib.rs
rust/src/treefile.rs
src/libpriv/rpmostree-core.cxx

More prep patches from #3340

---

docs/administrator-handbook.md

I would swear, *swear* we had this before but...apparently not.

docs: Give a kernel override example too

---

src/daemon/org.projectatomic.rpmostree1.xml

This is required for introspection for zbus-xmlgen:
https://crates.io/crates/zbus_xmlgen

src/daemon: Exhaustively set arg direction for DBus interface

---

rust/src/daemon.rs
rust/src/fstype.rs

fstype: Add license identifier
I really should have actually looked at CI.
---
daemon: Drop unused import
---

Two small patches

---

rust/src/composepost.rs

Bump to cap-std-ext 0.23.1
The `ensure_dir_with` API is now there.
---
Use direct `Permissions::from_mode` API
I may have missed that this existed, or it's new.  Either way,
no need for a helper.
---
postprocess: A bit more porting to `cap_std`
One notable change here is I changed a few paths to be absolute
(relative to the dirfd) because we can now do so safely and not need
to be paranoid about a leading `/`.
---

postprocess: A bit more porting to `cap_std`

---

rust/src/daemon.rs
rust/src/treefile.rs

Split out of https://github.com/coreos/rpm-ostree/pull/3439

Prep patches for conditional include

---

docs/layering.md

Rather than hardcoding a release, script downloading from the next fcos
stream

docs/layering.md: script using next fcos stream

---

configure.ac
packaging/rpm-ostree.spec.in

Various smaller bugfixes and enhancements.

Release 2022.3

---

configure.ac
packaging/rpm-ostree.spec.in

For https://github.com/coreos/rpm-ostree/issues/3486 and
https://github.com/coreos/rpm-ostree/issues/3487.

Release 2022.5

---

src/daemon/rpmostreed-utils.cxx

This drops a bunch of needless `goto` statements; they did not perform
any additional cleanup/action. The exit code is now directly returned
in the spot where an error happens.

daemon/utils: avoid superfluous gotos

---

rust/src/daemon.rs

Followup from code review on previous PR.
No particular strong reason, I just have slowly gained better
Rust iterator-fu and like to use it =)

daemon/sysroot: Use iterators more

---

src/daemon/rpmostreed-os.cxx

This drops a bunch of goto codepaths from the DBus RPM diff
handlers.

daemon/dbus/os: remove some goto statements

---

rust/src/extensions.rs

Might be nice to add `read_to_string_optional()` to cap-std-ext too.

extensions: Port to cap-std

---

rust/src/core.rs
rust/src/lib.rs
rust/src/origin.rs
rust/src/utils.rs
src/app/rpmostree-builtin-rebase.cxx
src/app/rpmostree-builtin-status.cxx
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h
src/libpriv/rpmostree-origin.cxx
src/libpriv/rpmostree-origin.h

RpmOstreeOrigin thinning prep patches

---

rust/src/bwrap.rs
rust/src/daemon.rs
rust/src/extensions.rs
rust/src/rpmutils.rs
rust/src/treefile.rs
src/libpriv/rpmostree-origin.cxx
src/libpriv/rpmostree-origin.h

Split out of https://github.com/coreos/rpm-ostree/pull/3545. See individual commit messages.

Prep patches for #3545

---

rust/src/core.rs

Basically stuff that came up in PR review.
Mostly by requiring UTF-8, we can use APIs like `split_once`,
remove the error path conversion to UTF-8, etc.

core: Minor cleanups for kernel hmac bits

---

.github/workflows/container.yaml

Per discussion it's not legacy.

ci: Rename some of the GH actions

---

src/app/rpmostree-clientlib.cxx

This adds auto-cleanup implementation on `TransactionProgress`, in
order to drop a couple of goto statements from clientlib logic.

app: implement auto-cleanup for TransactionProgress

---

src/libpriv/rpmostree-editor.cxx

This tweaks the editor-prompting logic to avoid goto statements
and to simplify error handling.
Unfortunately a `GLnxTmpfile` with auto-cleanup cannot be directly
used here due to the file access pattern (by path). Thus we keep
using the existing plain `GFile` with manual deletion for now.

libpriv/editor: rework error handling to avoid goto statements

---

src/daemon/rpmostreed-sysroot.cxx

This reworks several error handlers which are more complex than
actually needed. In all these case, the goto statements can be
dropped and replaced by linear logic instead.

daemon: simplify some error cases

---

src/daemon/rpmostreed-sysroot.cxx

This drops a bunch of goto codepaths from the DBus ReloadConfig
handler.

daemon/dbus: remove some goto statements

---

configure.ac
packaging/rpm-ostree.spec.in

Colin Walters (2):
Downgrade tracing-subscriber to 0.3.9
Release 2022.7
Luca BRUNO (1):
daemon/dbus: remove some goto statements

Release 2022.7

---

src/daemon/rpmostreed-os.cxx

This reworks error handling for several DBus methods.
Those methods do operate on a transaction-based mechanism, with
support for detecting/merging existing transactions.
The transaction-detection logic was intermixed with error-handling
code, and the whole implemented via goto statements.
This untangles the code by tackling the error-handling side,
reworking it to avoid goto jumps in the error cases.

daemon/dbus: split apart error handling and transaction detection

---

src/daemon/rpmostreed-os.cxx

This tweaks the transactions detection/creation code, so that it
uses plain conditional logic instead of goto statements.

daemon/dbus: rework transactions detection and creation

---

src/app/rpmostree-clientlib.cxx

This drops one goto codepath from the transaction handler.

app/clientlib: remove one goto statement

---

rust/src/sysroot_upgrade.rs

This rolls in all the fixes in 0.7.1, and wires up the progress
notifications for layers.

Update to ostree-ext 0.7.1, add container progress notifications

---

ci/testdeps.txt
tests/compose/test-ima.sh

This verifies that we at least make it as far as having the xattr
in the ostree.

tests: Add a compose IMA test

---

rust/src/history.rs

history: Port to cap-std

---

rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-builtin-override.cxx
src/app/rpmostree-override-builtins.cxx
src/libpriv/rpmostree-core.cxx

Prep patches from https://github.com/coreos/rpm-ostree/pull/3670

---

src/daemon/rpmostreed-deployment-utils.cxx

The Rust bridging code wants to take a reference to the vdict, which
is not possible with a stack allocated vdict.
Switch to heap allocation.
I think actually it would be possible for us *not* to take a reference
here but let's do the safe fix for now.
Closes: https://github.com/coreos/rpm-ostree/issues/3655

daemon: Fix passing stack allocated vdict to Rust

---

tests/compose.sh

tests/compose: Bump FCOS commit to latest

---

src/app/rpmostree-compose-builtin-tree.cxx

This pairs with https://github.com/coreos/coreos-assembler/pull/2889
If fsync is disabled on our target repository, take that as a hint
we should not care about durability for our cache repositories either.

compose: Disable fsync on cache repositories if it's disabled on target

---

Cargo.toml
rust/libdnf-sys/Cargo.toml
rust/rpmostree-client/Cargo.toml
rust/src/bwrap.rs
rust/src/composepost.rs
rust/src/container.rs
rust/src/core.rs
rust/src/dirdiff.rs
rust/src/initramfs.rs
rust/src/lockfile.rs
rust/src/normalization.rs
rust/src/sysroot_upgrade.rs
rust/src/treefile.rs

rust: Switch to 2021 edition

---

src/libpriv/rpmostree-util.cxx
src/libpriv/rpmostree-util.h

I was looking at this file and noticed these APIs were unused.

util: Delete some dead code

---

rust/src/importer.rs

I just think this is a bit more elegant.

importer: Use a more functional-style fold

---

ci/installdeps.sh

To pull in a fix for a clap breakage.

ci: Use my branch of cxxbridge-cmd

---

rust/src/composepost.rs

`set_error_if_cancelled()` is the API to do this.

composepost: Minor cleanup for cancellation

---

src/app/rpmostree-builtin-kargs.cxx

Make `rpm-ostree kargs` like the others and use
`rpmostree_transaction_client_run` to complete the transaction.
This fixes a bug at the same time: if `--reboot` is used, we don't want
to e.g. query the daemon or we'll risk racing with it shutting down.
This in turn can cause unsightly assertion errors as the machine goes
down.
It also fixes minor UX issues like not printing the reboot hint when we
are in fact rebooting.
Reported-by: Dusty Mabe <dusty@dustymabe.com>

app/kargs: Use common function to run transaction

---

configure.ac
packaging/rpm-ostree.spec.in

Mainly I really want to get the new chunked image support
that landed in ostree-rs-ext out, but we have quite a lot here
and I think it's time!

Release 2022.11

---

src/app/rpmostree-polkit-agent.cxx

We don't want to have a hard dependency on polkit.  Some read-only DBus
APIs (e.g. `rpm-ostree status`) can be invoked unprivileged.
xref https://bugzilla.redhat.com/show_bug.cgi?id=2105405

polkit-agent: Don't print a warning if not installed

---

rust/src/treefile.rs

For use in hashing fixes, xref https://github.com/coreos/rpm-ostree/pull/3887

treefile: `#[derive(Clone)]`

---

rust/src/treefile.rs

fixes: https://github.com/coreos/rpm-ostree/issues/3796
Did string manipulation after serializing to json string. The manipulation involves modifying json value of the field ostree_layers to None.
There are several other possible methods to solve this issue:
1) Get the treefile as a mutable in the `fn get_checksum` args and replace the value of treefile.base.ostree_layers with empty string. Then hash it to get a checksum without names of layers. Then replace the empty string back with the ostree_layers stored in a separate variable. 
2) Create a entirely new struct which is identical to BaseComposeConfigFields but does not have a ostree_layer field in it. Then use a function to switch between the both structs types.  
I found string manipulation to be the least disruptive as it would not …

treefile: Exclude ostree_layer_names from checksum 

---

rust/src/cliwrap/yumdnf.rs

This is intended to pair with
https://github.com/coreos/rpm-ostree/pull/3886
which is adding a `yum image` command.  The way we were
previously intercepting `--help` and writing a generic message
breaks the user experience.
Just let the clap parser output an error message for unknown options
itself.

yumdnf: Remove interception of --help and --version

---

docs/container.md

Writing this now, I think it's really obvious we do want
`rpm-ostree compose container`.  But let's at least talk
about the `container-encapsulate` bits here too.

docs/container: Talk about `compose container-encapsulate`

---

rust/src/bwrap.rs
rust/src/composepost.rs
rust/src/normalization.rs

Part of https://github.com/coreos/rpm-ostree/issues/3832

rust/bwrap: Use cap-std

---

rust/src/main.rs

Fixes: https://github.com/coreos/rpm-ostree/pull/3904/commits/60c8facfda1f79744a6a570613828772a7f93d93
We changed the method to be non-async (mostly) so it needs to run
from the worker thread.  There's a bit of the code which does
run async using `block_on` and we can only do that from the worker
thread.
Closes: https://github.com/coreos/rpm-ostree/issues/3968

Fix tokio panic in legacy `rpm-ostree container-encapsulate` path

---

configure.ac
packaging/rpm-ostree.spec.in

A lot of stuff here; stabilized apply-live, various container
enhancements, etc.

Release 2022.13

---

rust/src/container.rs

It turns out the part that's really slow right now is that RPM
apparently walks the entire database to implement "find the package
owning /usr/bin/foo".  What we need to do is build up this mapping
as part of the build process, and dump it out to a lookaside
file (e.g. `rpm-ostree compose tree --write-owners-file=foo.db`)
and then have the encapsulation code pick it up.
Alternatively, we could change the encapsulation code to walk
all RPMs, but eh.

container: Add progress spinners to `compose container-encapsulate`

---

rust/src/treefile.rs

I was going to look at using `metadata` in coreos-assembler
and realized that if we want it to be a generic store, we
really need to ignore changes to it for our purposes.
External users will need to parse it on their own for change
detection.

build: Ignore changes to `metadata`

---

rust/src/cliwrap/yumdnf.rs
tests/kolainst/destructive/cliwrap

Let's also expose this functionality in a clear way.

cliwrap/yumdnf: Add `dnf image apply-live`

---

rust/src/treefile.rs

I keep forgetting to manually update the merge function after adding a treefile field.

treefile: Merge metadata field

---

rust/src/compose.rs

It's going to be really useful in general to see diffs across builds. This also highlights the advantage of the reproducible chunked layers we have.
Since we already fetched the previous image, print out a diff of the size.

compose-image: Print diff of layers

---

docs/ex-rebuild.md
docs/experimental.md

I went to use this and had to read some of the test suite code to remember how it works.  Time to document it - we need to do better about this type of thing.

docs/experimental: Describe `ex rebuild`

---

rust/src/cliwrap/kernel_install.rs

This fixes kernel overrides in rhel8 at least, xref https://bugzilla.redhat.com/show_bug.cgi?id=2122299
We really need to unify the c++/rust code here.

cliwrap: Also inject /dev/random into cliwrap'd dracut

---

rust/src/composepost.rs
tests/compose/test-installroot.sh

This pairs with
https://github.com/ostreedev/ostree/pull/2722/commits/0085494e350c72599fc5c0e00422885d80b3c660
Basically, while I think it'd make sense actually for the baseline `ostree commit` process to handle this, for now let's put it here in rpm-ostree (where it can be in Rust too).  Though a definite negative is that we're now traversing the whole filesystem again.

compose: Handle embedded whiteouts

---

rust/src/composepost.rs
tests/compose/test-installroot.sh

Cherry picks to rhel8 branch:
- compose: Handle embedded whiteouts

[rhel8]  compose: Handle embedded whiteouts

---

docs/architecture-core.md

We have a lot of documentation gaps here.

architecture: Document /var

---

configure.ac
packaging/rpm-ostree.spec.in

I mainly want to get the "useradd in container" changes and the fix for unauth containers out.

Release 2022.15

---

.github/workflows/ci.yaml
tests/encapsulate.sh

Move to new official location.

ci: Fix references to old FCOS location

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/lib.rs
rust/src/sysroot_upgrade.rs
src/daemon/rpmostreed-deployment-utils.cxx
tests/kolainst/destructive/container-image

Kind of embarrassing we didn't do this yet.  I hit this while working on adapting zincati to update from containers.

Add version to status even for containers

---

Cargo.lock
Cargo.toml

Aiming to drop the experimental bits from containers soon.

Update to ostree-ext 0.9

---

docs/container.md

There's a whole lot of other stuff to fill out, but let's start.

docs/container: Flesh out a bit more and tweak

---

docs/container.md

I think this does need to be spelled out.

docs/container: Explain you can upgrade too

---

rust/src/composepost.rs

composepost: Port a few bits to cap-std

---

rust/src/composepost.rs

composepost: Port directory size computation to cap-std
Prep for dropping `openat`.
---
composepost: Port altfiles mutation to cap-std
Prep for dropping `openat`.
---

Two more cap-std porting patches

---

rust/src/composepost.rs

Part of porting away from `openat`.

composepost: Port symlink generation to cap-std

---

rust/src/composepost.rs

Regression from cap-std porting around absolute symlinks *again*. The `try_exists()` API will follow symlinks, which is not what we want here.
This was hit in the fedora-iot builds.

composepost: Handle existing absolute symlinks

---

rust/src/composepost.rs

Part of moving away from `openat`.

composepost: Port rpmdb hardlinking to cap-std

---

.github/workflows/ci.yaml
.github/workflows/scorecard.yml

ci: Update to checkout@v3
v2 is being deprecated.
---
Add OSSF Scorecard workflow
More info at https://github.com/marketplace/actions/ossf-scorecard-action
---
Switch to upload-artifact@v3
To quiet deprecation warnings.
---

A few CI updates

---

configure.ac

Release 2022.18

---

man/rpm-ostree.xml

docs/rebase: Document rebasing to a container image

---

src/app/rpmostree-clientlib.cxx

The default 25 second timeout is too easy to hit on heavily loaded systems.  We've hit many variants of this;
https://github.com/coreos/rpm-ostree/pull/3905/commits/55445ba0d0fa8bdd7b4249d85b084bb6e8658b8c has more links for example.

client: Bump most dbus method timeouts to 5 minutes

---

rust/src/passwd.rs

This helps debug https://github.com/coreos/rpm-ostree/issues/4244

passwd: Add various error prefixing

---

src/libpriv/rpmostree-core.cxx

To help debug https://github.com/coreos/rpm-ostree/issues/4029

core: Add some more debugging and error info around repos

---

tests/common/libvm.sh

One of those super clear examples of software maintenance being 80% of the work...

ci: Stop using Fedora 32

---

configure.ac
packaging/rpm-ostree.spec.in

Release 2023.2

---

rust/src/console_progress.rs

To debug https://github.com/coreos/rpm-ostree/issues/4284

console: Also print which task is being overwritten

---

configure.ac
packaging/rpm-ostree.spec.in

Release 2023.3

---

configure.ac
packaging/rpm-ostree.spec.in

Particularly to get the fix for https://github.com/coreos/rpm-ostree/issues/4284 out.

Release 2023.4

---

src/daemon/rpmostreed-sysroot.cxx

This is a first step towards fixing
https://github.com/coreos/rpm-ostree/issues/4415
because then in a future change we can make `RegisterClient` carry additional data that says the caller will pass the interactive auth flag correctly.
It doesn't ever make sense to prompt for this specific API.

daemon: Never do interactive auth for RegisterClient

---

rust/src/compose.rs

The keys are now under `ex-integrity`, and we can just propagate the whole group.

compose: Adapt to composefs change with `ex-integrity` group

---

rust/src/container.rs

We got a bare
```
error: Invalid checksum of length 0 expected 32
```
in a bug report; this will help narrow it down very slightly, whether the problem is the commit object filename or something in the pull.

deploy-from-self: Add some error prefixing

---

configure.ac
packaging/rpm-ostree.spec.in

Release 2023.5

---

configure.ac
packaging/rpm-ostree.spec.in

Release 2023.6

---

src/daemon/rpmostreed-os.cxx

daemon/search: Fix memory leaks

---

ci/test-container.sh

maybe this will last longer...

ci: update ignition on test-container test

---

rust/src/scripts.rs

Like the others.
cc https://github.com/openshift/os/pull/1351#issuecomment-1709131706

scripts: Also ignore kernel-64k scripts

---

docs/bootc.md
docs/experimental.md

Let's document the state of this.

docs: Add bootc

---

Cargo.lock

Update to ostree-ext 0.12.2

---

configure.ac

We have a decent set of stuff accumulated and I think we're in a stable state.

Release 2023.8

---

packaging/rpm-ostree.spec.in

https://issues.redhat.com/browse/RHEL-2243

packaging/rpm-ostree: update python3 macros and builddep

---

docs/administrator-handbook.md

Came up in https://github.com/coreos/fedora-coreos-tracker/issues/1591.

docs/handbook: Add more details about inactive overrides

---

Cargo.lock

Bump to ostree-ext 0.12.3

---

configure.ac
packaging/rpm-ostree.spec.in

A variety of accumulated fixes and improvements.

Release 2023.9

---

configure.ac
packaging/rpm-ostree.spec.in

Release 2023.10

---

src/daemon/rpmostreed-deployment-utils.cxx
src/libpriv/rpmostree-util.cxx

Motivated by seeing a recent issue around the base commit being pruned.

daemon: Add a bit more error prefixing

---

tests/vmcheck/test-misc-2.sh

Update the checking log refer to
https://github.com/ostreedev/ostree/commit/28cc761806e1c87f106c82cc08cbf0dab30344b6.

test-misc-2.sh: update checking log

---

.cci.jenkinsfile
tests/kolainst/destructive/client-layering-upgrade

Xerf to Jonathan's comment https://github.com/coreos/rpm-ostree/pull/4806#discussion_r1474979226

tests: minor fix for `client-layering-upgrade`

---

configure.ac
packaging/rpm-ostree.spec.in

I want to get the `opt-usrlocal` bits out.

Release 2024.4

---

tests/vmcheck/test-initramfs.sh
tests/vmcheck/test-kernel-args.sh

Xerf https://github.com/ostreedev/ostree/pull/3206

ci: sync tests with bootloader naming

---

rust/src/container.rs

I hit this panic; let's check before we do any processing.

container: Check that we found packages

---

docs/HACKING.md

Use patch as recommended in the documentation.

docs/HACKING: Update crate patching example

---

tests/kolainst/destructive/container-image

See the change https://github.com/coreos/coreos-assembler/pull/3888

test: update kolet path to `/usr/local/bin`

---

docs/architecture-daemon.md

Commit 456405e90bed2a875a56dfc3ac51c64aafaab75e renamed `rpm-ostreed.service.in` to be `rpm-ostreed.service`. This PR adjusts sources to changes.

docs: update `rpm-ostreed.service` reference

---

docs/administrator-handbook.md

I thought we had this documented somewhere already but it doesn't seem like it. This came up again recently, so let's cover it.

docs/administrator: document `status --json` and requested packages

---

Cargo.lock

This fixes several notable bugs.

Update ostree-ext to 0.15.3

---

packaging/rpm-ostree.spec

bootc is merging with ostree-ext which we depend on let's start preparing packaging for this long term change

packaging: Require bootc

---

src/libpriv/rpmostree-core.cxx

The filesystem package in Fedora is *absoulutely* insane; it basically reimplements itself in lua because it can't rely on being first in the transaction, when it'd be infinitely saner to just define it to be first (via a metadata flag, whatever).
Anyways...because we don't run that lua code, and for probably even crazier upgrade reasons the sbin link is only made in lua, detect when the package has the provides, and create the link.
Now that I think about it we probably never needed the provides, and we could have just unconditionally made the link if it wasn't already a directory.
But anyways, using the provides seems cleaner and scopes the blast radius down a bit.
xref: https://gitlab.com/fedora/bootc/tracker/-/issues/29

core: Create usr/sbin -> bin if we detect merged sbin filesystem

---

.github/workflows/ci.yaml
docs/experimental-build-chunked-oci.md
docs/experimental.md
rust/src/cli_experimental.rs
rust/src/compose.rs
rust/src/container.rs
tests/build-chunked-oci/Containerfile

Closes: https://github.com/coreos/rpm-ostree/issues/5221

experimental: Add build-chunked-oci

---

rust/src/compose.rs

For some reason I don't understand at all, there's a race condition in this code where *sometimes* the permissions of the temporary root are 0777 when they should be 0755. Digging in only slightly I think this may actually be a refcounting bug in the `CANONICAL_PERMISSIONS` code in ostree?
But anyways, we expect most people to use sensible mode bits so let's start out with mode 0755 in a `root` directory in the tempdir.

tests/compose: Canonicalize perms for root

---

rust/src/kernel_install.rs

when replacing the kernel packages using rpm-ostree but with the layout in /usr/lib/kernel/install.conf set to ostree we need to check for a wrapped systemd before calling dracut to get the correct modules in the initramfs.
When rpm-ostree kernel-install is called from dnf or rpm we don't wrap before running scripts so we were ok in that path.
Fixes https://github.com/coreos/fedora-coreos-tracker/issues/1870

kernel_install: unwrap systemd if it's wrapped

---

rust/src/treefile.rs

treefile: Add error context for finalize.d

---

docs/build-chunked-oci.md
docs/container.md

Signed-off-by: John Eckersberg <jeckersb@redhat.com>

docs: expand on chunked images

---

.github/workflows/ci.yaml
deny.toml

Update the cargo-deny-action and allow the license used by the systemd create which triggers with the new action.

ci: Update the cargo-deny-action

---

rust/src/composepost.rs

When updating the file_contexts.subs_dist file with some selinux policy workarounds, don't hardcode the "targeted" policy, but instead read the current policy from /etc/selinux/config.
Fixes https://github.com/coreos/rpm-ostree/issues/5381

postprocess: Don't hardcode "targeted" policy

---

docs/container.md

For use cases that want to go containers, but still use ostree on the wire for static deltas.

docs: Describe how to map container -> ostree

---

.gemini/config.yaml

Created by [GitHub workflow](https://github.com/coreos/repo-templates/actions/workflows/sync.yml) ([source](https://github.com/coreos/repo-templates/blob/main/.github/workflows/sync.yml)).
Sync with coreos/repo-templates@49a2f429d118f0eeca4965d11922bbe74dd7b56e.

Sync repo templates ⚙

---

rust/src/compose.rs
tests/build-chunked-oci/test.sh

This inspects the --output image to see if all layers (except the first) have the ostree.components annotation. If they do, pass the existing output image's manifest to the rechunker to reuse its layers. This avoids change cascading when there are minimal changes to the new image.
fixes #5302

rechunk: Use previous-build-manifest if output image is chunked

---

docs/build-chunked-oci.md

Some docs and a test to validate the docs are correct. Also refactored the tests a bit to share code.

Docs for new rechunker features and a test for recursively setting user.component xattr
