src/libpriv/rpmostree-scripts.cxx

The scriptlet in glibc adds a dependency on bash to glibc-common, which
is required by glibc, so effectively the whole world depends on bash.
I want to rewrite the script in lua to drop this dependency.
Quoting https://bugzilla.redhat.com/show_bug.cgi?id=2018913#c34:
```
warning: SCC #1: 5 members (5 external dependencies)
warning: 	glibc-2.35-2.fc37.x86_64
warning: 		-> glibc-minimal-langpack-2.35-2.fc37.x86_64
warning: 		-> glibc-common-2.35-2.fc37.x86_64
warning: 	ncurses-libs-6.2-9.20210508.fc36.x86_64
warning: 		-> glibc-2.35-2.fc37.x86_64
warning: 	bash-5.1.16-2.fc36.x86_64
warning: 		-> ncurses-libs-6.2-9.20210508.fc36.x86_64
warning: 		-> glibc-2.35-2.fc37.x86_64
warning: 	glibc-common-2.35-2.fc37.x86_64
warning: 		-> glibc-2.35-2.fc37.x86_64
warning: 		-> …
```

scripts: add replacements scripts for /sbin/ldconfig calls in glibc-common

---

rust/src/treefile.rs

Just like all the other options in the tree.
Otherwise this throws off the `error_if_base` check.

treefile: Skip serializing `container-cmd` if None

---

docs/treefile.md
rust/src/lib.rs
rust/src/treefile.rs
src/libpriv/rpmostree-core.cxx
tests/kolainst/destructive/container-image

The way we use manifests in FCOS and RHCOS really pushes the limits of
rpm-ostree's include system.
In FCOS for example, we often need to have some tweaks applied based on
the version of Fedora being targeted by the stream (especially around
rebase preparations time, and of course rawhide).
Currently, we do this by adding such tweaks in the `manifest.yaml`,
which is unique per stream. But if there are multiple streams that need
this change (e.g. `rawhide`, `branched`, `next-devel`, `next`), it
becomes cumbersome and error-prone to modify all their manifest files.
We could add a conditional include based on `releasever` similar to what
was done with `arch-include`, but this only hints at a need for more
customizable include logic.
Now with the introduction of arbitrary variables, let's add …

treefile: Add conditional includes

---

rust/src/testutils.rs

We picked this up with the merge of openat-ext 0.2.3.

testutils: Drop deprecated openat-ext usage

---

src/app/rpmostree-composeutil.cxx

That way, we're not creating an empty `commitmeta` in the default path.
Follow-up to #3472.

app/composeutil: Canonicalize empty detached metadata to NULL

---

rust/src/treefile.rs

Came up in review of a recent PR.  We don't need to allocate
a new memory buffer to read from another memory buffer.
Performance doesn't matter *here* at all, but it's good to use
the right patterns in test code because the muscle memory there
applies to production code too.
As a bonus notice we don't need `.as_bytes()` because `Cursor`
works over `AsRef<[u8]>`.

treefile: Use `std::io::Cursor` when reading byte arrays

---

src/libpriv/rpmostree-scripts.cxx

Ideally we should probably rework this function instead to dedupe a bit
with `rpmostree_script_run_sync`. But specifically for lua, hopefully we
can eventually clean things up somehow as discussed in
https://github.com/coreos/fedora-coreos-tracker/issues/1080.
Fixes: https://github.com/coreos/rpm-ostree/issues/3487

scripts: Support transfiletriggerin lua replacements

---

Cargo.lock

Mainly this drops the dependency on the old `nix-0.22`.

Bump to containers-image-proxy 0.4.1

---

packaging/make-git-snapshot.sh
packaging/rpm-ostree.spec.in

Otherwise when building unprivileged in OpenShift as a large uid, we can
get errors like:
```
tar: value 1000710000 out of uid_t range 0..2097151
```
It's good hygiene anyway.

packaging: Canonicalize tarballs to uid/gid 0

---

.gitignore

Not sure whether the latter is a new arrival or not but it's showing up in my list. The former is due to my use of Visual Studio Code.

Ignore .vscode and libgnlx-config.h

---

packaging/make-git-snapshot.sh

Workaround to remove Windows specific binaries that we don't need from the vendored sources.
See: [rust-lang/cargo#7058](https://github.com/rust-lang/cargo/issues/7058)

packaging: Remove unneeded Windows binaries from vendor snapshot

---

ci/codestyle.sh
rust/libdnf-sys/cxx/libdnf.cxx
tests/common/libtest.cxx

Followup to the previous patch.  When I was testing the original
PR I ran `clang-format` on everything (i.e. not just stuff in `src`)
and was confused why these files differed from the original PR.
I see no reason to limit to files in `src`, even though there's only
two C++ files outside of there today.
CC @jeamland

Require clang-format on all C/C++ files

---

Makefile.am

Follow-up to https://github.com/coreos/rpm-ostree/pull/3475 and https://github.com/coreos/rpm-ostree/pull/3498.

Makefile: add `make clang-format` to format tree

---

Cargo.lock
Cargo.toml

We want the new `symlink_metadata_optional` flag to aid cap-std porting,
xref https://github.com/coreos/rpm-ostree/pull/3468

Update to cap-std-ext 0.23.3

---

src/libpriv/rpmostree-postprocess.cxx

This tweaks the mtree-writing logic in order to always set the exit
code, both on success and on error. It has no practical side-effects,
but it helps dropping a `goto` and avoiding an implicit dependency on
pre-initialized data.

libpriv/postprocess: always set exit code

---

docs/architecture-core.md

The `/var` question came up on an internal chat.

docs: Mention mount point mutability

---

rust/src/treefile.rs
src/app/rpmostree-pkg-builtins.cxx
src/libpriv/rpmostree-container.cxx
src/libpriv/rpmostree-container.h

Split out of https://github.com/coreos/rpm-ostree/pull/3501.

Minor prep patches for treefile and container work

---

src/libpriv/rpmostree-importer.cxx
src/libpriv/rpmostree-rpm-util.h

This adds the autocleanup definition for librpm `FD_t`. It allows
simplifying a bunch of error handlers and dropping some `goto`
statements.

libpriv/import: implement autocleanup for rpmfd

---

rust/src/builtins/compose/mod.rs

Notably, we start using the safe rustix binding to `mknodat`
and can drop our manual one.

compose: Complete porting to cap-std

---

src/app/rpmostree-builtin-deploy.cxx
src/app/rpmostree-builtin-upgrade.cxx
tests/vmcheck/test-autoupdate-check.sh

We're unlikely to fix this soon (and IMO what we really want is automatic
updates on by default everywhere, not to polish `--preview`), but for
now let's try to stem the tide of duplicates.

deploy: Warn about reliability of `--preview`

---

rust/src/client.rs

Adding onto the pile of hacks here unfortunately.  Basically
RHEL8 systemd seems to count explicit `systemctl start` invocations
against the restart limit.  We hit this in tests in openshift/machine-config-operator
which are invoking `rpm-ostree status` and `rpm-ostree kargs` frequently.

client: Don't invoke `systemctl start` if unit is already active

---

Cargo.lock
rust/src/cliwrap.rs
rust/src/live.rs

I really don't like the "error swallowing" behavior of `.exists()`,
so let's use this.

Bump to cap-std 0.24.2, use `try_exists()`

---

rust/src/composepost.rs

See https://src.fedoraproject.org/rpms/rpm/c/391c3aeb66e8c2a0ac684580ac82c41d7da2128b?branch=rawhide
We don't need this and it breaks our current flow.

composepost: Also remove stamp file created by recent RPM `%posttrans`

---

rust/src/daemon.rs
rust/src/deployment_utils.rs
rust/src/lib.rs
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-deployment-utils.h
src/daemon/rpmostreed-os.cxx

This moves the deployment lookup helper to Rust (now that all its
consumers have been cleaned from goto statements).

daemon/dbus: port some deployment logic to Rust

---

rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-override-builtins.cxx
src/libpriv/rpmostree-container.cxx
src/libpriv/rpmostree-core.cxx
tests/kolainst/destructive/container-image
tests/kolainst/kolainst-build.sh

```
commit 98bd1cff568206545167c6c82c9274c63e60ee58
Date:   Tue Mar 22 16:53:44 2022 -0400
app/override: Support override remove in container flow
This one doesn't really require any work. The core already does the
right thing for the generated treefile with the `override-remove` knob
set. So it's just a matter of wiring it through.
```
---
```
commit a55205829f43a188e37a166869ac04a4c08e74b2
Date:   Tue Mar 22 16:54:23 2022 -0400
app/override: Support override replace in container flow
This one requires a bit more work. The main issue is that replacement
overrides usually heavily leverage the package cache repo. But here we
don't have that.
I think it's simpler to keep them separate instead of trying to make the
same key work in both modes. So we add a new
`override-replace-local-rpms` …
```

app/override: Support `override remove` and `override replace` in container flow

---

rust/src/capstdext.rs
rust/src/lockfile.rs

openat::Dir::open will fail when asked to open an empty path
(e.g. the result of Path::new("")) which can happen when a compose
command is given a filename with no preceeding path components.
For example, `--ex-write-lockfile-to=./lockfile.json` would
succeed while `--ex-write-lockfile-to=lockfile.json` would fail.
This change special cases the handling of an empty path by
replacing it with `Path::new(".")`.

Fix handling of lockfile parent directory

---

tests/vmcheck/test-history.sh

This is a racy hack because the journal could still be flushing things
while we try to delete it.
But anyway, it was needed when we would reuse the same VM for multiple
vmcheck tests. This is no longer the case since rebasing on top of
`kola`. So just nuke it.

vmcheck/history: delete journal hack

---

src/libpriv/rpmostree-rpm-util.cxx

I hit this when doing some bits in the compose path that
query the rpmdb.

rpmutil: Ensure libdnf is initialized when loading rpmdb

---

rust/src/lib.rs
rust/src/origin.rs

I'd like to implement https://github.com/coreos/rpm-ostree/issues/1265
for both the client-side and the container flow. But to do that, I'd
rather not have to wire it through all the layers that need to know
about it.
In a move towards https://github.com/coreos/rpm-ostree/issues/2326, I'd
like to try to have everything in the `DeployTransaction` ->
`RpmOstreeSysrootUpgrader` -> `RpmOstreeContext` flow only deal in
treefiles. But to not change the format on disk just yet, we still need
to deserialize from and serialize back into a `GKeyFile` at the I/O
boundaries (really, libostree API boundaries).
We have a function for the former, but not the latter. This patch adds
one.

rust/origin: support converting treefile to origin

---

.github/workflows/container.yaml
ci/test-container.sh
src/app/libmain.cxx
src/app/rpmostree-builtin-cleanup.cxx
src/app/rpmostree-builtin-ex.cxx
src/app/rpmostree-builtin-types.h
src/app/rpmostree-clientlib.h

ci: Be verbose for tar extraction
I want to verify we're doing the right thing.
---
cli: Opt-in some CLI verbs to working inside ostree containers
The work to progress having some rpm-ostree functionality work inside
(ostree based) containers is great, but in the current shuffle
we lost an essential check.  Only a few CLI commands today work,
and they need to opt-in.
Before this patch, all the other CLI verbs, e.g. `rpm-ostree status`
just crash and burn inside an ostree container.
xref https://github.com/coreos/rpm-ostree/issues/3540
---

 cli: Opt-in some CLI verbs to working inside ostree containers

---

ci/test-container.sh
src/libpriv/rpmostree-container.cxx
src/libpriv/rpmostree-postprocess.cxx

container: Cleanup rpmdb after installs
Really, we should get this API down into librpm.
Closes: https://github.com/coreos/rpm-ostree/issues/3540

container: Cleanup rpmdb after installs

---

src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-rpm-util.cxx

As we're working on "container native" (rpm)-ostree, it feels
natural to have the extensions build happen as part of e.g. a
`Dockerfile` build that simply pulls in the base image.
And to do that, we don't need any of this "offline" stuff that
the compose extensions path is using.  Here we're running
rpm-ostree inside a container, and conceptually we mostly just
need the libdnf side.

compose extensions: Support `--rootfs`

---

.cci.jenkinsfile
ci/cosa-overrides.sh
ci/prow/fcos-e2e.sh
rust/src/composepost.rs

ci: Drop skopeo override
It's actively downgrading things now.
---
composepost: Make rpmdb location `pub(crate)`
Prep for supporting ostree-container layer splitting work.
---

Two minor container-split prep patches

---

docs/extensions.md
src/app/rpmostree-compose-builtin-tree.cxx

Came up in code review.  Also while I'm here add a tweak to the
doc.

extensions: Validate we don't have `--repo` and `--rootfs`

---

man/rpm-ostree.xml

This behavior seems to have effectively become implicit, I am not
completely sure we always did this.
AFAICS there's no API to turn it off; it could make sense to do so.
But anyways, let's document the status quo.

man: Document that `rebase` and `deploy` will also update layered packages

---

packaging/rpm-ostree.spec.in

Trying to build current git in COPR for C8S, we get:
```
= note: /usr/bin/ld: cannot find -lassuan
collect2: error: ld returned 1 exit status
```
(As part of a *huge* linker invocation)
I am pretty sure this is because
`/usr/lib/rpm/macros.d/macros.rust:  -Clink-arg=-Wl,-z,relro,-z,now`
specifically `-znow` requires all shared libraries present at build
time.
In current Fedora 35 we have:
```
$ grep Requires /usr/lib64/pkgconfig/gpgme.pc
Requires: gpg-error, libassuan
$
```
Which causes `gpgme-devel` to `Require` `libassuan-devel`, but
this `Requires` is missing in C8S gpgme.

spec: BR `libassuan-devel` on rhel8

---

src/daemon/rpmostreed-os.cxx
src/daemon/rpmostreed-sysroot.cxx

For some reason on at least current C9S, dbus-broker is returning
a different error when polkit is not available.  Looking at it,
the two errors come from here
https://github.com/bus1/dbus-broker/blob/92142f321fc80c76ab1cc973ce2defa1039cac4a/src/bus/driver.c#L743
But I don't quite understand the circumstances in which one is sent
versus the other.
In any case, this should be a very safe and targeted change to
ensure we handle both errors.
Closes: https://github.com/coreos/rpm-ostree/issues/3554

daemon: Handle `org.freedesktop.DBus.Error.ServiceUnknown` too

---

src/app/rpmostree-compose-builtin-tree.cxx

I definitely tested the previous patch (and so did Joseph)
but I am fearing that I did further cleanup before pushing
that broke it.
What we're seeing right now is a segfault trying to use this with
RHCOS (which notably doesn't have a `ref` in the treefile).
Anyways, we should only be trying to resolve the base rev in
the "outside" path, not the in-container path.  (Right now, but
once we can depend on a newer ostree inside the container we can
actually make this all work symmetrically)

compose: Fix handling of base rev

---

rust/src/daemon.rs
rust/src/extensions.rs
rust/src/testutils.rs

daemon: Port to cap-std
Part of an ongoing effort.
---
extensions: Port to cap-std
Part of an ongoing effort.
---
testutils: Port to cap-std
Part of an ongoing effort.
---
testutils: Port to rustix for `Mode`
Eventually we'll want only rustix and not `nix`.
---

A few cap-std patches, plus one more

---

rust/src/core.rs
rust/src/lib.rs
src/libpriv/rpmostree-kernel.cxx

Prior to this commit, the .vmlinuz.hmac file was assumed to be:
```
<hmac>  /boot/vmlinuz-<version>
```
This is because the ARK kernel.spec so-happens to run hmac512sum on that path while building the RPM. Because absolute paths to the kernel don't make sense for Core-OS, `/boot/` was removed from the start of the path. This means that the prior emergent behavior was a `basename`, where supported. Unfortunately, some custom kernels build with a path other than `/boot/`, and the prior behavior would log an error and abort.
At the time of this commit, using the basename is under consideration in ARK. However, there are many existing custom kernels that rpm-ostree users may want to use.
Given that a basename was being performed (when no error is encountered), this change reflects that …

use basename when cleaning up the .vmlinuz.hmac file

---

rust/src/bwrap.rs
rust/src/client.rs
rust/src/composepost.rs
rust/src/daemon.rs
rust/src/lockfile.rs
rust/src/nameservice/shadow.rs
rust/src/passwd.rs
rust/src/testutils.rs

I didn't try to convert everything, just did some to start the ball
rolling, avoid having a flag day that would conflict with other outstanding
PRs etc.

partial, tree-wide: Switch to using inline variables in `format!`

---

rust/src/daemon.rs
rust/src/lib.rs
rust/src/origin.rs
rust/src/treefile.rs
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-origin.cxx
src/libpriv/rpmostree-origin.h
tests/kolainst/destructive/initramfs-etc

Now that we have all getters backed by the treefile, we can start migrating the setters. Do this for the override commit and initramfs-etc files to get the ball rolling. More to come.

Migrate source of truth for override-commit and initramfs-etc files

---

.cci.jenkinsfile
.github/workflows/container.yaml

The compose tests keep flaking out in FCOS CI/Jenkins.  I am not
totally sure why, but I think it's related to the fact it's on
bare metal (which is great) but that Kubernetes uses CPU shares
and most tools which try to count processors are confused by that.
We have 3 CI systems, and actually I think GH actions is a good
match for our legacy compose tests.  It gives us a VM, in which
we can easily run a privileged container.
Further, GH actions is nicer here in that the legacy compose tests
can appear as a separate check status.

ci: Move legacy compose tests to GH actions

---

src/daemon/rpmostreed-daemon.cxx
src/daemon/rpmostreed-daemon.h
src/daemon/rpmostreed-transaction.cxx

We got a panic inside `rpmostreed_transaction_new_cleanup` because
there was no tokio handle associated with the current thread.
The goal of the original PR here was to grab the tokio context
from the main (initial) thread.  Now, in that stack trace
GDBus is clearly executing the callback on a worker thread.
As best I can tell from looking at the GDBus source, this can
happen in cases where method authorization is in play; there's a
whole dance where that bit gets dispatched to a worker, then we
try to schedule the callback on the original main context.
(Also, one can configure all GDBus method invocations to run
in a thread, but we're not doing that)
I am not totally sure why this isn't *always* crashing - it might
only occur in situations where the main context is not idle?
Anyways, I …

daemon: Move tokio handle reference into daemon

---

Cargo.lock
Cargo.toml
rust/src/container.rs
rust/src/lib.rs
rust/src/main.rs
rust/src/sysroot_upgrade.rs
src/lib/rpmostree-package-priv.h
src/libpriv/rpmostree-refts.cxx
src/libpriv/rpmostree-refts.h
src/libpriv/rpmostree-rpm-util.cxx
src/libpriv/rpmostree-rpm-util.h

The headlining feature here is https://github.com/ostreedev/ostree-rs-ext/pull/123
which adds support for "chunked ostree".
We gain a new `rpm-ostree container-encapsulate` option which
is like `ostree container encapsulate`, but generates chunked
images using the RPM database.
And on the client side, we now know how to handle incremental
updates - chunks that haven't changed won't be redownloaded.
---

Update to ostree-ext 0.7, add new `container-encapsulate`

---

src/libpriv/rpmostree-importer.cxx

clang `scan-build` flags it as possibly uninitialized, but I think
that's just because it can't prove the conditionals.  Anyways,
no real cost to initializing it.

importer: Initialize cpio offset

---

src/app/libmain.cxx
src/app/rpmostree-builtin-cleanup.cxx
src/app/rpmostree-builtin-rebuild.cxx
src/app/rpmostree-builtin-shlib-backend.cxx
src/app/rpmostree-builtin-status.cxx
src/app/rpmostree-clientlib.cxx
src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-composeutil.cxx
src/app/rpmostree-db-builtin-diff.cxx
src/app/rpmostree-override-builtins.cxx
src/app/rpmostree-pkg-builtins.cxx
src/daemon/rpmostree-sysroot-core.cxx
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-daemon.cxx
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-os-experimental.cxx
src/daemon/rpmostreed-os.cxx
src/daemon/rpmostreed-sysroot.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-importer.cxx
src/libpriv/rpmostree-kernel.cxx
src/libpriv/rpmostree-origin.cxx
src/libpriv/rpmostree-postprocess.cxx
src/libpriv/rpmostree-scripts.cxx
src/libpriv/rpmostree-util.cxx
src/libpriv/rpmostree-util.h

clang's `scan-build` static analyzer says that our current pattern
is not safe.  Replace our usage of `CXX_TRY_VAL` with `CXX_TRY_VAR`
that moves the type declaration into the macro.  Crucially, the
variable is only created on the success path.
I think C++ has special handling for exceptions and things like
`auto var = somefunc();` where if `somefunc()` throws it knows that
`var` is not initialized.  But this doesn't work with the GCC statement-expression
extension.
Note that we can no longer do e.g.:
`self->treefile_rs = CXX_TRY(...)`
so the new pattern is:
```
CXX_TRY_VAR(tf, ...);
self->treefile_rs = std::move (tf);
```
Also, while I'm here I honestly find the `ROS` thing was a bit *too*
magic.  So I ported everything to explicitly say `rpmostreecxx::`
for the namespace.
Eventually, we …

tree-wide: Rework C++ try/catch to GError bridging

---

Cargo.lock

We managed to ship this bug in the current 2022.6 release:
https://github.com/tokio-rs/tracing/issues/2046
Which is definitely embarassing enough to cut a new release.  (For both them and us, but I explicitly mean we should cut an rpm-ostree 2022.7 with this downgrade)
Closes: #3589

Downgrade tracing-subscriber to 0.3.9

---

src/libpriv/rpmostree-refts.cxx
src/libpriv/rpmostree-rpm-util.cxx
src/libpriv/rpmostree-rpm-util.h

Ye olde "librpm treats explicit epoch 0 differently than unset"
bites us again when I tried `rpm-ostree container-encapsulate fedora/35/x86_64/silverblue`.
`perl-NDBM_File` has an explicit `0` epoch, and this causes
an assertion error because the nevra we get from our pkglist is
different than what librpm returns.

refts: Correctly canonicalize explicit zero epoch

---

rust/src/daemon.rs
rust/src/extensions.rs
rust/src/lib.rs
rust/src/origin.rs
rust/src/passwd.rs
rust/src/treefile.rs
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-os.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-origin.cxx
src/libpriv/rpmostree-origin.h

This starts with initramfs regeneration and args, but more will be added.
Works on top of https://github.com/coreos/rpm-ostree/pull/3561.

libpriv/origin: Migrate source of truth for more fields to treefile

---

src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-rpm-util.cxx

I don't believe it's reachable in practice for `name` to be
`NULL` here, but let's silence the analyzer.
(This code really wants to be in Rust)

Add some assertions to silence `gcc -fanalyzer`.

---

rust/src/lib.rs
rust/src/treefile.rs
src/libpriv/rpmostree-core.cxx
tests/kolainst/destructive/container-image
tests/kolainst/kolainst-build.sh

This implements the semantics discussed in
https://github.com/coreos/rpm-ostree/issues/1265.
For now, it's only supported in treefile format. Will wire it up to
`override replace` soon.
Also for now, this only works in the container flow. The client-side
will come soon, but it still needs more cleanups there to avoid having
to wire this through a non-trivial number of APIs.

Add support for repo overrides in container flow

---

src/libpriv/rpmostree-rpm-util.cxx

rpmutil: Plug a memory leak in capability conversion

---

tests/compose/test-install-langs.sh
tests/kolainst/destructive/apply-live
tests/kolainst/destructive/container-image
tests/kolainst/destructive/layering-local

This is like https://github.com/coreos/coreos-assembler/pull/2814
but for our tests, required now that
https://github.com/coreos/coreos-assembler/pull/2810
merged into coreos-assembler.

fixes for "the world changed underneath us" CI failures

---

rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-json-parsing.cxx
src/libpriv/rpmostree-json-parsing.h

This oxidizes one JSON parsing helper.

libpriv/json-parsing: port one helper to Rust

---

rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-tree.cxx

This renames one fallible getter method, using a more explicit
'require' wording.

treefile: rename one method

---

configure.ac
packaging/rpm-ostree.spec.in

This fixes a critical bug in 2022.7 which broke pulling
layered container images from base images generated by earlier
rpm-ostree versions - https://github.com/ostreedev/ostree-rs-ext/pull/280
Plus various other improvements.

Release 2022.8

---

src/libpriv/rpmostree-importer.cxx
src/libpriv/rpmostree-importer.h

This reworks the initialization logic for the ostree branch member
in the RPM importer. Branch name can be derived from the RPM header,
and both of them can be directly set in the constructor.
It seems safe to assert that both are populated, and drop further
conditional logic.

libpriv/importer: simplify ostree branch handling

---

src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-importer.cxx
src/libpriv/rpmostree-importer.h

This drops the cached SHA256 of the header from the RPM importer.
The digest is only calculated and used right after importing an RPM,
thus there is strictly no need to cache it.
Additionally, this avoids possibly unsafe access to the field while
still uninitialized.

libpriv/importer: avoid caching header digest

---

rust/src/lib.rs
rust/src/origin.rs
rust/src/treefile.rs
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-origin.cxx
src/libpriv/rpmostree-origin.h

See individual commits. Part of the work to thin out `RpmOstreeOrigin`.

libpriv/origin: Move module-related bits to treefile

---

rust/src/daemon.rs
rust/src/lib.rs
rust/src/origin.rs
rust/src/treefile.rs
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-origin.cxx
src/libpriv/rpmostree-origin.h

See individual commits. Part of the work to thin out `RpmOstreeOrigin`.

libpriv/origin: Move overrides-related bits to treefile

---

rust/src/importer.rs
rust/src/lib.rs
src/libpriv/rpmostree-importer.cxx

This starts moving some of the RPM importer code to Rust, beginning
with the logic which handles tmpfiles.d entries for /var/lib/
symlinks.

libpriv/importer: port logic for /var/lib/ symlinks to Rust

---

Makefile-rpm-ostree.am
Makefile.am
rust/libdnf-sys/build.rs
rust/libdnf-sys/cxx/libdnf.cxx
rust/libdnf-sys/cxx/libdnf.hpp
rust/libdnf-sys/lib.rs
rust/src/lib.rs
rust/src/treefile.rs
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-cxxrs-prelude.h
src/libpriv/rpmostree-origin.cxx
src/libpriv/rpmostree-origin.h

We're finally there! Quoting the before last commit:
```
libpriv/origin: Drop GKeyFile member from RpmOstreeOrigin
Everything is backed by the treefile now, so we no longer need to also
maintain a `GKeyFile` copy in sync.
This completes the hollowing of `RpmOstreeOrigin`.
The next phase will be to make callers use the treefile APIs directly so
that we can delete `RpmOstreeOrigin` entirely.
```

libpriv/origin: Finish thinning out RpmOstreeOrigin

---

rust/src/importer.rs
rust/src/lib.rs
src/libpriv/rpmostree-importer.cxx

This ports the /opt symlinking logic in the RPM importer to Rust.

libpriv/importer: port logic for /opt symlinks to Rust

---

rust/src/importer.rs
rust/src/lib.rs
rust/src/utils.rs
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-importer.cxx
src/libpriv/rpmostree-util.cxx
src/libpriv/rpmostree-util.h

This moves the logic for path translation and the ostree importing
callback to Rust.

libpriv/importer: port path translation to Rust

---

.cci.jenkinsfile

We're seeing issues where CI sometimes hits EAGAIN on `fork`:
https://github.com/coreos/fedora-coreos-tracker/issues/1186
It's possible something changed recently that made rpm-ostree use more
threads than before and more likely to hit this.
There's no way for us control the PID limit from our side (it's a
node setting), so let's just lower parallelism here. (Another approach
is splitting it into multiple pods, but it doesn't seem worth the
complexity yet.)

ci: Reduce parallelism of vmcheck tests to 5

---

ci/test-container.sh
rust/src/client.rs
rust/src/cliwrap.rs
rust/src/cliwrap/cliutil.rs
rust/src/cliwrap/rpm.rs
rust/src/cliwrap/yumdnf.rs
rust/src/lib.rs

lib: Add an API to get "system host"
I think we in the future will want to more carefully dispatch
on the type.
---
cliwrap: add install verb, support being run in a container
This is preparatory work for actually having e.g. `yum install`
do what we want in a container.
---
cliwrap: Enable `yum install foo` in a container
For the "ostree native container" bits, the goal is to make things
*extremely obvious* to someone who is using a `Dockerfile` to build
derived images.
Another way to say this is that a goal is for ostree to
"fade into the background".  It's still there - just not something
everyone needs to learn or care about.
This makes it so that typing `yum install usbguard && yum clean all`
Just Works as one would expect.
---

cliwrap: Enable `yum install foo` in a container

---

src/libpriv/rpmostree-core.cxx

libdnf internally adds an `install_root` prefix to vars directories,
resulting in misplaced lookups to `<install_root>/etc/dnf/vars`.
As a workaround, this inserts a relevant amount of `/..` in order to cancel
out the path prefix.
Ref: https://github.com/coreos/rpm-ostree/issues/3241

libpriv/core: workaround libdnf vars path lookup

---

rust/src/cliwrap.rs

cliwrap: Use `Utf8Path` to drop an `unwrap()` also `ok_or_else`
Minor cleanup I had locally while I was working on the code
earlier but forgot to submit.
---
cliwrap: More Utf8Path usage
Just a general cleanup.
---

cliwrap: Use `Utf8Path` to drop an `unwrap()` also `ok_or_else`

---

rust/src/composepost.rs
rust/src/lib.rs
src/libpriv/rpmostree-container.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-postprocess.cxx
src/libpriv/rpmostree-postprocess.h

Prep for calling it from Rust code.

postprocess: Move rpmdb cleanup into Rust 

---

src/libpriv/rpmostree-rpm-util.cxx
src/libpriv/rpmostree-rpm-util.h

Prep for use in IMA work, where we need to merge fcap xattrs
with IMA xattrs.

rpmutil: Factor out helper for fcaps to single variant

---

docs/treefile.md
rust/src/lib.rs
rust/src/treefile.rs
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h
src/libpriv/rpmostree-importer.cxx
src/libpriv/rpmostree-importer.h
src/libpriv/rpmostree-postprocess.cxx

The alignment between ostree and IMA is actually quite good.  IMA
signatures are just extended attributes, and ostree has first-class
native support for those.
RPM represents IMA signatures in an ad-hoc way, and then a plugin
pulls bits from the header and does the `lsetxattr` call.
One thing that ostree is pretty good at is that one can synthesize
data in memory into the final ostree commit, without actually needing
it to hit the physical filesystem at build time.  This is crucial
for SELinux, where we want to be able to set security contexts
in the resulting build without actually requiring matching SELinux
policy on the *build* server.
IMA has similar issues; we don't want to blindly use `rpm-plugin-ima`
at *build* time.  That would potentially conflict with IMA policy
set up for the …

build: Add support for propagating RPM IMA signatures

---

rust/src/importer.rs
rust/src/lib.rs
src/libpriv/rpmostree-importer.cxx

This moves the cached ostree branch label to the Rust portion of
the RPM importer.

libpriv/importer: move ostree branch caching to Rust

---

rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-tree.cxx

It's pointless to carry this around when it's unused.
Prep for porting to cap-std.

treefile: Remove unused workdir

---

rust/src/importer.rs
rust/src/lib.rs
src/libpriv/rpmostree-importer.cxx

This moves the RPM importer logic for doc-files filtering to Rust.

libpriv/importer: port docs filtering to Rust

---

Cargo.lock

A few minor things, also prep for bumping cap-std-ext.

Update to ostree-ext 0.7.2

---

Cargo.lock
Cargo.toml
rust/src/importer.rs
rust/src/lib.rs
rust/src/treefile.rs
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-importer.cxx
src/libpriv/rpmostree-importer.h

This moves the RPM importer flags to Rust, backed by `bitflags`.

libpriv/importer: move importer flags to Rust

---

configure.ac
packaging/rpm-ostree.spec.in

Compose:
- Add support for propagating RPM IMA signatures
Container:
- We now support `yum install foo`
- Fix `override replace` and `override remove` support
- Support whitespace-separated packages in `ex-override-replace` key
Internals:
- Bump libdnf submodule to latest, which should fix https://bugzilla.redhat.com/show_bug.cgi?id=2083715
- Oxidize more bits in the origin and importer code
- Move testing to Fedora 36
```
Colin Walters (19):
lib: Add an API to get "system host"
cliwrap: add install verb, support being run in a container
cliwrap: Enable `yum install foo` in a container
core: Check for errors from `hy_subject_get_best_solution`
treefile: Handle whitespace splitting for remote override packages
treefile: Simplify code for whitespace-splitting repo packages
postprocess: Move …
```

Release 2022.9

---

src/daemon/rpmostreed-transaction-types.cxx
tests/kolainst/destructive/container-image

Since the container flow is experimental, we need to handle
rebasing back to ostree.
There's still an issue here in that we're not pruning container image
refs when rebasing, but that's also true of rebasing between
container images today.
Closes: https://github.com/coreos/rpm-ostree/issues/3677

daemon: Handle rebasing back from container to ostree

---

.github/workflows/container.yaml
ci/codestyle.sh
rust/src/composepost.rs

ci: Verify we have no `goto` usage in C/C++
This is important for conversion to Rust, but also interacts
better with C++ exceptions.
---
tests: Fix dependency on uid/gid in compose tests
Trying to do a build in GH actions, I was really confused initially
why `test_tmpfiles_d_translation()` was failing there.  It turns
out the test was indirectly depending on the uid being 4 characters
long (1000, from coreos-assembler) because we end up writing the
current uid into the filesystem, and then the test asserts on the
total size of all regular files.
Fix the test to dynamically compute the expected size.
---
ci: Also build clang in Github Actions
Let's leave the Prow workloads to things that want nested virt
basically.
---

3 small CI patches

---

Cargo.toml
Makefile-rpm-ostree.am
configure.ac
packaging/rpm-ostree.spec.in
rust/libdnf-sys/Cargo.toml
rust/libdnf-sys/build.rs
rust/src/utils.rs

Enable compilation with librhsm
First, add a generic `--enable-featuresrs=$x` autoconf bit which just passes
through to `cargo build --features $x` so we don't need to mirror all
future options in autoconf.
Use this to add `--enable-featuresrs=rhsm` which basically boils
down to passing `-DENABLE_RHSM_SUPPORT=1` to the libdnf cmake bits.
This is important for subscriptions on RHEL.
---
spec: Add bcond for rhsm mirroring libdnf
Do the same thing the libdnf spec is doing to enable the feature.
---

Enable compilation with librhsm

---

src/daemon/rpmostreed-sysroot.cxx

Use G_IO_ERROR_BUSY for "Transaction in progress" error, thus the caller
can do specific actions when something else is ongoing.
Closes https://github.com/coreos/rpm-ostree/issues/3070

rpmostreed-sysroot: Use G_IO_ERROR_BUSY for "Transaction in progress" error

---

.copr/Makefile

This is similar to 8c6ea612 ("ci: Mark git checkout as safe") but for
COPR. It seems the git checkout is mounted in.
For more information, see:
https://github.com/actions/checkout/issues/760

copr: Mark git checkout as safe

---

.copr/Makefile

Adding the checkout as a safe directory is not enough. The same issue
happens again for each submodule we have. Rather than listing those
explicitly, let's just disable this security check.
While we're here, drop the duplicate `ci/installdeps.sh` call.

copr: Disable git repo ownership security

---

src/app/rpmostree-clientlib.cxx

Otherwise we can see a bare `error: Operation timed out` which
is painful to debug.

client: Add error prefixing for RegisterClient failures

---

rust/src/scripts.rs

Yet another kernel package variant whose %posttrans we want to ignore.
As mentioned in there, I think we should change the strategy so that we
detect kernel packages like we do in the core based on its `Provides` to
know to ignore %posttrans.
Alternatively/additionally, we should work with kernel and systemd teams
so that e.g. it short-circuits if it detects an "offline" system. That
would also benefit containers, which AFAIK even today runs dracut on
kernel installs.
Closes: #3720

rust/scripts: Ignore `kernel-automotive-core.posttrans`

---

rust/src/composepost.rs
rust/src/cxxrsutil.rs
rust/src/daemon.rs
rust/src/lib.rs
rust/src/live.rs

I was going to do some further oxidation and as I was typing out the
whole `Pin<&mut T>` thing again I was thinking about how in other
places we were passing plain Rust references i.e. `&Foo` not
`Pin<&mut Foo>`.
With this, it works fine to pass borrowed glib-rs types across via
cxx-rs.  I am not totally sure how I got it into my head originally
that we needed `Pin<&mut T>` here.
In particular, this case of C/C++ → Rust is basically the same as
the use case of GObject signals (e.g. Rust GTK+ application catching
a resize signal).  We can use
https://docs.rs/glib/latest/glib/translate/trait.FromGlibPtrBorrow.html
which is designed for this.
Another way to look at this is: We don't need to bump the gobject
reference count here - we have the Rust lifetime rules to protect us.
The `Pin<&mut …

rust: Add "reborrow" API, use for live path (+1 cancellable bit)

---

rust/src/lib.rs
rust/src/live.rs
rust/src/treefile.rs
rust/src/utils.rs

Cleanup followup to https://github.com/coreos/rpm-ostree/pull/3723/commits/b2c7bf7fc46de45ef0b0f47e48e9f068e2b81210

rust: Drop a few more `Pin<&mut T>`

---

rust/src/core.rs
rust/src/cxxrsutil.rs
rust/src/lib.rs
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-cxxrs-prelude.h

core: Oxidize commit_has_matching_sepolicy
No specific motivation, just noticed that this one is relatively
easy (no libdnf bits).
---
core: Oxidize get_header_variant
No specific motivation, just keeping up momentum.
---

core: Two small oxidation patches

---

rust/src/cliwrap/dracut.rs
tests/kolainst/destructive/cliwrap

This should fix `kdump.service` which we test in FCOS at least.

cliwrap/dracut: Don't intercept if we're running in systemd

---

src/libpriv/rpmostree-container.cxx

Making sure we print the transaction when running on a container, for example:
```
Installing 3 packages:
kernel-5.17.11-300.fc36.x86_64 (@commandline)
kernel-core-5.17.11-300.fc36.x86_64 (@commandline)
kernel-modules-5.17.11-300.fc36.x86_64 (@commandline)
```

rpmostree-container: print transaction

---

rust/src/lib.rs
rust/src/origin.rs

rust/origin: Drop unnecessary `Pin<&mut T>`

---

rust/src/lib.rs
rust/src/passwd.rs

rust/passwd: Drop unnecessary `Pin<&mut T>`

---

rust/src/builtins/apply_live.rs
rust/src/lib.rs
rust/src/live.rs
src/libpriv/rpmostree-diff.cxx
src/libpriv/rpmostree-diff.hpp

This one is subtle.  Again here, cxx.rs wants to try to match up
rust `&` and `&mut` with C++ `const &` vs `&`.
However...on the C side, we take raw `OstreeRepo *` pointers that
all implicitly support "interior mutability".
We can then (safely AIUI) use `const_cast` to cast away the `const`
that cxx wants to get a reference, which we then turn into a raw
C pointer which is passed to the C side.

diff: Drop use of Pin<&mut T> for ostree repo

---

src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-postprocess.cxx
src/libpriv/rpmostree-postprocess.h

For one thing, I nearly fell into the trap that `std::optional<Treefile&>`
is undefined behavior and one needs this weird `reference_wrapper`
thing.
But better, this means that we only have the default values in
*one place* - in `treefile.rs`.  Previously e.g. the code had the
default of `true` for `machineid-compat` in the postprocess bits too.

compose: Make a default treefile instead of using `std::optional`

---

src/libpriv/rpmostree-kernel.cxx

I want to test out using zstd for the initramfs; so let's allow
configuring that by dropping a config file in `/etc/dracut.conf.d`
as intended.
Also, we should default to whatever dracut defaults to; and if
someone e.g. wants to force on something else, they can do that
via injecting `/etc/dracut.conf.d` too.
In current Fedora, the dracut default is still gzip, but compressed
in parallel via `pigz`.

kernel: Stop hardcoding `dracut --gzip`

---

rust/src/importer.rs
rust/src/lib.rs
src/libpriv/rpmostree-importer.cxx

This moves the RPM importer logic for rpmfi overrides to Rust.

libpriv/importer: move rpmfi overrides map to Rust

---

src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-importer.cxx
src/libpriv/rpmostree-rpm-util.cxx
src/libpriv/rpmostree-rpm-util.h

This removes some dead code related to a signal handling workaround
which was required for older librpm versions. It got altered at the
time when RHEL 7 support got dropped, and what remains of that logic
seems to be effectively a no-op.
Ref: https://github.com/coreos/rpm-ostree/pull/1794

libpriv/rpm-util: remove dead code for signal handling

---

Cargo.lock

This pulls in https://github.com/ostreedev/ostree-rs-ext/pull/251
at least which I believe is the patch which fixes the
errors we're seeing when package layering in some cases.
xref https://bugzilla.redhat.com/show_bug.cgi?id=2095528

rust: Bump to ostree-ext 0.6.5

---

rust/src/utils.rs

I read https://internals.rust-lang.org/t/micro-feature-if-in-vec/16662
and thought of this function.  Obviously a mostly pointless
cleanup but, I like writing elegant Rust code =)

utils: Clean up `get_features()`

---

rust/src/importer.rs
rust/src/lib.rs
src/libpriv/rpmostree-importer.cxx

This moves the RPM importer buffering logic for tmpfiles.d entries
to Rust.

libpriv/importer: move tmpfiles.d entries buffering to Rust

---

rust/src/container.rs
rust/src/fedora_integration.rs
rust/src/lib.rs
rust/src/testutils.rs
src/daemon/rpmostree-package-variants.cxx
src/daemon/rpmostree-package-variants.h
src/libpriv/rpmostree-rpm-util.cxx
src/libpriv/rpmostree-rpm-util.h

rpmutil: Drop unnecessary `Pin<&mut T>`
Minor ongoing cleanup.
---
lib: Drop unnecessary `Pin<&mut T>` from package variant API
Minor ongoing cleanup.
---

Two more: Drop unnecessary `Pin<&mut T>`

---

rust/src/client.rs
rust/src/importer.rs
rust/src/lib.rs

rust/client: Drop use of Pin<&mut T>
Part of an ongoing cleanup.
---
rust/importer: Drop use of `Pin<&mut T>`
Part of an ongoing cleanup.
---

more Drop use of `Pin<&mut T>`

---

Cargo.toml
Makefile-rpm-ostree.am
ci/build.sh
ci/installdeps.sh
configure.ac
packaging/rpm-ostree.spec.in
rust/libdnf-sys/Cargo.toml
rust/libdnf-sys/build.rs
rust/src/utils.rs

Enable compilation with librhsm
First, add a generic `--enable-featuresrs=$x` autoconf bit which just passes
through to `cargo build --features $x` so we don't need to mirror all
future options in autoconf.
Use this to add `--enable-featuresrs=rhsm` which basically boils
down to passing `-DENABLE_RHSM_SUPPORT=1` to the libdnf cmake bits.
This is important for subscriptions on RHEL.
(cherry picked from commit f4fb7668af9340aaead9236863ef29726020f3a2)
---
spec: Add bcond for rhsm mirroring libdnf
Do the same thing the libdnf spec is doing to enable the feature.
(cherry picked from commit f9d4d307825b663cf222b079db6b4efb04f7555f)
---
ci: Enable librhsm
To ensure we cover building it.
---

rhel8: Enable compilation with librhsm

---

rust/src/origin.rs
rust/src/treefile.rs
src/app/rpmostree-builtin-deploy.cxx
src/app/rpmostree-builtin-rebase.cxx
src/app/rpmostree-builtin-reset.cxx
src/app/rpmostree-builtin-upgrade.cxx
src/app/rpmostree-clientlib.cxx
src/app/rpmostree-clientlib.h
src/app/rpmostree-override-builtins.cxx
src/app/rpmostree-pkg-builtins.cxx
src/daemon/org.projectatomic.rpmostree1.xml
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-origin.cxx
src/libpriv/rpmostree-origin.h

This new modifier will allow us to pass through future modifiers in
native treefile format rather than having to add separate modifiers each
time. Now that the origin is treefile-backed, it's a simple matter of
merging in the given treefile.

daemon: Add `treefile` modifier to `UpdateDeployment`

---

configure.ac
packaging/rpm-ostree.spec.in

Release notes draft: https://hackmd.io/fQG88NY5RqaDDZRcZh_wdQ

Release 2022.10

---

src/app/rpmostree-override-builtins.cxx
src/daemon/rpmostreed-os-experimental.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-rpm-util.cxx
src/libpriv/rpmostree-rpm-util.h
tests/kolainst/destructive/override-pinning
tests/vmcheck/install.sh

```
commit 5b3cee5a8a5b95f85c38d4ce5ab8a2768a1b8f49
Date:   Fri Jun 10 13:31:24 2022 -0400
app/override: Always treat NEVRA as frozen
If we're given a NEVRA and `--from`, handle it right away as a frozen
local override instead of converting it to a remote override (which
we'll add client-side support for soon).
A NEVRA pin is functionally the same as a local override after the repo
fetching, and it's silly to always try to refetch the same NEVRA from
the remote every upgrade.
```
---
```
commit 11eb8054b9207e6a54dba782a74106d49c34f8d5
Date:   Fri Jun 10 13:31:25 2022 -0400
core: Support package names only for remote overrides
Initially, I wanted to support remote overrides with partial package
names, e.g. NEVR and NEV. However, I don't think the use case is strong
enough combining with …
```

Various remote override handling tweaks

---

tests/kolainst/destructive/override-pinning

PR #3757 renamed `ReplacedBasePackages` to `LocalOverrides` and PR #3758
independently added a new test which expects the old output. Fix it.
Classic semantic merge conflict[1].
[1] https://bors.tech/essay/2017/02/02/pitch/

tests/override-pinning: Adapt to latest expected output

---

rust/src/capstdext.rs
rust/src/composepost.rs

See https://pagure.io/releng/failed-composes/issue/3660
The port to cap-std regressed only the *non-unified* core case
for tmpfiles.d translation.  Here cap-std's `read_link()` API correctly
checks for relative paths for the link name, but it *also* bombs
out if the link *target* is absolute, even if we're not going to
follow it.
I think this is arguably buggy behavior.  But, that's a debate
for a future time.
Now, this bug was masked in our CI because it doesn't occur in
unified core mode where we handle tmpfiles.d translation as part
of package imports.
Add and use internal helpers for reading (and writing, for tests)
absolute symlinks.

composepost: Add and use helpers for reading/writing absolute symlinks

---

rust/src/builtins/mod.rs
rust/src/builtins/usroverlay.rs
rust/src/lib.rs
rust/src/main.rs

This moves the 'usroverlay' CLI verb to its own builtins module,
out of main.
Minor cleanup before introducing further verbs adopting the
same layout.

rust/builtins: split out 'usroverlay' CLI verb

---

.gitignore
src/app/rpmostree-override-builtins.cxx
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-os-experimental.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h
src/libpriv/rpmostree-origin.cxx
src/libpriv/rpmostree-origin.h
src/libpriv/rpmostree-rpm-util.cxx
src/libpriv/rpmostree-rpm-util.h
tests/kolainst/destructive/override-pinning

Split out of https://github.com/coreos/rpm-ostree/pull/3636. That should be the last of them!

Final prep patches for remote overrides

---

Cargo.lock
Cargo.toml
ci/installdeps.sh
rust/libdnf-sys/Cargo.toml

Latest cxx release should be fixed now.

Go back to following upstream cxx and bump cxx to 1.0.69

---

Cargo.toml
ci/installdeps.sh
packaging/make-git-snapshot.sh

I spent some time on https://github.com/cgwalters/cargo-vendor-filterer
intending to use it to drop out a lot of ugly stuff like `.a` files
in Windows crates.

Use `cargo vendor-filterer`

---

ci/test-container.sh
rust/src/daemon.rs
src/app/rpmostree-builtin-status.cxx
src/app/rpmostree-override-builtins.cxx
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-core-private.h
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-util.cxx
src/libpriv/rpmostree-util.h
tests/kolainst/destructive/override-replace-repo
tests/kolainst/kolainst-build.sh

This add support for specifying remote overrides from the CLI in both
the host and the container paths.
This is pretty straightforward since the treefile and core already
support it. We just wrap the requests into a treefile and feed it to the
lower levels.

app/override: Support remote overrides

---

Cargo.toml
rust/src/main.rs

Pairs with https://github.com/ostreedev/ostree-rs-ext/pull/321
and https://github.com/containers/containers-image-proxy-rs/pull/32
I saw https://www.reddit.com/r/rust/comments/v8e9fa/local_async_executors_and_why_they_should_be_the/
go by and I think it's a good argument why one should use single-threaded
tokio by default.
Specifically for rpm-ostree, this takes the daemon down from:
```
[root@cosa-devsh ~]# cat /proc/1759/task/*/comm
rpm-ostree
tokio-runtime-w
tokio-runtime-w
tokio-runtime-w
tokio-runtime-w
tokio-runtime-w
tokio-runtime-w
tokio-runtime-w
tokio-runtime-w
tokio-runtime-w
tokio-runtime-w
tokio-runtime-w
tokio-runtime-w
tokio-runtime-w
tokio-runtime-w
tokio-runtime-w
tokio-runtime-w
tokio-runtime-w
gmain
gdbus
pool-/usr/bin/r
[root@cosa-devsh ~]#
```
To:
```
[root@cosa-devsh …
```

Only use single-threaded tokio reactor

---

ci/test-container.sh
rust/src/cliwrap.rs
rust/src/cliwrap/kernel_install.rs

Adds kernel-install wrap to properly override replace the kernel packages on container builds.

Wrap kernel-install calls on containers

---

ci/testdeps.txt
docs/HACKING.md

The dependencies installed by running `./ci/installdeps.sh` do not
include `cpio`, which is required to pass the `initramfs` test in `make
check`.
Adds a new section to `HACKING.md` that explicitly mentions this.

docs/HACKING: Mention cpio as test dependency

---

Cargo.lock

Notably this pulls in the latest rustix, which means we only
have one copy linked in process.  rustix is a quite nontrivial
project (roughly equivalent in scope to a C library).
In the future I plan to use e.g. `cargo deny` to ensure we don't
get in this situation again.

rust: Update to memfd 0.6.1

---

ci/test-container.sh
docs/cliwrap.md
rust/src/cliwrap.rs

Add environment variable to globally skip cli wraps. This is a follow up of #3689

rust/src/cliwrap: Add `RPMOSTREE_CLIWRAP_SKIP` to skip cliwraps

---

Cargo.lock
Cargo.toml
rust/src/capstdext.rs
rust/src/composepost.rs

This drops the copy of the code we have here.  At some point in
the future I may to add the API to cap-std's high level.

Use symlink API from cap-primitives

---

rust/src/capstdext.rs
rust/src/composepost.rs
rust/src/normalization.rs

Add some helper conversions from `openat` temporarily.
Part of an ongoing effort.

normalization: Port to cap-std

---

rust/src/bwrap.rs
rust/src/composepost.rs
rust/src/core.rs
rust/src/extensions.rs
rust/src/nameservice/group.rs
rust/src/nameservice/passwd.rs
rust/src/nameservice/shadow.rs
rust/src/normalization.rs
rust/src/treefile.rs

composepost: Drop unnecessary `mut`
We can just directly use the return value of the condition instead
of `if condition { var = true }`.
---
bwrap: Change append API to take an iterator
Just noticed this when I had the code open for something else.
It's more generic/flexible to take an iterator here; that way at least
one caller doesn't need a temporary `Vec`.
---
rust: Use `.map(BufReader::new)` in two places
I find this more readable; either it drops an extra variable,
or lessens the indentation.
---
rust: Just use `Cursor` for reading byte arrays
Wrapping a byte array in a `BufReader` is pointless; as a bonus
also, one can create a `Cursor` directly from a `&str` instead
of needing to invoke `as_bytes()`.
---

A few minor patches just to feel alive

---

rust/src/builtins/apply_live.rs
rust/src/client.rs
rust/src/lib.rs
rust/src/testutils.rs
src/app/rpmostree-clientlib.h

lib/rust: Drop two more `Pin<&mut T>`

---

src/app/rpmostree-builtin-rebase.cxx

`-r` is used for reboot, `-m` is used for remote

cli: fix rebase help around remote flag

---

docs/treefile.md

I went to look at our docs for `packages` as I couldn't remember
the incantation for a version selector (I was trying `skopeo >= 1.7.0`)
and was surprised at just how bad the docs were.
(This also could really use an example list, but let's start with
a small patch)

doc/treefile: Elaborate on all the changes we made to `packages`

---

Cargo.toml

This will fix a currently s390x-specific build failure
because `rustix` only depends on the `errno` crate if it's using the
libc backend, and this creates currently `s390x` specific build failures
for us.
Closes: https://github.com/coreos/rpm-ostree/issues/3839

rust: Also vendor for `s390x-unknown-linux-gnu`

---

Cargo.lock
Cargo.toml

See rationale in https://github.com/bytecodealliance/rustix/issues/215
I wrote it so that we can use it here.
And specifically this will fix a currently s390x-specific build failure
because `rustix` only depends on the `errno` crate if it's using the
libc backend, and this creates currently `s390x` specific build failures
for us.
(This overlaps with https://github.com/coreos/rpm-ostree/pull/3840 and is an alternative, complementary fix)

rustix: use libc backend

---

rust/src/extensions.rs
rust/src/lib.rs
rust/src/origin.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-tree.cxx

This is part of https://github.com/coreos/rpm-ostree/issues/3832
but also just a general code cleanup - in general, using file descriptors
is great, but libdnf doesn't support them, so we are awkwardly holding
onto a dfd and using `/proc` to make it a path.
Since our treefile input is today always a filesystem path, we might
as well expose that back - we're just holding onto the parent directory
*path*.
If in the future we converted the treefile code to accept a cap-std
`Dir` as input, then in theory we'd likely want to push for libdnf
to have `dnf_context_set_repo_dfd` or so.
But, this simplifies the code today.

treefile: Retain directory path, not dfd

---

rust/src/cxxrsutil.rs
rust/src/daemon.rs
rust/src/deployment_utils.rs
rust/src/lib.rs
rust/src/sysroot_upgrade.rs
src/libpriv/rpmostree-util.cxx
src/libpriv/rpmostree-util.h

lib/daemon: Drop unnecessary Pin<&mut T>
Part of an ongoing effort.
---
lib: Drop one unnecessary Pin<&mut T>
Part of an ongoing effort.
---
lib: Drop a few more unnecessary Pin<&mut T>
Part of an ongoing effort.
---

A few more patches to drop unnecessary `Pin<&mut T>`

---

ci/test-container.sh
rust/src/client.rs

The modularity code is native Rust, which is great, but means it
currently bypasses the infrastructure we added mostly on the C++
side (where most CLI entrypoint logic is) to detect the case of
ostree host/DBus versus container etc.
The Rust side already has a nice `ClientConnection` object that
basically expresses the need for an ostree host.  And we already
had a Rust API that's useful to error out here; combine those
two and tweak the error message.
(A future patch will change `ex module` to actually work, but
this is a correct starting point)

Give a better error for `ex module` in a container

---

rust/src/core.rs

Adding this breadcrumb should hopefully increase the odds we'll
eventually drop this.

rust/core: Add kernel-ark MR in HMAC comment

---

rust/src/composepost.rs
rust/src/treefile.rs

Part of https://github.com/coreos/rpm-ostree/issues/3832

treefile: Port one API to cap-std

---

.github/workflows/ci.yaml
ci/ridiculous-rhel-devel-workaround.sh
configure.ac

build: Drop dependency on rpm to 4.16
This is what's in RHEL9 right now.
---
ci: Add c9s build
We need to cover c9s to keep making upstream releases there.
---

Fix build on c9s and add CI

---

docs/treefile.md
rust/src/treefile.rs
src/daemon/rpmostree-sysroot-upgrader.cxx

Users should use `/etc/dracut.conf.d` instead. This option does not work
when regenerating the initramfs in the container flow.
We'll want to keep supporting it internally for a while in the upgrade
code, until all known composers have moved away from it, and reasonably
enough time for client systems to get the resulting updated trees.
See discussions in https://github.com/coreos/rpm-ostree/issues/3799.

treefile: Deprecate `initramfs-args` key

---

rust/libdnf-sys/cxx/libdnf.hpp

`rust::String` will throw on invalid UTF-8.  Noticed by
RHT-internal static analyzer.

libdnf-sys: Remove incorrect `noexcept`

---

Cargo.lock
rust/src/live.rs

Cargo.lock: Bump cap-std-ext
To pick up the new API we need.
---
live: Port to cap-std
Part of https://github.com/coreos/rpm-ostree/issues/3832
---

live: Port to cap-std

---

rust/src/treefile.rs

I switched things to just use `std::fs::write()` because porting
to cap-std isn't really important or worth it here.

treefile: Port tests away from openat

---

Cargo.toml

Mainly motivated by not having prebuilt `.a` files in our sources.

rust: Drop rustix linux_raw backend (and pre-generated `.a` files)

---

Cargo.lock
Cargo.toml

rust: Also vendor for `s390x-unknown-linux-gnu`
This will fix a currently s390x-specific build failure
because `rustix` only depends on the `errno` crate if it's using the
libc backend, and this creates currently `s390x` specific build failures
for us.
Closes: https://github.com/coreos/rpm-ostree/issues/3839
---
Bump to ostree-ext 0.8.1
Pull in the fix for https://github.com/ostreedev/ostree-rs-ext/issues/339
---

rhel8: Two cherry picks

---

src/libpriv/rpmostree-kernel.cxx

From the added comment:
The only baked special files we need are /dev/[u]random (see below).
So tell dracut to not even try to create the other ones (/dev/null,
/dev/kmsg, and /dev/console) since it'll fail anyway (and print ugly
messages) since we don't give it `CAP_MKNOD`.
My reason for doing this now is that we've been cleaning up dracut
errors in FCOS and these errors are the last remaining ones.

libpriv/kernel: Run dracut with `DRACUT_NO_MKNOD=1`

---

.github/workflows/ci.yaml
tests/encapsulate.sh

This will hopefully soon be the default, but we were missing CI for
it.  As a bonus, this *also* tests the `ostree-remote-registry`
flow that does the ostree GPG verification when pulling a container.

tests/encapsulate.sh: Explicitly test chunked encapsulation here

---

packaging/rpm-ostree.spec.in

I think this got cargo-culted from somewhere else in the far
distant past; as best I can tell, we never used it.
Closes: https://github.com/coreos/rpm-ostree/issues/3870

packaging: Drop `gnome-common`

---

ci/ridiculous-rhel-devel-workaround.sh

And now it happened; the version of util-linux in the container
versus the source we're trying to clone got out of sync.
Replace both packages to hopefully fix CI.

ridiculous-rhel-devel-workaround: Try to replace all packages

---

src/libpriv/rpmostree-core.cxx

This moves the overlaying of ostree layers earlier in the composing
process, so that their content is present on disk before any
scriptlet is run.
Before this, layered files were added only after `%pre` and `%post`
logic already ran. However, that resulted in troubles when trying
to add configuration fragments which would influence scriptlets behavior
(e.g. `sysusers.d` entries), as the files were not present in the target
envinroment at the time the scripts are executed.
This friction was notably observed with systemd `%post` script, which runs
`systemd-sysusers` and would miss any customization/fragments from ostree
layers.

libpriv/core: overlay ostree content before running scriptlets

---

ci/test-container.sh
rust/src/lib.rs
rust/src/modularity.rs
src/libpriv/rpmostree-container.cxx
src/libpriv/rpmostree-container.hpp
src/libpriv/rpmostree-core.cxx
tests/kolainst/destructive/layering-modules

This just plumbs through the bits into the treefile/rebuild flow,
although we also now need an API that exposes the `rebuild` flow to
C++.
Unfortunately due to circular dependencies we can't reference
the Rust-defined `Treefile` type in a C++ API that is then exposed
back to Rust, so we serialize the treefile as a string.
Closes: https://github.com/coreos/rpm-ostree/issues/3736

Enable `ex module` in a container

---

rust/src/dirdiff.rs
rust/src/live.rs

Part of https://github.com/coreos/rpm-ostree/issues/3832
This one had all the subtleties, *all* of which involve symlinks:
- Need to remember to swap the order of arguments to `symlink`
- Drop to cap-primitives to read/write absolute links instead of just calling `read_link`
- Use `symlink_metadata` and not `metadata`

dirdiff: Port to cap-std

---

ci/test-container.sh
rust/src/client.rs
rust/src/cliwrap/yumdnf.rs

We actually default to this...which is its own whole issue.  But
for now, just silently accept it for compatibility.
This required some juggling to separate out a new "global options"
struct from the subcommand.  (One can write both `yum -y install foo`
and `yum install -y foo`).  Luckily, clap supports this really well.

cliwrap: Add -y option to yum/dnf

---

.copr/Makefile
.gitattributes
.github/workflows/ci.yaml
.gitignore
Makefile-rpm-ostree.am
Makefile.bindings
ci/install-cxx.sh
ci/installdeps.sh
ci/verify-cxx.sh
docs/HACKING.md
docs/RELEASE.md
packaging/make-git-snapshot.sh
rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/cxx.h
rust/src/lib.rs

Closes: https://github.com/coreos/rpm-ostree/issues/3252
This avoids creating a magical, manual error prone step in the
release process, at the cost of dealing with generated code in git.

build-sys: Switch to committing cxx.rs generated code

---

rust/libdnf-sys/lib.rs
rust/rpmostree-client/src/lib.rs
rust/src/bwrap.rs
rust/src/client.rs
rust/src/cliwrap.rs
rust/src/composepost.rs
rust/src/container.rs
rust/src/cxxrsutil.rs
rust/src/daemon.rs
rust/src/deployment_utils.rs
rust/src/importer.rs
rust/src/initramfs.rs
rust/src/lib.rs
rust/src/origin.rs
rust/src/passwd.rs
rust/src/testutils.rs
rust/src/treefile.rs
rust/src/utils.rs

lib: Add `deny(clippy::dbg_macro & todo)`
We don't want these in production code in git.
---
rust: Fix single-character clippy lint
I think this can be slightly more efficient.
---
rust: Fix clippy unnecessary ref lints
---
rust: A few more misc clippy fixes
---
rust: A few more misc clippy fixes
---
rust: A few more misc clippy fixes
---
rust: A few more misc clippy fixes
---
rust: A few more misc clippy fixes
---

rust: Minor misc clippy fixes

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/bwrap.rs
rust/src/composepost.rs
rust/src/cxxrsutil.rs
rust/src/lib.rs

The end of an ongoing cleanup.  I also noticed that clippy
was warning about the `transmute` in this code, so it's nice
to be able to fix that by just deleting it!

Remove last uses of `Pin<&mut someglibtype>`

---

rust/src/builtins/scriptlet_intercept/groupadd.rs
src/libpriv/rpmostree-scripts.cxx

This introduces a new `RPMOSTREE_SCRIPT_PKG_NAME` environment
variable which gets propagated through `bwrap` into the context
of scripts. It allows sandboxed logic to introspect the package name.

libpriv/scripts: inject pkgname in scriptlets environment

---

docs/administrator-handbook.md
rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/client.rs
rust/src/lib.rs
src/app/rpmostree-clientlib.cxx
src/app/rpmostree-pkg-builtins.cxx
tests/kolainst/destructive/apply-live

This is the dual/inverse of
https://github.com/coreos/rpm-ostree/pull/3884/commits/87a1da1fb36a9b23ac9215317ce7580d61aecd7f
A big difference between rpm-ostree and yum/dnf today is
rpm-ostree does *not* prompt when you type `rpm-ostree install foo`;
it just does the operation by default.  One rationale for this is because
it doesn't apply live, it really can't break anything before
the admin has a chance to take action.
Valid cases here include:
- Discovering that you typo'd the package name
- Adding the package drags in a lot more dependencies than expected
However, when we added `-A/--apply-live` we broke that guarantee.
Now of course unlike traditional yum we have rollbacks.   But still,
I think in the future we should switch the default to prompting for
confirmation *only* when …

install: Add `-y/--assumeyes` option, prompt on tty by default

---

.github/workflows/ci.yaml
rust/src/cxxrsutil.rs
rust/src/treefile.rs

rust/cxx: Fix clippy lint around use of `transmute`
Casting the pointer and then synthesizing a reference from it
is apparently better:
https://rust-lang.github.io/rust-clippy/stable/index.html#transmute_ptr_to_ref
---
rust/treefile: Allow a clippy lint
I think the way this code is now is fine.
---
ci: Add a clippy check
This uses a pinned toolchain, like our other CI flows.
---

Fix remaining clippy lints + add CI

---

rust/src/builtins/scriptlet_intercept/mod.rs
rust/src/builtins/scriptlet_intercept/useradd.rs
rust/src/core.rs
src/libpriv/useradd-wrapper.sh

This re-routes `useradd` calls in scriptlets, in order to
automatically generate the corresponding sysusers.d fragments.
It follows the same logic as the existing `groupadd` interception.

core: wrap and intercept `useradd` calls in scriptlets

---

rust/src/cliwrap/yumdnf.rs

Based on https://github.com/coreos/rpm-ostree/pull/3884 to avoid conflicts
---
yumdnf: Add a `yum image rebase` subcommand
This wraps `rpm-ostree rebase --experimental <container>` - but
notice that it *only* supports container flows.  While here, we also
remove the confusing `ostree-unverified-registry:` type prefix strings.
Instead, the new happy path for a *signed* image (via e.g. sigstore)
looks just like `yum image rebase quay.io/examplecorp/my-coreos:latest`
and that's it!
Instead of the string prefixes here, we have e.g.
`yum image rebase --no-signature-verification quay.io/examplecorp/my-coreos:latest`
which *translates* today to the existing
`rpm-ostree rebase ostree-unverified-registry:quay.io/examplecorp/my-coreos:latest`
The high level goal here is that in a cliwrap-based …

yumdnf: Add a `yum image rebase` subcommand

---

rust/src/client.rs
rust/src/lib.rs
rust/src/main.rs
tests/kolainst/destructive/container-image

This is how we want to expose it to users, so use the deprecation
warning infrastructure (which is also a way to remind ourselves
about things we can remove in the future).  Change the test
code to use the new CLI.

Deprecate `ex-container` entrypoint (use `ostree container`)

---

Cargo.lock
tests/kolainst/destructive/container-image

rust: Bump to ostree-ext 0.8.2
---
tests/container-image: Use `--compression-fast`
What we really want is https://github.com/ostreedev/ostree-rs-ext/issues/153
to support pushing/pulling directly from `containers-storage`, but
in the short term this should improve CI times.
---

rust: Bump to ostree-ext 0.8.2 &&  tests/container-image: Use `--compression-fast`

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/container.rs
rust/src/lib.rs
rust/src/main.rs
src/app/rpmostree-builtin-compose.cxx
src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-compose-builtins.h
tests/encapsulate.sh

One really awkward thing right now is that anything on the Rust
side isn't emitted when one runs `rpm-ostree --help`.  Long
term we need to hard port all the CLI to Rust.
In the short term, I wanted to promote/document `container-encapsulate`.
Let's fix the "not in --help" problem by moving it where it probably
should have been to start - under the `compose` verb which is
our "build stuff".

Move `container-encapsulate` under `compose`

---

src/daemon/rpm-ostreed.service.in
tests/kolainst/nondestructive/misc.sh

Significantly bump this timeout from the default because
we do a lot of stuff on daemon startup.
Immediate motivation is https://bugzilla.redhat.com/show_bug.cgi?id=2111817
But this is also related to the same problems that motivated
https://github.com/coreos/rpm-ostree/issues/3850
(cc https://github.com/coreos/rpm-ostree/pull/2932 )
We switched from the default DBus timeout of 25 seconds to the
systemd default of 90s; this bumps us all the way up to 5 minutes.
I think the right long term fix is the socket activation, but this
is an easy backportable fix that will hopefully paper over spurious
failures.
(That said, anyone who is hitting this regularly probably has
a system too slow to really use, but...let's not stand in their
way)

unit: Bump `TimeoutStartSec=5m`

---

docs/administrator-handbook.md
docs/cliwrap.md
man/rpm-ostree.xml
rust/src/live.rs
src/app/libmain.cxx
src/app/rpmostree-builtin-applylive.cxx
src/app/rpmostree-builtin-ex.cxx
src/app/rpmostree-builtins.h
src/app/rpmostree-ex-builtins.h
tests/kolainst/destructive/apply-live
tests/kolainst/destructive/cliwrap

I think it's time; this has been basically working for a long
time now.  We implicitly stabilized most of this anyways
when we added `rpm-ostree install -A`.
There are a ton more things we can do, but I think
the status quo is useful.  Let's ensure people don't fear to use it.
One specific motivation I have here is to have `yum install foo`
default to `rpm-ostree install -A` and it's all just clearer
if the `apply-live` as a whole is stable.

Stabilize `rpm-ostree apply live`

---

rust/src/scripts.rs

New in rawhide.
The entire filesystem package is insane.  Every hack in there would go
away if we just taught traditional yum/dnf to install it first, in
the same way we do in rpm-ostree.

scripts: Ignore filesystem.posttrans

---

rust/src/cliwrap/yumdnf.rs
tests/kolainst/destructive/cliwrap

Previously the design logic around `yum install` here was to
try to encourage people to containerize and do things like
install debug tools in a `toolbox`.
But, this lecture model lacks empathy. And more importantly,
not every rpm-ostree based OS will want this.  For now I commented
out the code for this, I'm thinking we add an opt-in config
file flag that allows enabling this mode.
(But, an issue right now is we only have a daemon config, not
a client config file...and if you follow this, perhaps the
config flag should actually be in `/etc/dnf.conf`...which
we should really start reading...and that's a whole other
ball of wax.)
So for now let's just make `yum install cowsay` do what the user
asked for.
(Also, this makes more sense now that we correctly handle `-y`,
which we didn't …

yumdnf: Make `yum install cowsay` just do it and not lecture

---

src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-postprocess.cxx
src/libpriv/rpmostree-postprocess.h
tests/compose/test-container.sh

Now that we have `rpm-ostree container-encapsulate` which generates
chunked reproducible images, it makes sense to generalize this again
(particularly as part of "yum image") to also build non-bootable
base images (i.e. that don't have a kernel or SELinux labeling).

compose: Fix `container` to work again, add a test

---

rust/src/isolation.rs
rust/src/sysroot_upgrade.rs
src/daemon/rpm-ostreed.service.in

This is a different approach to
https://github.com/coreos/rpm-ostree/pull/3239
A core principle I want to maintain going forward is that the host
updates is isolated from containerized applications.
Today for example the containers/storage stack will do things like
access `~/.docker` and worse things like `/var/lib/containers` for
caching purposes.
Quite a while ago when we added the `rpm-ostree-countme.service`
we also added a use of `DynamicUser=yes` there, but only for that
service.
I was thinking about this and realized that systemd for quite some
time has given us the ability to have our own code opt-in to
the user ID switch; this is the `+` prefix to the `ExecStart`.
(One side effect is this *also* disables the existing `ProtectHome`
etc. but as we move to isolate more that will be …

Use `DynamicUser=yes` for main service, isolate container fetch

---

src/app/rpmostree-builtin-status.cxx
tests/vmcheck/test-misc-2.sh

This tripped up libostree installed tests which parses it directly from
`rpm-ostree status`:
https://github.com/ostreedev/ostree/blob/4471c252a9c9/tests/kolainst/destructive/staged-deploy.sh#L104
We should change that to use `--json` instead, though it was useful in
this case. Add a test here instead that would've caught this.
Fixes: 76e55de4 ("app/status: Reuse `print_values` to print rpmmd
repos")

app/status: Fix printing commits without rpmmd-repos metadata

---

src/daemon/rpm-ostreed.service.in

This fixes https://bugzilla.redhat.com/show_bug.cgi?id=2111817
The way systemd implements `InaccessiblePaths` involves
recursively traversing all mounted paths in the target root, and
unmounting them; this takes about a tenth of a second in the kernel.
Further, after each unmount, it also re-parses
`/proc/self/mountinfo`.  The combination of these two things
makes handling mounts there `O(N²)` in userspace CPU time.
The implementation of `BindReadOnlyPaths` seems better; it just
effectively overmounts, which avoids any `O(N²)` behavior.

Switch to `BindReadOnlyPaths` for `/var/lib/containers`

---

.gitignore
Makefile-daemon.am
src/daemon/rpm-ostree-bootstatus.service
src/daemon/rpm-ostree-countme.service
src/daemon/rpm-ostreed-automatic.service
src/daemon/rpm-ostreed.service

First, there's no reason anymore to add `@bindir` to our systemd units.
systemd itself has had support for traversing default paths since
at least RHEL8.  I think the absolute path requirement dates
to RHEL7 era systemd.
(We were also subsituting some bits for ASAN, but that's been
dead code for a while and in any case would have been better
handled by injecting a drop-in into `/etc`)
Second, the build system has always been buggy in that we
were missing rules to regenerate when the source unit changed,
which caused me quite a bit of debugging confusion at one point.

build-sys: Stop generating systemd units

---

rust/src/builtins/compose/commit.rs
rust/src/cliwrap/yumdnf.rs
rust/src/core.rs
rust/src/ffiutil.rs
rust/src/history.rs
rust/src/importer.rs
rust/src/live.rs
rust/src/lockfile.rs
rust/src/treefile.rs

We haven't yet enabled gating on clippy here, but I recently
discovered the `--fix` mode which is *so nice* for plowing through
things like the "extra &" lints.

rust: Run `cargo clippy --fix`

---

rust/src/utils.rs

I want to be able to detect in OCP when we have a new enough
rpm-ostree to use the container path.
I started doing some version-number parsing, but then realized
what we really want is a feature.
(That said, now that I think about it a bit more this feature
in theory should be dynamic, e.g. the daemon could detect on
startup whether `/usr/bin/skopeo` exists and is new enough, etc.
But, no need to block on that right now)

Add an always-on `container` feature

---

src/libpriv/rpmostree-kernel.cxx
tests/compose/test-misc-tweaks.sh
tests/kolainst/destructive/container-image

There's a valid use case of installing a 3rd party RPM which has
pre-built kmods for *multiple* kernel versions.  What we care about
here is that there aren't actually multiple kernel binaries aka
`vmlinuz`.
Closes: https://github.com/coreos/rpm-ostree/issues/3965

core: Ignore subdirectories of `/usr/lib/modules` without a kernel

---

.git-blame-ignore-revs

We can include in this file commits which do mechanical changes like
linting that are rarely of value when tracing through history. You can
then tell `git blame` to ignore those commits using:
```
git config blame.ignoreRevsFile .git-blame-ignore-revs
```
The GitHub blame UI automatically does this.
Closes: #3963

Add .git-blame-ignore-revs and seed with `clang-format` commit

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/container.rs
rust/src/lib.rs
src/app/rpmostree-builtin-ex.cxx
src/app/rpmostree-ex-builtins.h
tests/kolainst/destructive/container-update-inplace

This experimental command is intended to be mainly used in OCP
where we're trying to do a cutover to the new format container images.
However, we have the problem of old disk images where the rpm-ostree
there is too old to understand the container bits.  (Not to mention
skopeo is too old)
This code (+ integration test) demonstrates running the new OS
update *as a privileged container* which mounts the host filesystem
and performs the update that way.
A downside of this is that we only write the raw ostree commit;
we don't write the container-ostree refs; in other words, the
next update will need to re-pull the container.  That's...fixable,
it just requires a bit more nontrivial work that we can do later
as an optimization.

Add `ex deploy-from-self`

---

rust/src/utils.rs
src/libpriv/rpmostree-kernel.cxx
tests/compose/test-misc-tweaks.sh
tests/kolainst/destructive/container-image

Add an always-on `container` feature
I want to be able to detect in OCP when we have a new enough
rpm-ostree to use the container path.
I started doing some version-number parsing, but then realized
what we really want is a feature.
(That said, now that I think about it a bit more this feature
in theory should be dynamic, e.g. the daemon could detect on
startup whether `/usr/bin/skopeo` exists and is new enough, etc.
But, no need to block on that right now)
(cherry picked from commit e7a364781c5faea029ab36d3641e5e416176f03d)
---
core: Ignore subdirectories of `/usr/lib/modules` without a kernel
There's a valid use case of installing a 3rd party RPM which has
pre-built kmods for *multiple* kernel versions.  What we care about
here is that there aren't actually multiple kernel binaries aka …

[rhel8] Two cherry picks

---

tests/common/libvm.sh
tests/kolainst/destructive/container-image
tests/vmcheck/test-cached-rpm-diffs.sh
tests/vmcheck/test-download-only.sh
tests/vmcheck/test-layering-basic-2.sh
tests/vmcheck/test-layering-relabel.sh
tests/vmcheck/test-layering-relayer.sh
tests/vmcheck/test-layering-rpmdb.sh
tests/vmcheck/test-layering-unified.sh
tests/vmcheck/test-misc-2.sh
tests/vmcheck/test-override-local-replace.sh
tests/vmcheck/test-override-remove.sh

To ensure we consistently have the `ostree.bootable` key which
we'd like to make mandatory in the future.
cc https://github.com/ostreedev/ostree-rs-ext/commit/9c4a75b3778a3f2fdece095f8f5f7a6289ab512d

tests: Use `--bootable` when generating derived commits

---

Cargo.lock
tests/kolainst/destructive/container-image

Mainly for the whiteout support, which is going to be
really important for handling package overrides.

rust: Bump to ostree-ext 0.8.4

---

docs/treefile.md
rust/src/treefile.rs

This has the same rationale as https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table
In FCOS we're using `rojig` solely for the `name` value; with this
we can add
```
metadata:
name: fedora-coreos
```
into the FCOS manifest and stop (ab)using `rojig`.

treefile: Add generic metadata

---

src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h

core: Initialize unprivileged member variable
This was added a while ago but apparently never used; prep for
future work around unprivileged builds.
---
core: Add an API to deinitialize libdnf
The compose side currently deallocates the whole core object.  Today
the commit logic is duplicated in compose/build and core.  This will
help move us fully to using the core for commit.
---
core: Also only set bootable metadata if `!container`
The commit logic is duplicated between core/compose; this currently
doesn't matter, but it will in the future when we unify these.
---

A few prep patches for unprivileged compose/build

---

ci/ridiculous-rhel-devel-workaround.sh
rust/src/client.rs

It looks like util-linux in the container is in sync again with the one
we clone, so we can just install what we need. However using yum
instead of rpm avoids the exit code 24 and might future proof this
in case the dependencies get out of sync again.

ridiculous-rhel-devel-workaround: use yum localinstall instead of rpm -U

---

ci/test-container.sh
rust/src/cliwrap/rpm.rs

This was breaking `rpm -e ansible` in https://github.com/coreos/coreos-layering-examples/blob/2da697387875f2f24cc697cf2871c4b212f9ff43/ansible-firewalld/Dockerfile#L12 when cliwrap is enabled.

cliwrap/rpm: Don't drop privileges in a container image

---

rust/src/client.rs

This was introduced in a previous patch; since the imports are only used in tests, move them there.

client: Fix some unused variable warnings

---

src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-composeutil.cxx
src/app/rpmostree-composeutil.h

It's been an unused parameter since we moved the checksum logic into the treefile.
Prep for future work in pushing the checksum computation into core.

compose: stop passing JSON treefile to function computing checksum

---

Cargo.toml
packaging/rpm-ostree.spec.in

Way back when, we landed a2bbc12812cb3a012cc4af50ff918dca21795c9e "rust: Enable lto by default".
However at the time, rpm-ostree was a C program with a Rust shared library.  Later we flipped it to being a Rust program with a C++ shared library.
And...that fixes the problem of leaking symbols that motivated having LTO on by default.
Let's defer the decision of using LTO to higher level build systems; operating systems/distros might set `RUSTFLAGS=-C lto` globally or per package as desired.
The immediate motivation here is that I don't always remember to do non-release builds locally and LTO is still a lot slower than non-LTO.

build-sys: Disable LTO by default

---

tests/common/libvm.sh

For some reason in CI this seems to flake sometimes; probably because the test VM is being slow, and podman's timeout here manifests as an error.
```
[2022-09-12T07:50:36.497Z] FAIL: autoupdate-check
...
[2022-09-12T07:50:36.497Z]    autoupdate-check: ++ vm_cmd podman rm -f ostree_server
[2022-09-12T07:50:36.497Z]    autoupdate-check: ++ ssh -o User=root -o ControlMaster=auto -o ControlPath=/dev/shm/ssh-vmcheck-1662968784022193459.sock -o ControlPersist=yes -F /tmp/test.5GM9dO/ssh-config vmcheck podman rm -f ostree_server
[2022-09-12T07:50:36.497Z]    autoupdate-check: time="2022-09-12T07:50:30Z" level=warning msg="StopSignal SIGTERM failed to stop container ostree_server in 10 seconds, resorting to SIGKILL"
[2022-09-12T07:50:36.497Z]    autoupdate-check: …
```

ci: Tweaks for stopping infra container

---

rust/src/compose.rs
src/app/rpmostree-compose-builtin-tree.cxx

The new `compose image` container-native flow has a gap: we need to be able to specify an input ostree repository for the `ostree-layers` and `ostree-override-layers` bits.
I'm experimenting with rebasing the guts of `cosa build` for FCOS on top of `compose image`, and this is the main gap.

compose-image: Add `--layer-repo` option

---

src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-composeutil.cxx
src/app/rpmostree-composeutil.h
src/daemon/rpmostree-sysroot-upgrader.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h

core: Make checksum API support caller picking the algorithm
Prep for deduplicating with compose side which uses SHA-256.
---
Deduplicate code to compute state digest
Like most projects of nontrivial size, we're really good at
accumulating little bits of duplicated code.  Like barnacles on a
ship.
In this case, we have duplicate code to compute the "state checksum"
between the compose side and the core.  And for extra fun,
they used different checksum algorithms (SHA-256 vs SHA-512) for
probably no good reason.
Anyways, deduplicate them.  This is prep for properly pushing
more logic down into the core.
---

Deduplicate code to compute state digest

---

tests/kolainst/destructive/container-image

We're seeing this flake increasingly in CI; I think Prow may have gotten a bit slower?
- Update the test metadata to use the new kola YAML format and add a comment
- Bump the timeout
- Add another missing `--compression-fast`

tests/container-image: Add another fast compression, bump timeout

---

rust/libdnf-sys/cxx/libdnf.hpp
src/libpriv/rpmostree-util.cxx

Noticed by RHT-internal static analyzer:
* ensure package entries are not `NULL` before dereferencing them.
* drop an incorrect `noexcept` annotation, as `rust::String` will throw on invalid UTF-8.

libpriv: misc fixes from static code checking

---

tests/compose-image.sh

The test here flaked I think because the repository changed during the test, or we hit a different mirror.  Add `--offline` to ensure reproducibility.

tests: Use `--offline` for second build

---

.github/workflows/ci.yaml

Differential ShellCheck is a GitHub action that performs **differential ShellCheck scans** on shell scripts changed via PR and reports results directly in PR. The beauty of differential scans is that you will get **reports only about newly added defects**. 
Since this repository has few shell scripts, I think you might find some value in having a shell linter. Differential ShellCheck action is able to produce reports in SARIF format. GitHub understands this format and is able to display it nicely as a PR comment, and on the `Files Changed` tab, please see below.
Documentation is available at [@redhat-plumbers-in-action/differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme). Let me know If you are missing some feature or setting. I'm always …

ci(lint): add shell linter - Differential ShellCheck

---

Cargo.lock

Mainly this picks up improvements for `ostree container commit`.

rust: Update to ostree-rs-ext 0.8.5

---

Cargo.lock

rust: Update to ostree-ext 0.8.6

---

rust/src/compose.rs

This is something we want to support in general, and is needed for replacing the FCOS build process with this.

compose-image: Support `--lockfile`

---

rust/src/sysroot_upgrade.rs
rust/src/utils.rs

In OCP we link this to the kube pull secret, which is mode 0600.
Default to reading it as root and passing it via a memfd.
Closes: https://github.com/coreos/rpm-ostree/issues/4032

container: Ensure unprivileged fetch can read `/run/ostree/auth.json`

---

docs/container.md

It exists now; let's highlight it first, and move the "migrate existing ostree commits" into a secondary section.

docs: Describe `compose image`

---

Cargo.lock

rust: Bump ostree-ext

---

src/app/rpmostree-override-builtins.cxx

Previously,
```
$ podman run --rm -ti quay.io/fedora/fedora-coreos:stable
$ rpm-ostree override replace foo
**
rpm-ostreed:ERROR:src/app/rpmostree-override-builtins.cxx:203:gboolean handle_override(RPMOSTreeSysroot*, RpmOstreeCommandInvocation*, const char* const*, const char* const*, const char* const*, GCancellable*, GError**): assertion failed (fds.size () > 0): (0 > 0)
Bail out! rpm-ostreed:ERROR:src/app/rpmostree-override-builtins.cxx:203:gboolean handle_override(RPMOSTreeSysroot*, RpmOstreeCommandInvocation*, const char* const*, const char* const*, const char* const*, GCancellable*, GError**): assertion failed (fds.size () > 0): (0 > 0)
Aborted (core dumped)
```
Now:
```
$ rpm-ostree override replace foo
error: Non-local replacement overrides not implemented yet
```

override: Don't crash if argument produces no file descriptors

---

tests/common/libtest.sh
tests/kolainst/destructive/apply-live

In our other offline tests we do a rebase to a `vmcheck` ref; let's add a helper that does that so that things that want to test *package* upgrades using the offline repo don't try to access the real FCOS ostree repo.

tests: Add a helper to go more fully offline

---

Cargo.lock

The main motivation is to ship the new `ostree container commit` semantics for OCP 4.12.
Besides that we mostly have small compatible fixes https://github.com/ostreedev/ostree-rs-ext/compare/ostree-ext-v0.8.4...ostree-ext-v0.8.7

rhel8: rust: Bump to ostree-ext 0.8.7

---

rust/src/cliwrap/kernel_install.rs

This fixes kernel overrides in rhel8 at least, xref https://bugzilla.redhat.com/show_bug.cgi?id=2122299
We really need to unify the c++/rust code here.

[rhel8] cliwrap: Also inject /dev/random into cliwrap'd dracut

---

src/libpriv/rpmostree-core.cxx
tests/kolainst/destructive/override-pinning
tests/kolainst/kolainst-build.sh

The tightly-scoped function `rpmostree_find_and_download_packages` function just takes a query and returns fds to downloaded packages. It does not do any depsolving, so it's up to us to select the exact package we want to download. This means explicitly telling libdnf we want the latest version. This matches e.g. `dnf download`.
Closes: #4037

core: Filter for latest when downloading packages

---

rust/src/builtins/apply_live.rs
tests/kolainst/destructive/apply-live
tests/kolainst/kolainst-build.sh

Reolves #3992 
apply-live.rs: Does a daemon-reload after configuration changes made to /usr/lib/systemd/system
This is done to avoid prompting the user for restarting "some" services, which creates confusion.

apply-live: Invoke systemctl daemon-reload after unit files change

---

src/libpriv/rpmostree-kernel.cxx

Before commit 80bb67c2c9fb4e4048880963d04d3a4d36c85b9a, rpm-ostree required there is only one directory in `/usr/lib/modules` and the directory represents the installed kernel. However, it was revealed that 3rd-party RPMs can have pre-built modules for several kernel versions, and the requirement prevented from installing them. The commit was intended to solve the problem by ignoring directories which do not contain a file named `vmlinuz`.
However, the upstream kernel actually produces RPMs without `vmlinuz` in `/usr/lib/modules`, and the logic introduced by the commit prevented them from being installed.
This change replaces the logic with yet another alternative that retrieves the kernel version from the kernel file name in the boot directory. The kernel version can be used to identify …

core: Get the kernel version from the kernel path

---

rust/src/container.rs

This really must be the new default since we want to drop the old format very soon.

container: Encapsulate at format version 1 by default

---

src/app/libmain.cxx
src/app/rpmostree-builtin-rebuild.cxx
tests/kolainst/nondestructive/misc.sh

Right now `ex rebuild` only works in an (ostree) container and trying to run it on an ostree host system, despite all the checking in that function just segfaults.
And the reason here is very illuminating: We were passing `NULL` for the out parameter for the DBus client.  Let's use that to instead be the signal that a command is current container *only*.
But, this is really a perfect example of where Rust would have entirely prevented this problem.

rebuild: Fix logic for container-only handling

---

.cci.jenkinsfile
rust/src/sysroot_upgrade.rs
tests/kolainst/destructive/layering-fedorainfra
tests/kolainst/destructive/layering-modules

This is prep for https://github.com/ostreedev/ostree-rs-ext/issues/332

upgrade: Warn and sleep if we find a deprecated v0 format container

---

.github/workflows/ci.yaml
ci/container-build-integration.sh
src/libpriv/systemctl-wrapper.sh

We need to honor the use of `systemctl` when executed by dracut.
This only ocurrs right now in the non-unified container path.
---
ci: Add a test case for container builds
This is derived from code added in
https://github.com/ostreedev/ostree-rs-ext/commit/972a1349d7643de7dd61d953d4b924b8e069bebd
Basically, let's test that two representative coreos-layering-examples
still build.
---

systemctl-wrapper: Pass through usage of --root directly && container ci

---

rust/src/composepost.rs
tests/compose/test-basic.sh

First motivation: this logic is not idempotent as it should be, and someone hit this when trying to test out a local commit created via `compose commit`.
But bigger picture, quite a while ago we did
https://github.com/ostreedev/ostree/commit/73e3ccc401829025a9151fddff29d67a0ac2321d
I think we're at the point where we can hard require that updated ostree.

composepost: Drop unnecessary injection of presets

---

Cargo.lock
rust/src/container.rs

Also, cool, this drops out structopt and a bunch of duplicate dependencies!

Update to ostree-ext 0.8.8

---

rust/src/client.rs
src/app/rpmostree-clientlib.cxx

Before:
```
$ sudo rpm-ostree install foobar.rpm
error: Preparing D-Bus arguments: No such file or directory (os error 2)
```
After:
```
$ sudo rpm-ostree install foobar.rpm
error: Preparing D-Bus arguments: Handling argument foobar.rpm: No such file or directory (os error 2)
```
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2134215#c10

app: Improve error-prefixing in local RPM file handling

---

src/daemon/org.projectatomic.rpmostree1.xml
src/daemon/rpmostreed-os.cxx
tests/common/libtest.sh
tests/kolainst/Makefile
tests/kolainst/nondestructive/misc.sh

This is to implement one of missing methods required for gnome-software to stop calling libdnf directly in it.
See https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1793 for more information.

daemon: Implement ListRepos method

---

src/app/rpmostree-builtin-status.cxx
tests/kolainst/nondestructive/misc.sh

Unfortunately the implement involves some ugly grubbing through GVariant...really need to port this stuff to Rust.
Closes: https://github.com/coreos/rpm-ostree/issues/2829

status: Make `--booted --json` do the expected thing together

---

.github/workflows/ci.yaml
ci/test-container.sh
rust/src/builtins/scriptlet_intercept/groupadd.rs
rust/src/builtins/scriptlet_intercept/useradd.rs
rust/src/builtins/scriptlet_intercept/usermod.rs
src/libpriv/rpmostree-container.cxx
src/libpriv/rpmostree-scripts.cxx
tests/kolainst/kolainst-build.sh

First, right now our container flow doesn't use the "unified core" mode which means we aren't intercepting scripts.  We hence can't set the environment variable which gives us the package name.
Rework the sysusers file generation to not include the package name - in the end, while it is useful for debugging, in practice I don't think it's necessary.
Next, if we're in a container build, turn on the sysusers.d interception by default.  I think this is the default stance we should be taking now, and the container flow is a fresh new API.
Finally, add support for `useradd -G` which is used by libvirt, e.g. https://src.fedoraproject.org/rpms/libvirt/blob/rawhide/f/libvirt.spec#_1621
`useradd -r -u 107 -g qemu -G kvm -d / -s /sbin/nologin -c "qemu user" qemu`

Rework useradd(etc) sysusers integration to work in container flow

---

ci/container-build-integration.sh

https://github.com/coreos/coreos-layering-examples/pull/37 changed Dockerfile to Containerfile which now breaks our CI.

ci: use Containerfile instead of Dockerfile

---

src/app/rpmostree-builtin-deploy.cxx
tests/kolainst/nondestructive/misc.sh

Closes: https://github.com/coreos/rpm-ostree/issues/4110

deploy: Don't crash if no revision specified with --register-driver

---

Cargo.lock
tests/kolainst/destructive/container-rebase-upgrade

tests: Add a test case that verifies remote registry + podman
This test case verifies rebasing and then upgrading from
a remote registry.
---
Update to ostree-ext 0.8.9
In particular this should fix us trying to load the authfile
Closes: https://github.com/coreos/rpm-ostree/issues/4107
---

Update to ostree-ext 0.8.9

---

tests/vmcheck/test-override-kernel.sh

https://bodhi.fedoraproject.org/updates/FEDORA-2022-267416288f etc.

tests/override-kernel: Adapt for Linux kernels newer than 5

---

src/libpriv/rpmostree-util.cxx

This seems to only be happening with newer gcc (or something in the glib2 headers changed?).

util: Fix `-fpermissive` warning

---

src/libpriv/rpmostree-postprocess.cxx
tests/kolainst/nondestructive/misc.sh

There is a bug in the latest semanage code which causes an invocation of `semodule --rebuild-if-modules-changed` to still write a policy even though nothing changed since a full policy build. On FCOS and RHCOS, this bug is triggered as early as `ostree admin deploy` in cosa when creating the disk images. This results in shipping images with a policy diff baked in.
Hack around this by immediately rerunning
`semodule --rebuild-if-modules-changed` after building the policy.
Fixes: https://github.com/openshift/os/issues/1036

libpriv/postprocess: work around semanage bug

---

src/libpriv/rpmostree-postprocess.cxx
tests/kolainst/nondestructive/misc.sh

There is a bug in the latest semanage code which causes an invocation of `semodule --rebuild-if-modules-changed` to still write a policy even though nothing changed since a full policy build. On FCOS and RHCOS, this bug is triggered as early as `ostree admin deploy` in cosa when creating the disk images. This results in shipping images with a policy diff baked in.
Hack around this by immediately rerunning
`semodule --rebuild-if-modules-changed` after building the policy.
Fixes: https://github.com/openshift/os/issues/1036
(cherry picked from commit 479050e7540dc90de9ec6f49960b98e095537224)

[rhel8] libpriv/postprocess: work around semanage bug

---

docs/treefile.md
rust/src/treefile.rs
tests/compose-image.sh

As part of our expansion into a general "dnf image", it now makes total sense to use what's today `rpm-ostree compose image` to generate *non*-bootable container images.  For example, we could use this to generate coreos-assembler.
Then, we have the same compelling features that we use for the OS that apply there:
- sane change detection
- chunking
We could also use this to generate other containers, such as our buildroot image.

treefile: Make `container: true` opt-in to saner defaults

---

Makefile-daemon.am

This is a fixup for the previous change to not generate the systemd units.

build-sys: Don't delete systemd units in `make clean`

---

docs/container.md
docs/layering.md
rust/src/cliwrap/yumdnf.rs
src/app/rpmostree-builtin-rebase.cxx
tests/kolainst/destructive/container-image

I think we have sufficient experience with this to call this functionality officially stable.

Stabilize container functionality

---

rust/src/compose.rs
tests/compose-image.sh

I think we should also support this in the treefile, but adding it to the CLI is straightforward and useful in cases where one wouldn't want to invalidate the cache.
Closes: https://github.com/coreos/rpm-ostree/issues/4133

compose/image: Add `--label`

---

src/daemon/rpmostree-sysroot-upgrader.cxx
tests/kolainst/destructive/container-image

In this whole project of "ostree native containers", there's been some fuzziness as far as whether the container stuff is just a "transport" or whether it more *replaces* the ostree data.
We definitely have support for the former, which we need.
But there's this confusing leftover logic on the client side which uses the base ostree commit if we can - which we can *only* do if there's exactly one container image layer.  Which...is really a dead approach now that we have "chunked" container images.
Switch to always deploying the merge commit, since that's what we'll use in all real production scenarios.
This is prep for image layer GC handling - we want to be able to *always* fetch the container image merge commit.
Currently trying to do that trips up in our integration tests which use a …

Always use merge commit for container deployments

---

Cargo.lock

Pulls in two notable bugfixes.

Update to ostree-ext v0.9.1

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/lib.rs
rust/src/sysroot_upgrade.rs
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-transaction-types.cxx
tests/kolainst/destructive/container-image

Depends:
- https://github.com/coreos/rpm-ostree/pull/4137
- https://github.com/ostreedev/ostree-rs-ext/pull/403
---
daemon: Query container image commit
If a container image reference is pruned, we must not error
out when computing the status.  The deployment roots will hold
a strong reference to the deployed commit, so query via the commit
digest to find metadata about the pulled container image.
---
When rebasing, prune previous container by default
When using `rpm-ostree rebase` on ostree branch names, by
default we prune the previous branch/ref to avoid leaking
space (i.e. requiring the user/admin to manually prune it).
We do have the `--skip-purge` option to suppress this behavior.
When we added the container bits, we ignored this at the time.
But we really need to do this by …

Properly prune previous containers when rebasing

---

rust/src/composepost.rs

composepost: Port default target bits to cap-std
Part of an ongoing effort to drop `openat`.
---
composepost: Port remove files handling to cap-std
Part of an ongoing effort to drop `openat`.
---
composepost: Port script function to cap-std
Part of an ongoing effort to drop `openat`.
---
composepost: Port rpmdb symlinking to cap-std
Part of an ongoing effort to drop `openat`.
---
composepost: Port os-release handling to cap-std
Part of an ongoing effort to drop `openat`.
---
composepost: Port outer wrapper function to cap-std
Part of an ongoing effort to drop `openat`.
---

composepost: A few more cap-std porting patches

---

.github/workflows/ci.yaml
ci/test-container.sh
configure.ac
packaging/rpm-ostree.spec.in
src/libpriv/rpmostree-core.cxx
tests/common/libtest.sh
tests/compose-image.sh
tests/compose.sh
tests/kolainst/destructive/layering-modules
tests/vmcheck/test-override-kernel.sh

(FCOS was bumped to Fedora 37, which of course we hadn't been testing here until now, so time to make the necessary adjustments)
The interrupt safety API was dropped as being unnecessary.

build: Compile with rpm 4.18

---

docs/treefile.md
rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/extensions.rs
rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-core.cxx
tests/compose/test-basic-unified.sh
tests/compose/test-basic.sh

As part of improving our treefile composition capabilities, add a new
`repovars` field to the spec to support driving yum repo variables from
the treefile.
This will be used for example to parameterize the `rhel-8-server-ose`
yum repo definition based on the RHCOS stream.
There's more improvements possible here, like supporting treefile
variable substitution.

treefile: Support `repovars` key

---

packaging/rpm-ostree.spec.in

I.e. https://src.fedoraproject.org/rpms/rpm-ostree/c/f5f08e67231ae0e560b5cc1c844c48b3f7b33cb4
I'd like the spec in this repo to be canonical and the ones in dist-gits to just be direct imports.

packaging/spec: Upstream "Disable LTO on 32 bits"

---

packaging/rpm-ostree.spec.in

We're not going to be releasing for el8 anymore so shed this bit.

packaging/spec: Drop el8-specific block

---

rust/src/container.rs
rust/src/main.rs

We need to use `CxxResult` across the cxx (Rust <-> C++) bridge to ensure that we format errors correctly.  I noticed this when looking at an error from `rpm-ostree compose container-encapsulate`.

container-encapsulate: Format errors correctly

---

rust/src/utils.rs

This adjusts the path translation logic for `/etc` and `/opt`, fixing two buggy corner-cases.
Fixes: https://github.com/coreos/rpm-ostree/issues/4165

importer: fix translation of top directories

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/lib.rs
rust/src/sysroot_upgrade.rs
src/daemon/rpmostree-sysroot-core.cxx

This will handle cleaning up correctly after e.g. `rpm-ostree cleanup -p`.
Closes: https://github.com/coreos/rpm-ostree/issues/4179

Prune container image layers during cleanup too

---

Cargo.lock
Cargo.toml
rust/src/builtins/apply_live.rs
rust/src/client.rs
rust/src/compose.rs
rust/src/composepost.rs
rust/src/container.rs
rust/src/core.rs
rust/src/cxxrsutil.rs
rust/src/daemon.rs
rust/src/fedora_integration.rs
rust/src/initramfs.rs
rust/src/live.rs
rust/src/modularity.rs
rust/src/origin.rs
rust/src/passwd.rs
rust/src/sysroot_upgrade.rs
rust/src/testutils.rs
rust/src/utils.rs

Depends:
---
Fortunately, having cap-std at 1.0 lets us avoid level
of semver bumps going forward.

Update to ostree-ext 0.10, glib 0.16, cap-std 1.0

---

rust/src/sysroot_upgrade.rs

We had duplicate "prune image layers and log the result" logic; centralize that so we consistently get the number of layers pruned in the journal.

sysroot: Centralize layer prune + logging

---

rust/src/lockfile.rs

Fixes recent deprecation warnings.  The first one of these, doing "Get the current date&time, but set the time to a canonical value" was surprisingly hard and non-obvious.

lockfile: Port to non-deprecated chrono APIs

---

rust/src/sysroot_upgrade.rs

The `remove_image()` API is already idempotent, let's use that to handle the case where the user manually pruned the image.

upgrade: Make image pruning idempotent

---

src/daemon/rpmostree-sysroot-upgrader.cxx
tests/kolainst/destructive/container-rebase-upgrade

For https://github.com/coreos/rpm-ostree/issues/4176 We'll fix this at some point soon, but for now let's clearly error out.

upgrader: Can't currently check-only in container flow

---

docs/ex-rebuild.md

This PR fixes the reference to the treefile.md doc in the ex-rebuild.md page of the doc.

Fix the treefiles reference link in ex-rebuild.md

---

Makefile.bindings
ci/verify-cxx.sh
rust/src/lib.rs

This makes rebuilding the bindings more obvious.

Use default `all` rule for bindings

---

docs/administrator-handbook.md
man/rpm-ostree.xml
src/app/libmain.cxx
src/app/rpmostree-builtin-initramfs.cxx

This came up recently. It can be confusing to understand the difference between the two. Add some more details around that.

Documentation tweaks for the `initramfs` and `initramfs-etc` commands

---

README.md

And clean up the ascii-art diagram to mention this and while we're here use Unicode for line drawing.

README.md: More clearly link to container bits

---

src/app/rpmostree-builtin-status.cxx
src/daemon/rpmostreed-deployment-utils.cxx

We had a GC bug which then propagates into a hard daemon failure right now because we try to gather data on all deployments.
Make this non-fatal; we should try to stumble forward as much as possible so that one can e.g. perform an upgrade operation.

daemon: Make failure to query base image non-fatal

---

Cargo.lock

Pulls in a few fixes, including https://github.com/ostreedev/ostree-rs-ext/pull/432

Update to ostree-ext 0.10.1

---

rust/src/cliwrap/kernel_install.rs

This solves #4190, lot of copied code, needs cleaning up But does the approach makes sense?

cliwrap/kernel_install: use original systemctl when running dracut

---

rust/src/composepost.rs

Part of an ongoing effort to drop `openat`.

composepost: Port selinux timestamp tweaks to cap-std

---

Cargo.lock
Cargo.toml
rust/src/capstdext.rs
rust/src/composepost.rs
rust/src/ffiutil.rs
rust/src/passwd.rs
rust/src/utils.rs

This changes the last few bits to cap-std, and finally drops `openat`!

Finish porting to cap-std

---

tests/kolainst/destructive/container-image

This closes the CI gap found in
https://github.com/fedora-silverblue/issue-tracker/issues/392

ci: Verify package layering across upgrades

---

Cargo.lock

Update to cap-std-ext 1.0.2

---

src/daemon/rpmostreed-transaction.cxx

In https://issues.redhat.com/browse/OCPBUGS-2866 we're seeing a timeout, this will in the future help us potentially understand a root cause (is it sysroot loading being slow or the locking or something else)?

daemon: Add logging of sysroot load and locking times

---

src/app/rpmostree-builtin-cleanup.cxx
src/app/rpmostree-clientlib.cxx

We're seeing DBus method timeouts in some cases, this will help narrow down more precisely which method is failing (is it talking to the daemon at all, is it against the
transaction, etc)

client: Add some more error prefixing

---

rust/src/container.rs
tests/encapsulate.sh

I meant to do this after landing the ostree-ext updates in order to push forward https://github.com/coreos/coreos-assembler/pull/3214

encapsulate: Add `--copymeta-opt`

---

src/app/rpmostree-compose-builtin-tree.cxx
src/daemon/rpmostree-sysroot-upgrader.cxx
src/libpriv/rpmostree-core.cxx

Use `auto&` where we should
Spotted by cppcheck.
---
upgrader: Use g_strdup() to match g_free()
In practice, these are always the same, but the analyzer
doesn't know that today.
---

Two minor staticanalysis fixes

---

Cargo.lock
configure.ac
rust/src/isolation.rs
rust/src/sysroot_upgrade.rs

sysroot: Use ostree-ext isolation and auth paths
When the authfile code was drained into ostree-ext, we want
to start using it instead of having a duplicate copy.
xref https://github.com/containers/containers-image-proxy-rs/issues/44
---
Update to ostree-ext 0.10.3
This fixes pulls from authenticated registries.
Closes: https://github.com/containers/containers-image-proxy-rs/issues/44
---
build: Release 2022.19
This fixes pulls from authenticated registries.
---

sysroot: Fix conflicting authentication options && build: Release 2022.19

---

ci/prow/Dockerfile.ci-updates
ci/prow/Dockerfile.fcos
ci/prow/Dockerfile.fcos2
ci/prow/e2e-upgrades.sh
ci/prow/kola/upgrades

This will help cover the gap in pulling from remote authenticated registries.
The logic here mirrors that in
https://github.com/containers/bootc/blob/main/ci/run-kola.sh

ci: Add infrastructure for use with Prow upgrade testing

---

.github/workflows/ci.yaml

Fixes [deprecation warnings](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) for Node.js 12.

workflows: update actions to current major versions

---

src/libpriv/rpmostree-core.cxx
tests/compose/test-lockfile.sh

I'm trying to reuse the x86_64 lockfile generated during a cosa build to
ensure that multi-arch builds for the same version will match (on
streams where we don't yet have in-git lockfiles). One issue with that
is that some packages are arch-specific (like `bootupd`), so composes on
s390x will fail. This relaxes the lockfile logic so that a locked
package can be ignored if we didn't find that package name at all in the
repos when in non-strict mode.
Lockfile semantics are to restrict the set of packages the depsolver
picks from, not to force the installation of some packages even if
unrequested (this is true even for strict mode). So if a locked package
name doesn't exist at all in the repos, there are no packages to
restrict.
We still warn so that a mistyped package name can more easily …

core: Allow lockfiles to reference missing package names

---

src/daemon/rpmostreed-sysroot.cxx

This case is very different from the "brand new txn" path, and useful to write explicitly.

sysroot: Log when client joins an existing transaction

---

Cargo.lock

This specifically pulls in
https://github.com/dtolnay/cxx/commit/02d2600ebc5f9f25295a1f4c1ee84917cbc87690 which we need to compile on newer Rust versions.  (At least we do without relaxing must-use rules)

[rhel8] Update to latest cxx

---

Cargo.lock
rust/src/container.rs
rust/src/lib.rs
rust/src/sysroot_upgrade.rs
src/daemon/rpmostree-sysroot-core.cxx
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-transaction-types.cxx
tests/kolainst/destructive/container-image

Add version to status even for containers
Kind of embarrassing we didn't do this yet.  I hit this
while working on adapting zincati to update from containers.
(cherry picked from commit 1bab8ab2b1b85428f706b458b142d94c42bff832)
---
daemon: Query container image commit
If a container image reference is pruned, we must not error
out when computing the status.  The deployment roots will hold
a strong reference to the deployed commit, so query via the commit
digest to find metadata about the pulled container image.
(cherry picked from commit e2aee762c0a63d8c6630c3b0a8f761002376dfa3)
---
Update to ostree-ext 0.8.10
This includes fixes for image GC.
---
When rebasing, prune previous container by default
When using `rpm-ostree rebase` on ostree branch names, by
default we prune the previous …

OCPBUGS-4858: Backport image GC fixes to rhel8 branch

---

src/libpriv/rpmostree-kernel.cxx

When deriving the kver from the `vmlinuz` file found in `/boot` and `/usr/lib/ostree-boot`, we need to strip the trailing bootcsum digest if we added it. This is an issue for Fedora IoT, which still uses `boot-location: new` (we should probably move to deprecate that option in favour of just `modules`).
Closes: #4241

libpriv/kernel: fix kver parsing from vmlinuz in /boot and /usr/lib/ostree-boot

---

Cargo.lock

Closes: https://github.com/coreos/rpm-ostree/issues/4237

Update to ostree-ext 0.10.4

---

ci/prow/kola/upgrades

Not doing so resulted in a flake because zincati was repeatedly restarting.

tests/upgrades: Disable zincati

---

.gitignore
rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/lib.rs
rust/src/lockfile.rs
src/libpriv/rpmostree-core.cxx
tests/compose/test-lockfile.sh

This is a follow-up to 660c7294 ("core: Allow lockfiles to reference
missing package names"). There, we loosened semantics so that locked
package could be ignored if that package name doesn't exist at all in
the repos.
This patch loosens it further so that we don't immediately error out if
the locked package's NEVRA doesn't exist in the repos and instead rely
on the depsolver to error out for us. We still warn if we couldn't find
a locked package to be helpful.
Note the semantics of the lockfile are still maintained. In relaxed
mode, we exclude all packages of the same name as those found in the
lockfile. In strict mode, we exclude all packages not locked. The key
difference with this patch is that if a locked NEVRA couldn't be found
in the repos, it's only an error if the compose needs …

core: Further loosen lockfile handling

---

.gitignore

This reverts commit 4dfe6864cae0e351f67f51ba82a273a66f5475da.
It's cleaner for developers who use clangd to keep these entries in a repo-level exclude list or user-level `.gitignore` file.

Revert ".gitignore: add clangd-related files"

---

src/app/rpmostree-builtin-cleanup.cxx

We're seeing an `-EIO`, trying to chase down whether it's this cleanup code.

cleanup: Add some error prefixing

---

configure.ac
packaging/rpm-ostree.spec.in

v2023.1
- Log when a client joins an existing transaction.
- Fix local initramfs regeneration on systems composed with
`boot-location: new`.
- Fix container flow in Turkish locales ( https://github.com/coreos/rpm-ostree/issues/4237 )
- Loosen lockfile semantics so that a missing locked package does not trigger
an error unless the compose requires it.
- Drop support for locking by source packages.
- Update workflow actions to Fedora 37.
- Replace unmaintained actions-rs/toolchain with dtolnay/rust-toolchain.
- Add more error-prefixing in passwd, kernel, and cleanup-related paths.
- Add container-based upgrade test via Prow.
```
Benjamin Gilbert (2):
workflows: update actions to current major versions
workflows: replace actions-rs/toolchain with dtolnay/rust-toolchain
Colin Walters (8):
ci: …
```

Release 2023.1

---

Cargo.lock
rust/src/compose.rs
rust/src/sysroot_upgrade.rs

In preparation for https://github.com/ostreedev/ostree-rs-ext/pull/454

Update ostree-ext, use version API

---

rust/src/compose.rs

I've fairly often seen large image pushes (e.g. with lots of new blobs) failing when copying to at least `ghcr.io`.
Let's expose `--retry-times` from skopeo to start.
I'm a bit tempted to bump it to 3 by default.

compose/image: Add `--copy-retry-times`

---

rust/src/treefile.rs
rust/src/utils.rs

This addresses the root cause of
https://github.com/coreos/rpm-ostree/issues/4029
Basically we were calling `set_repos_dir("")` on the libdnf side and it simply did not handle that, failing to open the directory.
(Though I'm not saying "Closes" since we should still fix the
file monitoring stuff)
I don't yet know why this seemed to work in some cases but not others though.

treefile: Return `.` instead of `""` for parent directory

---

man/rpm-ostreed.conf.xml
src/daemon/rpm-ostreed.conf
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-daemon.cxx
src/daemon/rpmostreed-daemon.h
tests/kolainst/destructive/initramfs-etc
tests/kolainst/destructive/layering-local

This knob provides an easy way for a sysadmin to disable all package
layering and initramfs customizations without having to muck around
with polkit policies. This has been requested a few times in the past
(and again recently) in environments where we want more safety checks
(e.g. Fedora IoT/RHEL for Edge). There's more we could do of course for
that use case (I think sealing `/etc` has come up, though that probably
belongs better in libostree), but this is low-hanging.
We do this at the upgrader level rather than higher up in the stack to
be sure we catch all paths, but also so that if the feature is enabled
on a system with existing customizations, rpm-ostree still permits doing
a `reset` to bring it back in line.
Closes: #4061

Support `LockLayering=true` config knob

---

rust/src/container.rs
rust/src/main.rs
src/libpriv/rpmostree-core.cxx
tests/common/libtestrepos.sh

It's been `ostree container` for a while, I don't think we need this alias anymore.  Searching reveals only usage in old forks of coreos-assembler etc.

Drop `ex-container` entrypoint

---

rust/src/main.rs

I just happened to glance at this main code; I think we can now drop this.

main: Drop deprecated `container-encapsulate` entrypoint

---

rust/src/core.rs
rust/src/lib.rs
rust/src/sysroot_upgrade.rs
src/daemon/rpmostree-sysroot-upgrader.cxx
src/libpriv/rpmostree-core.h
src/libpriv/rpmostree-util.cxx
src/libpriv/rpmostree-util.h

This is aiming to fix https://issues.redhat.com/browse/OCPBUGS-7275
Basically to handle the rpmdb transition from bdb to sqlite seamlessly,
we need to down-convert because for bad historical reasons we
use the *host* rpm stack to do writes; and here the host only
can write to bdb.
So on the next boot after an upgrade with layered packages, we will
be in a situation where the host rpmdb is bdb - this is the same
as a traditional dnf/yum system.
Where things diverge is that there the `rpmdb-migrate.service`
will kick in and mutate the system live.  In our case, such mutation
conflicts with our philosophy and technology.  What will happen
for us instead is that because we always start from the new base
image, we'll detect that host preferred rpmdb is `sqlite`, the
target is `sqlite`, and …

[rhel8] Temporarily transition rpmdb to bdb

---

Cargo.lock
rust/src/compose.rs
rust/src/container.rs

Uses the ostree container library to compare OCI compliant images

Add --compare-with-build to cli

---

docs/ex-replace.md

The kernel-vanilla-repos moved to a new location. Adjust the example accordingly.
While at it, also add kernel-modules-core (a new subpackage) and kernel-modules-extra
to the example, as the transaction will otherwise fail.

docs: adjust to new location of kernel-vanilla-repos

---

ci/prow/e2e-upgrades.sh
src/daemon/rpmostreed-transaction.cxx
tests/vmcheck/test-cached-rpm-diffs.sh

This fixes https://bugzilla.redhat.com/show_bug.cgi?id=2169622
The new glib changed to use non-abstract sockets by default,
which broke us because we'd slowly grown more isolation, specifically
the daemon has been using `PrivateTmp` for a while and we'd
been relying on abstract sockets to pierce that.
Change to use `/run` which should always be shared by client
and daemon.  While we're here, make it a well-known static path
because there can be only one transaction at a time.
We also do need to explicitly make the socket world-accessible
because that was the semantics of the previous abstract socket.
Also, plug leaks here by ensuring we call `g_dbus_server_stop()`.
(But really we should also change this to be crash safe, probably
with a temporary directory, but that's a larger change)

daemon: Use a socket in `/run`, require non-abstract

---

rust/src/scripts.rs

Ignore posttrans for kernel-rt-core which is used on OCP/RHCOS.

rust/src/scripts.rs: ignore posttrans for kernel-rt-core

---

packaging/rpm-ostree.spec.in

Otherwise, minimal environments like Anaconda might omit this. xref https://github.com/rhinstaller/anaconda/pull/4561#issuecomment-1442494914

spec: Add `Requires: /usr/bin/setpriv`

---

Cargo.lock

Mainly for Anaconda to use the new deploy CLI.

Bump ostree-ext

---

rust/src/lib.rs
rust/src/main.rs
rust/src/utils.rs
tests/common/libtest.sh
tests/kolainst/destructive/cached-sigs
tests/kolainst/destructive/layering-fedorainfra

main: Don't use timestamps and colors in tracing logs when running in systemd
It's just broken to write colors into the journal.  We also should
omit timestamps because journald already does that.
Motivated specifically by `ext.rpm-ostree.destructive.cached-sigs`
which started failing.
---
cached-sigs: Be compatible with `cosa build-fast`
cosa build-fast will not use a refspec; let's synthesize one since
it's required for this test.
---
libtest: Hack around regression in journalctl
See https://github.com/systemd/systemd/pull/26476#issuecomment-1465038424
A patch to improve `-n/--lines` together with `--grep` broke
our use in combination with `--after-cursor`.  Pipe instead
to `head -1` to hack around this.
---
tests/layering-fedorainfra: Bump to newer systemd
Trying to override with such …

A logging fix and attempt to fix the cached-sigs test

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/importer.rs
rust/src/lib.rs
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-importer.cxx
src/libpriv/rpmostree-importer.h

See https://bugzilla.redhat.com/show_bug.cgi?id=2177225
This is really a no-op on rhel9 and current Fedora, but trying to land the code here so we can have it run through CI, and then backport to rhel8.

core: Don't try to load rpm IMA sigs client side unless requested

---

Cargo.lock
Cargo.toml

I happened to notice that our Tokio was old; I'm not sure why dependabot wasn't updating it.

Bump tokio to 1.26

---

rust/src/scripts.rs

closes: https://github.com/coreos/rpm-ostree/issues/4341

rust/src/scripts: ignore rt and automotive debug scripts.

---

.github/workflows/ci.yaml

Also, update `differential-shellcheck` to the latest version (`v4.0.2`) - https://github.com/redhat-plumbers-in-action/differential-shellcheck/releases Push events are supported since `v4.0.0`.
Fixes:
- https://github.com/redhat-plumbers-in-action/differential-shellcheck/issues/215
- https://github.com/redhat-plumbers-in-action/differential-shellcheck/issues/222
This should get rid of annoying messages from the `github-code-scanning` bot.

ci: trigger `differential-shellcheck` workflow on `push`

---

.github/workflows/ci.yaml

Permissions `security-events: write` are required to upload scan results (SARIF) to GitHub successfully.
doc: https://github.com/redhat-plumbers-in-action/differential-shellcheck#usage
This should hopefully finally fix the issue:
- https://github.com/redhat-plumbers-in-action/differential-shellcheck/issues/222
/cc @cgwalters I'm sorry, I missed this detail the first time around.
logs: https://github.com/coreos/rpm-ostree/actions/runs/4519749017/jobs/7960410287#step:4:35
follow-up to:
- https://github.com/coreos/rpm-ostree/pull/4345

ci(fix): add missing permissions - `security-events`

---

tests/vmcheck/test-override-kernel.sh

Implementing the check for kernel-modules-core as we do on the fedora-coreos-config repo:
https://github.com/coreos/fedora-coreos-config/blob/testing-devel/tests/kola/rpm-ostree/kernel-replace#LL89C47-L89C66

tests/vmcheck/test-override-kernel: account for kernel-modules-core

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-pkg-builtins.cxx

Add --enablerepo=, --disablerepo and --setreleasever cli options. This options are only honored on the container path.
Closes: https://github.com/coreos/rpm-ostree/issues/4293

treefile: Add enablerepo/disablerepo/setreleasever cli options

---

ci/test-container.sh
rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/cxx.h
tests/compose-image.sh
tests/kolainst/destructive/layering-modules
tests/vmcheck/test-override-kernel.sh

This fixes the failures seen on: https://github.com/coreos/rpm-ostree/actions/runs/4743787372/jobs/8425291293?pr=4370

ci: Make sure cxx code is clang-formatted

---

Cargo.lock
deny.toml

I think we may have gotten sufficiently far behind on processing dependabot PRs that it just gave up?  Not sure.
Do a big bump to catch up.

Cargo.lock: Bump many dependencies

---

rust/src/cliwrap/kernel_install.rs

Fix typo in error log if initramfs generation fails

---

configure.ac
src/daemon/rpmostreed-transaction-types.cxx

Simplify idempotent operations.
Allows us to drop `existing_kargs` variable.
Fixes the corner case where `--append foo --append-if-missing foo` would append `foo` twice.
Uses new libostree OstreeKernelArgs API symbols:
ostree_kernel_args_contains
ostree_kernel_args_append_if_missing
ostree_kernel_args_delete_if_present
Signed-off-by: Rafael Garcia Ruiz <rafael.garcia@collabora.com>

kargs: Simplify idempotent append and delete operations

---

src/app/libmain.cxx
src/app/rpmostree-builtins.h
src/app/rpmostree-clientlib.cxx
src/daemon/rpm-ostreed-automatic.service

This replaces the need for `StandardOutput=null` in the automatic upgrade unit, and can also be used for custom upgrade units, such as that proposed in
https://github.com/coreos/fedora-coreos-docs/pull/540

app: Add a global `-q/--quiet` flag

---

rust/src/scripts.rs

Red Hat is planning to rename the kernel package to `kernel-redhat` in a future minor release of RHEL 9 (see related fedmag post[[1]]).
Extend the `%posttrans` hack to cover these new packages.
[1]: https://fedoramagazine.org/changes-eln-kernel-rpm-nvr/

scripts: Ignore kernel-redhat `%posttrans` scripts

---

.github/dependabot.yml
Cargo.lock

rust: Bump various crates
Dependabot still isn't keeping up.
---
rust: Bump dependabot PR limit to 6
To help it keep up.  But honestly I think what I really
want is a way to tell it to group a few likely-not-to-break crates
such as `anyhow`.
---

rust: Bump various crates &&  rust: Bump dependabot PR limit to 6

---

src/libpriv/rpmostree-output.cxx
src/libpriv/rpmostree-output.h

- Allocate a unique serial per Progress instance
- Output the serial alongside the text, which is really a unique string format that will tell us where in the code it's being called
- Add `g_debug()` output with both in the constructors, and just the serial in other methods
This should help us figure out on the daemon side which specific code is trying to do a percent progress while we have a plain task.
cc https://github.com/coreos/rpm-ostree/issues/4284

output: More daemon-side progress debugging

---

src/daemon/rpmostreed-sysroot.cxx
src/daemon/rpmostreed-transaction.cxx
src/libpriv/rpmostree-output.cxx
src/libpriv/rpmostree-output.h

This is needed because for transactions (which are always run in a thread today) we want output to go to the transaction's DBus progress.  But for other methods which are not transactions, we don't have a channel for status reporting, so output needs to
continue to go to the journal.   If we mix these two things due to
concurrent method invocations, the client may get confused and crash.
Closes: https://github.com/coreos/rpm-ostree/issues/4284

Make output handling thread-local

---

man/rpm-ostree.xml

So they're more discoverable and for consistency with other commands.

man/rpm-ostree: Document `status` switches

---

src/app/rpmostree-clientlib.cxx

This is actually quite important for general "understanding of the system" purposes. We can close this FIXME without needing to print the transaction type.
Motivated specifically by a theory that this may relate to https://github.com/coreos/rpm-ostree/issues/4284 if somehow the client gets confused as to which transaction it's monitoring.

client: Print when we're attaching to an existing transaction

---

tests/kolainst/destructive/initramfs-etc

Our tests should test the main interface now and avoid the warning.

tests: Drop `ex` from initramfs-etc

---

src/daemon/rpmostreed-os.cxx

We had no logging at all for the "non-transactional query" methods, and it would have been quite helpful to have them when debugging a recent problem.
Also, tweak some debug messages along the OS state reload path for clarity.

daemon: Add logging for invocations of non-txn methods

---

ci/test-container.sh

Since f36 was untagged from coreos-pool.

tests/container: Update package fixtures to f38

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h

Dependabot will update cxx, but not regenerate the bindings today.

Regenerate cxx bindings

---

Cargo.lock
Cargo.toml
rust/src/builtins/scriptlet_intercept/groupadd.rs
rust/src/builtins/scriptlet_intercept/useradd.rs
rust/src/builtins/scriptlet_intercept/usermod.rs
rust/src/builtins/usroverlay.rs
rust/src/cliwrap/rpm.rs

This Just Worked for the derive case, but man the builder/imperative path is painful.
This will pair with https://github.com/ostreedev/ostree-rs-ext/pull/381 so that we only have one version of clap in our depchain.

Port to clap v4

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/compose.rs
rust/src/lib.rs
src/app/rpmostree-compose-builtin-tree.cxx

compose: Oxidize bits propagating `core.fsync`
Prep for synchronizing the composefs keys too, but also
on general principle.
---
compose: Also propagate ex-{fsverity,composefs}
To aid https://github.com/ostreedev/ostree/pull/2640
---

compose: Also propagate ex-{fsverity,composefs}

---

Cargo.toml

This is nicer than having a hardcoded list.

build-sys: Use new `tier = 2` from cargo-vendor-filterer

---

docs/administrator-handbook.md
docs/ex-replace.md

Fixes #4054 
- Added example for local file overrides
- Added example or Fedora Koji/Bodhi overrides
- Added example for overriding podman based on the version defined in the Fedora updates-testing repo

Added more override examples

---

src/app/libmain.cxx

Fixes #4357 
- Added helper function to compare `RpmOstreeCommand` objects
- Used `qsort` to sort the array of `RpmOstreeCommand` commands alphabetically

Sorted builtin commands alphabetically

---

rust/src/importer.rs

rpm upstream did
https://github.com/rpm-software-management/rpm/commit/0f957330f24cdb2510e0bbdface54ffa8064b8ce
The file metadata is still duplicated in the header, and *that* seems unlikely to change soon.  So we can just safely drop this "sanity check".
Closes: https://github.com/coreos/rpm-ostree/issues/4437

importer: Drop non-root files in CPIO check

---

src/libpriv/rpmostree-core.cxx

I think originally something higher level was intending to catch this "reinstall exact base package version" case, but it's way simpler to just return a clear error here instead of crashing.
Assertions should only be used for things we're *pretty sure* can't be reached and particularly when it may be a hard to recover from internal consistency error.  That's not the case here.
Closes: https://github.com/coreos/rpm-ostree/issues/4141

core: Error out instead of aborting on reinstalls

---

packaging/rpm-ostree.spec.in

Updating the template to follow:
https://docs.fedoraproject.org/en-US/legal/update-existing-packages/
rawhide packages have been updated as well: https://github.com/coreos/fedora-coreos-tracker/issues/1497

packaging/rpm-ostree.spec.in: use SPDX license identifier

---

Cargo.lock
rust/src/sysroot_upgrade.rs
src/daemon/rpm-ostreed.service
tests/kolainst/destructive/container-image

Bump to ostree-ext 0.11.1
Mainly for the pulling from containers-storage fixes.
---
Drop isolation when fetching from containers-storage:
This enables
`rpm-ostree rebase ostree-unverified-image:containers-storage:localhost/mytestimage`
The history here is pretty fun:
- I changed rpm-ostreed to block access to `/var/lib/containers`
in https://github.com/cgwalters/rpm-ostree/commit/94666faad0d403f5830184d10b1729236d783a41
- We added basic support for fetching from containers-storage in
https://github.com/ostreedev/ostree-rs-ext/pull/396
which worked for ostree, but not rpm-ostree because of the above
- Then we changed to isolate skopeo fetches by default
https://github.com/ostreedev/ostree-rs-ext/pull/413/commits/48dfc0b74dc12bd11b0d697ba5302a6188ad795e
which broke it in ostree too, but …

Bump ostree ext &&  Drop isolation when fetching from containers-storage:

---

src/libpriv/rpmostree-postprocess.cxx

This drops a deprecation warning.
At this point, I think we can hard require the new policycoreutils.

postprocess: Use --refresh now

---

man/rpm-ostree.xml
src/app/libmain.cxx
src/app/rpmostree-builtins.h
src/app/rpmostree-pkg-builtins.cxx
src/daemon/org.projectatomic.rpmostree1.xml
src/daemon/rpmostreed-os.cxx

Fixes #1877 
Implemented Features:
- Builtin `search` command for rpm-ostree to search for packages within the set of repos (`rpm-ostree search kernel`)
- Allows multiple search terms (`rpm-ostree search kernel python`)
- Allows glob patterns (`rpm-ostree search *kernel`)
Edge cases covered:
- Returns from function when no packages are specified
- Outputs `No matches found.` when no packages match the search query

Add a `search` CLI verb and DBus API 

---

rust/src/builtins/scriptlet_intercept/groupadd.rs

According to Colin's pointer, this is to fix the error when running `rpm-ostree install libvirt` in container,
```
bash# env RPMOSTREE_EXP_BRIDGE_SYSUSERS=1 rpm-ostree install libvirt
...
+ test -v RPMOSTREE_EXP_BRIDGE_SYSUSERS
+ rpm-ostree scriptlet-intercept groupadd -- /sbin/groupadd -f -g 107 -r qemu
error: a value is required for '--force <force>' but none was supplied
For more information, try '--help'.
```

sysuers: fix error if running `groupadd` with `-f`

---

src/app/rpmostree-pkg-builtins.cxx
src/daemon/rpmostreed-os.cxx
tests/kolainst/nondestructive/misc.sh

Fixes #1877 
**New Implementations:**
- `kola` tests added
- Duplicate package removal feature fixed
- `Name & Summary` search feature fixed
**As stated in the commit message:**
Previously, the `Name & Summary` search function would only return results that contained ALL search terms within BOTH the name and summary. With this commit, results in which search terms match EITHER the name or summary will be returned. This better matches `dnf`/`yum` CLI functionality.
**Old `Name & Summary` search function:**
```
$ rpm-ostree search python3-jupyroot
===== Name Matched =====
python3-jupyroot : ROOT Jupyter kernel
```
```
$ rpm-ostree search python3-jupyroot kernel
No matches found.
```
**New `Name & Summary` search function:**
```
$ rpm-ostree search python3-jupyroot
===== Name Matched ===== …
```

Add `kola` tests and fix `Name & Summary` search

---

src/libpriv/rpmostree-kernel.cxx

It sometimes happens during osbuild that there are two kernel rpms installed while setting up the initial error message, leading to something like:
error: Finalizing rootfs: During kernel processing: Multiple vmlinuz- in usr/lib/ostree-boot
With the user unsure what the two kernel versions were. With this change we print the kernel versions.

kernel: Specify multiple kernel or initramfs in error message

---

ci/test-container.sh

- Use the fedora 37 ignition rpm for the override replace test
- Drop f36 and f37 tests
Took some of what @cgwalters did on #4496 that would need to be rebased after this.

ci/test-container.sh: use f37 ignition for replace test

---

rust/src/container.rs

This would have likely slightly helped debug
https://github.com/coreos/coreos-assembler/pull/3508#issuecomment-1629913936

container: Clarify error for nonexistent previous manifest file

---

rust/src/passwd.rs

passwd: Rename func `data_from_json` to `write_data_from_treefile`
---
passwd: sync `etc/{,g}shadow` according to `etc/{passwd,group}`
Refer to https://github.com/coreos/rpm-ostree/issues/49#issuecomment-1612626563, do testing:
1. Remove bin line in group and passwd
2. Build FCOS, see logs:
```
systemd.post: Creating group 'bin' with GID 1.
systemd.post: Creating user 'bin' (bin) with UID 1 and GID 1.
systemd.post: /etc/gshadow: Group "bin" already exists.
```
According to @cgwalters 's pointer:
The above log will lead systemd-sysusers (during systemd.post)
exit early before saving the updated `/etc/{passwd,group}` refer
to [code](https://github.com/systemd/systemd/blob/main/src/sysusers/sysusers.c#L820), and bin user/group will not be saved finally.
The root cause is that `gshadow` is …

passwd: sync `etc/{,g}shadow` according to `etc/{passwd,group}`

---

src/app/rpmostree-clientlib.cxx

Debugging https://access.redhat.com/support/cases/#/case/03562249 where we see just a bare `error: The connection is closed`.

client: Add an error prefix in deployment path

---

Cargo.lock
Makefile-rpm-ostree.am
rust/src/main.rs

This updates us to vendor the provisional-repair code.  One can now run `ostree provisional-repair` directly.
(Yes, it's very confusing how in rpm-ostree, we vendor the ostree-ext
source, and then install a wrapper symlink which tells the main
(C) `ostree` binary to call back into us... but it's how the
`ostree container` stuff has been working for a long time)

main: Update ostree-ext, add provisional-repair entrypoint

---

.cci.jenkinsfile
Cargo.lock
Cargo.toml
ci/test-container.sh
deny.toml
rust/src/main.rs

rust/src/main.rs: Add bootc entry point

---

docs/container.md

Fixes: https://github.com/ostreedev/ostree-rs-ext/issues/507
Documents: https://github.com/ostreedev/ostree-rs-ext/blob/main/lib/src/container/mod.rs
See: https://github.com/ublue-os/main/issues/132#issuecomment-1553869288

docs: Document ostree native container URL format

---

rust/src/main.rs

This reverts commit 2d07002d2e6a3516195a3e413e1047c6a7661365.
It turns out that this is used by osbuild today
https://github.com/osbuild/osbuild/blob/14d31633a4b14878735ed5222befb895b16de2d1/stages/org.osbuild.ostree.encapsulate#L112
We'll do a patch to port to the new API there but let's just carry this for $time where values of $time are probably at least a year.

Revert "main: Drop deprecated `container-encapsulate` entrypoint"

---

src/libpriv/rpmostree-postprocess.cxx

There is no particular cost to always adding composefs metadata to rpm-ostree composes, so always do so if libostree is new enough and has the support compiled in.

commit: Always enable generation of composefs metadata if possible

---

Cargo.lock
Cargo.toml
rust/src/builtins/scriptlet_intercept/groupadd.rs
rust/src/builtins/scriptlet_intercept/useradd.rs
rust/src/builtins/scriptlet_intercept/usermod.rs
rust/src/cliwrap.rs
rust/src/composepost.rs
rust/src/core.rs
rust/src/dirdiff.rs
rust/src/initramfs.rs
rust/src/passwd.rs
rust/src/treefile.rs

This works better with dependabot because there's only one thing to bump.
At the time, I thought cap-std would stay at 1.0 for the forseeable future, but that didn't happen.
xref https://github.com/bytecodealliance/cap-std/commit/963eebf3ab52b04a2e8b9ba88ce6308bbed5cbd0#r121651362

Use cap-tempfile via cap-std-ext

---

src/app/rpmostree-builtin-status.cxx

I don't think this is really reachable; current gcc just can't prove that if we return `TRUE` that we always set it.

status: Fix possibly uninitialized warning

---

Cargo.lock
rust/src/sysroot_upgrade.rs

To pull in several recent fixes.
Note that we now need to `require_bootable` when importing.

Bump to ostree-ext 0.11.5

---

packaging/rpm-ostree.spec.in

Use systemd macros to enable/disable the rpm-ostree-countme.timer unit following the global systemd presets.
This fixes the timer enablement on systems that do no preset-all like Fedora CoreOS.
See: https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_systemd

packaging/spec.in: Enable rpm-ostree-countme.timer following presets

---

man/rpm-ostree.xml

Came up on chat, and this is important since it differs from traditional `rpm/dnf` today.

man: Describe GPG key behavior

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/builtins/usroverlay.rs
rust/src/lib.rs
rust/src/main.rs
src/app/libmain.cxx
tests/kolainst/nondestructive/misc.sh

main: Move usroverlay parsing back to C++ consistently
Otherwise, we end up segfaulting because
`rpm-ostree -h usroverlay` confuses things.
Unfortunately, if we expose it publicly in our help text
it needs to have a C++ trampoline.
---
usroverlay: Pass arguments to `ostree admin unlock`
So that `--help` works.
Closes: https://github.com/coreos/rpm-ostree/issues/4508
---

Fix `rpm-ostree -h usroverlay` segfault

---

configure.ac
packaging/rpm-ostree.spec.in

v2023.7
This is a bugfix release that includes:
* A bootc-lib fix for https://github.com/containers/bootc/issues/112 which was breaking our builds.
* The fix for https://github.com/coreos/rpm-ostree/issues/4508 which caused segfaults when any flag was passed between the `rpm-ostree` command and `usroverlay` option.
```
Colin Walters (3):
man: Describe GPG key behavior
main: Move usroverlay parsing back to C++ consistently
usroverlay: Pass arguments to `ostree admin unlock`
Joseph Marrero (1):
Update bootc-lib
```
**Full Changelog**: https://github.com/coreos/rpm-ostree/compare/v2023.6...v2023.7

Release 2023.7

---

Cargo.lock

To pick up the critical fix in https://github.com/containers/containers-image-proxy-rs/pull/52/commits/95da872de1464d67fe38a1ccbb98e6f22087a189
Also happily this seems to drop out some now redundant dependencies.

Bump to containers-image-proxy 0.5.5

---

src/daemon/rpmostreed-os.cxx

Here `clang-analyzer` found a legitimate bug, through a quite deep call stack.  Before this change, providing zero search terms like this results in a segfault:
```
$ rpmostree_busctl_call_os Search as 0
```
In exactly the way predicted by the static analysis.
Verify we have at least one term at entry into the function, and also add further assertions later.

search: Fix a NULL ptr deref with zero terms

---

.github/workflows/autovendor.yml
packaging/make-git-snapshot.sh

packaging: Write to target/
This is already under `.gitignore` and ensures that things watching
for changes like IDEs won't transiently see temporary files.
---
ci: Add autovendor flow
This aids reproducibility to have an auto-generated vendor
snapshot that we save reliably.
---

packaging: Write to target/ &&  ci: Add autovendor flow

---

src/app/rpmostree-pkg-builtins.cxx
src/daemon/rpmostreed-os.cxx
src/daemon/rpmostreed-sysroot.cxx

sysroot: Silence clang-analyzer warning
I think this is another case of clang-analyzer not understanding
the "GError rules"; it's getting confused by the `NULL` checks here
and thinking that if `authority == NULL` it's possible `error == NULL`
too.  But it can't see into the implementation of libpolkit.
---
pkg-builtins: Add assertions to quiet clang-analyzer
In theory, the server could have not sent this data.  Add
assertions to require this.
---

Two unimportant clang-analyzer fixes

---

.github/workflows/autovendor.yml

I copied this from bootc but forgot that there we're auto-vendoring from the `cli` directory.  Fix this to work from the toplevel here.

ci/autovendor: Make it work

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h

We don't currently automate regenerating these when updates to the `cxx` crate land via dependabot.  We should probably add a gating CI check.

cxx: Regenerate

---

src/app/rpmostree-pkg-builtins.cxx
tests/kolainst/nondestructive/misc.sh

These only work in the container flow today, for anti-hysteresis reasons.

install/uninstall: Error out with --enablerepo on booted host

---

src/libpriv/rpmostree-core.cxx

core: Print total imported
It'd be slightly useful for debugging to cross-check
how many packages were imported.
xref https://github.com/coreos/rpm-ostree/issues/4565
---
core: Include repo name in download error
For better debuggability.
---
core: Add warning when we have pkgs to download in cache-only mode
To help debug https://github.com/coreos/rpm-ostree/issues/4565
---

core: Some minor debug patches for https://github.com/coreos/rpm-ostree/issues/4565

---

Cargo.lock
rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/lib.rs
rust/src/sysroot_upgrade.rs
src/daemon/rpmostree-sysroot-core.cxx
tests/kolainst/destructive/container-image

Update to ostree-ext 0.11.6
---
Remove unreferenced container images in cleanup, not rebase
This allows users to pin a deployment and have the container
image be retained.
Closes: https://github.com/coreos/rpm-ostree/issues/4391
---

Update to ostree-ext 0.11.6 && Remove unreferenced container images in cleanup, not rebase

---

.cci.jenkinsfile

As a workaround for a virtiofs bug:
https://gitlab.com/virtio-fs/virtiofsd/-/merge_requests/197
xref coreos/coreos-assembler#3428 (comment)
---

ci: Run cosa unprivileged

---

Cargo.lock
Cargo.toml

We had a problem in the previous release with having bootc float on a git commit because it ends up meaning "whatever happens to be on the developer's machine" when cutting a release, which is not OK from a reproducibility PoV.
Dependabot I think can help us update this.

Pin bootc to a git tag

---

Cargo.lock
Cargo.toml
rust/src/compose.rs
rust/src/container.rs
rust/src/dirdiff.rs
rust/src/importer.rs
rust/src/origin.rs

This chain of bumps gets us to:
- glib 0.18
- cap-std 2 (and cap-std-ext 3)
- libsystemd 0.6
And notably drops out a really old nix-0.23.2.

lib: Update to bootc 0.1.1 (ostree-ext 0.12, cap-std-ext 3.x)

---

rust/src/lockfile.rs

And add a unit test while we're here.

lockfile: Port away from deprecated chrono method

---

Cargo.lock
Cargo.toml
rust/src/composepost.rs
rust/src/utils.rs

composepost: Use O_TMPFILE, not memfd
An anonymous tmpfile is strictly better than memfd for a case
like this, where we want to be able to page back to disk if needed
for some reason.
Prep for dropping a dependency on the `memfd` crate.
---
rust: Drop dependency on `memfd`
The immediate motivation here is to ideally get back to one version
of `rustix` - we have just too many versions of `nix` and `rustix`.
The slight additional ergonomics of the `memfd` crate aren't
really worth it over using the already-safe rustix interface
directly.
---

rust: Drop dependency on `memfd`

---

rust/src/bwrap.rs
rust/src/cliwrap/cliutil.rs
rust/src/main.rs

Aiming to centralize on one system interface library eventually.

Port a few things from nix to rustix

---

Cargo.toml
docs/container.md
rust/src/compose.rs
tests/compose-image.sh

A long time ago I did
https://github.com/containers/skopeo/pull/1757/commits/08b27fc50e4da2501124d573b4a449dfeee260ad in preparation for this change.
Basically this is what we really want to be the default, but couldn't at the time: "Create a new image if one doesn't exist".
For completeness though, we also add support for `always` (which is the existing `--initialize`) as well as `--never` (which ensures we never overwrite an existing image, in case
someone cares).
However in testing this out: it basically works OK with a registry transport which is the big one, but:
- It just plain doesn't work with `.ociarchive` due to skopeo bugs
- It even more unfortunately doesn't work with `oci` directories and a target image reference; e.g. `--format=oci manifest.yaml oci:foo:sometag`

compose-image: Add `--initialize-mode`

---

.gitmodules

Matches https://github.com/ostreedev/ostree/commit/01a847a2d1c86df57e3e21d11df103eb34cd465a
gitlab.gnome.org is down right now, but it's been somewhat flaky in the past.  Our CI uptime becomes an *intersection* of all systems it depends on, and by cutting out gitlab.gnome.org we increase its reliability.

gitmodules: Switch to github for libglnx

---

src/libpriv/rpmostree-core.cxx
tests/vmcheck/test-override-replace-2.sh

E.g. we currently process all files under `/var/lib/selinux/targeted` as
going into `/usr/etc/selinux/targeted` instead. But the rpmdb doesn't
know that. So we need to do the translation even when deleting.
Another notable dir which falls in that bucket is `/boot`.
Fixes: #3421

core: Convert path to ostree convention when deleting

---

rust/src/container.rs

To support systems which built containers not via
`rpm-ostree compose image` etc.

container: Make `rpmostree.inputhash` optional

---

configure.ac
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-postprocess.cxx
tests/kolainst/destructive/layering-local

This pairs with https://github.com/coreos/rpm-ostree/pull/4495/commits/dbe78217c0205dad372c84b2cf0a299003787952 where we generate composefs metadata for base images.
It's going to be useful to do it for client side builds too, so that we can treat them symmetrically.  It doesn't have a very high cost, just a metadata traversal.

core: Add composefs digest for local commits too

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/composepost.rs
rust/src/lib.rs
src/libpriv/rpmostree-postprocess.cxx

Prep for other work.
---
compose: Rename postprocess_final to postprocess_final_pre
Because...it's not actually final.  Prep for adding a "really final"
function.
---
compose: Reintroduce postprocess_final
Subsubming the rpmdb function that was already there; prep for
doing more at that stage.
---

compose: Two minor cleanups

---

ci/test-container.sh

These hardcoded package versions just ruin CI.  We're unlikely to break this.
Eventually what we'll want to do is set up something like a COPR that auto-regenerates "dummy" changes.

ci: Bump hardcoded Ignition version

---

deny.toml

We want to require FIPS validation downstream, so we use openssl.
Motivated by hitting this in bootc in https://github.com/containers/bootc/pull/134

deny: Add ring

---

ci/installdeps.sh
configure.ac

Hard require ostree 2023.7

---

rust/src/bwrap.rs

I've seen us leak fuse processes on the build side; I think this happens when we get SIGINT (ctrl-c).  Ensure that in this case the fuse process gets SIGTERM, so it can gracefully unmount itself.

Ensure rofiles-fuse gets SIGTERM if we exit

---

ci/prow/e2e-upgrades.sh

Try to fix
```
kola -p qemu run --append-ignition config.ign --oscontainer ostree-unverified-registry:xxx --qemu-image ./fedora-coreos-38.20231002.3.1-qemu.x86_64.qcow2 ext.rpm-ostree.upgrades --output-dir /logs/artifacts/kola
=== RUN   ext.rpm-ostree.upgrades
2023-10-23T08:12:31Z platform: some systemd units failed: zincati.service
```

ci/upgrade: disable `zincati.service` in config.bu

---

ci/installdeps.sh
configure.ac
docs/treefile.md
rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/composepost.rs
rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-postprocess.cxx
src/libpriv/rpmostree-postprocess.h
tests/compose/test-misc-tweaks.sh

Depends on https://github.com/ostreedev/ostree/pull/3063
This is intended for use with https://github.com/ostreedev/ostree/issues/2868 but is conceptually orthogonal to it; we probably want to try switching to this by default actually.

treefile: Add option to label `/usr/etc` as `/etc`

---

src/libpriv/rpmostree-rpm-util.cxx

In general, libsolv isn't thread-safe.[[1]] There are multiple functions which return pointers that can be invalidated by other threads. It's hard to follow the libsolv side of this, but I think `solvable_lookup_bin_checksum()` (called by `dnf_package_get_chksum()`) is such a case. Because we do importing in bulk using multi-threading, rpm-ostree triggers this bug.
This is the root cause of #4565, where during the `cosa fetch` we embed the wrong repodata chksum_repr in the cached RPM's OSTree commit. So then `cosa build` considers it a cache miss when it sees the mismatch and wants to redownload it.
A trivial way to reproduce #4565 more easily is with:
```diff
diff --git a/src/libpriv/rpmostree-rpm-util.cxx b/src/libpriv/rpmostree-rpm-util.cxx
index 658a5fd8..ad8dc104 100644
--- …
```

libpriv/rpm-util: Query package repo checksum under lock

---

Cargo.lock

Update to ostree-ext 0.12.5

---

rust/libdnf-sys/cxx/libdnf.hpp
rust/libdnf-sys/lib.rs
rust/src/lockfile.rs

As part of Bodhi gating, we need to deal with source RPM names and not binary RPMs. E.g. Bodhi CI messages include Koji NVRs, not binary RPMs. Having to do the translation between SRPM and RPM is expensive because you need either repodata or e.g. bring up a VM and query the rpmdb.
Instead, just have rpm-ostree output the SRPM name as a metadata field in the output lockfile. cosa already saves this and outputs it in the build dir so it ends up in S3 and is much easier to work with.
Obviously there's some redundancy there since every binary RPM from the same source RPM will have the same field. But it doesn't seem worth extending the schema for it instead of just working with it as is.
Related: https://github.com/coreos/fedora-coreos-tracker/issues/1617

lockfile: add SRPM name in metadata field

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/cliwrap/kernel_install.rs
rust/src/initramfs.rs
rust/src/lib.rs
src/libpriv/rpmostree-kernel.cxx
tests/kolainst/destructive/initramfs-padding

Any arbitrary amount of padding between concatenated CPIOs is allowed:
https://www.kernel.org/doc/Documentation/early-userspace/buffer-format.txt
However, some initramfs decompressors in the kernel expect a minimal amount of padding to detect EOF and allow the kernel outer loop to try out other decompressors for the next payload. This is the case for lz4. This upstream patch allows the lz4 decompressor to treat padding as EOF:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2c484419efc09e7234c667aa72698cb79ba8d8ed
But it assumes that the padding is at least 4 bytes.
Since padding doesn't hurt regardless of the compression used, let's just unconditionally add it.
Fixes https://github.com/coreos/rpm-ostree/issues/4683.

libpriv/kernel: Add padding between dracut initramfs and random CPIO

---

configure.ac
packaging/rpm-ostree.spec.in

Release 2023.11

---

rust/src/composepost.rs
rust/src/lib.rs
rust/src/ostree_prepareroot.rs
tests/compose/test-rootfs-transient.sh

This pairs with https://github.com/ostreedev/ostree/pull/3114
Basically we want to detect the case where the OS has opted-in to this new mode and *not* symlink things.
I originally thought we could implement this by just moving all the toplevel directories, but then I hit on the fact that because the `filesystem` package is creating all the toplevel directories in lua script which we ignore...that doesn't work.
So we need to keep making them by hand.

composepost: Support rootfs.transient=yes

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/lib.rs
rust/src/sysroot_upgrade.rs
src/daemon/rpmostree-sysroot-core.cxx
tests/kolainst/destructive/container-image

I was debugging something else and stumbled into this; not heavily tested yet but I think this was a regression from 2ed82eea08ba0e4c9d4639b0c39f380dcb45bbf7

Ensure container image layers are pruned

---

rust/src/tmpfiles.rs

tmpfiles: Rename reader function
---
tmpfiles: Change `read_tmpfiles` to return a direct hashmap
While returning an iterator was more elegant, it makes
error handling much more difficult *and* we had intermediate
`collects()` that meant it wasn't really lazy.
Trying to remove the intermediate `collect` runs into borrowing
issues (on the input `&Dir`) and this isn't a high performance
path so doing the more obvious simpler thing is better.
---
tmpfiles: Collect into a BTreeMap for reproducibility
I hit a test failure in one run because HashMap is not ordered
predictably.
---
tmpfiles: Drop intermediate re-allocation
Since we're now returning a direct map we don't need
to convert to a set, we can just ignore the values when iterating.
---

A few minor updates for tmpfiles code

---

rust/src/tmpfiles.rs

tmpfiles: Fix error contexts
We weren't actually formatting these, so the error looks like:
`error: Deduplicate tmpfiles entries: readdir {RPMOSTREE_TMPFILESD}: No such file or directory (os error 2)`
It's simpler to just not format.
---
tmpfiles: Handle old caches
I actually did get bitten by having an old cache where
there's nothing in the `RPMOSTREE_TMPFILESD` dir.
Just handle the case where the directory doesn't exist.
For good measure, also gracefully no-op if the destination tmpfiles.d
directory doesn't exist.
---

Tmpfiles handle old cache

---

configure.ac
packaging/rpm-ostree.spec.in

v2023.12
Notable bug fixes are:
- rpm-ostree now will remove duplicate tmpfiles entries #4697
- rpm-ostree now will properly prune container layers #4720
```
Colin Walters (9):
tmpfiles: Add a unit test
tmpfiles: Rename reader function
tmpfiles: Change `read_tmpfiles` to return a direct hashmap
tmpfiles: Collect into a BTreeMap for reproducibility
tmpfiles: Drop intermediate re-allocation
composepost: Support rootfs.transient=yes
Ensure container image layers are pruned
tmpfiles: Fix error contexts
tmpfiles: Handle old caches
HuijingHei (4):
rpm-ostree-0-integration.conf: remove `/var/lib` tmpfiles entry as it is duplicated in `var.conf`
rpmostree-postprocess.cxx: remove `var/` in unified core mode
utils.rs: remove duplicate tmpfiles entries
tmpfiles.rs: minor update
```
**Full …

Release 2023.12

---

src/libpriv/rpmostree-core.cxx

When removing package, will also remove the generated tmpfile config under the rpm-ostree tmpfiles.d directory. Since https://github.com/coreos/rpm-ostree/pull/4697, we use the new directory like `usr/lib/rpm-ostree/tmpfiles.d`, but for old `usr/lib/tmpfiles.d`, failed with `error: opendir(usr/lib/rpm-ostree/tmpfiles.d): No such file or directory`.
With this patch, check if `usr/lib/rpm-ostree/tmpfiles.d` does not exist, will use old `usr/lib/tmpfiles.d` instead.
Also needs https://github.com/coreos/rpm-ostree/pull/4727. 
Fixes: https://github.com/fedora-silverblue/issue-tracker/issues/523

Check generated tmpfiles.d dir when removing package

---

src/daemon/rpmostreed-transaction-types.cxx
tests/vmcheck/test-kernel-args.sh

Revert part of https://github.com/coreos/rpm-ostree/commit/1a1ef139d41d49d0907cc18d402a9ca8ba0e6de5
`ostree_kernel_args_delete_if_present()` calls
`ostree_kernel_args_contains()` which only looks at the `key`
part, which makes `delete-if-present` failed when there is
existing `key`. `append-if-missing` will hit the same problem.
```
]# rpm-ostree kargs --append=crashkernel=1G
]# rpm-ostree kargs
... crashkernel=1G
]# rpm-ostree kargs --unchanged-exit-77 --delete-if-present=crashkernel=auto
error: No karg 'crashkernel=auto' found
]# rpm-ostree kargs --unchanged-exit-77 --append-if-missing=crashkernel=auto
No changes.
```
And fix corner case when `append` and `append-if-missing` with
the same value which will append twice.
Fixes: https://github.com/coreos/rpm-ostree/issues/4718

kargs: run `delete-if-present` and `append-if-missing` failed when there is existing `key`

---

configure.ac
packaging/rpm-ostree.spec.in

This release fixes two regressions, one introduced in 2023.13 for upgrades with layered packages, and one for kernel argument handling.

Release 2024.1

---

Cargo.toml

Exclude test files from the `idna` create that we don't need for rpm-ostree. Those test fiels include invalid Unicode code points for testing and that triggers rpminspect checks for Fedora RPM packaging.
Fixes: https://github.com/coreos/rpm-ostree/issues/4760
See: https://github.com/servo/rust-url/blob/master/idna/tests/IdnaTestV2.txt

Cargo.toml: Exclude idna/tests for vendor tarball

---

Makefile-rpm-ostree.am
ci/prow/Dockerfile
rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/composepost.rs
rust/src/lib.rs
src/app/rpm-ostree-0-integration-opt-usrlocal.conf
src/app/rpm-ostree-0-integration.conf
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-postprocess.cxx

Prep patches for `/opt` and `/usr/local` support

---

rust/src/lockfile.rs
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-importer.cxx
src/libpriv/rpmostree-rpm-util.cxx
src/libpriv/rpmostree-rpm-util.h

When handling file caps, we need to be able to get the actual xattr
bytes. Currently, libcap doesn't provide a public API for this.
Meanwhile, we've been hacking around this by redefining internal libcap
structs and using internal fields. This is extremely brittle since any
change to the struct will break us.
And this is exactly what happened in the libcap currently in rawhide. A
new field was added to the struct:
https://git.kernel.org/pub/scm/libs/libcap/libcap.git//commit/?id=aca076443591ba18438b60e41294b59a324daf04
This patch works around the lack of a public API a different way: we
allocate an `O_TMPFILE`, set caps on it, then read back the xattr. This
is more heavyweight but few binaries actually have file caps anyway. It
also requires `CAP_SETFCAP`, but that's already the case …

libpriv: Stop digging in private libcap internals

---

docs/container.md

See: https://github.com/coreos/rpm-ostree/pull/4703
See: https://github.com/ostreedev/ostree-rs-ext/pull/567
See: https://github.com/opencontainers/image-spec/blob/main/config.md
Fixes: https://github.com/coreos/rpm-ostree/issues/4712

docs: Add generic container image configuration support

---

Makefile-rpm-ostree.am
docs/treefile.md
rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/composepost.rs
rust/src/importer.rs
rust/src/lib.rs
rust/src/treefile.rs
src/app/rpm-ostree-0-integration-opt-usrlocal-compat.conf
src/app/rpm-ostree-0-integration-opt-usrlocal.conf
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-postprocess.cxx
tests/compose/test-state-overlays.sh
tests/kolainst/destructive/state-overlays
tests/kolainst/kolainst-build.sh
tests/vmcheck/test-layering-basic-1.sh

This solves the `/opt` problem by using the new state overlay concept in
OSTree: an overlay filesystem is mounted on top of `/usr/lib/opt` and
the upper dir is automatically "rebased" whenever new content comes in.
Concretely, this means that app state is carried forward, all while
allowing the (OSTree-managed) package contents to be updated.
We also solve the `/usr/local` problem the same way. The app state issue
isn't really present there, but `/usr/local` has traditionally been
system state. We want to keep supporting dropping files there all while
also supporting shipping OSTree-owned content.
See also: https://github.com/ostreedev/ostree/issues/3113
Fixes: https://github.com/coreos/rpm-ostree/issues/233

Support RPMs installing in `/opt` and `/usr/local`

---

src/libpriv/rpmostree-rpm-util.cxx

Fixes c4ada850 ("libpriv: Stop digging in private libcap internals").

libpriv/rpm-util: Fix cap_t leak

---

.cci.jenkinsfile
ci/prow/kola/upgrades
tests/kolainst/destructive/client-layering-upgrade

Enhance 2 upgrade tests:
- `kolainst`: Do client-side layering tests on old build, then upgrade
rpm-ostree to new version, then upgrade to another new update.
- `prow/e2e-upgrades`: Start old build with upgraded rpm-ostree,
do layering tests, then upgrade to another new update.
Fixes: https://github.com/coreos/rpm-ostree/issues/4776

upgrade-test: add 2 upgrades test

---

.copr/Makefile
ci/prow/Dockerfile
ci/prow/fcos-e2e.sh
rust/src/composepost.rs
tests/kolainst/destructive/state-overlays
tests/kolainst/kolainst-build.sh

When `/opt` packages get moved to `/usr/lib/opt`, they're not being labeled properly; they get the `lib_t` label instead of `usr_t` (or e.g. `bin_t` for `/opt/bin`).
This apparently works for e.g. Google Chrome (for which the `/usr/lib/opt` translation was added). But with state overlays, the goal is to support all `/opt` packages and things will break without proper labeling.
Add an equivalency rule so that `/usr/lib/opt` is labeled like `/opt. This fixes the SELinux issues that occur when layering Puppet in https://github.com/coreos/rpm-ostree/issues/233#issuecomment-1856720559.
This should probably be upstreamed to SELinux (along with the `/usr/etc` equivalency rule just above).
Side note: in the status quo model where `/opt` is a symlink to `/var/opt`, everything is *also* mislabeled …

composepost: Add SELinux equivalency rule for /usr/lib/opt → /opt

---

rust/src/cliwrap/rpm.rs

This is sometimes used in scripts to query aspects of the host system.
E.g. this is used by Fedora's pkg-config:
https://src.fedoraproject.org/rpms/pkgconf/blob/95c0bbee/f/pkg-config.in#_6
This in turn gets hit by kdump which runs dracut which has modules that
runs `pkgconf` to query some directory paths.

cliwrap/rpm: mark `--eval`/`-E` as safe

---

ci/prow/fcos-e2e.sh
rust/src/composepost.rs
rust/src/passwd.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-postprocess.cxx
tests/kolainst/destructive/apply-live
tests/kolainst/destructive/cliwrap
tests/kolainst/destructive/state-overlays

Since both Prow and CoreOS CI do a compose and run kola tests, we
can change one of them to cover some different options without losing
coverage on the default path.
Follow-up to #4728.

ci: Test `opt-usrlocal-overlays` end-to-end in Prow CI

---

docs/compose-server.md

Hello,
I stumbled upon a dead link to osbuild blog which is no longer part of the website. The documentation might be a good replacement. Feel free to close or change the PR. I just decided to open PR instead of an issue.
Martin

docs: replace dead link to osbuild blog

---

ci/test-container.sh
rust/src/cliwrap.rs

Right now, if a system is already cliwrapped, doing `install-to-root` will incorrectly think the already wrapped entrypoints are the real binaries and do the wrong thing.
Fix this by checking if the directory holding wrapped binaries already exists. If yes, then no-op.

cliwrap: make `install-to-root` idempotent

---

docs/building-rpm-ostree-and-autosd.md

Myself and Eric we spend a bunch of time to create rpm-ostree RPM for later inject it into autosd image. To avoid others to spend time in such effort, here a documentation.

docs: Add doc about build rpm-ostree+autosd

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/bwrap.rs
rust/src/composepost.rs
rust/src/core.rs
rust/src/lib.rs
src/libpriv/rpmostree-postprocess.cxx

We have two `bool` values here and that's a code smell.  I was going to add another option and we definitely don't want three bools.
We already have an enum here related to what's going on, so change things to use it.

bwrap: Pass mutability flag, not unified core

---

Cargo.lock

lib: Bump to ostree-ext 0.13.3

---

rust/src/live.rs
tests/kolainst/destructive/apply-live

I'm a very happy rpm-ostree user on Fedora Silverblue, but sometimes when I want to make a live change to my system with:
```
rpm-ostree install -A blah
```
I'll get an error message like:
```
error: packages would be changed: 34, enable replacement to override
```
and then I think oh, I have to pass that override so I do
```
sudo rpm-ostree apply-live --enable-replacement
```
*but* the argument is not `--enable-replacement`, it is in fact `--allow-replacement`.
This PR changes that error text to more closely match the correct command-line argument needed to override the error, so the error would now be:
```
error: packages would be changed: 34, allow replacement to override
```
It's subtle, but I think an ever so slight usability improvement.

Change "enable replacement" error text to "allow replacement" to match command-line interface

---

ci/prow/fcos-e2e.sh
docs/treefile.md
rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/composepost.rs
rust/src/lib.rs
rust/src/ostree_prepareroot.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-postprocess.cxx
tests/compose/libbasic-test.sh
tests/compose/libcomposetest.sh
tests/compose/test-misc-tweaks.sh
tests/compose/test-state-overlays.sh
tests/kolainst/destructive/apply-live
tests/kolainst/destructive/state-overlays

xref https://github.com/ostreedev/ostree-rs-ext/issues/607
We need to support having `/opt` and `/usr/local` be directly
on the rootfs.  Change the existing knob for this to be more
configurable.  The stateoverlay path is now an internal-only
knob; we expect people to do that externally.

compose: change opt_usrlocal_overlays to be an enum

---

src/libpriv/rpmostree-scripts.cxx
tests/vmcheck/test-layering-scripts.sh

The file trigger pattern isn't necessarily a directory. It seems just like a generic pattern applied to all file entries in the header of the packages being installed. (Technically we need to support globs in there too but we're currently not doing.)
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2269247

libpriv/scripts: support files in transfiletriggerin patterns

---

ci/prow/fcos-e2e.sh
rust/src/passwd.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-postprocess.cxx
tests/kolainst/destructive/state-overlays

This reverts commit e1e78cf9df902d895a7fce9dc719726c283e9d03.
It breaks idempotency with osbuild.
Closes: https://github.com/coreos/rpm-ostree/issues/4879

Revert "compose: Inject our static tmpfiles.d dropins earlier"

---

src/app/rpmostree-pkg-builtins.cxx

We should specify on the CLI description of the install sub-commands that releasever, disablerepo & enablerepo only work on a container build. 
This should clear the confusion: https://bugzilla.redhat.com/show_bug.cgi?id=2219097

install: specify sub-commands that are container build only.

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/container.rs
rust/src/fsutil.rs
rust/src/lib.rs
src/libpriv/rpmostree-refts.cxx
src/libpriv/rpmostree-refts.h

While toying around with building my own custom FCOS builds, I noticed that running `cosa build container` with a package set similar to Silverblue's resulted in ~2hr builds, the vast majority of which was in the "Building package mapping" task. After this change, the runtime on my build shrank to ~15 mins.
`$ time cosa build container`
**Before**
```
real    10m47.769s
user    52m14.763s
sys     46m38.546s
```
**After**
```
real    15m37.333s
user    2m38.751s
sys     0m14.410s
```
The speedup is accomplished by avoiding the need to query the rpmdb for every file. Instead the rpmdb is walked to build a cache of the files to providing packages, so that when the ostree filesystem is walked later it can just check the cache. The cache is structured similarly to rpm's internals, where paths …

container-encapsulate: make build_mapping_recurse significantly faster

---

Makefile-daemon.am
packaging/rpm-ostree.spec.in
rust/src/passwd.rs
src/daemon/rpm-ostree-fix-shadow-mode.service
tests/compose/libbasic-test.sh

passwd: create `/etc/[g]shadow` with mode 0
Because of how our composes work, we need to manually inject
passwd-related things before installing packages. A somewhat recent
regression in that area made it so that the `/etc/shadow` and
`/etc/gshadow` files were created with default permissions (0644), which
meant they were world readable.
Fix this by explicitly setting their modes to 0. Ideally, we would rely
on the canonical permissions set in the `setup` package here, but it's
tricky to fix that without reworking how we install `setup` and handle
`passwd` treefile options.
Fixes fdb879c8 ("passwd: sync `etc/{,g}shadow` according to
`etc/{passwd,group}`").
Fixes #4401
---
unit: chmod /etc/[g]shadow[-] to 0000
fdb879c introduced a regression where /etc/[g]shadow[-] files where
created with …

CVE-2024-2905: passwd: create /etc/[g]shadow with mode 0 & unit: chmod /etc/[g]shadow[-] to 0000

---

rust/src/scripts.rs

This PR fixes rpm-ostree on Oracle Linux UEKR7. UEKR7 has a different package layout than UEKR6. In particular, some postinstall scripts that used to run in "kernel-uek" are now run as part of "kernel-uek-core".  This causes rpm-ostree to output lots of errors and eventually fails.
The fix is to add "kernel-uek-core" to the ignore list of posttrans scripts.
Sample snippet of output showing the errors before the fix:
```
rpm-ostree compose tree --unified-core  --repo=./ostree  configs/manifest.yaml
...
⠤ Running posttrans scripts... kernel-uek-core
...
kernel-uek-core.posttrans: cp: setting attributes for '/var/tmp/dracut.HpI4IW/initramfs/shutdown': Operation not supported
kernel-uek-core.posttrans: dracut-install: ERROR: installing '/usr/lib/dracut/modules.d/99shutdown/shutdown.sh' to …
```

Add kernel-uek-core.posttrans to list of ignored package scripts

---

rust/src/lib.rs
rust/src/main.rs
rust/src/passwd.rs
src/daemon/rpm-ostree-fix-shadow-mode.service
tests/kolainst/destructive/shadow

It was pointed out that in the previous change here we missed the fact that the previous deployments were accessible.
- Move the logic into Rust, adding unit tests
- Change the code to iterate over all deployments
- Add an integration test too
Note: A likely future enhancement here will be to finally deny unprivileged access to non-default roots; cc
https://github.com/ostreedev/ostree/issues/3211

shadow: Adjust all deployments

---

src/daemon/rpmostree-sysroot-upgrader.cxx
tests/kolainst/destructive/container-rebase-upgrade

Related change in ostree is https://github.com/ostreedev/ostree/pull/3208.
Fixes: https://github.com/ostreedev/ostree/issues/3228

kargs: keep spaces in double quotes

---

packaging/rpm-ostree.spec.in

The rust-toolset macros in RHEL 10 are now compatible with Fedora's in terms of handling vendoring and automatic generation of license information and bundled provides.
This upstreams the contribution from yselkowitz on Fedora: https://src.fedoraproject.org/rpms/rpm-ostree/pull-request/61

rpm-ostree.spec.in: Update rust macro usage

---

src/app/rpmostree-builtin-upgrade.cxx
src/daemon/rpmostreed-deployment-utils.cxx
tests/kolainst/destructive/container-update-check
tests/vmcheck/test-autoupdate-check.sh

update-check: Print unreliability warning on stderr
Print warnings on stderr so that we can format the stdout as JSON.
---
deployment_utils: Also add version to cached update
Adding the version of the cached update to `rpm-ostree status --json`
output will make it easier to use it for update checks in Plasma
Discover when updating using Ostree Native Containers.
Fixes: https://github.com/coreos/rpm-ostree/issues/4711

deployment_utils: Also add version to cached update

---

docs/treefile.md

The semantics around this are a bit confusing and I had to rederive them again today. Ideally we'd change it to something less surprising (specifically the second rule) but that'd be a breaking change. Let's at least try to document it well.
Obviously these rules apply to any list we merge, but postprocess scripts in particular are imperative bits of code and may affect each other and so it's not surprising that one would care more about the semantics for those vs e.g. `packages`. So let's document it there.

docs/treefile.md: Document postprocess script ordering

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/lib.rs
rust/src/sysroot_upgrade.rs
src/daemon/rpmostreed-deployment-utils.cxx
tests/kolainst/destructive/container-update-check

container-update-check: Validate version in manifest diff
---
deployment_utils: Fix version for cached container update
Previous change used the version of the current deployment instead of
the one from the pending container update.
Store the new version alongside the manifest diff to be able to return
it as part of the cached update logic.
Fixes: https://github.com/coreos/rpm-ostree/pull/4923
Fixes: https://github.com/coreos/rpm-ostree/issues/4711

deployment_utils: Fix version for cached container update

---

ci/test-container.sh
docs/administrator-handbook.md
rust/src/client.rs
src/app/rpmostree-builtin-ex.cxx
src/app/rpmostree-clientlib.cxx
src/libpriv/rpmostree-core.cxx
tests/compose.sh
tests/compose/test-basic-unified.sh
tests/kolainst/destructive/client-layering-upgrade
tests/vmcheck/test-layering-scripts.sh
tests/vmcheck/test-override-kernel.sh
tests/vmcheck/test-override-replace-2.sh

Fix Fedora 40 Ci Bugs

---

src/app/rpmostree-compose-builtin-tree.cxx
src/daemon/rpm-ostreed.service
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-os.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-container.cxx
src/libpriv/rpmostree-core-private.h
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h
tests/common/libtest.sh
tests/kolainst/destructive/filelists

Fixes https://github.com/coreos/fedora-coreos-tracker/issues/1643
Disable filelists from being downloaded by default for Fedora 40. Adds
the `DNF_CONTEXT_SETUP_SACK_FLAG_SKIP_FILELISTS` where applicable,
which prevents the filelists from being downloaded.
For the changes in `rpmostree_context_prepare()`, disabling filelists is
conditional on whether a filepath was specified for `rpm-ostree install`
(ie. rpm-ostree install /usr/bin/htop).
For the changes in refresh_md_transaction_execute(), `rpm-ostree
refresh-md` will not download filelists if they were not previously
downloaded. If they were previously downloaded, the filelists will be
updated.
Since there are many functions affected by this change, the option to
return to the previous filelist behaviour is also implemented. This is
done …

disable downloading filelists by default

---

src/daemon/rpm-ostree-fix-shadow-mode.service

fixes: https://github.com/coreos/fedora-coreos-tracker/issues/1722

rpm-ostree-fix-shadow-mode.service: don't run if OS is not installed

---

rust/src/daemon.rs
src/daemon/rpmostree-sysroot-core.h
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-transaction-types.cxx
tests/vmcheck/test-misc-2.sh

Now that we've stabilized and made public deployment finalization APIs,
let's use them.
This also fixes an issue where when creating a locked deployment using
the legacy API (i.e. touching the `/run/ostree/staged-deployment-locked`
file before calling the staging API), if a staged deployment already
exists, libostree would just nuke the lockfile (this behaviour was
introduced in https://github.com/ostreedev/ostree/pull/3077).
In theory the legacy API (via the lockfile) should keep working, but
the core issue is that there's no way for libostree to know if the
lockfile is carried-over state, or was freshly created for the current
invocation.
So let's not try to salvage the legacy API and just move over to the
new one.
We already have finalization tests; they will now test that the new API …

daemon: use new finalization APIs

---

ci/test-container.sh
rust/src/core.rs
src/libpriv/kernel-install-wrapper.sh

It's confusing right now how specifically for the kernel, one has to use this obscure `rpm-ostree cliwrap install-to-root /` command to make it work. Let's just always enable it: in the client-side layering case, we don't run kernel scriptlets anyway so the wrapper is unused, and in the container case, this will allow users to not have to enable cliwrap and have it leak into their derived image.
I guess in theory, this should also allow us to *stop* ignoring kernel scriptlets and rely on this instead, though let's leave that for a separate investigation.
Closes: #4949

core: also wrap `kernel-install` for scriptlets

---

rust/src/sysroot_upgrade.rs

This at least gives us a spinner when we're fetching layers, so folks know something is happening.
As the comment says we *can* get byte-level progress, but it just needs more plumbing work with our complex internal output infrastructure.
Note that I had to move the layer progress bits into a tokio LocalSet because the progress output stuff is a thread local.

container: Add spinner/progress for layer fetches

---

configure.ac
packaging/rpm-ostree.spec

```
Colin Walters (2):
Remove modularity support entrypoints
container: Add spinner/progress for layer fetches
HuijingHei (1):
kargs: keep spaces in double quotes
Jonathan Lebon (5):
docs/treefile.md: Document postprocess script ordering
daemon: use new finalization APIs
ci/test-container: move URL definitions to the top
core: also wrap `kernel-install` for scriptlets
packaging: drop `.in` extension on `rpm-ostree.spec.in`
Joseph Marrero (2):
Release 2024.6
rpm-ostree-fix-shadow-mode.service: don't run if OS is not installed
Luke Yang (3):
Various Fedora 40 fixes
Update to f40 kernel
Disable downloading filelists by default
Timothée Ravier (6):
docs/HACKING: Add example for ostree-rs-ext crate development
update-check: Print unreliability warning on stderr
deployment_utils: Also add …
```

Release 2024.6

---

README.md

Let's more clearly indicate the current status of rpm-ostree directly in the README and link to relevant pages with more information.

README: reflect development status

---

man/rpm-ostreed.conf.xml
rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/lib.rs
rust/src/treefile.rs
src/daemon/rpm-ostreed.conf
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-daemon.cxx
src/daemon/rpmostreed-daemon.h
tests/kolainst/destructive/layering-local
tests/kolainst/kolainst-build.sh

We already have a knob for this in the treefile, and we already generate a treefile in the client-side case to hand to the core. So this is just wiring up a knob in the config file to it.
Closes: #718

Add `Recommends=` knob in rpm-ostreed.conf

---

rust/src/scripts.rs

This adds the posttrans scripts from [ELRepo's](https://elrepo.org/) `kernel-lt` and `kernel-ml` packages to the list of scripts to skip. These packages contain an LTS kernel and a mainline kernel from kernel.org built for RHEL.

rust/src/scripts.rs: ignore posttrans for ELRepo's kernel-lt and kernel-ml

---

ci/test-container.sh

Those packages have been untagged from the pool as per https://github.com/coreos/fedora-coreos-tracker/issues/1674.

ci/test-container: Stop using f38 packages

---

packaging/Makefile.dist-packaging
packaging/make-git-snapshot.sh

And in this week's entry for the "longest description of the shortest change" competition:
I needed to build a pre-release distribution tarball of rpm-ostree for Reasons™. I noticed, however, that the resulting tarball wasn't consistent:
```console
$ git branch
jeamland/repeatable-dist
* main
$ git describe
v2024.6-34-ga172e482
$ make -C packaging -f Makefile.dist-packaging dist-snapshot
[copious output]
$ ls -l packaging/rpm-ostree-2024.6.34.ga172e482.tar.xz 
-rw-r--r--. 1 bjrice bjrice 12266796 Jun 19 16:26 packaging/rpm-ostree-2024.6.34.ga172e482.tar.xz
$ sha256sum packaging/rpm-ostree-2024.6.34.ga172e482.tar.xz
61222360cb42aba5eb4ddd9880bb292eda8de6da3c25c646835f26ed493ba571  packaging/rpm-ostree-2024.6.34.ga172e482.tar.xz
$ make -C packaging -f Makefile.dist-packaging dist-snapshot …
```

Replace the mtime of vendored files with the commit timestamp when making a distribution tarball

---

ci/build-check.sh
ci/build.sh
ci/ci-commitmessage-submodules.sh
ci/clang-analyzer.sh
ci/clang-build-check.sh
ci/codestyle.sh
ci/commit-validation.sh
ci/composepost-checks.sh
ci/container-build-integration.sh
ci/coreosci-rpmbuild.sh
ci/cosa-build.sh
ci/cosa-overrides.sh
ci/install-cxx.sh
ci/install-test-deps.sh
ci/installdeps.sh
ci/libbuild.sh
ci/prow/e2e-upgrades.sh
ci/prow/fcos-e2e.sh
ci/prow/kola/upgrades
ci/ridiculous-rhel-devel-workaround.sh
ci/test-container.sh
ci/unit.sh
ci/verify-cxx.sh
ci/vmcheck-provision.sh

Explicitly mark all CI scripts as Apache 2.0 or MIT to clarify applicable licenses.
CC authors: @jlebon @cgwalters @HuijingHei @lukewarmtemp @jmarrero @lucab
Other folks in the git log that I have not CC'ed yet (and their commits):
Andreas Hartmann <hartan@7x.de> (685eb168)
Benno Rice <benno.rice@oracle.com> (dc63a249)
Kalev Lember <klember@redhat.com> (184c017b)
Another option is to not include the `ci` directory in the release tarballs.

ci: Add SPDX-License-Identifier: Apache-2.0 OR MIT

---

rpmostree-cxxrs.cxx
rust/src/container.rs
rust/src/lib.rs
src/libpriv/rpmostree-refts.cxx
src/libpriv/rpmostree-refts.h
tests/compose-image.sh

Without this, `package_meta` is unable to distinguish between copies of the same package installed for different architectures; for example, many systems need both the `x86_64` and `i686` version of glibc.
Fixes https://github.com/coreos/rpm-ostree/issues/4609
--
I realized that simply removing the check as I suggested in https://github.com/coreos/rpm-ostree/issues/4609#issuecomment-2221267196 would be incorrect; this would mean that `package_meta` could potentially return the wrong metadata, if two identically-named packages for different architectures were installed. Instead, this is an attempt to add `arch` as a parameter to `package_meta`, and get it to find the correct metadata. The check is left in place, but should only occur if duplicate packages for the same arch have somehow …

Add `arch` as a parameter to `package_meta`

---

ci/test-container.sh

Per https://github.com/coreos/rpm-ostree/pull/5014#issuecomment-2223849471
"kdump-utils is a separate package now and requires kexec-tools."

ci: Uninstall kexec harder

---

docs/treefile.md

Clarify with example how to use the `packages` keyword in treefile syntax reference doc, especially the version query syntax that requires special non-obvious quoting.
---
My whole team of developers have all independently believed the version query syntax was broken because it wasn't clearly communicated in this doc how the single quotes needed to be used. The only example or reference we've found that clarified it was in a closed Issue about different code paths for handling `install` vs `compose` needing to be merged.

Clarify version query syntax usage in treefile doc

---

configure.ac
packaging/rpm-ostree.spec

v2024.7
This is mainly a bugfix release and oen new feature:
#4974 Add `Recommends=` knob in rpm-ostreed.conf
One notable bugfix comming from ostree-rs-ext https://github.com/ostreedev/ostree-rs-ext/pull/648 fixes Processing deferred hardlinks.
````
Benno Rice (1):
packaging: Use git timestamp as mtime for vendored files
Colin Walters (2):
Remove all modularity support
ci: Uninstall kexec harder
Jonathan Lebon (3):
README: reflect development status
Add `Recommends=` knob in rpm-ostreed.conf
ci/test-container: Stop using f38 packages
Jordan Webb (2):
rust/src/scripts.rs: ignore posttrans for ELRepo's kernel-lt and kernel-ml
Add `arch` as a parameter to `package_meta`
Mike (1):
Clarify version query syntax usage in treefile doc
Timothée Ravier (1):
ci: Add SPDX-License-Identifier: …
```

Release 2024.7

---

packaging/rpm-ostree.spec

After the initial changes to ostree-ext introducing support for
zstd:chunked, which can be found in this pull request:
https://github.com/ostreedev/ostree-rs-ext/pull/615,
an additional PR modified the dependency on zstd during build
time to use pkg-config.
You can review these changes in the pull request:
https://github.com/ostreedev/ostree-rs-ext/pull/628.
These updates also required modifications to bootc, detailed in
this pull request: https://github.com/containers/bootc/pull/586.
This commit mirrors those changes in rpm-ostree.
With these changes, it will be possible to build RPMs on systems
that do not have zstd-devel pre-installed in the build root.

packaging/rpm-ostree.spec: add libzstd-devel BuildRequires

---

rust/src/bwrap.rs

I believe cosa is hitting an error in this code path, but we can't inspect the error because there's no journald running in supermin:
https://github.com/coreos/coreos-assembler/issues/3848
We don't gain much by printing this error to the journal since it shouldn't be very common. Print it on stderr instead where it's more likely to have visibility.

rust/bwrap: log `fusermount -u` errors to stderr

---

tests/kolainst/nondestructive/misc.sh

The "Duplicate line" log is happend during initramfs. 
From Jonathan's suggestion https://github.com/coreos/rpm-ostree/issues/5040#issuecomment-2288821807: 
we will ignore log entries from before switchroot when doing check.
Fixes https://github.com/coreos/rpm-ostree/issues/5040

ci: fix test failing for Duplicate lines in journal

---

src/libpriv/rpmostree-core.cxx

This should fix:
```
32. rpm-ostree-2024.7/src/libpriv/rpmostree-core.cxx:1786:15: use_after_free: Using internal representation of destroyed object temporary of type "std::string".
```

core: Fix Coverity WRAPPER_ESCAPE

---

src/libpriv/rpmostree-core.cxx

Older versions of rpm-ostree bail if this isn't found. In practice we may as well keep this until the end of time...
Closes: https://github.com/coreos/rpm-ostree/issues/5048

core: Continue to write now-empty `rpmostree.modules` metadata

---

rust/src/tokio_ffi.rs
rust/src/utils.rs

- Suppress a dead code warning on the tokio guard; it's just there for drop semantics.
- Delete an unused function.

rust: Squash two minor build warnings

---

packaging/rpm-ostree.spec
rust/src/bwrap.rs

The specs between upstream, fedora and centos are out of sync. This attempts to sync it to restart using it as the source of truth.

packaging/rpm-ostree.spec: Update to sync with rawhide

---

rust/src/sysroot_upgrade.rs

It's useful to see in the progress output how many layers there are to fetch.
This is similar to
https://github.com/containers/bootc/pull/524/commits/6eb57180a3c82393b70edb702fb9c4db53e54c32 which ended up being totally reworked in a nicer way in https://github.com/containers/bootc/pull/655/commits/d8b5df2f378b54c3a60ccaa673a60a7bbca5d653
But doing the latter would require nontrivial changes to our DBus API around status and progress reporting...and I'd like to think about how we tackle that more generally in e.g. https://github.com/containers/skopeo/issues/658
Closes: https://github.com/coreos/rpm-ostree/issues/5024

sysroot: Add total layer count to output

---

packaging/rpm-ostree.spec

0%{?rhel} matches rhel derived family distros `el` check seem to break the condition
https://gitlab.com/redhat/centos-stream/rpms/rpm-ostree/-/merge_requests/57#note_2093239477

packaging/rpm-ostree.spec: Update fuse conditional

---

docs/cliwrap.md
docs/treefile.md
rust/src/cliwrap.rs
rust/src/treefile.rs

I'm looking at handling kernel overrides:
- https://github.com/coreos/rpm-ostree/issues/4726
- https://gitlab.com/fedora/bootc/tracker/-/issues/22
And I think the cliwrap thing turned out to be the wrong approach for this.
There's consensus now it was the wrong approach, so deprecate it.

Deprecate cliwrap

---

packaging/rpm-ostree.spec

rust_arches are no longer needed or required for building on Fedora or RHEL 
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1716

packaging/rpm-ostree.spec: Drop rust_arches

---

rust/src/cliwrap/kernel_install.rs
rust/src/initramfs.rs

Prep for handling kernel-install in a different way, where we add a drop-in that is invoked by the existing binary instead of intercepting it entirely.
No functional changes intended (yet).

Move dracut code from cliwrap to initramfs module

---

packaging/rpm-ostree.spec

spec: Do not build on ix86 for fedora
---
spec: %autorelease can't be resolved by COPR
Fix RPM pakcage name issue like
`rpm-ostree-2024.8.28.g3c9febff-%autorelease.x86_64.rpm`

spec: Do not build on ix86 for fedora

---

rust/src/scripts.rs

This is all about migrations and hacks, which we don't need since every filesystem tree is constructed fresh.
xref https://gitlab.com/fedora/bootc/tracker/-/issues/29

scripts: Ignore filesystem.transfiletriggerin

---

docs/treefile.md
rust/src/composepost.rs
rust/src/treefile.rs

Revert "build(deps): bump regex from 1.10.6 to 1.11.0"
This reverts commit c46951f2d9ae896cbcd24bceed7c2e4930d44400.
---
treefile: Add an `edition`
This will allow us to clean up some defaults and change some semantics.
In particular, I'd like to add an opinionated mechanism to copy files
from git into the build.
For now, `edition: "2024"` just flips on `tmp-is-dir: true` and fixes
`boot-location`.
---
treefile: Add finalize.d
This is a total escape hatch for arbitrary mutation of
the filesystem tree just before we do an ostree commit.
---

treefile: Add an `edition` && treefile: Add finalize.d

---

Cargo.lock
Cargo.toml
docs/treefile.md
rust/src/kickstart.rs
rust/src/lib.rs
rust/src/treefile.rs

The treefile syntax is...ok, but it is bespoke to us and we never really emphasized its use outside of our sphere.
As I'm looking at https://gitlab.com/fedora/bootc/tracker/-/issues/32 I'd really like to expose something that has existing widespread use as a default entrypoint.
kickstart is really old, long predating even virtualization.
It has a decent set of features (includes, comments) as a baseline specifically as a mechanism to define package sets, it has key features we want:
- turning off weak dependencies
- excludes
This is just a stub kickstart parser...the next step is to wire this up into the treefile.

compose: Initial kickstart support

---

docs/treefile.md
rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/composepost.rs
rust/src/lib.rs
rust/src/treefile.rs
src/libpriv/rpmostree-postprocess.cxx
tests/compose/test-installroot.sh

We hit another case where people are pulling a container image with devices in `/dev` in the tar stream; they're then trying to commit this to an ostree.
There's much better ways to fix this:
- Change the image to stop including devices as there's no reason to do so
- Switch to logically bound images instead of physically bound
- Use the composefs backend for c/storage
Eventually I may look at "quoting" generally in ostree, but it's fairly invasive: https://github.com/ostreedev/ostree/issues/2568
In practice today, simply ignoring the files will happen to work for "podman run" of such images; podman will just use overlayfs to stitch together the `diff` directories, and doesn't try to do any validation of their contents today.
(Queue the composefs integration, which *would* do that but …

treefile: Add ignore-devices

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/core.rs
rust/src/lib.rs
src/app/rpmostree-builtin-status.cxx
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-transaction-types.cxx
tests/kolainst/destructive/container-rebase-upgrade

Having a digested pullspec is the container flow equivalent of an
ostree checksum origin. So having a custom origin in that case is useful
there for the same reasons (i.e. it means that something else is likely
managing the host and we want to reflect that info in the origin).
We're thinking of using this in FCOS when we move from OSTree to OCI
for updates.

daemon/transaction-types: Support custom origins for digested pullspecs

---

docs/treefile.md
rust/src/compose.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-core.cxx
tests/compose/test-misc-tweaks.sh

Both of those are motivated by the fedora-bootc use case to clean up the container-native compose path. See individual commit messages.
Related: https://gitlab.com/fedora/bootc/tracker/-/issues/39

compose: Allow missing `repos` key and add `--source-root` flag

---

src/app/rpmostree-compose-builtin-tree.cxx

Makes it on par with the base compose stuff. The information about which package is coming from which repo is really useful for debugging things.

compose: Print transaction when composing extensions

---

src/libpriv/rpmostree-core.cxx
tests/kolainst/destructive/layering-local

This effectively reverts https://github.com/coreos/rpm-ostree/pull/4594/commits/c1156001c096c261bc5c41ab56da7a3b0f476656
I was wrong, if we don't have fsverity today on the repo (a common case) then this entails a full read of all files. For more information see https://github.com/ostreedev/ostree/pull/3326

core: Don't add composefs metadata client side

---

src/libpriv/rpmostree-core.cxx

So it's more obvious in complex CI environments what the repositories are.

core: List all other repos when we fail to find a repo

---

packaging/rpm-ostree.spec

Trying to install the build dependencies in current c9s hits:
```
Error: Transaction test error:
file /usr/lib/rpm/fileattrs/cargo_vendor.attr from install of rust-toolset-1.82.0-1.el9.noarch conflicts with file from package cargo-rpm-macros-26.2-1.el9.noarch
```
which is clearly a bug in the packaging but it seems rust-toolset is dead, so let's stop using it.
https://issues.redhat.com/browse/RHEL-67475

spec: Drop rust-toolset requires on RHEL

---

docs/treefile.md
rust/src/treefile.rs

I want to stop abusing the `rojig` key in the CoreOS treefiles. But before we can switch over to `metadata`, we need variable substitution supported there too.
Note the `metadata` key can have arbitrarily nested values. For now, we just implement variable substitution for the first level of values since that's all we need.

treefile: Support variable substitution in `metadata`

---

configure.ac
packaging/rpm-ostree.spec

v2024.9
This release has multiple dependency updates and CI fixes, additionally there are 3 notable changes:
* We deprecated cliwrap https://github.com/coreos/rpm-ostree/pull/5088
* Add initial kickstart support https://github.com/coreos/rpm-ostree/pull/5119
* Support custom origins for digested pullspecs https://github.com/coreos/rpm-ostree/pull/5120
```
Aashish Radhakrishnan (1):
packaging/rpm-ostree.spec: Drop rust_arches
Colin Walters (15):
sysroot: Add total layer count to output
Deprecate cliwrap
Move dracut code from cliwrap to initramfs module
scripts: Ignore filesystem.transfiletriggerin
Revert "build(deps): bump regex from 1.10.6 to 1.11.0"
treefile: Add an `edition`
treefile: Add finalize.d as experimental
compose: Initial kickstart support
treefile: Add ignore-devices
core: …
```

Release 2024.9

---

src/daemon/rpm-ostreed-automatic.timer

This suggestion would update the timer behaviour of `rpm-ostreed-automatic.timer` to be more in line with the behaviour of `dnf-automatic.timer`.
**Problem Statement**
On a laptop which spends a lot of time in sleep mode, the timer frequency used by `rpm-ostreed-automatic.timer` is so infrequent that the service rarely ends up running.
To solve this, we can add
```ini
Persistent=true
```
This brings the behaviour into line with how `dnf-automatic.timer` works:
https://github.com/rpm-software-management/dnf/blob/69d1f641cda28fc543846524d15ec7291baf3e5a/etc/systemd/dnf-automatic.timer#L10
Just adding this alone can cause issues in environments with slow network bring-up, so we can also add:
```ini
Wants=network-online.target
```
Which also matches the `dnf-automatic.timer` behaviour:
I've …

Update timer to be more in-line with dnf-automatic

---

ci/libbuild.sh

The copr build environment does not have `dnf5-command(builddep)` installed. That caused dnf builddep command error.
```
dnf -y builddep ./contrib/packaging/bootc.spec
Unknown argument "builddep" for command "dnf5". Add "--help" for more information about the arguments.
It could be a command provided by a plugin, try: dnf5 install 'dnf5-command(builddep)'
make: *** [/mnt/workdir-c4js6f0t/bootc/.copr/Makefile:5: srpm] Error 2
```
dnf5 needs dnf5-command(builddep) installed to run "dnf builddep"
The copr build error log: https://log-detective.com/contribute/copr/8427985/srpm-builds

ci: fix copr build Unknown argument "builddep" for command "dnf5"

---

docs/debug.md

Add a initial doc on how to enabled verbose debugging to aid users trying to contribute or figure out issues.
I tested this with rpm-ostreed.

docs: Add debug.md

---

docs/treefile.md
rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/cliwrap.rs
rust/src/cliwrap/kernel_install_wrap.rs
rust/src/core.rs
rust/src/initramfs.rs
rust/src/kernel_install.rs
rust/src/lib.rs
rust/src/main.rs
rust/src/scripts.rs
rust/src/treefile.rs
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-scripts.cxx
src/libpriv/rpmostree-scripts.h

incorporates #5097 
closes: https://github.com/coreos/rpm-ostree/issues/4726
This will pair with: https://gitlab.com/fedora/bootc/base-images/-/merge_requests/62 which makes the integration work.
This builds and works on the following Containerfile.
Need to figure out how to properly deal with the commented out code still.
```
FROM $image
RUN curl -O -L -k https://kojipkgs.fedoraproject.org//packages/kernel/6.12.0/0.rc1.20241005git27cc6fdf7201.22.fc42/x86_64/kernel-6.12.0-0.rc1.20241005git27cc6fdf7201.22.fc42.x86_64.rpm && \
curl -O -L -k https://kojipkgs.fedoraproject.org//packages/kernel/6.12.0/0.rc1.20241005git27cc6fdf7201.22.fc42/x86_64/kernel-core-6.12.0-0.rc1.20241005git27cc6fdf7201.22.fc42.x86_64.rpm && \
curl -O -L -k https://kojipkgs.fedoraproject.org//packages/kernel/6.12.0/0.rc1 …
```

kernel-install: integration

---

.github/workflows/autovendor.yml
ci/installdeps.sh

To avoid issues like https://github.com/coreos/cargo-vendor-filterer/issues/110

ci: Use `cargo install --locked`

---

ci/test-container.sh
rust/src/cli_experimental.rs
rust/src/lib.rs
rust/src/main.rs

We already have `rpm-ostree ex` which is the same thing. However, adding things to that requires touching C code, which we often immediately turn back around and have invoke Rust, which is super annoying to juggle.
This CLI code is Rust from the start which makes adding commands more ergonomic.
For now this is just a placeholder.

Add `rpm-ostree experimental`

---

Cargo.lock
Cargo.toml
rust/src/bwrap.rs
rust/src/cmdutils.rs
rust/src/compose.rs
rust/src/composepost.rs
rust/src/container.rs
rust/src/initramfs.rs
rust/src/kernel_install.rs
rust/src/lib.rs
rust/src/testutils.rs
rust/src/treefile.rs

The `.run()` helper here avoids a lot of duplicate/repetitive code, *and* we handle stderr in a much better way.
This is a general cleanup, but also prep specifically for adding more command invocations.

tree-wide: Import and use cmdutils from bootc

---

Cargo.lock
deny.toml
rust/src/compose.rs
rust/src/origin.rs

Our dependabot configuration:
- Splits up each depedency update into a separate PR
- Is configured to only have outstanding a maximum number of PRs at a certain time
These two things combined with the dependency graph size and rate
of churn mean we are now far behind.
We should change this to how bootc works: Queue all minor updates
into a big PR.
Anyways, let's catch up.

Cargo.lock: Update(*)

---

configure.ac
packaging/rpm-ostree.spec

```
Alex Haydock (1):
Update timer to be more in-line with dnf-automatic
Colin Walters (13):
packaging: Add a bcond without ostree_ext
tree-wide: `cargo clippy --fix` + a few manual warning fixes
core: stop wrapping kernel-install when layout=ostree is set
packaging/Dockerfile: This is long since dead
cliwrap: use `const` over `static`
ci: Use `cargo install --locked`
Add `rpm-ostree experimental`
tree-wide: Import and use cmdutils from bootc
core: Create usr/sbin -> bin if we detect merged sbin filesystem
Cargo.lock: Update(*)
Fix use of deprecated GString::to_str()
Cargo.lock: Downgrade cxx to avoid missing cxxbridge-cmd during vendoring
deny.toml: Update allowed licenses
Joseph Marrero Corchado (3):
docs: Add debug.md
src/libpriv: Add kernel-install-integration
Release 2025.1
Xiaofeng …
```

Release 2025.1

---

src/libpriv/rpmostree-rpm-util.cxx

I'm working on doing container reencapsulation and using a user-mode repo and got burned by the hardlinking here and rpm always *writing* to the repo even when reading it.
Most systems we care about have reflinks so it's cheap. And in practice most usage of this before was actually checking out from bare (not bare-user) repos, so we were copying anyways.

libpriv/rpm: Always copy rpmdb even in user mode checkouts

---

Cargo.lock
Cargo.toml
deny.toml
packaging/rpm-ostree.spec
rust/src/sysroot_upgrade.rs

Depends: https://github.com/coreos/rpm-ostree/pull/5226
The idea is ostree-ext is deprecated in favor of bootc; however
we still directly use it here, and fixing that is going to take
a while longer than I thought.
Switch to pulling a pinned version from bootc's git, so
at least we don't need to maintain a formal crate for it
and think about API stability.

Use ostree-ext from bootc

---

packaging/rpm-ostree.spec

`rpm-ostree` copr build failed on RHEL and CentOS Stream with error `No matching package to install: 'rust-packaging'`. This PR is to fix this issue.

copr: fix "No matching package to install: 'rust-packaging'" in

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/lib.rs
rust/src/sysroot_upgrade.rs
src/daemon/rpmostree-sysroot-upgrader.cxx

If using OSTree remote signature verification for an OCI pull, print the verification text we get from ostree-ext.
Requires: https://github.com/containers/bootc/pull/1028

daemon/upgrader: Print OSTree signature verification text when pulling OCI

---

packaging/rpm-ostree.spec

This should fix https://github.com/containers/bootc/issues/1033 by ensuring the copr builds use the same logic.
(It's so annoying that we have default branching on packages,
but keeping them in sync is so annoying in general that
we end up merging, which defeats the reason for having branches
at all, and so we end up with these version conditionals anyways)

spec: Add version conditionals

---

rust/src/cliwrap.rs
rust/src/core.rs
rust/src/kernel_install.rs

The `is_ostree_layout()` function parsed the real root filesystem. But we started using it in *unit tests* which creates unpredictable behavior.
The unit test for the core script wrapping was failing for me, and digging in I don't see how it could have ever passed. I don't think we're actually running the Rust tests in CI...need to dig into that.
- Change `is_ostree_layout` to take a cap-std root
- Add a unit test for it alone
- Change all users to pass the rootfs
- Fix the `undo()` method to undo the kernel-install wrapping correctly
With this the unit test passes again, and we shouldn't have any behavior which depends on the development root.

core/cliwrap: Fix is_ostree_layout() in unit tests

---

.github/workflows/ci.yaml

This dropped out in
https://github.com/coreos/rpm-ostree/pull/5153/files and we missed that that run was also doing unit tests.

ci: Run Rust unit tests

---

Cargo.lock
Cargo.toml
rust/src/normalization.rs
tests/compose/libbasic-test.sh
tests/compose/test-misc-tweaks.sh

See https://github.com/rpm-software-management/rpm/issues/2219
This is one of the things that makes builds unreproducible in
general, which is worth fixing alone.
But the thing immediately driving this now for me is that I
think we're getting some ill-defined behavior because we
may have these files hardlinked (via ostree) and depending
on the container build environment, we may or may not see
modifications "through" the hardlink:
https://docs.kernel.org/filesystems/overlayfs.html#index
If we happen to mutate the `rpmdb.sqlite-shm` file in
one path but not the other confusion could easily result.
(Actually what we want to do really is drop our other
hardlinked copies of the rpmdb entirely, but that's
a bigger change)
Out of conservatism for now, we only do this if
`rpmdb-normalize` is set …

compose: Drop rpmdb sqlite journaling files if rpmdb-normalize

---

rust/src/compose.rs
rust/src/importer.rs
rust/src/tmpfiles.rs
src/libpriv/rpmostree-importer.cxx

Just prep for more work.
---
Move more tmpfiles code into tmpfiles module
Before we kind of viewed the "translate tmpfiles in package import"
as the core flow, but I think that needs to be a peer of
"postprocess tmpfiles".
Move all the tmpfiles code from importer.rs into tmpfiles.rs.
No functional changes.
---
importer: Add a comment linking to the consumer side
---
tmpfiles: Canonicalize import order
- std
- external crates
- local crates
---
tmpfiles: Rename escape function
I think this is clearer.
---

tmpfiles: Misc cleanup patches

---

src/libpriv/05-rpmostree.install

This is in response to https://bugzilla.redhat.com/show_bug.cgi?id=2342078

05-rpmostree.install: check for layout=ostree and install.conf presence

---

configure.ac

I messed up the release and only bumped the embedded spec file, better late than never so as not to confuse ourselves for the next release.

build-sys: Bump version to 2025.3

---

src/libpriv/rpmostree-container.cxx

Prep for the next change which ensures we cleanup rpmdb leftovers; we can't do that while possibly holding an open reference.

container: Do rpmdb cleanup in outer scope

---

packaging/rpm-ostree.spec

fixes https://github.com/coreos/rpm-ostree/issues/5261 by removing the conditional.
#5259 should address the issues seen on local package system with selinux policies.

packaging/spec: remove kernel_install conditional

---

configure.ac
packaging/rpm-ostree.spec

v2025.4
This is a bugfix release with fixes for kernel-install integration and rpmdb cleanup. 
When running on package mode systems now we will avoid calling into rpm-ostree kernel-install #5259 and when rpm-ostree kernel-install is called we will check if we are cli wrapping systemctl and unwrap it to allow the initramfs to be created correctly.
When running rpmdb cleanup now we make sure to close any open connection to the rpmdb.  #5247 
```
Colin Walters (2):
container: Do rpmdb cleanup in outer scope
build-sys: Bump version to 2025.3
Joseph Marrero Corchado (3):
05-rpmostree.install: check for layout=ostree and install.conf presence
kernel_install: unwrap systemd if it's wrapped
packaging/spec: remove kernel_install conditional
```
**Full Changelog**: …

Release 2025.4

---

rust/src/compose.rs
rust/src/container.rs

To try to debug https://gitlab.com/fedora/bootc/base-images/-/merge_requests/81#note_2320945827

compose: More error context for container-encapsulate

---

src/libpriv/rpmostree-core.cxx

Ignore xattrs when doing a copyup from the repo.
As far as I can tell and think of, this should always be safe. Basically we care about xattrs like
`security.selinux` and `security.capabilty`. For SELinux, we always relabel at the end when generating the commit. For `security.capability`, it's defined by the RPM. Other xattrs we shouldn't default to inheriting
from the "base" object - the RPM should set them
in general.
This enables using `rpm-ostree compose` in a podman/docker container which applies e.g. `container_t` to all files.

core: Ignore xattrs in copyup for rpmfi overrides

---

rust/src/cli_experimental.rs
rust/src/compose.rs

For consistency, but also because it can be confusing to have the enum variant be named the same as the underlying struct.
This caused a runtime issue for me that I can't reproduce anymore, but for posterity:
```
$ rpm-ostree experimental compose build-chunked-oci
thread 'tokio-runtime-worker' panicked at /var/home/jlebon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.27/src/builder/debug_asserts.rs:281:9:
Command build-chunked-oci: Argument group name must be unique
'BuildChunkedOCI' is already in use
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: task 1 panicked with message "Command build-chunked-oci: Argument group name must be unique\n\n\t'BuildChunkedOCI' is already in use"
```

rust: Rename `BuildChunkedOCI` struct to `BuildChunkedOCIOpts`

---

ci/prow/Dockerfile.buildroot

Attempting to fix https://github.com/coreos/rpm-ostree/issues/5280

ci/prow: Add a Dockerfile for build_root

---

src/libpriv/rpmostree-postprocess.cxx

OSTree should own generating this, we definitely don't want it in the image's `/boot`.
ref https://issues.redhat.com/browse/RHEL-64736

postprocess: Remove boot/loader

---

.github/workflows/ci.yaml
Cargo.lock
Cargo.toml
rust/src/cli_experimental.rs
rust/src/compose.rs
src/libpriv/rpmostree-postprocess.cxx
tests/compose-rootfs/Containerfile
tests/compose-rootfs/manifest.yaml

The loss of the buildah feature forces us to have a flow like this.

Add `experimental compose rootfs`

---

.github/workflows/ci.yaml
rust/src/compose.rs
rust/src/containers_storage.rs
rust/src/lib.rs
rust/src/reexec.rs

compose: Split off a containers_storage module
Prep for further work.
---
compose: Support buildah too
It's helpful for us to support build environments that only have podman,
as well as those that only have buildah. They're mostly doing the same
things; an abstraction over them is trivial. From this code, the only
difference really is `podman create` vs `buildah from`.
---
compose: Add some error prefixing
Turned out I was missing skopeo.
---

compose: Support buildah too

---

ci/test-container.sh
rust/src/cli_experimental.rs
rust/src/composepost.rs
rust/src/treefile.rs

We are working towards rebasing FCOS and RHCOS on top of fedora-bootc
and rhel-bootc. As one can imagine, we are quite heavily invested in
treefiles currently, so being able to keep using what we already have as
we transition into becoming a layered build is valuable.
Dockerfiles are great of course as the common language used to build
container images. But it's not great for implementing complex logic.
Add a new `rpm-ostree experimental compose treefile-apply` command
which takes a treefile, but applies its directives _live_ in the running
environment.
So in this model, the business logic in the Dockerfile is kept to a
minimum and all the heavy lifting happens via
`RUN rpm-ostree compose treefile-apply manifest.yaml`.
A very small subset of the treefile spec is actually supported. The …

Add new `treefile-apply` experimental command

---

ci/test-container.sh

ci/test-container.sh: Make it easier to execute locally and run `treefile-apply` test earlier

---

configure.ac
packaging/rpm-ostree.spec

v2025.5
```
Colin Walters (15):
compose: More error context for container-encapsulate
chunked-oci: Rework to support --from too
treefile: Add error context for finalize.d
core: Ignore xattrs in copyup for rpmfi overrides
Update bootc
postprocess: Remove boot/loader
ci/prow: Add a Dockerfile for build_root
postprocess: Add an error prefix
Add `experimental compose rootfs`
compose: Split off a containers_storage module
compose: Support buildah too
compose: Add some error prefixing
ci: Various fixes
core: Use source root for repos and dnf vars
compose-rootfs: Add --source-root-rw
Jonathan Lebon (5):
rust: Rename `Opt` struct to `ComposeImage`
rust: Rename `BuildChunkedOCI` struct to `BuildChunkedOCIOpts`
Add new `treefile-apply` experimental command
ci/test-container.sh: Make it easier to …
```

Release 2025.5

---

rust/src/compose.rs

When I added the gpgkey= rewriting, I tested it when using Fedora as a buildroot, targeting CentOS Stream. The relevant thing here is parsing the CS `.repo` files, which just have e.g.
`gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial-SHA256`
But Fedora actually uses basearch *and* releasever repo variables: `gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch`
Now there aren't actually *per architecture* keys so this never made sense but let's move on.
It turns out...it's even harder than that, the rawhide repo file (only) actually uses multiple keys:
`gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-rawhide-$basearch file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-44-$basearch`
In order to handle transitory state.
Anyways, so the fix here is to:
- If we see a …

compose-rootfs: Fix gpgkey= with Fedora examples

---

.github/workflows/ci.yaml
rust/src/compose.rs
rust/src/containers_storage.rs

containers_storage: Only reexec if we're in a container
This fixes running this command directly as root outside
of a container.
---
build-chunked-oci: Propagate creation timestamp with --from
When we're building from an existing image, ensure that we
also inherit its creation timestamp. This is implemented
by ensuring the embedded ostree commit uses that timestamp,
which is then honored by the underling ostree-container
encapsulation logic.
---

build-chunked-oci: Propagate creation timestamp with --from

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/compose.rs
rust/src/lib.rs
src/app/rpmostree-builtin-compose.cxx
src/app/rpmostree-compose-builtins.h
tests/compose-rootfs/Containerfile

Expose this as `rpm-ostree compose rootfs`.

compose: Stabilize `compose rootfs`

---

.github/workflows/ci.yaml
rust/src/compose.rs
rust/src/container.rs

container-encapsulate: Quiet multiple owners
Right now this is all normal and expected basically. If someone
needs to debug a case around this later we can add some
sort of verbose debugging.
---
container-encapsulate: Propagate --max-layers
The existing CLI has this, just propagate it.
---

container-encapsulate: Two patches

---

rust/src/compose.rs

I'm trying to debug
`error: Generating commit from rootfs: Processing dir var: Writing content object: Incorrectly sorted xattr name, index=2`
right now (and the "Processing dir var" is new and at least mildly helpful)

chunking: Add some error context

---

.github/workflows/ci.yaml
rust/src/compose.rs
rust/src/containers_storage.rs

The previous change made us work rootless, but broke running rootful. This is going to be quite painful in practice to unwind... right now I care more about rootful, so let's make that one work again (and test going from containers-storage -> containers-storage in CI).

chunking: Fix working as rootful

---

rust/src/compose.rs

This is effectively the inverse of https://github.com/ostreedev/ostree-rs-ext/pull/679/commits/e33340dbab9c909f4f8172d8f2bc8b3656ab2341
Came up in https://gitlab.com/redhat/centos-stream/containers/bootc/-/merge_requests/437#note_2368026538

compose-rootfs: Also set xattrs on target root

---

Cargo.lock
Cargo.toml

To pull in
https://github.com/containers/bootc/pull/1096/commits/57bd0dc9835669274696998386a547afb6709ff5 specifically so that it gets used by Anaconda.

Bump to latest bootc

---

rust/src/compose.rs

chunked: Default format-version to 1
Having to specify it is annoying.
---
chunking: Use NonZeroU32, expand docs
The first we do elsewhere, it obviously can't be zero.
And more docs are good.
---

chunking: two minor patches

---

docs/treefile.md
rust/src/treefile.rs
tests/compose/test-misc-tweaks.sh

It's useful to have the source directory too to be able to copy things from it for example. I plan to use this for bootc-base-imagectl in fedora-bootc.

treefile: Set RPMOSTREE_WORKDIR for finalize.d

---

rust/src/compose.rs
tests/compose-rootfs/Containerfile
tests/compose-rootfs/manifest.yaml

Just output a "plain" fsroot. We can't do ostree-container because (unlike compose image) we won't have the ostree.final-diffid indicator in the output image, so ostree/bootc won't honor all the ostree stuff.
Combined with a prior bug where we were missing setting the `security.capability` flag, this was causing the failures in trying to do the centos-bootc build.
Closes: https://github.com/coreos/rpm-ostree/issues/5314

compose-rootfs: Don't output ostree-container format

---

rust/src/compose.rs
src/app/rpmostree-compose-builtin-tree.cxx

Many use cases will be fine combining these two steps, and it's annoying to do them separately if you don't need that.
But more specifically this also fixes a problem when referencing a manifest that refers to e.g. `basearch` which isn't populated in a separate `postprocess` step.

compose: Add compose install --postprocess

---

rust/src/compose.rs
tests/compose-rootfs/Containerfile

The trick we did here in working around `compose install` generating a `rootfs` subdirectory by moving its contents into the parent meant we lost the mode bits.
Somehow, only when targeting this for CentOS we hit on the mode being 0700 (I think this may relate to umask? We probably need to audit our whole codebase to avoid umask issues; but really in the longer term switch to trusting the `filesystem` rpm instead of manually extracting the root).

compose-rootfs: Fix perms for /

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/lib.rs
rust/src/sysroot_upgrade.rs
src/app/rpmostree-builtin-rebase.cxx
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-transaction-types.cxx
tests/kolainst/destructive/container-image
tests/kolainst/destructive/container-rebase-upgrade

In FCOS, we want to keep a tagged refspec in the origin, but still be
able to deploy a specific image.
Enable this.
(It's not quite the same as the OSTree case of course, because there's
no concept of branches there. But at least we can enforce that the
digest is located in the same repo as the canonical refspec.)
This is tracked on the bootc side in
containers/bootc#1165.

daemon,app: Support rebasing/deploying specific digests in OCI path

---

.github/workflows/ci.yaml
docs/build-chunked-oci.md
rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/compose.rs
rust/src/lib.rs
src/app/rpmostree-builtin-compose.cxx
src/app/rpmostree-compose-builtins.h

Expose this as `rpm-ostree compose build-chunked-oci`
Signed-off-by: John Eckersberg <jeckersb@redhat.com>

compose: Stabilize `compose build-chunked-oci`

---

.github/workflows/ci.yaml
rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/core.rs
rust/src/lib.rs
src/libpriv/rpmostree-core.cxx
tests/compose-image.sh

rpmostree-core: Emulate new %sysusers RPM scriplet
As part of the migration to direct sysusers support in RPMs, packages
are no longer creating their users/groups in %pre scripts as they rely
on RPM to do the work in a built in %sysusers scriplet.
The RPM library does not expose a direct interface to call those
scriplets so we instead emulate the process by directly calling out to
the binary pointed by `%__systemd_sysusers`, if it is set.
See: https://fedoraproject.org/wiki/Changes/RPMSuportForSystemdSysusers
See: https://github.com/rpm-software-management/rpm/commit/009d1397331a89413e2c5eead163cadb47ccdb4b
See: https://github.com/fedora-silverblue/issue-tracker/issues/636
See: https://gitlab.com/fedora/ostree/sig/-/issues/70
See: https://github.com/coreos/rpm-ostree/issues/5333
--- …

rpmostree-core: Emulate new %sysusers RPM scriplet

---

rust/src/compose.rs

The tempdir holds the ostree repo.
I'm looking at an issue reported in a downstream build that failed like this:
```
+ rpm-ostree experimental compose build-chunked-oci --bootc --format-version=1 --rootfs /target-rootfs --output oci-archive:/buildcontext/out.ociarchive
Generating commit...
error: Generating commit from rootfs: syncfs: Not a directory
subprocess exited with status 1
subprocess exited with status 1
```
Which frankly has me just confused. The `syncfs` here is almost certainly coming from libostree's sync of the target repo.
And "Not a directory" is especially weird, implying that `repo/tmp` got swapped with something else?

compose: Ensure tempdir is dropped after commit

---

README.md

It seems to be causing more confusion than help right now. We're going to keep maintaining this project for a long time because people are using it and it's shipped in products.
The main original goal of the notice was to ensure people didn't show up out of the blue and start proposing big new changes, but in reality that's unlikely to happen anyways. The "promoting where things are happening" is already done organically by just, well, seeing where things are happening.

README.md: Effectively revert deprecation notice

---

rust/src/compose.rs
src/app/rpmostree-compose-builtin-tree.cxx
tests/compose-rootfs/Containerfile

- First ensure we're always ignoring SELinux here, in this use case we rely on e.g. bootc to do client side labeling. Doing this required a fix in the compose path.
- Second and more importantly, ensure we don't leak user.ostreemeta xattrs into the target root! This is just generally ugly, and will e.g. cause object duplication on disk. But worse, having `user.` xattrs provokes backwards incompat bugs from https://github.com/ostreedev/ostree/pull/3346

compose-rootfs: Ensure we don't emit user.ostreemeta

---

.github/workflows/ci.yaml
Cargo.lock
Cargo.toml
deny.toml
rust/src/compose.rs
rust/src/container.rs
tests/build-chunked-oci/Containerfile.test
tests/build-chunked-oci/test.sh

- Move build-chunked-oci test into its own script; motivated
by extending this and making it easier to run outside GHA.
Less bash-in-YAML
- Ensure we pass the correct container metadata down to
build-chunked-oci to preserve labels
- Because all we do is rearrange files in tarballs basically
(i.e. we don't execute any code in the target) we should handle
cross-architecture rechunking OK. Ensure that we also
propagate the architecture from the original manifest.
Closes: #5340 
---

build-chunked-oci: Handle multi-arch, perserve labels

---

ci/test-container.sh
docs/treefile.md
rust/src/treefile.rs

Working on moving openshift/os over to `treefile-apply` and identified a few more things we need. See individual commit messages.

Various enhancements and tweaks for OCP node image build

---

rust/src/core.rs
src/libpriv/rpmostree-core.cxx

At least in FCOS, we add sysusers dropins via overlays and we need those
already present when running `systemd-sysusers`.
Looking at the history here, there's no reason it seems why we were
only processing ostree layers in the path where we had RPM packages
to overlay. It should be safe to move out of that gate. Anyway on the
client side nothing is hooked to that so it still remains a server-side
feature.
Closes: #5353

core: Process ostree layers before running sysusers

---

rust/src/compose.rs

rust/src/compose: Show full comment in command line help
Remove an empty comment line to make sure that the entire comment is
shown in the help text on the command line. Otherwise, the sentences
after the blank line are not shown.
---
rust/src/compose: Add max-layers opt to compose image
Mirror the option added to the chunk command for the compose image
command to directly pass the max-layer option when chunking.

rust/src/compose: Add max-layers opt to compose image

---

configure.ac
packaging/rpm-ostree.spec

```
Colin Walters (7):
tree-wide: Run clang-format with clang 20.1.3
test-container: Update for F42
tests: Drop testing of ostree-container
tests/container-image: Rework to handle container base
tests/cached-sigs: Fix to handle container refspec by default
tests: Drop override-kernel
tests/override-replace-2: Update to support f42
Iain Collins (1):
daemon/transaction-types: pass an empty dictionary instead of NULL to change_origin_refspec
Jonathan Lebon (19):
treefile: Support inlined conditional includes
treefile-apply: Add `--var` option
treefile-apply: Handle `repos` key
treefile-apply: Enable versionlock plugin when running dnf
treefile-apply: Tweak `versionlock` hack
core: Move sysusers docstring to the Rust side
rust/core: Drop unnecessary Vec
core: Process ostree layers before …
```

Release 2025.8

---

rust/src/bwrap.rs

According to the docs [1] g_spawn_check_exit_status is deprecated and also that users should check their code to make sure they aren't conflating wait and exit statuses.
Let's just avoid it altogether by calling wait_check() [2] which will wait() and then call g_spawn_check_wait_status(), which is basically what our code was doing before, but without the conflation of wait and exit status.
[1] https://gnome.pages.gitlab.gnome.org/libsoup/glib/glib-Spawning-Processes.html#g-spawn-check-exit-status
[2] https://gnome.pages.gitlab.gnome.org/libsoup/gio/GSubprocess.html#g-subprocess-wait-check

rust/bwrap: child_wait_check: let gio check status

---

rust/src/bwrap.rs
rust/src/composepost.rs
tests/compose.sh

Let's merge it with STDOUT so we still get the STDERR logs when
running commands.
The reason I came upon this is because when we run rpm-ostree compose
postprocess scripts we were clearly not getting all of the output. For
example a lot of our scripts are `set -x` but none of that output was
getting printed anywhere, and also things like `systemctl preset-all`
wouldn't show any output at all (which apparently that commands writes
its output to STDERR for some reason).

rust/bwrap: don't swallow STDERR when running commands

---

src/app/libmain.cxx

We will never see the confusing "regex version mismatch" again. No one ever cared and it was never actionable.

main: Silence SELinux log spam

---

tests/vmcheck/test-override-replace-2.sh

Let's also override container-selinux with the release day version, otherwise periodically we'll encounter issues where container-selinux requires newer and newer versions of selinux-policy and we'll have to update this test multiple times a release.

tests/override-replace-2: increase reliability of selinux override

---

rust/src/compose.rs
src/libpriv/rpmostree-kernel.cxx

Since f4aecb9b ("rust/bwrap: don't swallow STDERR when running commands"), we now have the stderr from dracut, which reveals that it spews lots of warnings about being unable to copy xattrs when running from an `rpm-ostree compose rootfs`.
I think this comes from the `user.ostreemeta` xattr which hasn't been stripped yet.
It'd be better anyway to do this stripping within the rpm-ostree core I think, but for now it's actually trivial to work around this by setting `DRACUT_NO_XATTR`.
I'm pretty sure we could set this unconditionally, but out of an abundance of caution, we only do this for now from the `rpm-ostree compose rootfs` path where we know we want this.
Fixes: https://gitlab.com/fedora/bootc/tracker/-/issues/66

libpriv/kernel: Pass through `DRACUT_NO_XATTR` when running dracut

---

rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/lib.rs
rust/src/passwd.rs
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-kernel.cxx
tests/kolainst/destructive/layering-useradd

I'm looking at https://github.com/coreos/rpm-ostree/issues/5365 - this is prep work just adding unit & integration test coverage for the existing code.
---
tests: Add a layering-useradd test
Verifies our behavior with useradd/groupadd in `%post`.
---
passwd: Accept borrowed value
Prep cleanup.
---
passwd: Some basic unit tests for prepare_rpm_layering
- Rename inner helper to complete_rpm_layering to match
---
passwd: Make merge take a dfd
This allows it to be more sanely unit testable.
---

passwd: Prep work for fixing https://github.com/coreos/rpm-ostree/issues/5365

---

.github/dependabot.yml

Dependabot is hopelessly behind now, and the chance that a minor or patch update *individually* breaks something has been in practice near zero.

dependabot: Group minor+patch updates

---

src/libpriv/rpmostree-scripts.cxx

Fixes https://github.com/coreos/rpm-ostree/issues/5411. Follow-up for https://src.fedoraproject.org/rpms/glibc/pull-request/145 (rawhide) and https://src.fedoraproject.org/rpms/glibc/pull-request/144 (f42).
Thank you for contributing to rpm-ostree.
If you are adding functionality to tree composes, please add
a corresponding test to the compose-test suite. Similarly,
if adding a client-facing feature, consider the vmcheck
suite. Regressions fixes are also great candidates for new
tests.
If you're not sure where or how to add tests, don't hesitate
to ask for help from the maintainers.
Cheers!

scripts: suppress error about glibc.posttrans scriptlet

---

Cargo.lock
Cargo.toml
deny.toml

To pick up recent fixes, but especially to
Closes: https://github.com/coreos/rpm-ostree/issues/5406

Update to bootc 1.3.0

---

Cargo.lock
Cargo.toml
docs/build-chunked-oci.md
rust/src/compose.rs
rust/src/container.rs
tests/build-chunked-oci/test.sh

This creates all parent directories in tar layers
Resolves: #5416
Signed-off-by: John Eckersberg <jeckersb@redhat.com>

rechunker: Add `--format-version=2`

---

src/app/libmain.cxx
src/app/rpmostree-builtin-deploy.cxx
src/app/rpmostree-builtin-initramfs-etc.cxx
src/app/rpmostree-builtin-initramfs.cxx
src/app/rpmostree-builtin-kargs.cxx
src/app/rpmostree-builtin-rebase.cxx
src/app/rpmostree-builtin-upgrade.cxx
src/app/rpmostree-override-builtins.cxx
src/app/rpmostree-pkg-builtins.cxx

This was classified as experimental originally, but is clearly stable and in use by zincati etc.
Motivated by potential use in OpenShift and other places.

Un-hide finalization APIs

---

.cci.jenkinsfile
docs/treefile.md
rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/core.rs
rust/src/lib.rs
rust/src/treefile.rs
src/libpriv/rpmostree-core.cxx
tests/common/libvm.sh
tests/compose/test-misc-tweaks.sh

In the work to rebase FCOS/RHCOS to fedora-bootc/rhel-bootc, I want to make it possible to opt out of the passwd/group bits baked in the minimal manifests (the problem there of course goes back to UID/GID drift issues -- this has caused issues as well on the IoT/Edge side). The current passwd/group files in the minimal manifest are both outdated and incomplete (most of it can in fact trace its lineage all the way back to Fedora Atomic Host).
But more generally, in the FROM scratch flow, users _should_ have the ability to customize which user gets which UID. And one could imagine an option like `bootc-base-imagectl --passwd mypasswd --group mygroup` but (1) while the format is well-known, using it as an interface for building root filesystems is less so, and for example has no …

treefile: Add `sysusers:` knob

---

rust/src/bwrap.rs
rust/src/compose.rs
rust/src/composepost.rs
rust/src/treefile.rs
tests/compose/test-basic-unified.sh
tests/kolainst/destructive/layering-local
tests/kolainst/kolainst-build.sh

This reverts commit https://github.com/coreos/rpm-ostree/commit/f4aecb9b62a97eee8368ca8058b33325891cd62d.
It causes ill-defined behavior with older glib, resulting in
file descriptor mis-assignments.
Also add tests that verify that we do get both stdout and stderr from both postprocess scripts and package scripts.
Closes: https://github.com/coreos/rpm-ostree/issues/5436

Many patches for stderr

---

rust/src/compose.rs
tests/build-chunked-oci/test.sh

This allows the use of oci-archive when the archive doesn't yet exist.
fixes #5442

rechunker: Use open_image when transport is oci-archive

---

ci/test-container.sh

I'm really tempted to just rip out all the testing for these hardcoded package versions that break our CI every 6 months.

ci: Bump afterburn version

---

docs/treefile.md
rust/src/treefile.rs

This change allow to set the 'repo-metadata' option into the base manifest file instead of being forced to set it into the leaf manifest file (the one with the last include).
We now serialize 'repo-metadata: inline', causing an input hash change for people explicitely setting the default.

treefile: merge 'repo-metadata' config

---

docs/treefile.md
rpmostree-cxxrs.cxx
rpmostree-cxxrs.h
rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-tree.cxx
tests/compose/test-advisories-metadata.sh

Similar to repo-metadata, advisories-metadata option allow to set
if you should store advisories information in the commit metadata,
in the detached metadata, or not at all.

treefile,compose: add advisories-metadata option

---

configure.ac
packaging/rpm-ostree.spec

Release 2025.11
```
Alexander Larsson (1):
Fix SELinux aliases for /usr/etc/systemd/system (and similar)
Chris Kyrouac (1):
Update version of afterburn
Colin Walters (3):
ci: Bump afterburn version
ci: Update for coreos-assembler API break
ci: Drop NEVRA override testing
Etienne Champetier (4):
compose: sort packages before rpmtsOrder()
treefile: merge 'repo-metadata' config
treefile,compose: add advisories-metadata option
compose: allow write-lockfile-to / lockfile / lockfile-strict together
Jonathan Lebon (2):
compose: Add `--lockfile` to `rpm-ostree compose rootfs`
compose: Add `--label` for build-chunked-oci
Joseph Marrero Corchado (1):
Release 2025.11
Marco Hünseler (1):
fsutil.rs: Make `is_dir` return correct information
ckyrouac (3):
rechunker: Recursively add directories with …
```

Release 2025.11

---

src/app/rpm-ostree-0-integration.conf

This PR resolved rpm-ostree part of issue https://issues.redhat.com/browse/RHEL-106203.
I only remove `/usr/local/man` tempfile create in `rpm-ostree`, but I can't fix `/home` and `/srv` which is created by systemd https://github.com/systemd/systemd/blob/main/tmpfiles.d/home.conf

Remove /usr/local/man tempfile create

---

.github/actions/bootc-ubuntu-setup/action.yml
.github/workflows/ci.yaml

This cleans up disk space, which we're now hitting.
However to really be consistent we need to stop using `container:` in all jobs and switch to having this action run first step, and then spawn podman (or docker) inside jobs.

ci: Import bootc setup action, use in a few jobs

---

tests/build-chunked-oci/test.sh

The github action is running out of disk space. Cleanup the images between tests to free up space.

rechunker: Cleanup test state mid run
