src/rpmostree-postprocess.c

I sometimes run "rpm-ostree compose tree" directly, mainly so I can
use gdb and/or nonstandard options.  In this case I don't get
version numbers injected.
That happens to trigger a bug in this code.

postprocess: Don't g_critical if previous commit doesn't have version

---

configure.ac
src/rpmostree-postprocess.c

This matches recent work in OSTree to use *at() - it's faster and less
prone to error.  In the case of directories which are mutable by
processes in different security domains, it's more secure too.  (That's
not the case here though).

compose: Use *at() relative lookups for xattrs

---

src/rpmostree-compose-builtin-tree.c

We're going to start adding our own metadata, so take this initial
step of having the user-specified metadata accumulated into a builder.

compose: Convert metadata handling into builder

---

src/rpmostree-compose-builtin-tree.c
src/rpmostree-passwd-util.c
src/rpmostree-passwd-util.h

I'm planning to replace the caching code with something that inspects
the previous commit rather than a lookaside cache, so raise this code
up to a higher level.

compose: Raise up the code to read the previous (OSTree) commit

---

src/rpmostree-passwd-util.c

Maybe we should make this into an explicit error, but anyways
I somehow ended up with an empty /usr/etc/passwd in the tree
contents, I think due to bugs in earlier work there.
This causes fmemopen to return EINVAL, which errors out the
compose.  Let's stumble forwards here.
Now that I think about it, it might be a valid case to have an
existant but empty /usr/etc/passwd in the tree - when we migrate to
systemd-sysusers, I think we'll want an empty file there by default.

passwd: Avoid EINVAL if previous passwd data is empty somehow

---

src/rpmostree-passwd-util.c

This was breaking the
make -C packaging -f Makefile.dist-packaging dist-snapshot-without-compose-tooling
build.

passwd-util: Drop unnecessary #include

---

doc/treefile.md
src/rpmostree-compose-builtin-tree.c
src/rpmostree-passwd-util.c
src/rpmostree-passwd-util.h

Needs some docs. also a bit more testing before merging, as a bunch of code got moved about and reused.
Basically the migrate code will now look at the files pointed to by check-passwd/check-group so that they can be migrated across branches.

passwd: Use check-* file json config. entries to migrate data across commits

---

doc/treefile.md

See the code.  (We could change the code to match the docs, but I like
the extra `d` and it's basically ABI now anyways).

docs: It's ignore-*removed*, not ignore-remove

---

src/rpmostree-compose-builtin-tree.c

The header was renamed in newer versions of libhif.
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

build: replace libhif/hif-context-private.h with libhif/hif-utils.h

---

configure.ac
src/rpmostree-treepkgdiff.c

We will work on both old and new versions.
See https://github.com/rpm-software-management/hawkey/commit/8ce3ce754f50b4284587ceaa2eb4c0acf328912a

treepkgdiff: Adapt to Hawkey 0.5.3 API break

---

autogen.sh

Otherwise the git submodule invocations produce errors.

Fix running autogen.sh from outside the source directory

---

Makefile-lib.am
Makefile.am
src/lib/rpmostree-db.h
src/lib/rpmostree.h

This avoids symbol leakage.  Previously we were at risk of exporting
other random API from libpriv, as well as libglnx.

build: Use -fvisibility=hidden and explicit exports

---

doc/rpmostree-sections.txt
src/lib/rpmostree-package.c
src/lib/rpmostree-package.h

Equivalent to `hy_package_cmp()`, but works for comparing packages from different memory pools.
This a stop gap measure in light of https://github.com/rpm-software-management/hawkey/pull/90
If and when that pull request gets merged, then this function could at some later point simply call `hy_package_cmp()`.

Add rpm_ostree_package_cmp()

---

doc/treefile.md
src/libpriv/rpmostree-postprocess.c

If this is set we don't do anything special for kernel or /boot, as such things are not needed when running in a container.
I need this as i'm trying to use rpm-ostree for a xdg-app runtime, but i imagine it can be useful in other cases too.

Support container=true in treefile

---

src/libpriv/rpmostree-postprocess.c

It moved from `/usr/sbin` -> `/usr/bin`, which obviously broke
rpm-ostree.
No reason to hardcode absolute paths here.

postprocess: Don't use absolute paths for helpers like dracut

---

src/app/main.c

This change causes the subcommands to be sorted alphabetically when
`rpm-ostree` is invoked without an argument or with `--help`.  This
matches the behavior of the `ostree` command.

Sort subcommands alphabetically

---

src/app/rpmostree-compose-builtin-tree.c

Bodhi points rpm-ostree at the "gold" Fedora repo via `file:///`, and
libhif is brokenly checking the mtime on `file://` repos.
Work around that here by just ignoring cache ages, because at present
we don't actually cache really - we drop the RPMs in the tempdir.
(Long term having actual caching of the RPMs would be nice, but
we can revisit this when we get there)
Closes #156

compose: Fix "too old" error for "old" file:/// repos

---

src/app/rpmostree-compose-builtin-tree.c

Someday we'll enhance RPM; see
https://github.com/rpm-software-management/rpm/issues/8
But anyways right now at least a few people have tried,
and we get all the way past downloading packages and then bomb
out when doing the actual transaction with a useless error
message.
So let's be up front about this.

compose: Require being run as root

---

tests/test-basic.sh

The assert[_not]_file_has_content functions used grep to check the
pattern against the content. This meant that the '.' characters are
interpreted as "any char". Yesterday, the date was 20150910 and thus the
otheros' tree's version was labelled as such. This date also happens to
match the 1.0.10 pattern, and thus caused the test to fail.
This patch makes sure this doesn't happen again by escaping all the dots
to make them literal.

tests/test-basic.sh: make dots literal

---

src/daemon/org.projectatomic.rpmostree1.xml
src/daemon/rpmostreed-sysroot.c

It's helpful to know what OS is being updated when there are multiple OS objects.

daemon: Expose the path that started a transaction

---

src/app/rpmostree-builtin-upgrade.c
src/daemon/org.projectatomic.rpmostree1.xml
src/daemon/rpmostreed-deployment-utils.c
src/daemon/rpmostreed-deployment-utils.h
src/daemon/rpmostreed-os.c

I'd like to propose returning a info dictionary from the methods that return cached rpm diffs. This commit right now just changes the xml to the proposed api. If you like the idea then I can fill in the code.

daemon: Add info dictionary to cached results

---

Makefile-rpm-ostree.am
man/rpm-ostree.xml
src/app/main.c
src/app/rpmostree-builtin-compose.c
src/app/rpmostree-builtin-db.c
src/app/rpmostree-builtin-deploy.c
src/app/rpmostree-builtin-rebase.c
src/app/rpmostree-builtin-rollback.c
src/app/rpmostree-builtin-status.c
src/app/rpmostree-builtin-upgrade.c
src/app/rpmostree-builtins.h
src/app/rpmostree-compose-builtin-sign.c
src/app/rpmostree-compose-builtin-tree.c
src/app/rpmostree-db-builtin-diff.c
src/app/rpmostree-db-builtin-list.c
src/app/rpmostree-db-builtin-version.c
src/app/rpmostree-dbus-helpers.c
src/app/rpmostree-dbus-helpers.h
src/app/rpmostree-libbuiltin.c
src/app/rpmostree-libbuiltin.h
src/daemon/org.projectatomic.rpmostree1.xml
src/daemon/rpmostreed-deployment-utils.c
src/daemon/rpmostreed-os.c
src/daemon/rpmostreed-transaction-types.c
src/daemon/rpmostreed-transaction-types.h
src/daemon/rpmostreed-utils.c
src/daemon/rpmostreed-utils.h
tests/test-basic.sh

Following up on https://github.com/projectatomic/rpm-ostree/issues/172 and https://github.com/GNOME/ostree/pull/147.
I'm still working on test cases for this, but I wanted to get the code changes posted ASAP.
This enhances the `rpm-ostree rebase` command to allow rebasing to any version.
Syntax changes are:
```
rpm-ostree rebase [-V / --to-version=VERSION] [-R / --to-revision=CHECKSUM] [REFSPEC]
```
Note: `REFSPEC` is now optional, but only if `--to-version` or `--to-revision` is specified.  Defaults to the booted deployment's origin refspec.
I know we talked about putting version lookup directly in `libostree` and I still want to, but I'm shying away from it for the moment because I think it needs more thinking through.  The way I'm solving version lookups here is really slow and clunky …

Deploy any version

---

src/app/main.c

We are currently using `PACKAGE_NAME` for version output, which returns
exactly what it says it does: the package name.  Not very useful when
looking for version information.
`PACKAGE_STRING`, on the the other hand, returns the package name and the
version.  Much better!
This is nicely documented in the autoconf manual [1].
[1] http://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Initializing-configure.html#Initializing-configure
Signed-off-by: Micah Abbott <miabbott@redhat.com>

Use PACKAGE_STRING for version output

---

src/app/rpmostree-dbus-helpers.c

`rpm-ostree deploy X.Y.Z | cat` was aborting on the client side.  I
noticed this when using it via Ansible.

app: Handle progress when not being connected to a tty

---

src/libpriv/rpmostree-postprocess.c

We should tell the user that we will run the postprocess script *before*
we run it to help them diagnose issues if things go wrong.
Resolves: #188

postprocess.c: be more verbose when running script

---

src/daemon/rpmostreed-deployment-utils.c

Otherwise we trip an assertion.  In the future I think we should
likely encourage `file:///ostree/repo` or so, and thus support
`gpg-verify`.

daemon: Treat local deployments as gpg-verify=false

---

Makefile-libpriv.am
src/app/rpmostree-compose-builtin-tree.c
src/libpriv/rpmostree-hif.c
src/libpriv/rpmostree-hif.h

As we start to do more package things, extract common helper functions
around HifContext * that by default operates on the system root.
Some of these bits should go in libhif, but the immediate plan is to
iterate here, then push downwards later.

Extract a shared internal rpmostree-hif.[ch]

---

Makefile-libpriv.am
Makefile-rpm-ostree.am
src/app/main.c
src/app/rpmostree-builtin-internals.c
src/app/rpmostree-builtins.h
src/app/rpmostree-internals-builtin-unpack.c
src/app/rpmostree-internals-builtins.h
src/libpriv/rpmostree-unpacker.c
src/libpriv/rpmostree-unpacker.h

I'd like to experiment with different things that end up
reusing chunks of the rpm-ostree internals, such as libhif, the
helpers we already have around RPM, etc.
In this particular case I'm experimenting with unpacking/committing
RPM packages as non-root.  Eventually most of this should end up as
internal private shared library, but it's convenient to have an
ABI-unstable and hidden "internals" command to run things directly.

Add testing-only `internals` subcommand, with `unpack` verb

---

configure.ac

For some reason my CD builder didn't trigger this, but we do actually
need `-larchive` (and we want to have the dependency metadata so
packagers know to BuildDepends on it).

build: Add `libarchive` to pkg-config deps

---

src/daemon/org.projectatomic.rpmostree1.conf

Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1297473
Gotta poke some holes in the policy so normal users can run `rpm-ostree status`.
Also allow for introspection and property getting, since there's no reason to block those.
This could be a good opportunity to revisit PolicyKit integration, which we originally deferred.
But this gets the bug fixed.

Update D-Bus security policy for rpm-ostreed

---

tests/libtest.sh
tests/setup-session.sh.in

For the same reasons as described in GNOME/ostree#187. In summary: we
want to make it easy for testers to clean up after we're done by not
setting the immutable flag.
Note that I had to also add it to setup-session.sh so that the daemon
inherited the env var. The libtest.sh hunk is redundant in that case,
but still necessary if the tests are run directly.

tests: make ostree use mutable deployments

---

src/daemon/main.c

There are many reasons why the daemon may not be able to start up. An
initialization error doesn't/shouldn't reflect a programming mistake,
but instead a runtime issue in the environment.
Thus, if we fail to start the daemon, we shouldn't use g_error(), which
dumps core. We should instead print the GError and clean up as nicely as
we can.
Resolves: https://github.com/projectatomic/rpm-ostree/issues/194

daemon: don't dump core on error

---

Makefile-tests.am
tests/test-ucontainer.sh

Running `make check` would fail because test-ucontainer.sh uses
test-repo, which points directly to the installed_testdir, where it is
not installed yet.
We make another processed version of test-repo.repo.in which instead
points to the repo in the srcdir and make use of that in
test-ucontainer.sh.
There are probably other ways of solving this, but this is the one that
jumped out at me.

test-ucontainer.sh: use test-repo in srcdir

---

.travis.yml
configure.ac

I'd like to use Homu immediately as a replacement for the github merge
button, because I really dislike merge commits for single patches.
I think it shouldn't be too hard to unify our existing PR testing with
this.

Add a stub travis file to enable Homu

---

src/libpriv/rpmostree-postprocess.c
src/libpriv/rpmostree-rpm-util.c
tests/compose/yum/empty.spec

These patches are backports of bug fixes that happened during the package layering rework. My guess is we don't need the brutal hack patch anymore, but might as well leave it in for now.
Fixes #379.

Fixes for the 2016.3 release

---

tests/common/libvm.sh

This patch clearly underscores the issue.

libvm: Fix typo in "using ssh-config" case

---

src/libpriv/rpmostree-core.c
tests/vmcheck/test-basic.sh

This PR uses https://github.com/ostreedev/ostree/pull/1156
to ensure that when installing packages containing files with
exact same content, the files will be merged.
When installing packages containing conflicting files,
the error will still be detected at the ostree side.
The checkout overwrite option at rpm-ostree side is also
modified to accomodate the changes made in ostree side.
A test is added for regression.

tests/core: allow merging identical files during installation

---

rust/src/treefile.rs

It's tempting to enable this by default in YAML...one step at a
time though.

rust/treefile: Fix mutate-os-release typo

---

src/libpriv/rpmostree-unpacker-core.c

Fedora rawhide has switched its RPM payload compression to zstd:
https://fedoraproject.org/wiki/Changes/Switch_RPMs_to_zstd_compression
See also https://bugzilla.redhat.com/show_bug.cgi?id=1728346.

unpacker: Add support for zstd

---

.papr.yml
docs/manual/treefile.md
rust/src/treefile.rs

A long time ago we added architecture-specific package lists
via e.g. `packages-ppc64le`.  Much more recently we added
support for having the `include` key be a list - multiple includes.
By combining these two and supporting architecture-conditional includes,
we've effectively added architecture-conditionals to *all* keys.
Notably we want this for Fedora CoreOS today which is using
`remove-from-packages` on `grub2-tools` which isn't present on
s390x.

treefile: Support `arch-include`

---

src/app/rpmostree-builtin-deploy.c
src/app/rpmostree-builtin-rebase.c
src/daemon/rpmostreed-transaction-types.c
tests/vmcheck/test-upgrades.sh

In FCOS, we want to make sure that Zincati is always deploying a newer
tree to prevent downgrade attacks in certain threat models.
For completeness, also add the option to `rebase`.
Need to add tests for this.

app/deploy: Add --disallow-downgrade switch

---

OWNERS

This will help us integrate with OpenShift Prow:
https://github.com/coreos/fedora-coreos-tracker/issues/263

OWNERS: New file for Prow integration

---

src/app/rpmostree-builtin-reset.c

Otherwise, e.g. `rpm-ostree reset foobar` doesn't actually error out.
Some users have hit this as a typo for
`rpm-ostree override reset foobar`.

app/reset: Fix argc range check

---

tests/vmcheck/test-misc-1.sh

The `EOF` needs to be alone on a line to be valid. The way to redirect
the output is unintuitively to do it at the beginning of the line
instead.

tests/vmcheck: Fix test-misc-1.sh syntax

---

.papr.yml

This was useful in combination with Homu since it only had to watch one
context. Since we're not using Homu anymore (and Tide instead looks at
all statuses by default), let's just drop it. This brings down the
number of statuses on PRs by one more (and so one less context to
override when needed).
Relatedly, also just test on `master` now.

ci/papr: Drop `required` branch

---

configure.ac
src/libpriv/rpmostree-unpacker-core.c

It's not in RHEL8.1, and I'm trying to rebase rpm-ostree.

unpacker: Build with older libarchive without zstd

---

src/libpriv/rpmostree-core.c

Don't just filter down packages by NEVRA, but also filter out those that
don't match the checksum too. We were enforcing checksum matches already
before this, but only *after* depsolving and simply erroring out if they
didn't match.
However, because of how RPM signing is implemented in Fedora, it is
possible to have the same NEVRA in two different repos, each with two
different hashes. E.g. right now for example, `efivar-libs` wasn't
rebuilt for f31, and so f31 is just shipping the f30 RPM, but signed
with the f31 key. And of course, we also had the f30 version in the
pool.
This patch allows us to transition over to the f31 version with
everything else by not getting thrown off by the f30 version already in
the pool. (Still need to investigate how the pool will deal with this.)

core: Filter locked packages by checksums before depsolving

---

HACKING.md

Per discussion in https://github.com/coreos/rpm-ostree/pull/1929

HACKING.md: Document libdnf vendoring rationale

---

configure.ac
packaging/rpm-ostree.spec.in
src/libpriv/rpmostree-core.c

We don't *actually* use this ourself, but librepo does, and libdnf gets confused
if librepo doesn't support it.  This is the case in RHEL8 currently.
Basically what breaks is trying to use the Fedora EPEL repo (has zchunk metadata)
on RHEL CoreOS.  And we have a test in kola that does this today.

Detect whether zchunk (zck) is available at build time

---

src/app/rpmostree-compose-builtin-rojig.c
src/app/rpmostree-compose-builtin-tree.c
src/libpriv/rpmostree-core.c
src/libpriv/rpmostree-rojig-assembler.c
src/libpriv/rpmostree-rojig-build.c
src/libpriv/rpmostree-rpm-util.c

In which it is discovered that [scan-build exists](https://clang-analyzer.llvm.org/scan-build.html).
No real bugs in this batch, just quieting the scanner.

Scan build fixes

---

src/libpriv/rpmostree-kernel.c

As mentioned in the comment block:
```
If there's an HMAC file, fix the path to the kernel in it to be
relative. Right now, the kernel spec encodes `/boot/vmlinux-$kver`,
which of course not going to work for us. We should work towards making
this change directly into the kernel spec.
```
For background, see this comment and following:
https://github.com/ostreedev/ostree/pull/1962#issuecomment-547488164
---
This is dependent on some dracut fixes too, so let's not merge this yet!

libpriv/kernel: Hack around vmlinuz path in HMAC file

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/libdnf_sys.rs
rust/src/lockfile.rs
src/app/rpmostree-compose-builtin-tree.c
src/libpriv/rpmostree-core.c
src/libpriv/rpmostree-rpm-util.c
src/libpriv/rpmostree-rpm-util.h
tests/compose-tests/test-lockfile.sh

E.g. the generation timestamp, repos that were enabled, and their
generation timestamps.
This is just generally useful, though I'd like to make use specifically
of the new `metadata.generated` key in FCOS to drive versioning:
https://github.com/coreos/fedora-coreos-releng-automation/pull/50

rust/lockfile: Add more metadata to generated lockfiles 

---

src/libpriv/rpmostree-kernel.c

A lot of history with this. But essentially, dracut tries to `mknod` a
few character devices like `/dev/random` and `/dev/urandom` and fails.
We originally blocked `cap_mknod` because, well, `%post` scripts don't
really need to do that, and it would get wiped anyway. But there is a
use case for dracut's CPIO: we want `/dev/*random` to be available in
early boot *before* systemd even mounts `devtmpfs` because libgcrypt as
part of its constructor-time selftests in FIPS mode wants to read from
there.
For more fun, see:
https://bugzilla.redhat.com/show_bug.cgi?id=1778940
https://bugzilla.redhat.com/show_bug.cgi?id=1401444
https://bugzilla.redhat.com/show_bug.cgi?id=1380866

libpriv/kernel: add cap_mknod to dracut run

---

src/app/rpmostree-builtin-kargs.c
src/daemon/rpmostreed-transaction-types.c
tests/vmcheck/test-kernel-args.sh

Code I wrote for the machine-config-operator expected it to
work, and I don't see a reason not to support it.
See https://github.com/openshift/machine-config-operator/issues/1265

kargs: Support --append and --delete simultaneously

---

configure.ac
src/daemon/rpm-ostreed.service.in
src/daemon/rpmostreed-sysroot.c
src/daemon/rpmostreed-transaction.c
tests/vmcheck/test-kernel-args.sh

This is all we need to tell libostree that we support a read-only
`/sysroot` and `/boot`.
See https://github.com/ostreedev/ostree/issues/1265
PR in https://github.com/ostreedev/ostree/pull/1767

daemon: Use MountFlags=slave and opt-in to OSTree read-only /sysroot

---

docs/manual/treefile.md
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-rojig.c
src/app/rpmostree-compose-builtin-tree.c
src/libpriv/rpmostree-util.c
src/libpriv/rpmostree-util.h
tests/check/jsonutil.c

This allows replacing the `.` in automatic version increments
with whatever one wants (as long as it's a single ASCII character)
right now.
The specific motivation here is for at least RHEL CoreOS to use
`version-suffix: "-"` so that its versions can become valid
semantic versions.
Related: https://github.com/coreos/rpm-ostree/issues/1954

compose: Add an `automatic-version-suffix` key

---

tests/common/libtest-core.sh
tests/common/libvm.sh
tests/vmcheck/overlay.sh

- Have libvm.sh inherit libtest, otherwise we don't have `fatal`
- Add `error: ` prefix to `fatal` messages for clarity
- Add missing plural

tests: Misc tweaks

---

src/libpriv/rpmostree-core.c
tests/compose/test-basic.sh

This is a follow-up hack to #1797 to force libdnf to let us use modular
packages as if they were regular packages until we actually support
modules correctly (#1435).
A repo marked as a modular hotfix means that libdnf doesn't try to
filter out modular RPMs from the repo as it usually does.
Resolves: https://pagure.io/releng/failed-composes/issue/717

core: Mark all repos as "modular hotfixes"

---

src/libpriv/rpmostree-util.c
tests/vmcheck/test-db.sh

We were basing whether to print the `Upgraded`/`Downgraded` heading on
the iteration count rather than the actual first iteration where a valid
upgrade/downgrade was found. And because of how we print our diff, this
confusingly can make it look like downgrades are part of the same
upgrade section.
Closes: #1821

libpriv/util: Fix human diff printing for upgrades/downgrades

---

rust/src/treefile.rs

This was missed in the conversion; just noticed while
working on the code around here.

treefile: Use ref_from_raw_ptr

---

src/libpriv/rpmostree-importer.c
tests/compose/test-basic-unified.sh

Translate RPM paths under `/var/run` to `/run` automatically; this
quiets down systemd.  Since we end up running `systemd-tmpfiles`
a few times in FCOS reducing spew here is particularly valuable.
The bug is really in the packages here but...we don't have an
agile process for fixing them.
Note that for this fix to take effect, if you have a `cache/pkgcache-repo`
you'll need to remove it.

importer: Use /run instead of /var/run

---

docs/manual/treefile.md
rust/src/treefile.rs
src/app/rpmostree-composeutil.c
src/libpriv/rpmostree-core.c
tests/common/libtest-core.sh
tests/compose/test-excludes.sh
tests/compose/test-misc-tweaks.sh

In FCOS we have a kola test that basically does `rpm -q python`.
It's...a bit silly to spawn a whole VM for this.  Ensuring that
some specific packages don't get included has come up in a few
cases.
I think FCOS/RHCOS at least will want to blacklist `dnf` for example.
And as noted above, FCOS could blacklist `python`.
One major benefit of doing this inside rpm-ostree is that one
gets the full "libsolv error message experience" when dependency
resolution fails, e.g. blacklisting `glibc` I get:
```
Problem 79: conflicting requests
- package coreos-installer-systemd-0.1.2-1.fc31.x86_64 requires coreos-installer = 0.1.2-1.fc31, but none of the providers can be installed
- package coreos-installer-0.1.2-1.fc31.x86_64 requires rtld(GNU_HASH), but none of the providers can be installed
- package …
```

treefile: Add exclude-packages

---

src/libpriv/rpmostree-core.c
src/libpriv/rpmostree-core.h
src/libpriv/rpmostree-kernel.c
src/libpriv/rpmostree-passwd-util.h
tests/vmcheck/test-initramfs.sh

This fixes a longstanding spew of error messages from the initramfs
because we don't have nss-altfiles set up there.  Rather than
trying to do it, just do the dance of re-synthesizing `/etc/passwd`
as it traditionally looks around running dracut, the same as we
do for scripts during core layering.
Yes, this is all a mess and hopefully I'll get to sysusers soon...

core,kernel: Set up /etc/passwd for dracut

---

tests/common/libvm.sh

Currently we pull from quay.io and api.ci, and the Fedora registry
is being very flaky.  I set up a mirror on api.ci for now.

ci: Pull Fedora from api.ci

---

src/app/rpmostree-compose-builtin-tree.c
src/daemon/rpmostree-sysroot-upgrader.c
src/libpriv/rpmostree-kernel.c
tests/vmcheck/test-override-kernel.sh

Keep the base initramfs arguments used in the commit metadata. The
reasoning for this is that when regenerating the initramfs locally with
`rpm-ostree initramfs --enable`, we want to match how it was built in
the treecompose. This is important because the rest of the treecompose
assumes that e.g. certain dracut modules are included or omitted.
Right now, the way we achieve this is with using `dracut --rebuild`.
However, we no longer have access to the base initramfs when replacing
the kernel. Another issue with `--rebuild` is that when we *do* use it,
dracut just dumbly appends the arguments to the base args. So we then
end up with e.g. two `--kver` args, two `--add ostree`, two `--tmpdir`,
etc...
Another way to look at at this patch is that it unifies client-side and
server-side paths …

 compose: Include base dracut args in commitmeta

---

.cci.jenkinsfile
ci/installdeps.sh
configure.ac
src/daemon/rpmostreed-sysroot.c
src/daemon/rpmostreed-transaction.c

The current `rpm-ostree-2020.1-1.fc31.x86_64` in Fedora
was [built with a truly ancient libostree](https://kojipkgs.fedoraproject.org//packages/rpm-ostree/2020.1/1.fc31/data/logs/x86_64/root.log)
because Fedora's build system is weird and only adds packages
released after "gold" into the buildroot via an override
that times out.
This actively breaks things because rpm-ostree isn't
detecting the read-only sysroot.
Let's bump our hard requirement.

build-sys: Hard require libostree 2020.1

---

tests/common/libvm.sh
tests/vmcheck/runtest.sh
tests/vmcheck/test-db.sh
tests/vmcheck/test-download-only.sh
tests/vmcheck/test-layering-basic-2.sh
tests/vmcheck/test-livefs.sh
tests/vmcheck/test-misc-1.sh
tests/vmcheck/test-misc-2.sh

We need to adapt some of our tests here which assume that `/sysroot` is
writable. However, in FCOS this is no longer the case now that we enable
`sysroot.readonly`.
We only remount rw for the couple of operations that need it so that we
still retain coverage for the ro path everywhere else.

vmcheck: Work around read-only /sysroot

---

src/app/rpmostree-dbus-helpers.c

In the large majority of cases, the `"Bus owner changed"` error is due
to something going wrong with the daemon rather than D-Bus itself. Let's
give a hint to check the journal so that users can investigate and e.g.
just paste the journal output as part of the initial issue report.

app/dbus: Suggest `journalctl -xe` if bus owner changes

---

rust/src/history.rs

The ostree test suite was creating deployments manually
(skipping the rpm-ostree upgrader layer which would write history)
and then calling `rpm-ostree cleanup` which tried to open the
history dir and failed.
Just return early if there's no history directory when we're
asked to clean up.

history: Avoid erroring if no history database to clean

---

src/daemon/rpmostree-sysroot-core.c

I was getting a dreaded not-quite-specific `syscore cleanup: No such file or directory`
error when hacking on the ostree tests.  I am pretty sure it's the history
code, but let's just do the usual thing and spread the error-prefixing love
in the whole area.

syscore: Add some error prefixing

---

src/libpriv/rpmostree-core.c
src/libpriv/rpmostree-unpacker-core.c

Seeing this in the FCOS pipeline:
```
Downloading from 'fedora-coreos-pool'... done
error: cannot open Packages database in /proc/self/fd/21/usr/share/rpm
Importing packages... done
error: Can't stat fd 38
```
The first error is librpm...which, is somehow not fatal?  It
also appears to be swallowing the underlying real error.
For the second had to Google search it but the main hit for `Can't stat fd` is
in libarchive which led me to this code, which is probably right.
But let's be sure by adding some error prefixing.

core: Add error prefixing in import path

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/lockfile.rs
rust/src/treefile.rs
rust/src/utils.rs

The failure crate isn't actively developed anymore.  The
main benefit of `anyhow` is it uses the standard error type.
More info:
https://docs.rs/crate/anyhow/1.0.28
Start the porting process.
Note that the `envsubst` crate has a public dependency on
`failure`, so we need to start mapping its errors.

rust: Start porting from failure to anyhow

---

rust/Cargo.toml
rust/src/composepost.rs
rust/src/coreos_rootfs.rs
rust/src/history.rs
rust/src/journal.rs

I previously ran out of steam in the switch and wanted to
get the PR out for feedback before continuing, but it turns
out I basically stopped 2 meters from the finish line.  Completing
the switch from `failure` → `anyhow` was quite easy.

rust: Fully remove failure crate

---

rust/src/libdnf_sys.rs

When we ran rustfmt, it converted our bare `extern` blocks to
`extern "C"` which has a different meaning apparently.
This caused cbindgen to try to interpret the structs, and it barfed
on the newtype void wrappers.
Looking at libgit2-rs, it seems to use these "uninstantiable types"
instead.
Prep for using `rustfmt`.

rust/libdnf_sys: Use uninstantiable type rather than wrapper struct

---

.cci.jenkinsfile
ci/build-check.sh
ci/codestyle.sh
rust/src/composepost.rs
rust/src/coreos_rootfs.rs
rust/src/history.rs
rust/src/lockfile.rs
rust/src/treefile.rs
rust/src/utils.rs

We haven't been consistent about doing this; I personally
think rustfmt is a big aggressive with the line wrapping
but eh, consistency is more important.
And heh so I tried to `git push --set-upstream cgwalters` and
that failed because there was an already extant `rustfmt`
branch from a while ago...looking at that code it got lost
in the CI refactoring - we're not running `build-check.sh`
at the moment.
Move the rustfmt bits into `codestyle.sh` which is closer
to where it should be anyways.

rust: rustfmt(*) and (re)add a CI check for it

---

src/libpriv/rpmostree-core.c

Someone in Freenode #silverblue hit
https://discussion.fedoraproject.org/t/rpm-ostree-giving-error/772
again, the problem would have been slightly more obvious
with this I hope.
(`Read only repository` could also be an OSTree one e.g.)

core: Add error prefixing when we fail to fetch an rpm-md repo

---

src/app/rpmostree-compose-builtin-tree.c
src/libpriv/rpmostree-core.c
tests/compose.sh
tests/compose/libcomposetest.sh

See individual commit messages

Prep patches for --ex-lockfile-strict

---

Makefile-rpm-ostree.am
docs/manual/treefile.md
rust/src/cliwrap.rs
rust/src/cliwrap/cliutil.rs
rust/src/cliwrap/dracut.rs
rust/src/cliwrap/grubby.rs
rust/src/cliwrap/rpm.rs
rust/src/lib.rs
rust/src/treefile.rs
src/app/main.c
src/app/rpmostree-builtin-cliwrap.c
src/app/rpmostree-builtins.h
src/libpriv/rpmostree-core.c
src/libpriv/rpmostree-kernel.c
tests/vmcheck/test-misc-1.sh

We need to be friendlier to people who are transitioning from
"traditional" yum managed systems.  This patchset starts to lay
out the groundwork for supporting "intercepting" binaries that
are in the tree.
To start with for example, we wrap `/usr/bin/rpm` and cause it
to drop privileges.  This way it can't corrupt anything; we're
not just relying on the read-only bind mount.  For example nothing
will accidentally get written to `/var/lib/rpm`.
Now a tricky thing with this one is we *do* want it to write if
we're in an unlocked state.
There are tons of other examples of binaries we want to intercept,
among them:
- `grubby` -> `rpm-ostree kargs`
- `dracut` -> `rpm-ostree initramfs`
- `yum` -> well...we'll talk about that later

Add support for wrapping binaries (rpm)

---

src/app/rpmostree-compose-builtin-tree.c
src/libpriv/rpmostree-core-private.h
src/libpriv/rpmostree-core.c
src/libpriv/rpmostree-core.h
tests/compose/libcomposetest.sh
tests/compose/test-lockfile.sh

Today, lockfiles only restrict the NEVRA of specifc package names from
which libsolv can pick. But nothing stops libsolv from picking entirely
different packages which still satisfy the manifest requests.
This was mostly a theoretical issue in Fedora CoreOS, but became reality
with the addition of Fedora 32 packages in the pool. libsolv would
happily try to pick e.g. `libcurl-minimal` from f32 instead of sticking
with the f31 `libcurl` from the lockfiles:
https://github.com/coreos/fedora-coreos-streams/issues/75#issuecomment-610734584
(But more generally, see
https://github.com/coreos/fedora-coreos-tracker/issues/454).
Let's add a `--ex-lockfile-strict` mode, which in CI and production
pipeline build contexts will require that (1) *only* locked packages are
considered by libsolv, and (2) …

compose: Add --ex-lockfile-strict

---

docs/manual/treefile.md
rust/src/treefile.rs
src/app/rpmostree-composeutil.c
src/libpriv/rpmostree-core.c
tests/compose.sh
tests/compose/test-lockfile.sh

In Fedora CoreOS, we have a "coreos-pool" repo from which all packages
in lockfiles are tagged for reproducible builds. This repo is shared
across all streams, including those on f31 and f32.
Thus, it makes no sense for composes to ever pick packages unconstrained
from the pool without being guided by a lockfile. Otherwise, one can
easily end up with e.g. f32 packages in an f31 compose.
Add a new `lockfile-repos` for this which is only used for fetching
lockfile packages and nothing else. This for example will also allow
e.g. `cosa fetch --update-lockfile` to Just Work as expected by only
fetching new packages from regular yum repos.

manifest: Add `lockfile-repos` field

---

src/app/rpmostree-compose-builtin-tree.c

Minor follow-up to #1858. Make the help string here more helpful and
accurate.

app/compose: Fix help string for --ex-lockfile-strict

---

src/app/rpmostree-builtin-status.c
tests/common/libvm.sh
tests/vmcheck/test-autoupdate-check.sh
tests/vmcheck/test-autoupdate-stage.sh

Pre-FCOS we made an effort for automatic updates but nowadays
with Fedora CoreOS we generally expect people to be using zincati.
Until we fix the "agent registration" problem:
https://github.com/coreos/rpm-ostree/issues/1747
Let's not confuse people by printing `AutomaticUpdates: disabled`.
Only print if it's set to a value in non-verbose mode.

status: Don't output AutomaticUpdates: disabled by default

---

src/app/rpmostree-composeutil.c

For Fedora CoreOS production streams, we want to *only* source from
lockfile repos. But right now, rpm-ostree doesn't allow not specifying
`repos`. Relax this restriction and just check that at least one of the
two was provided.

compose: Allow specifying lockfile-repos only

---

.cci.jenkinsfile

Right now, rebuilding ostree into the continuous tag is manual, so we've
only been doing it when necessary to fast-track something e.g. for
rpm-ostree or cosa (see [1] for the long-term goal).
Which means when finding an ostree to use to override in our CI-built
FCOS, we should just let dnf find whatever the latest version is, even
if it's just from the regular Fedora repos.
[1] https://github.com/packit-service/packit/issues/264

ci: Download the latest ostree even if from stable repos

---

ci/ci-commitmessage-submodules.sh

Jenkins does its own `git merge` when testing PRs. Doing a naive
`git diff ${merge_commit}^..${merge_commit}` won't work right because
it might perform a diff across multiple commits.
What we want to do here is to just skip trivial merge commits or
otherwise error out on them if they're non-trivial (since it likely
means that one did conflict resolution manually instead of rebasing,
which we should encourage).
The `origin/master..$HEAD` range will correctly still contain all the
parents of any merge commit which is not yet in `origin/master`.

ci-commitmessage-submodules: Ignore empty merge commits

---

Makefile-lib.am
Makefile.am

When g-ir-scanner runs, it uses a stub binary to help introspect the
target rpm-ostree library. That binary needs to link to the library, and
of course, transitively, to our bundled libdnf. Since we run the scanner
uninstalled, we use `LD_LIBRARY_PATH` to point the stub at the libdnf
from the build directory.
When we compile rpm-ostree, we use `-rpath` to point it at our libdnf,
which emits a `DT_RPATH` attribute. However, during dynamic linking at
runtime, it turns out that `LD_LIBRARY_PATH` has *lower* precedence than
`DT_RPATH`. This means that if there is already a libdnf at
`/usr/lib64/rpm-ostree`, it takes precedence.
This subtlety is mostly fine to ignore usually, because the stub doesn't
actually run any rpm-ostree business logic, so it doesn't really matter
that it runs against …

Makefile.am: Link with --enable-new-dtags

---

docs/manual/treefile.md
rust/src/treefile.rs
src/libpriv/rpmostree-core.c
src/libpriv/rpmostree-importer.c
src/libpriv/rpmostree-importer.h
tests/compose/test-misc-tweaks.sh

Same motivation as
https://github.com/ostreedev/ostree/pull/2091/commits/7392259332e00c33ed45b904deabde08f4da3e3c
I think we should encourage removing the writable bits from
executables.  This has happened to me:
https://thomask.sdf.org/blog/2019/11/09/take-care-editing-bash-scripts.html
And not having the writable bit may help prevent hardlink
corruption with OSTree in some cases.
We can't do this by default, but add a convenient treefile option
for it.
This starts out by just doing this for RPMs, but I'll add
a secondary pass which does it during postprocessing soon too.

treefile: Add readonly-executables

---

src/libpriv/rpmostree-core.c

This commit picks up the patch done by @cgwalters  for detection of custom kernels via provides. More work may need to be done in this area to ensure kernels are detected properly; however, I was able to test installing a custom kernel with it on Fedora Silverblue 32 using this command: 
`rpm-ostree override remove kernel kernel-core kernel-modules kernel-modules-extra --replace ./kernel*.rpm`
P.S.: Go easy on me, I'm new to this project :laughing: 
Fixes #1947

Recognize other kernel packages with provides

---

Makefile-daemon.am
Makefile-rpm-ostree.am
Makefile.am
configure.ac

We didn't ship this for a long time and...well, naming is hard, I guess
it's not going to happen soon.

build-sys: Remove --enable-new-name

---

configure.ac

Mostly motivated by keeping the release train going:
https://bugzilla.redhat.com/show_bug.cgi?id=1827712#c18

Release 2020.2

---

configure.ac

Going to update rpm-ostree for RHEL 8.3, we did a huge bump
in libdnf which now defaults to enabling zchunk in its build
system.  We added the infrastructure before to detect things,
so propagate that to libdnf.

build-sys: Disable zchunk for libdnf if we don't have it

---

src/daemon/rpmostree-sysroot-upgrader.c

This is a short-term hack until we can depend on the new
`timestamp-check-from-rev` from ostree:
ostreedev/ostree#2099
That way, we still get downgrade protection, but wrt the checked out
deployment, not the local ref.
For more information, see
#2094
coreos/fedora-coreos-tracker#481

upgrader: Reset ref before fetching commit by override

---

docs/manual/background.md

The lists of pros and cons for each approach in the background section
of the manual use markdown formatting that is rendered as nested
lists. Separate the lists of benefits and drawbacks so that readers of
https://rpm-ostree.readthedocs.io/en/latest/manual/background/ and the
rendered markdown on github can understand which items are pros and
which are cons.

docs/background: Fix benefits and drawbacks formatting

---

src/app/rpmostree-compose-builtin-tree.c

This was apparently removed in: 2263bb35f6f785b00ad3db4772498fa1877b29fe
It's done nothing for the last 5 years, I think it's safe to remove.
I was just looking at this code when thinking about extensions.

compose: Remove --output-repodata-dir

---

docs/manual/compose-server.md
src/app/rpmostree-compose-builtin-tree.c

Tracker: https://github.com/coreos/rpm-ostree/issues/729
---
Start adding some pain if `--unified-core` isn't provided
to help flush out anyone relying on it.  (And I think today
pungi is not passing it, so e.g. Fedora IoT/Silverblue are impacted)
Prep for merging https://github.com/coreos/rpm-ostree/pull/1793

compose: Add a "warn and sleep" if --unified-core is not provided

---

packaging/rpm-ostree.spec.in

The `rust-toolset` package does not exist in Fedora, so we cannot
use it for BuildRequires. Change the conditional to exclude ELN
from the %rhel conditional.
Signed-off-by: Stephen Gallagher <sgallagh@redhat.com>

spec: Fix up conditionals for ELN

---

src/daemon/rpmostreed-transaction-types.c

One OpenShift user saw this from rpm-ostree:
```
client(id:cli dbus:1.583 unit:machine-config-daemon-host.service uid:0) added; new total=1
Initiated txn UpdateDeployment for client(id:cli dbus:1.583 unit:machine-config-daemon-host.service uid:0): /org/projectatomic/rpmostree1/rhcos
Txn UpdateDeployment on /org/projectatomic/rpmostree1/rhcos failed: File header size 4294967295 exceeds size 0
```
which isn't very helpful. Let's add some error
prefixing here just to clarify this is pulling from
the repo.
xref https://github.com/ostreedev/ostree/pull/2118

daemon: Add an error prefix in local repo pulls

---

src/app/rpmostree-builtin-rebase.c
tests/vmcheck/test-misc-2.sh

We've been shipping the MCO code using this for a long time,
it needs to stay in its current form and is not experimental.

rebase: Remove requirement for --experimental with local rebases

---

.cci.jenkinsfile
src/libpriv/rpmostree-scripts.c
tests/kolainst/nondestructive/misc.sh

The latest crypto-policies package changed recently to dynamically set
the policy at install time so that if FIPS is enabled, the selected
backend is `FIPS`:
https://src.fedoraproject.org/rpms/crypto-policies/c/9b9c9f7378c3fd375b9a08d5283c530a51a5de34?branch=master
This doesn't really make sense for us though since the compose server
configuration should be decoupled from the installroot. (More generally,
this also affects e.g. `yum install --installroot`).
Override the script for now so that we always select the `DEFAULT`
policy. We'll discuss with upstream to see what the right solution is
there.
This also works around the fact that rpm-ostree doesn't yet implement
Lua (#749).
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1847454
Resolves: …

libpriv/scripts: Replace crypto-policies lua script

---

rust/src/ffiutil.rs

We need to use this alternative formatter to get full errors
including the full context chain.  IMO the anyhow default is broken.

ffiutil: Format full errors from anyhow

---

configure.ac
packaging/rpm-ostree.spec.in

Seems about time, but also to get the crypto-policies workaround out:
https://github.com/coreos/fedora-coreos-tracker/issues/540

Release 2020.3

---

RELEASE.md
configure.ac

The instructions for doing a release were outdated. Take the opportunity
to just move it to a dedicated markdown file and breaking it out to make
it easier to follow.
This is one step short of using a release checklist like some of the
other CoreOS projects do. This is a good base to eventually do that if
we want.

Move release instructions to RELEASE.md

---

ci/installdeps.sh

This is needed by the compose tests. This is part of cosa already, which
is why CI isn't hitting this, but we want to support users not
developing on top of the cosa buildroot container that can just run
`ci/installdeps.sh`.

ci/installdeps: add distribution-gpg-keys

---

src/libpriv/rpmostree-core.h
src/libpriv/rpmostree-postprocess.c
tests/compose/libbasic-test.sh

Following on to:
- http://lists.rpm.org/pipermail/rpm-maint/2017-October/006681.html
- https://github.com/coreos/rpm-ostree/pull/1142/
- https://github.com/openSUSE/libsolv/pull/386
Write a symlink in `/usr/lib/sysimage/rpm` pointing to our current
`/usr/share/rpm` - this way clients can start looking for it there,
and then at some point we'll flip the symlink around and
have `/usr/share/rpm` pointing to the new location.
(Doing a hard swap now has upgrade implications)

postprocess: Add a symlink /usr/lib/sysimage/rpm to the rpmdb

---

src/app/rpmostree-builtin-initramfs.c
src/app/rpmostree-builtin-kargs.c
src/app/rpmostree-builtin-rebase.c
src/app/rpmostree-builtin-reset.c
src/app/rpmostree-override-builtins.c
src/app/rpmostree-pkg-builtins.c
src/daemon/rpmostreed-transaction-types.c
tests/vmcheck/test-misc-2.sh

Both `upgrade` and `deploy` already support this. There's no reason why
all the remaining "deployment-creating" commands shouldn't. Prompted by
https://github.com/openshift/machine-config-operator/issues/1897 which
will need this specifically for `rebase`.

app: Add --lock-finalization switch to other commands

---

rust/src/treefile.rs
tests/compose/test-misc-tweaks.sh

Add a helper function for whitespace_split_packages() so that it now splits a String by whitespace only if it is not wrapped between single quotes.
This should allow RHCOS to use syntax like podman > 1.4 in the treefile.

Support greater than/less than versions for packages in treefile.

---

packaging/rpm-ostree.spec.in

This pull request was create automatically for the f33 change:
https://fedoraproject.org/wiki/Changes/UseMakeBuildInstallMacro
(Upstreamed from
https://src.fedoraproject.org/rpms/rpm-ostree/pull-request/39).

spec: Use make macros

---

src/daemon/rpmostreed-transaction-types.c

Otherwise it might still own tasks on the main context when reusing it
later on. And because it was already cleared, we can get `SIGSEGV`. See
also c9cbad94 (#1676).
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1859269

daemon/deploy: Finish OstreeAsyncProgress after pull

---

configure.ac
packaging/rpm-ostree.spec.in

Thin release. Mostly for a bunch of RHCOS-relevant fixes and
enhancements: 752f4f09 (#2178), 4d836dd8 (#2151) and f608eb09 (#2158).

Release 2020.4

---

src/app/rpmostree-builtin-ex.c
src/daemon/rpmostree-sysroot-upgrader.c
src/libpriv/rpmostree-kernel.c
src/libpriv/rpmostree-origin.c

Prep patches for `ex initramfs-etc`

---

rust/src/treefile.rs
src/libpriv/rpmostree-core.c
src/libpriv/rpmostree-postprocess.c
tests/compose/test-misc-tweaks.sh

Fix #2068: `remove-from-packages` deleting files that it shouldn't.
Filter out files that user wants removed at `checkout_package_into_root()`, instead of using the `handle_remove_files_from_package()` function that does not check whether files are used by other rpms before removing them.

Fix `remove-from-packages` deleting files it shouldn't

---

src/libpriv/rpmostree-core.c

This is the case in RHCOS, and it's confusing to see:
`Enabled rpm-md repositories:`
since one might think the text on the following lines are
the repositories.

core: Clearly show when no rpm-md repos are enabled

---

src/app/rpmostree-db-builtin-list.c
src/app/rpmostree-db-builtin-version.c
src/libpriv/rpmostree-util.c
src/libpriv/rpmostree-util.h

This will be fully obsoleted with https://github.com/coreos/rpm-ostree/pull/2206

util: Remove an (effectively) unused GCancellable

---

rust/src/ffiutil.rs

rust: Fix deprecation warnings

---

src/daemon/rpmostreed-transaction-types.c

Came up in https://github.com/coreos/rpm-ostree/issues/2210

deploy: Don't leak file descriptor passed for local rebases

---

src/libpriv/rpmostree-core.c
tests/vmcheck/test-layering-basic-1.sh

For the Fedora CoreOS extensions work, when layering packages, we need
to be able to tell libsolv to pick the packages which will go with the
base packages. IOW, it needs to know that the base packages shouldn't be
uninstalled.
While investigating
coreos/fedora-coreos-tracker#525, I realized
that libsolv does have a flag which allows us to express this:
`SOLVER_LOCK`.
This then allows libsolv to choose the right package for us (if found).
And in the case where it can't find a matching package, libsolv itself
will print exactly what the conflict is, which is more informative than
the "forbidden replacements" error we currently print out.
Update submodule: libdnf

core: Use SOLVER_LOCK for locking base packages

---

.cci.jenkinsfile

In the scenario where ostree is in the fcos overrides but *not*
bodhi, *and* a new test requires it, our CI will fail.
We aren't hard requiring the latest ostree right now.

ci: Use ostree from lockfile

---

src/app/rpmostree-compose-builtin-tree.c

Otherwise we could fail to check out the policy on a host
where the SELinux module is loaded but inactive, which would
deny calling `setxattr(security.selinux)`.
And in general we don't want to do chown/xattr at all here.
Closes: https://github.com/coreos/rpm-ostree/issues/2220

compose: Use user mode checkout for sepolicy

---

docs/manual/treefile.md
rust/src/treefile.rs
src/libpriv/rpmostree-core.c
tests/compose/libbasic-test.sh

The design of https://fedoraproject.org/wiki/Changes/Sqlite_Rpmdb
is problematic for us for multiple reasons.  The first big reason
is that rpm-ostree is designed for "cross" builds and e.g. today
we use a Fedora-derived container to build RHEL CoreOS images.
However the default database lives inside the `rpm` package which
means that if we e.g. upgrade the coreos-assembler container to F33
it will suddenly try to use sqlite for RHCOS which is obviously broken.
Related to this, rebases from f32 to f33 w/layered packages
are broken: https://bugzilla.redhat.com/show_bug.cgi?id=1876194#c3
With this we can configure things to continue to use bdb for f33
for ostree-based systems, so that by enforcing an upgrade order
f32 -> f33 [bdb] -> f34 [sqlite] ... the intermediate f33 w/bdb
still …

compose: Add rpmdb option, default to bdb

---

.cci.jenkinsfile
ci/msrv.sh

We lost this during the transition from PAPR to CoreOS CI. We don't have
a lot of new tests there since new unit tests tend to be in Rust, though
we should still run what we do have.
Repurpose the `rust` branch to more generically run all unit tests
and not just the Rust ones. It still also checks that compilation
against the MSRV works fine.

ci: Run C unit tests too

---

src/daemon/rpmostreed-sysroot.c

This *shouldn't* be happening but maybe it is somehow in
https://bugzilla.redhat.com/show_bug.cgi?id=1865839

sysroot: Log when forcibly closing a transaction

---

Makefile-libpriv.am
Makefile-rpm-ostree.am
configure.ac
src/app/rpmostree-builtin-compose.c
src/app/rpmostree-builtin-ex.c
src/app/rpmostree-ex-builtins.h
src/daemon/rpmostree-sysroot-upgrader.c
src/libpriv/rpmostree-importer.c
tests/compose/test-rojig-e2e.sh
tests/compose/test-rojig-pure.sh
tests/vmcheck/test-rojig-client.sh

We're seeing some CI failures that I think are a bug in rojig.
In the bigger picture...we never actually started using this,
and I think longer term shipping os updates via containers
probably makes more sense.
I put a *lot* of effort into this code and it's pretty cool
so it's hard to just delete it.  And *maybe* someone out there
is using it (but I doubt it).  So rather than just deleting
it entirely let's make it a build-time option.
I verified that it builds at least.

Add --enable-rojig, disable by default

---

scripts/bwrap-script-shell.sh
src/libpriv/rpmostree-bwrap.c
tests/compose/test-misc-tweaks.sh

It's part of the expected standard environment, and its omission
ended up breaking some bootupd work.
See https://github.com/coreos/bootupd/pull/84#issuecomment-709414840

Make /run a directory in scripts

---

rust/src/treefile.rs
src/app/rpmostree-compose-builtin-tree.c

It's tempting to flip the default, but let's encourage
people to adapt to the `modules` version now.
Plus infrastructure to add deprecation warnings here
will come in handy in the future.

compose: Print a warning with boot-location: new

---

src/daemon/rpmostree-sysroot-core.c
src/daemon/rpmostree-sysroot-core.h
src/daemon/rpmostree-sysroot-upgrader.c
src/daemon/rpmostreed-deployment-utils.c
src/daemon/rpmostreed-transaction-livefs.c
src/daemon/rpmostreed-transaction-types.c

This is a minor cleanup, dropping an unused sysroot parameter from
deployment logic in daemon codebase.

daemon: drop an unused sysroot parameter

---

rust/cbindgen.toml
rust/src/includes.rs
rust/src/lib.rs
rust/src/lockfile.rs
rust/src/syscore.rs
src/daemon/rpmostree-sysroot-core.c
src/libpriv/rpmostree-origin.h
src/libpriv/rpmostree-rpm-util.h
src/libpriv/rpmostree-rust-prelude.h

This starts bridging parts of the daemon syscore logic to Rust
plumbing, moving the livefs detection logic over there as a first
consumer. That was the simplest logic available for wiring, and
mostly meant as a sanity check.

daemon/syscore: push livefs introspection to Rust

---

configure.ac
rust/Cargo.toml

This avoids us leaking all of the Rust symbols as public
into our shared library.
Came up in team chat since one person tried to copy just `/usr/bin/rpm-ostree`
from the dev container into a target and got a linker crash; but
really we want to avoid all the duplicated symbols entirely.
(And we should investigate cross-language LTO because that's the
only way to get full savings)

rust: Enable lto by default

---

rust/src/ffiutil.rs
rust/src/lockfile.rs
rust/src/progress.rs
rust/src/treefile.rs
rust/src/utils.rs

Let's just use the GLib translation bits rather than rolling our own;
this applies primarily to `ffi_new_string()`.
However, I think in most cases performance here doesn't
matter enough to have an even more special case that avoids duplicating
the string.  Let's remove the `ffi_view_str()` optimization too
in favor of consistently using GLib translation.
In the future perhaps we should argue for adding a `from_glib_str_unchecked()`
to the upstream GLib bindings.

Remove ffi_view_str/ffi_new_string functions

---

Makefile-rpm-ostree.am
configure.ac
man/rpm-ostree.xml
packaging/rpm-ostree.spec.in
src/app/rpmostree-builtin-ex.c
src/app/rpmostree-builtin-initramfs-etc.c
src/app/rpmostree-builtin-reset.c
src/app/rpmostree-builtin-status.c
src/app/rpmostree-ex-builtins.h
src/daemon/org.projectatomic.rpmostree1.xml
src/daemon/rpmostree-sysroot-upgrader.c
src/daemon/rpmostreed-deployment-utils.c
src/daemon/rpmostreed-os.c
src/daemon/rpmostreed-transaction-types.c
src/daemon/rpmostreed-transaction-types.h
src/libpriv/rpmostree-origin.c
src/libpriv/rpmostree-origin.h
tests/kolainst/Makefile
tests/kolainst/destructive/initramfs-etc

This command allows users to cheaply inject configuration files in the
initramfs stage without having to regenerate the whole initramfs (or
even a new OSTree commit). This will be useful for configuring services
involved in bringing up the root block device.
```
$ echo 'hello world' > /etc/foobar
$ rpm-ostree ex initramfs-etc --track /etc/foobar
Staging deployment... done
Run "systemctl reboot" to start a reboot
$ rpm-ostree status
State: idle
Deployments:
ostree://fedora:fedora/x86_64/coreos/testing-devel
Version: 32.20200716.dev.1 (2020-07-16T02:47:29Z)
Commit: 9a817d75bef81b955179be6e602d1e6ae350645b6323231a62ba2ee6e5b9644b
GPGSignature: (unsigned)
InitramfsEtc: /etc/foobar
Unlocked: development
● ostree://fedora:fedora/x86_64/coreos/testing-devel
Version: 32.20200716.dev.1 …
```

Add new `ex initramfs-etc` command

---

rust/src/composepost.rs

Clippy reports this as an error; I think in practice Linux
doesn't return short writes for regular files, but it's still
a good idea to do the right thing here.

composepost: Fix to use write_all()

---

rust/src/treefile.rs

I happened to scroll past this code while doing something
else and noticed what we were doing here was silly - no need
to re-validate UTF-8 etc when serde can hand us a `String` directly.

treefile: Directly write to String

---

rust/src/lockfile.rs
rust/src/utils.rs

Particularly in places like the lockfile code where we were iterating
on a list of packages, validating UTF-8 and `memcpy()`ing strings
from C is...well, unnecessary.
I don't think there's any actual real performance concerns right
now but let's use this as a best practice because the patterns
we establish *will* be copy+pasted or at least used as inspiration
for other places where performance might matter.

rust: Use Borrow<GString> in a few places

---

configure.ac
packaging/rpm-ostree.spec.in

To get https://github.com/coreos/rpm-ostree/pull/2301 out.

Release 2020.7

---

rust/src/lockfile.rs

rust/lockfile: Use from_glib_full to avoid manual free

---

src/daemon/rpmostree-sysroot-upgrader.c
src/daemon/rpmostreed-errors.c
src/libpriv/rpmostree-postprocess.c
src/libpriv/rpmostree-refsack.h
src/libpriv/rpmostree-refts.h

As detailed in
https://gitlab.gnome.org/GNOME/glib/-/issues/600#note_877282, `volatile`
isn't actually needed in these contexts because the atomic operations
already give us strong enough guarantees. In GCC 11, this triggers a
diagnostic due to the `volatile` qualifier getting dropped anyway.
There is a WIP to do the same in glib:
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1719
This obsoletes this downstream patch:
https://src.fedoraproject.org/rpms/rpm-ostree/c/bbd2d17f

Drop use of `volatile`

---

rust/src/treefile.rs
src/app/rpmostree-composeutil.c

See https://github.com/coreos/rpm-ostree/pull/2206#issuecomment-721372634
The commit 7f579a55d3fb7ec1cb9f74f8ec6bc36675df2ccc broke hashing
of overlay commits; this is a super evil bug because it causes us
to silently do the wrong thing.
The cause here is the GLib bindings don't (AFAICS) support getting
a `&mut` for a GLib boxed value.
Move all of the treefile checksum code into one place - this is
far saner.  The reason I didn't do this before is that it
will cause a spurious rebuild when one updates rpm-ostree, but...eh.

treefile: Fix hashing of externals

---

ci/codestyle.sh
packaging/make-git-snapshot.sh

This updates a couple of shebangs for scripts using bash `pipefail`
option.

sh: fix bash shebang

---

docs/administrator-handbook.md
docs/compose-server.md
docs/index.md
docs/treefile.md

Those got moved to GitHub from readthedocs.io, meaning links pointing to specific pages return a 404, so this fixes that along with skipping the redirect for the links that just point to the main page.

docs: Update links to the OSTree documentation

---

rust/src/history.rs
rust/src/journal.rs

The `Journal::open` API has been deprecated in favour of the new
`OpenOptions` builder pattern.
We could dedupe this a bit more, though the mock journal in the history
code makes it trickier and there's little value in mocking the builder
pattern too.

rust: Move to new systemd journal API for opening

---

src/libpriv/rpmostree-scripts.c

There's some crazy stuff going on there with udev rules
that we don't need.  See some discussion in
https://bugzilla.redhat.com/show_bug.cgi?id=1742764

scripts: Neuter RHEL8 nvme-cli %post

---

src/daemon/org.projectatomic.rpmostree1.xml
src/daemon/rpmostreed-sysroot.c

This is technically an API break, but that method has never really been
very useful and I doubt it was ever seriously used. There is no wrapper
for it in the CLI client. Let's just delete it and pretend it never
existed.
In the end, I don't think the ability of supporting multiple separate
stateroots is widely used in practice.
Closes: #551

daemon: Drop CreateOSName

---

rust/src/composepost.rs
tests/compose/test-basic.sh

I was looking at the output of `ostree admin config-diff`
on a base FCOS boot.  It'd be really nice to trim that down
as much as possible, so we can cleanly capture the difference
between user config and system config.
Let's use static enablement rather than presets.

compose: Use static enablement for ostree systemd services

---

bindgen/Cargo.lock
bindgen/Cargo.toml

We've been neglecting this for a long time and it's been omitted
from dependabot.  Everything still seems to work.
Prep for converting to a workspace so we only have a single
`Cargo.lock`.

bindgen: Bump to 0.15

---

.cci.jenkinsfile
tests/check/jsonutil.c
tests/vmcheck/test-override-kernel.sh

This fixes the invalid datetime testcase, picking a new specifier
as `%f` recently became a valid one in glib.
Ref: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1605

tests/jsonutil: update invalid specifier

---

rust/src/core.rs
rust/src/lib.rs
src/libpriv/rpmostree-core.c
src/libpriv/rpmostree-core.h
src/libpriv/rpmostree-kernel.c

This adds a guard around the postprocessing logic dealing with
creating/destroying a temporary-etc context, and moves it to Rust.

libpriv/core: add a guard for temporary-etc context and move to Rust

---

rust/src/history.rs
src/app/rpmostree-builtin-status.c

I've been meaning to hook up `ex history` to a pager a-la-journalctl,
though it's not high-priority, and it'd be nice to do it in Rust instead
(I think this command would be a good candidate for more oxidation if we
move the CLI entrypoint to Rust.)
For now at least, let's not spam the full history by default. Instead,
limit it to 3, and add `--limit` and `--all` options to tweak that if
wanted (I thought about making `--limit -1` just mean all entries,
though I think I'd still want an explicit `--all` anyway.)

app/history: Limit entries to print to 3

---

tests/vmcheck/test-layering-scripts.sh

On traditional rpm systems this can hang because the outer
process may have an rpmdb lock, and the inner one wants
to acquire a lock.  Here we're sandboxing the `%post` script
and it's targeting a separate temporary filesystem compared to
the booted one (so there's no double locking).  Plus we don't
create the rpmdb in the target until all scripts have run.
Inspired by https://twitter.com/_msw_/status/1335981558717587473

tests: Add case for running rpm -q in a %post

---

src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-bwrap.cxx
src/libpriv/rpmostree-util.h

This avoids the casts required for `g_steal_pointer()`.

Add a helper move_nullify

---

Makefile-daemon.am
src/daemon/rpmostreed-sysroot.c
src/daemon/rpmostreed-transaction.cxx

And add a try/catch-convert-to-GError here too.  This will
allow us to throw exceptions from transaction implementations.

Port rpmostreed-transaction to C++

---

src/libpriv/rpmostree-scripts.c

Yet more print format issues uncovered by users running on armv7.
Also add a space between the specifier and the "ms" because it makes one
doubtful whether printf interprets this correctly.
I think this will resolve
https://bugzilla.redhat.com/show_bug.cgi?id=1906184.

libpriv/scripts: Fix uint64 printing

---

src/daemon/rpmostree-sysroot-upgrader.c

Fixes: e9011530e52fbc4e7b002c29ff20d2c08a97435c
Fedora Silverblue doesn't specify any `initramfs-args` in the
treefile.   The above commit then caused us to omit `--no-hostonly`
which completely fails today because we sandbox dracut off
from seeing the real hardware and things like the host filesystem.
It wasn't noticed because Fedora CoreOS does always specify
arguments in the treefile.
Closes: https://github.com/coreos/rpm-ostree/issues/2343

upgrader: Inject --no-hostonly again if no initramfs-args

---

src/app/rpmostree-builtin-livefs.c

The return value is floating, we need to sink.  Fixes
a critical warning.

livefs: Fix GVariant refcounting

---

rust/src/lib.rs

We're maintaining the operating system, let's hard require
that errors are checked.

rust: Add deny(unused_must_use)

---

Makefile-libpriv.am
src/libpriv/rpmostree-kernel.cxx

Prep for reworking `core.rs` to use cxx-rs
(Notable in this is the dropping of `goto out` by writing
a small struct with a destructor to handle the cleanup `unlinkat()` for us)

Port rpmostree-kernel to C++

---

src/daemon/rpm-ostreed.service.in

See https://github.com/ostreedev/ostree/commit/82679ce834732ba4941b097cd83c43902c0d6092
I've seen at least one user report a bunch of failing
services on CoreOS that might be due to `/boot` not mounting.
Let's make it explicitly clear this is required.
The error would then be systemd saying a dependency failed, rather
than ostree confusingly saying it can't invoke `readlinkat()`.

service: Explicitly RequiresMountsFor=/boot

---

src/daemon/rpmostreed-transaction.cxx

We have logging when a "client" connects to us over the main bus,
but none when a "process" connects to the transaction-private
DBus socket.
It's going to help us debug problems to log the latter.  In
the future we can try to correlate them, but for now simple
logging in a similar way should help.

transaction: Also log to journal when processes connect to txn

---

.cci.jenkinsfile
ci/msrv.sh

We need this for https://cxx.rs
While we're here:
- Add some more comments/links
- Since the Rust bits are now at the toplevel, we can explicitly
invoke `cargo`
- And since we can do that, use the `+` syntax to specify the
toolchain explicitly

msrv: Bump to Rust 1.48

---

src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostree-sysroot-upgrader.h
src/daemon/rpmostreed-daemon.c
src/daemon/rpmostreed-daemon.h
src/daemon/rpmostreed-transaction-types.cxx
src/daemon/rpmostreed-transaction.cxx
src/daemon/rpmostreed-transaction.h
tests/vmcheck/test-misc-2.sh

Related to https://github.com/coreos/rpm-ostree/issues/1747
Basically after this we can have `rpm-ostree status` output
e.g. `Agent: zincati` at least *after* an upgrade has happened.

daemon: Record the agent ID in the journal

---

packaging/rpm-ostree.spec.in

We got annobin (hardening) warnings in a downstream RPM analysis,
I think this will help ensure that the Rust code is built with
things like `-znow` etc.

spec: Propagate Fedora default rustflags

---

Makefile-daemon.am
Makefile-lib.am
Makefile-libpriv.am
Makefile-rpm-ostree.am
Makefile-tests.am
src/app/main.cxx
src/app/rpmostree-builtin-shlib-backend.c
src/app/rpmostree-builtins.h
src/lib/rpmostree-package.c
src/lib/rpmostree-shlib-ipc-private.h
src/lib/rpmostree.c
src/libpriv/rpmostree-rpm-util.c
src/libpriv/rpmostree-rpm-util.h

This is a potential path to fix
https://github.com/coreos/rpm-ostree/issues/2391
Basically our shared library and executable duplicate too much
code (particularly Rust).  Since most of the shlib APIs aren't
performance sensitive, let's have them fork off the binary
via a hidden CLI entrypoint and parse the output.

Rework shared library and build system

---

Cargo.toml
Makefile-rpm-ostree.am
configure.ac
docs/treefile.md
packaging/rpm-ostree.spec.in
rust/src/treefile.rs

There won't be any support for writing to the bdb backend in f34, so
e.g. pkglayering won't work (and obviously even composes wouldn't work
once the buildroot moves to f34).
Instead of requiring the whole world to add an `rpmdb` key in their
manifests, let's just add a compile flag for it, and tweak the spec file
to use this flag on f34.

Default to sqlite rpmdb backend on f34

---

ci/codestyle.sh
rust/src/testutils.rs
rust/src/treefile.rs

Moving the crate to the toplevel broke the CI check for `rustfmt`.
Fix it and run `cargo fmt`.

Run rustfmt, and fix CI check for it

---

Makefile-rpm-ostree.am

Makefile-rpm-ostree: fix path to cbindgen.toml

---

packaging/rpm-ostree.spec.in

Rename URLs with `projectatomic` to `coreos`, expand the `Source0`, and
move it down to be lower than `License` and `URL`.

spec: Minor tweaks

---

Makefile-daemon.am
configure.ac
src/libpriv/rpmostree-bwrap.cxx

Work on dropping cruft from our Autotools build system
in preparation for moving to `build.rs`.

build-sys: A few cleanup patches

---

src/app/rpmostree-builtin-livefs.cxx
tests/vmcheck/test-livefs.sh

The cool thing about this is it emphasizes how "integrated" apply-live
is versus the uncontrolled `rpm-ostree usroverlay`.  We're still
tracking the state of things reliably and can print it.

apply-live: Print a package diff

---

ci/build-check.sh
ci/install-extra-builddeps.sh

AFAICT, we just need `cxxbridge` to be in the `PATH` of the building
user. Let's avoid targeting privileged paths so devs can just run this
script directly without `sudo`.

ci/install-extra-builddeps: drop --root=/usr arg

---

rust/src/lib.rs
rust/src/origin.rs
rust/src/utils.rs

Let's land the half-completed Rust code so we can iterate on
and improve it while other patches land that might conflict
with work on the C++ side.

Add a partial reimplementation of origin parsing in Rust

---

.cci.jenkinsfile

I started writing a comment about why we run autotools twice,
then decided that was *much* uglier than extracting the binding
rules to a separate `Makefile`.  But I forgot to go back
and remove the first part, so do that now and fix up the comment.

ci: Don't run autotools twice

---

Cargo.lock
Cargo.toml
rust/src/cxx_bridge_gobject.rs
rust/src/lib.rs
rust/src/livefs.rs
src/app/rpmostree-builtin-livefs.cxx
src/daemon/rpmostree-sysroot-core.cxx
src/daemon/rpmostree-sysroot-core.h
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-transaction-livefs.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-cxxrs-prelude.h

(I'm going to start calling it `live-apply` instead of "livefs")
On one hand, this drops the unsafe bindgen glue.  On the other
hand it demonstrates a notable current ergonomic shortfall of
cxx-rs in that it doesn't support `Option<T>`, so we represent
optional strings by converting them to empty strings.
(Relatedly I discovered in C++ there is `std::optional<>` but it's in C++17.
I assume we can depend on that but let's for now match libdnf's
usage of `-std=c++14` because we know that works everywhere)

 Use cxx-rs for live-apply

---

src/lib/rpmostree-db.c
src/lib/rpmostree-package-priv.h
src/lib/rpmostree-package.c

We previously severed the dependency between the shared library
and our internal code, but the library still included internal
headers even though they weren't used.
This broke my attempt to natively use C++ in some headers.
Drop the unused headers and clean up the `#include`s.

lib: Cleanup `#include <>`s

---

src/libpriv/rpmostree-util.h

Now that the whole core codebase is "compile in C++ mode",
remove the ifdef and move the C++-specific `#include <>`s
up so it's more obviously supported to add new
C++ code (if necessary).

util: Remove `#ifdef __cplusplus`

---

rust/src/client.rs
rust/src/lib.rs
rust/src/utils.rs
src/app/rpmostree-dbus-helpers.cxx

Prep for the [fedora-integration PR](https://github.com/coreos/rpm-ostree/pull/2420).
This also generalizes the "fetch URL to tempfile" code into
supporting multiple at once - it's much more efficient to do
it that way because we can reuse a TCP connection to servers,
parsed certificates etc.

Move some client argument handling to Rust

---

rust/src/lib.rs
rust/src/utils.rs
src/app/rpmostree-builtin-shlib-backend.cxx
src/app/rpmostree-composeutil.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h
src/libpriv/rpmostree-util.cxx
src/libpriv/rpmostree-util.h
tests/check/test-utils.c

This makes the C++ side a bit uglier because the "variable mapping"
is more Rust-native but we only use it Rust side anyways.
(We can't yet move the basearch bits to rust because it depends on
libdnf, which requires buildsystem unification)
But all the unsafe FFI conversion drops out, as do the duplicated
C unit tests.

Complete move to cxx-rs for utils

---

rust/src/cliwrap.rs
rust/src/lib.rs
src/app/rpmostree-builtin-cliwrap.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-kernel.cxx

The example of how the `cliwrap_entrypoint()` function
can just be directly bound with this is a great
example of the cleanup.

Port cliwrap FFI to cxx-rs

---

tests/common/libvm.sh

Apparently small rpmdb changes can cause the size to stay the
same due to preallocation, and rsync defaults to skipping files
based on (name, size, mtime).  It's really ostree's mtime canonicalization
that's unfortunate here.
Anyways, we obviously don't care about performance here so use
`-I` to disable that rsync check.
(Also remove the `mkdir -p` since it's not necessary since a long time)
Closes: https://github.com/coreos/rpm-ostree/issues/2435

tests: Fix rsync of base rpmdb with sqlite

---

rust/src/journal.rs
rust/src/lib.rs
src/app/rpmostree-builtin-status.cxx

This is cleaner if we move the "catch and print errors" into
the Rust side.  We lose the "print errors as red" part but
eh we can readd that later Rust side.

Port Rust journal bits to cxx-rs

---

Cargo.toml
build.rs
rust/src/client.rs
rust/src/fedora_integration.rs
rust/src/lib.rs
rust/src/utils.rs
src/app/libmain.cxx
tests/kolainst/destructive/layering-fedorainfra

This adds support for e.g.:
```
$ rpm-ostree override replace https://bodhi.fedoraproject.org/updates/FEDORA-2020-2908628031
```
This will find the Koji builds from the listed update, download
all the RPMs (that aren't debuginfo) and pass them for overrides
in the same way we support `override replace http://somewebserver/foo.rpm`
now.
We also support directly linking a Koji build:
```
$ rpm-ostree override replace https://koji.fedoraproject.org/koji/buildinfo?buildID=1625029
```
There are some parts of this code that are *very* hacky, most
notably how we parse the Apache directory listings from kojipkgs
rather than speak XML-RPC (or drag in the `koji` package and
its large set of Python deps).
Bodhi at least has a modern HTTP+JSON API.
Also notably this still downloads *all* the other …

 Add fedora-integration: Support `override replace https://bodhi/...`

---

rust/src/journal.rs

This strengthens our journal filtering to ensure that we won't
read entries from e.g. a malicious process logging with a
syslog identifier `ostree`.

journal: Add filters for _UID=0

---

cbindgen.toml
rust/src/ffiutil.rs
rust/src/includes.rs
rust/src/lib.rs
rust/src/passwd.rs
src/libpriv/rpmostree-passwd-util.cxx
src/libpriv/rpmostree-passwd-util.h
src/libpriv/rpmostree-postprocess.cxx
src/libpriv/rpmostree-postprocess.h

This moves to Rust the in-memory structure holding passwd entries
(users and groups).

libpriv/passwd: move passwd database to Rust

---

rust/src/dirdiff.rs
rust/src/lib.rs
rust/src/live.rs
rust/src/ostree_diff.rs
tests/vmcheck/test-apply-live.sh

Gather the current diff of `/etc`, and filter out changes in
the tree which would overwrite it.
There is an OSTree API for diffs but it's a bit awkward, missing
some APIs in the Rust bindings and also `GFile` based unfortunately.
Doing this in Rust is nicer.  The dirdiff code obviously needs
a lot more testing, but I think it's right.

apply-live: Avoid clobbering changes in /etc

---

rust/src/client.rs
rust/src/cliwrap.rs
rust/src/composepost.rs
rust/src/core.rs
rust/src/cxxrsutil.rs
rust/src/fedora_integration.rs
rust/src/initramfs.rs
rust/src/lib.rs
rust/src/live.rs
rust/src/passwd.rs
rust/src/testutils.rs
rust/src/utils.rs

This is a workaround for the non-customizability of the cxx-rs
propagation of Rust result to C++ exception.  Right now we're
losing context.  Work around this by formatting on the Rust
side at exit points, explicitly converting an `anyhow::Error`
by printing it in "single line context".
Since we're likely to gain more things like this, unify
this with `cxx_bridge_gobject::` into a single `cxxrsutil::`.

rust: Add CxxResult

---

Cargo.lock

We want the `remove_all()` fix and the new copy API.

rust: Update to openat-ext 0.1.10

---

rust/src/lib.rs

Mainly went to fix the warning but decided to add some
comments while I was in here.

rust: Fix a pub(crate) warning, add a few doc comments

---

Makefile-rpm-ostree.am
src/app/rpmostree-compose-builtin-rojig.cxx
src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-compose-builtins.h
src/daemon/rpmostree-sysroot-upgrader.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h
src/libpriv/rpmostree-rojig-client.cxx

Split out of #2439.
```
commit a56bdf532e395059aaf264d9117c228ec5526164
Date:   Mon Jan 11 16:47:01 2021 -0500
Makefile-rpm-ostree: Link to librt
For some reason, when building with `-g -Og`, I get a linker error for
a missing `lio_listio`. Adding `-lrt` fixes it. (We already link against
this transitively, so it's not actually a net new `DT_NEEDED`.)
commit 43a14866649efed77a04b271ad9cd126a86490aa
Date:   Mon Jan 11 16:50:11 2021 -0500
core: Allow overriding downloaded RPMs target dir
This will be useful for a follow-up patch which adds `rpm-ostree compose
extensions` where we'll want to download to a separate directory.
commit d5c090fa4517694251e8e477f1085bb8fc0c558f
Date:   Mon Jan 11 16:51:16 2021 -0500
app/compose: Drop rojig-related prototypes
Those functions don't actually exist …
```

Extensions prep patches

---

tests/vmcheck/test-apply-live.sh

- Further nested sub/sub directories
- symbolic links that point to various corner cases like `/`, are
broken, to parents etc.

apply-live: Extend /etc test case

---

src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-scripts.cxx

Move the creation of the directory up into core.
Avoid the use of `goto out` since we can't really
do this anymore with C++ exceptions in play.

 scripts: Rework /var/lib/rpm-state creation, port to new style

---

packaging/rpm-ostree.spec.in

https://fedoraproject.org/wiki/Changes/Remove_make_from_BuildRoot
(Upstreamed from https://src.fedoraproject.org/rpms/rpm-ostree/c/6e99dd065de3277de2b5027fb8b81c3743ba6d68?branch=master)
Really, libdnf's `cmake` BR does pull it into the buildroot anyway right
now. Though we do still need it as well.

spec: Add BuildRequires: make

---

.github/dependabot.yml

This updates dependabot config, dropping the "tooling" subdirectory
and fixing the path to the top-level cargo manifest.
/cc @cgwalters @jlebon @kelvinfan001

github: update dependabot config

---

tests/vmcheck/test-misc-2.sh

Minor cleanup.
Follow up from https://github.com/coreos/rpm-ostree/pull/2461/.

vmcheck/test-misc-2: Fix $cursor variable

---

.cci.jenkinsfile

Otherwise, it defaults to `_SC_NPROCESSORS_ONLN` (via `%make_build` ->
`%_smp_mflags` -> `%_smp_build_ncpus` -> `%{getncpus}` ->
https://github.com/rpm-software-management/rpm/blob/48c0f28834eb377a54f27ee0b6950af7e6d537b8/rpmio/macro.c#L583).
And that's going to be wrong in Kubernetes because we're constrained via
cgroups.
The `%_smp_build_ncpus` macro allows overriding this logic via
`RPM_BUILD_NCPUS`.
See: https://github.com/coreos/coreos-ci/issues/23
See: https://github.com/coreos/coreos-assembler/pull/632
See: https://github.com/coreos/coreos-assembler/pull/1287

ci: Set RPM_BUILD_NCPUS when building RPMs

---

docs/HACKING.md

Following https://github.com/coreos/rpm-ostree/commit/c7a9c3b1dd0b8b627605898be6ebadaf868b2d2d,
it is no longer necessary to provision your own VM.

HACKING: Update vmcheck instructions

---

docs/HACKING.md

This is no longer supported.
Keep and rework the bit about `make vmsync`.
Also drop the bit about FAHC and CAHC.

docs/HACKING: drop reference to `make vmcheck HOSTS=...`

---

src/app/rpmostree-builtin-start-daemon.cxx
src/daemon/rpmostreed-utils.cxx
src/libpriv/rpmostree-bwrap.cxx
src/libpriv/rpmostree-util.cxx
src/libpriv/rpmostree-util.h
tests/check/postprocess.cxx

All of these cases are actually fine, but in general we
can't use `goto out` since we started using C++ exceptions
which will skip that control flow.

Remove some uses of `goto out`

---

rust/src/lib.rs

Docs are good, and move up `StringMapping` since multiple things
are likely to use it.

rust: Add a bit more info on cxx, move up StringMapping

---

src/app/rpmostree-builtin-deploy.cxx
src/app/rpmostree-builtin-status.cxx
src/daemon/org.projectatomic.rpmostree1.xml
src/daemon/rpmostreed-daemon.h
src/daemon/rpmostreed-transaction-types.cxx
src/daemon/rpmostreed-transaction-types.h
src/daemon/rpmostreed-transaction.h
tests/vmcheck/test-misc-2.sh

Record agent's systemd unit in each transaction and add D-Bus API option (for use by update drivers, e.g. Zincati) for serializing agent information into a JSON file in `/run`. Teach `rpm-ostree status` to read from this JSON file and at least be able to display its update driver's systemd unit for now.
Closes https://github.com/coreos/rpm-ostree/issues/1747.

Allow Update Driver Registration

---

ci/install-extra-builddeps.sh

This fixes `install-extra-builddeps.sh` helper, by letting cargo
detect whether the target binary is already present in the
environment with the expected version.
This is in order to avoid mismatches in generated code when the
library version is bumped, and stale binaries are present on
the system.

ci: fix install-extra logic

---

rust/src/cliwrap.rs
rust/src/composepost.rs
rust/src/fedora_integration.rs
rust/src/ffiutil.rs
rust/src/history.rs
rust/src/journal.rs
rust/src/live.rs
rust/src/lockfile.rs
rust/src/ostree_diff.rs
rust/src/passwd.rs
rust/src/testutils.rs
rust/src/treefile.rs
rust/src/utils.rs

Mostly straightforward stuff. It taught me about the `matches!` macro,
which looks really useful.
Wanted to turn this on in CI, but there's still a bunch of clippy
warnings coming from the `cxx.rs` stuff and some of our unsafe blocks.
For example, it wants the `files` arg in `initramfs_overlay_generate` to
be `&[String]` instead of `&Vec<String>` but that would break cxx.rs (it
looks like cxx.rs does support slices, but it would require creating one
from the vector we have to create anyway).

rust: Fix clippy warnings

---

src/libpriv/rpmostree-core.cxx

We temporarily set the rpmdb path to be an absolute path pointing under
the tmprootfs when writing the rpmdb. This throws off libsolv 0.7.17,
which learned to give the `_dbpath` macro precedence on where the rpmdb
is located:
https://github.com/openSUSE/libsolv/commit/04d4d036b275693a23eef75fba634e7cea2f1a6d
So then the rpmdb sanity-check we do when exiting
`rpmostree_context_assemble()` breaks because it can't find the expected
packages.
Because RPM macros are in global state, there's no elegant way of
setting it just for the rpmdb write operation (short of forking), so
just fix this by setting `_dbpath` back to the correct value after we're
done writing the rpmdb.
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/723

core: Set _dbpath back to /usr/share/rpm after writing rpmdb

---

src/app/rpmostree-builtin-deploy.cxx
src/daemon/rpmostreed-transaction-types.cxx
tests/vmcheck/test-misc-2.sh

It is sometimes useful to only register an update driver without
actually deploying anything. If the argument for `deploy` is an
empty string, only register driver and then no-op.

deploy: Allow empty string argument if `--register-driver`

---

.cci.jenkinsfile
ci/unit.sh

I think we did this at some point, but then stopped.
Prep for https://github.com/coreos/rpm-ostree/pull/2413
because we'll need a full build of the C++ side too in order
to `cargo test`.

ci: Make msrv test do full build + unit tests

---

rust/src/passwd.rs

This updates file copying to use the newer `copy_file_at` from
openat-ext.

rust/passwd: minor cleanup, switch to copy_file_at

---

Cargo.lock
Cargo.toml
Makefile-rpm-ostree.am
build.rs
rust/src/lib.rs
rust/src/rpmutils.rs
src/daemon/rpmostree-sysroot-core.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-rpm-util.cxx
src/libpriv/rpmostree-rpm-util.h
src/libpriv/rpmostree-util.h
tests/check/test-utils.cxx

rust: Link to our C/C++ dependencies and internal library
This allows us to fully use cxx-rs with `extern "C++"`.  Now
we do call back into the C/C++ today, but it only works outside
of cargo/Rust's knowledge.  Most notably, it means we can't
use our C code in `cargo test`.  And that's a problem
for moving some C/C++ code to Rust, because we want to port
the unit tests too.
For now, re-declare our dependencies and part of the build
system inside the Cargo build.  However, this is also
an important step towards using Cargo as our *sole* build
system.
We don't add build dependencies too often, so the short
term duplication should be OK.
However, a major unfortunate side effect of this is that
we now need to serialize the build process; almost all the
C/C++ comes first …

 Demo of first use of `extern "C++"`

---

rust/src/lib.rs

One is only used in the unit tests right now, the other we'll
likely use soon.
We should try doing something like https://github.com/rust-unofficial/patterns/blob/master/anti_patterns/deny-warnings.md in CI.

rust: Add some allow(dead_code)

---

src/app/rpmostree-compose-builtin-rojig.cxx
src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-postprocess.cxx
src/libpriv/rpmostree-postprocess.h

compose: Remove unused treefile_rs parameter

---

rust/src/extensions.rs
rust/src/lib.rs
src/app/rpmostree-compose-builtin-tree.cxx
tests/compose/test-basic-unified.sh

Let's include the final extensions file in JSON format as part of the
output directory. A key difference from the input file (apart from YAML
vs JSON) is that this is post-filtering, so any extensions which were
removed because the architecture does not match are not present.
This JSON file will be used by cosa and the MCO. See discussions in:
https://github.com/openshift/os/issues/409

extensions: Write JSON to output dir

---

tests/kolainst/destructive/layering-fedorainfra

The previous build was GC'd; unfortunately it's very nontrivial
to make this test truly robust over time because FCOS changes;
we might sometimes have an outstanding update, other times might
not etc.
Let's just sanity check the commands; ultimately they're
thin wrappers around just downloading packages so we don't need
deep checks.

tests/layering-fedorainfra: Update rpm-ostree build

---

ci/build-check.sh
tests/check/postprocess.cxx

This seems to work for me; we want to run the C unit tests.

 ci: Re-enable `make check`

---

Makefile-rpm-ostree.am
Makefile.bindings
packaging/make-git-snapshot.sh
rust/src/lockfile.rs

Makefile.bindings: Also generate pure rust/cxx.h
This is necessary in order to use `rust::` in our header files
that are also used by bindings.
---
lockfile: Note that comment is JSON
Otherwise rustc tries compile and run it as a doctest.

Rust is main prep

---

Makefile-lib.am
Makefile-rpm-ostree.am
configure.ac
src/lib/rpmostree-package.c
tests/kolainst/nondestructive/misc.sh

Prep for "Rust-as-main", where I want to build libdnf statically.
And this really completes the "library thinout" story because
now we avoid dragging our *private* `libdnf.so` into the caller's
address space, which can cause potential conflicts if they're
also linking the system one. (Which could easily occur with
something like gnome-software)
All we were using libdnf for (indirectly via libsolv) is comparing
version strings but librpm can already do that for us.

lib: Don't link to libdnf

---

rust/src/cliwrap.rs

We need to trim the starting whitespace, otherwise
it ends up in the script.
Just noticed while playing with `cliwrap: true`.

cliwrap: Fix indentation

---

rust/src/lib.rs
rust/src/utils.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-util.cxx
src/libpriv/rpmostree-util.h
tests/check/jsonutil.cxx

This demonstrates well the strength of the cxx-rs approach;
we can keep an API in C++ but add unit tests in Rust which
just works much more nicely.
Prep for https://github.com/coreos/rpm-ostree/pull/2502
which wants to drop the C++ unit tests.

Bridge "next version" API to Rust, use it for unit tests

---

Makefile.am

Notably this includes [std::optional](https://en.cppreference.com/w/cpp/utility/optional)
which I'd like to use.
The dnf-5-devel branch uses this too, and C++-17 is now well
supported in current GCC, which is available in RHEL8 DTS too.

build: Use -std=c++17

---

src/app/rpmostree-dbus-helpers.cxx
src/app/rpmostree-libbuiltin.cxx
src/app/rpmostree-polkit-agent.cxx
src/daemon/rpmostreed-daemon.cxx
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-os-experimental.cxx
src/daemon/rpmostreed-os.cxx
src/daemon/rpmostreed-sysroot.cxx
src/daemon/rpmostreed-transaction-applylive.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/daemon/rpmostreed-transaction.cxx
src/daemon/rpmostreed-utils.cxx
src/lib/rpmostree-package.c
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-importer.cxx
src/libpriv/rpmostree-origin.cxx
src/libpriv/rpmostree-passwd-util.cxx
src/libpriv/rpmostree-rpm-util.cxx

See https://github.com/rpm-software-management/libdnf/pull/1127
Basically IMO the "return if fail" pattern is a carry-over
from C GTK+ apps where the idea is it's better to try to stumble
forward than have the app crash for the user.
In our case though, IMO we absolutely should just crash
if our assertions trip, because we're maintaining the user's
root filesystem.

tree-wide: Convert g_return.*if_fail to g_assert

---

.cci.jenkinsfile
Cargo.toml
ci/build.sh
ci/clang-build-check.sh
ci/unit.sh

ci: Drop testuser creation
Nothing is using this; our unit tests don't change uids and
most of our testing is in VMs.
Dropping this makes it easier to run the scripts outside of CI.
---
ci: Split clang into separate script, run it in CoreOS CI
Let's do a build with clang as a cleanly separate context
instead of serially; and also do it unconditionally.  This
is prep for turning on more `-Werror` flow in both cases,
and also using clang `scan-build` in CI.
---
ci: Drop custom msrv checking
The way this tries to replace the system Rust is hacky and
actually I realized belatedly I may have broken it recently; basically
`installdeps.sh` re-adds the system one, and it's hard to be sure
with our current buildsystem we're using the newer one from `$PATH`.
What we really want to do here is use a …

A few CI patches

---

Makefile-rpm-ostree.am
build.rs
configure.ac

Move libdnf build over to Cargo
This is now further migration towards Cargo/Rust possible
because we switched our main binary.  We've had an internal
`libdnf-sys` crate for a while, but now it can take over
the build of the underlying library too (like many `-sys`
crates support).
This itself is just an incremental step towards migrating
the main rpm-ostree build system to e.g. cmake too (or
perhaps directly with the `cc` crate, not sure yet) and
driving it via `cargo` too.
---
build-sys: Move -lcap linkage purely to Rust
Now that we are generating solely a Rust binary, we can
have the canonical list of things to link on the Rust side.
---
build-sys: Move -lstdc++ -lrt into Cargo
More draining.
---
build-sys: Move -lm -ldl linkage into Cargo
More Rust, less shell/m4 - the world gets …

build-sys: Rollup rework v1

---

build.rs

Not running the code you think you are is an evil trap.
Fixes fallout from https://github.com/coreos/rpm-ostree/pull/2502/commits/b122579222892eb19555087adb0e026316d0d9f7

build-sys: Rebuild on C++ changes

---

src/libpriv/rpmostree-scripts.cxx

I think this changed in a recent refactoring; basically since
we're passing this stack-allocated value to the child spawn
function we need to keep it alive.  This of course would
have been caught by Rust...
```
==672376==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffc290d9440 at pc 0x55c88c318946 bp 0x7ffc290d8b10 sp 0x7ffc290d8b08
#0 0x55c88c318945 in script_child_setup src/libpriv/rpmostree-scripts.cxx:272
#1 0x7f92089da902  (/lib64/libglib-2.0.so.0+0x9f902)
#2 0x7f92089de20f  (/lib64/libglib-2.0.so.0+0xa320f)
#3 0x7f92089de52e  (/lib64/libglib-2.0.so.0+0xa352e)
#4 0x7f92089def02 in g_spawn_async_with_pipes (/lib64/libglib-2.0.so.0+0xa3f02)
#5 0x7f9208b7445f  (/lib64/libgio-2.0.so.0+0xab45f)
#6 0x7f9208b736d8 in g_subprocess_launcher_spawnv …
```

scripts: Fix a stack use-after-free

---

docs/extensions.md
rust/src/extensions.rs
rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h
tests/compose.sh
tests/compose/test-basic-unified.sh

See https://github.com/coreos/coreos-assembler/pull/2028#issuecomment-769459160 for background. Testing this on RHCOS with:
```yaml
repos:
- rhel-8-nfv
extensions:
usbguard:
kind: os-extension
packages:
- usbguard
kernel-rt:
kind: os-extension
architectures:
- x86_64
packages:
- kernel-rt-core
- kernel-rt-kvm
- kernel-rt-modules
- kernel-rt-modules-extra
- kernel-rt-devel
kernel-devel:
kind: development
packages:
- kernel-devel
- kernel-core
- kernel-headers
- kernel-modules
- kernel-modules-extra
match-base-evra: kernel
```
Works fine!
See individual commit messages for details.

Follow-ups to the extensions work

---

ci/libbuild.sh

Prow doesn't set this and it breaks our `cargo install`.

ci: Ensure HOME is set

---

ci/libbuild.sh

Actually it seems OpenShift sets HOME=/ for some reason; probably
related to the non-root uid default.
And whole lot of the Prow jobs do `export HOME=$(mktemp -d)` today.
I am tempted to add a `cosa entrypoint` command or something
that sanitizes the environment setup.

ci: Also test for HOME being writable

---

rust/src/lib.rs
rust/src/passwd.rs
src/libpriv/rpmostree-passwd-util.cxx

This moves `group` and `passwd` merging/deduplication to Rust.

libpriv/passwd: move entries deduplication logic to Rust

---

.cci.jenkinsfile
ci/build-check.sh
ci/build.sh
ci/ci-commitmessage-submodules.sh
ci/clang-build-check.sh
ci/commit-validation.sh
ci/coreosci-rpmbuild.sh
ci/libbuild.sh
ci/unit.sh

ci: Don't assume HEAD exists
For some reason the way Prow clones the repo it doesn't exist;
the git default of `..` should work though.
---
ci: Consistently source libbuild
Since we need to set HOME and PATH, let's do that in a central
place rather than scattering it around by having all of
our entrypoint scripts source the `libbuild.sh` shell "library".
Move the CoreOS CI entrypoint into a script like the others.

Even more CI patches

---

Makefile-rpm-ostree.am

This fixes link dependencies and build-libraries path, in order to
make Rust tests work.
It also introduces an additional wildcard target to allow specifying
a test filter to cargo.

make/rust-test: fix linking and loading

---

.cci.jenkinsfile

We're running them in Prow now and we're hitting capacity
issues in CentOS CI.  Bigger picture, the "just build and unit test"
stuff runs in any cluster, so let's save our bare metal capacity
for our compose/VM testing.

ci: Drop clang and unit tests from here

---

rust/libdnf-sys/build.rs

WITH_SWDB: Removed in https://github.com/rpm-software-management/libdnf/commit/99309fbe04dcbdf6f9f09ceac01549b6cebc1c09
WITH_GIR Removed in https://github.com/rpm-software-management/libdnf/commit/e2f2862bedd0c278ed9781624ddc6861686a4760
Also, most importantly: don't always reconfigure libdnf
This is a questionable default for the cargo `cmake` crate.
Building in Koji is failing I think due to timestamp issues
causing cmake to run twice.

libdnf: Various buildsys fixes

---

ci/clang-analyzer.sh
src/app/libmain.cxx
src/app/rpmostree-builtin-rebase.cxx
src/daemon/rpmostreed-daemon.cxx
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-os.cxx
src/lib/rpmostree.c
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-importer.cxx
src/libpriv/rpmostree-passwd-util.cxx
src/libpriv/rpmostree-postprocess.cxx
src/libpriv/rpmostree-rpm-util.cxx
src/libpriv/rpmostree-scripts.cxx
src/libpriv/rpmostree-util.h

ci: Add clang-analyzer.sh
There are really no excuses for any C/C++ project not to use
both ASAN+UBSAN and static analysis in CI.
---
tree-wide: Fix some spurious "Dead assignment" from clang-analyzer
This fixes some spurious warnings from clang-analyzer (aka `scan-build`) around
"Dead assignment".  Unfortunately the analyzer doesn't understand
the side effects of `__attribute__((cleanup))` here.
More info on the `(void)` pattern: https://clang-analyzer.llvm.org/faq.html#dead_store
---
tree-wide: Fix some "Dead assignment" from clang-analyzer
The `have_rpmdb` one was a leftover looks like.  In the `disabled_all_repos`
case it was clearly there for symmetry, but eh; it seems somewhat
unlikely that we add a *3rd* case there.  Also while we're
here change it to C++ `bool` so tools like …

Add ci/scan-build.sh and fix some warnings

---

src/daemon/rpmostree-sysroot-core.cxx
src/libpriv/rpmostree-core.cxx

If we get here, it's that we expect the pkgcache to be there. So don't
allow ENOENT (we weren't even checking for the ENOENT case here, which
shows that this was the intent).
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1925584

core: Don't allow noent when resolving pkgcache rev

---

ci/clang-analyzer.sh

This flow was missing from here which broke in CI.

ci/clang-analyzer: Install deps

---

src/app/libmain.cxx
src/app/rpmostree-compose-builtin-tree.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/daemon/rpmostreed-utils.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-importer.cxx
src/libpriv/rpmostree-kernel.cxx

tree-wide: Fix clang -Wgnu-designator/-Wunused-variable
clang warns about this:
https://clang.llvm.org/docs/DiagnosticsReference.html#wgnu-designator
Also fix unused variables and hard error on them.
---
transaction: Fix missing return in error case
Hooray for compiler warnings.
---

tree-wide: Fix clang -Wgnu-designator/-Wunused-variable

---

Makefile.am
ci/build-check.sh
ci/clang-build-check.sh
configure.ac

So...at some point we somehow lost `-Wall` in our
default compiler flags which means we were missing some
potentially important warnings.  And
we used to have `-Werror` on in CI which combined
with the above was strongly opinionated about not
landing warnings in git master.
Our default stance here remains the same; we have
an opinionated set of `-Werror=` that applies in
*all* configurations.   However that set moves
into Automake - I don't think we need to do
compiler version detection anymore, we can assume
a modern compiler.
We also add back in `-Wall` by default now.
Further in CI, add `-Werror`.  The implementation
here is in our buildsystem rather than
`export CXXFLAGS=-Werror` because unfortunately
we have to fix things in libdnf too, and I don't
want to block entirely on that.

build-sys: Add --enable-werror, rework compiler flags

---

Makefile-rpm-ostree.am
build.rs

Having our binary depend on the shared library, which in
turn depends on the binary (at runtime) is messy.
Instead, statically compile the shlib code into our binary.
This duplicates the text a bit, but it's not a lot of code.
The goal is to more easily in the future to e.g. move the
shared library out into a separate git repository entirely
that runs on a separate lifecycle - that would still build
using Automake for example while the main git repository
switches to purely cargo.
Another motivation is avoiding linker issues I had with other
patches due to this semi-cyclical dependency.

build-sys: Statically link binary against shlib code

---

rust/src/lib.rs
rust/src/live.rs
rust/src/progress.rs
src/app/rpmostree-dbus-helpers.cxx
src/daemon/rpmostree-sysroot-upgrader.cxx
src/libpriv/rpmostree-core-private.h
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-output.cxx
src/libpriv/rpmostree-output.h
src/libpriv/rpmostree-postprocess.cxx
src/libpriv/rpmostree-util.cxx
src/libpriv/rpmostree-util.h

Originally the Rust apply-live code was exposed from Rust to C
via bindgen.  But when working on that, I hit the problem
that our output infrastructure was C...and the "reverse direction"
binding stuff was just ugly.
This PR again IMO shows the value of the investment in cxx-rs
because we can now seamlessly call back from the Rust side
into a "C++-ish" progress API, which the C++ side is updated
to use.
The level of indirection here is obviously pretty silly
because the main thing on the C++ output side is basically
a function dispatcher, but...I didn't want to try to rework
that into Rust fully yet.  (But, the moment we do this
whole area will get a *lot* cleaner)
Anyways, in the end this makes it easy for the apply-live
code to output progress to the user which was sorely
needed.

 Bind output core into Rust, use in apply-live

---

src/app/rpmostree-compose-builtin-tree.cxx

We don't need it and it won't work in the unprivileged path where we're
running this in a cosa supermin (of course, this is all a bit silly
because we don't actually need privileges to begin with for this, but
there's a lot of momentum in sticking with that workflow).

extensions: Don't try to chown RPM packages

---

Cargo.lock
rust/libdnf-sys/Cargo.toml
rust/libdnf-sys/build.rs
rust/libdnf-sys/cxx/libdnf.cxx
rust/libdnf-sys/cxx/libdnf.hxx
rust/libdnf-sys/lib.rs
rust/src/ffiutil.rs
rust/src/lib.rs
rust/src/lockfile.rs
src/app/rpmostree-compose-builtin-tree.cxx

```
libdnf-sys: Drop C API, replace with cxx.rs bridge
Right now, we're using libdnf APIs from Rust via hand-crafted `extern C`
interfaces, which is extra dangerous because there is no signature
checking that happens at compile-time.
Until either we can automate libdnf bindings or use its C++ API directly
via cxx.rs, let's do some basic wrapping in C++ ourselves and use libdnf
through that API only instead. That gives us a lot more confidence and
makes the libdnf API feel more natural to use in Rust.
```
```
lockfile: Move ror_lockfile_read to cxx.rs
Pretty straightforward. Haven't moved `ror_lockfile_write` yet because
that's trickier to do and I'm still figuring out the most elegant way to
do this within cxx.rs' constraints.
```

libdnf-sys: Drop C API, replace with cxx.rs bridge and move ror_lockfile_read to cxx.rs

---

Cargo.toml
Makefile-lib.am
Makefile-rpm-ostree.am
Makefile.am
build.rs
configure.ac
packaging/rpm-ostree.spec.in

build: Drop introspection+clang hack
Forcing use of GCC breaks trying to use `clang -fsanitize=address`.
The real fix here anyways should have been avoiding passing
compiler flags to a compiler that doesn't understand them.
---
Add --enable-sanitizers (not on by default yet)
This way we at least get unit test coverage (which...
our unit test coverage doesn't do much because our
main code paths require privileges or virt).
One main blocker to this is that rustc doesn't expose
first-class support for this yet:
https://github.com/rust-lang/rust/issues/39699
At a practical level this works when building in release
mode but fails with `cargo test` for some reason; linker
arguments being pruned?  Not sure.
So I was able to use this when composing to find a bug,
but then for some other reason …

Add --enable-sanitizers (not on by default yet)

---

src/libpriv/rpmostree-refsack.h
src/libpriv/rpmostree-refts.h

Alternative fix to https://github.com/rpm-software-management/libdnf/pull/1139
aka https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1935
This way libdnf's `extern "C"` over the glib headers doesn't apply
because we already processed that header.

tree-wide: Include GLib headers before libdnf

---

rust/src/client.rs
rust/src/cliwrap.rs
rust/src/composepost.rs
rust/src/core.rs
rust/src/countme.rs
rust/src/dirdiff.rs
rust/src/fedora_integration.rs
rust/src/ffiutil.rs
rust/src/journal.rs
rust/src/lib.rs
rust/src/lockfile.rs
rust/src/main.rs
rust/src/ostree_diff.rs
rust/src/passwd.rs
rust/src/rpmutils.rs
rust/src/scripts.rs
rust/src/treefile.rs
rust/src/utils.rs

Specifically motivated by adding some docs in `treefile.rs` around
how to add a field, but I decided to just do a pass and
document everything at least a little.
View with e.g. `cargo doc --document-private-items`.

rust: Add module doc headers

---

tests/common/libvm.sh

Print error and exit if cannot find `tests/vmcheck/image.qcow2` or
bad symlink causing failure to spawn a VM when calling the
`vm_kola_spawn()` function.

tests/common/libvm: Print error if bad tests/vmcheck/image.qcow2

---

src/app/libmain.cxx
src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-dbus-helpers.cxx

This is actually a perfect example of the tradeoffs involved
in our team of C/Rust programmers trying to use C++ so we
can use cxx-rs =)
It turns out that "for (auto foo : bar)" is really yet another
one of those C++ sharp edges just waiting to cut.  That
version does a copy of each value; one almost always wants to use
"for (auto & foo : bar)" which like Rust's `.iter()`.
In most of our code we were OK making copies, they were just
a performance hit, but in another place I was relying on the
"side effect" of `.c_str()` but that meant our value got
destroyed.

tree-wide: Fix C++ range iteration to use references

---

Makefile-rpm-ostree.am

When working on a PR to add a sub-crate I hit the fact
that our `find` bit wasn't fully accurate and spent some
time debugging the fact that the code I got after `make`
wasn't up to date.
Since cargo is smart in general, let's stop trying to
second guess its dependencies and just run `cargo build`
every time `make` is run.
(I'm not sure why we didn't do this from the start)

build-sys: Always run `make` → `cargo build`

---

tests/vmcheck/test-layering-non-root-caps.sh

I didn't deep dive on this, just observed that the new output
matches what we laid down.  There's ~2.5 years of changes
and ~200 commits between 2.28 and 2.48.

tests/layering-non-root-caps: Adapt to new libcap output

---

.cci.jenkinsfile
Makefile.am
ci/build.sh
ci/ci-commitmessage-submodules.sh
ci/clang-analyzer.sh
ci/coreosci-rpmbuild.sh
ci/install-extra-builddeps.sh
ci/install-test-deps.sh
ci/installdeps.sh
ci/libbuild.sh
ci/testdeps.txt
configure.ac
packaging/make-git-snapshot.sh
tests/vmcheck/test-layering-non-root-caps.sh

ci: Drop: distro-sync, continuous repo
Doing the distro-sync costs ~3 minutes per execution, and it
happens multiple times.  Let's just ensure our images are up
to date instead.
Also drop the continuous repo (for now) - we added this
to test bleeding edge ostree, but I think we need to reintroduce
"git master" builds as whole separate CI flow (layered container)
instead.
---
ci: Add `time` prefixing before most commands
We don't have timestamps set up right now, and including
timing information is easy and useful to debug CI speed.
---

Two CI cleanups

---

Cargo.lock
Cargo.toml
rust/rpmostree-client/Cargo.toml
rust/rpmostree-client/src/lib.rs
rust/rpmostree-client/tests/fixtures/workstation-status.json
rust/rpmostree-client/tests/parse.rs
rust/src/testutils.rs
tests/kolainst/nondestructive/misc.sh

This is intended to be published to https://crates.io/crates/rpmostree-client
Part of https://github.com/coreos/rpm-ostree/issues/2389
This directly imports the code from
https://github.com/ostreedev/ostree/blob/5551c54c6e6eba8145b95bd3b28223f1941a9e8d/tests/inst/src/rpmostree.rs
Once merged and released I'll try converting the ostree test suite
over as well as Zincati.
Internally add a testutils helper to validate it works.

Add an rpmostree-client sub-crate

---

src/app/rpmostree-builtin-status.cxx
src/app/rpmostree-builtin-upgrade.cxx
src/app/rpmostree-libbuiltin.cxx
src/app/rpmostree-libbuiltin.h
tests/vmcheck/test-misc-2.sh

app/status: factor out get_sd_unit_objpath() function:
Factor out a `get_sd_unit_objpath()` function into `libbuiltin`
so we can reuse the code in `builtin_upgrade`.
app/upgrade: Do not upgrade if updates driver registered:
Do not perform an upgrade if detected that an updates driver has
been registered.
Add --force option to force an upgrade regardless of whether an
updates driver has been registered.
Closes: https://github.com/coreos/rpm-ostree/issues/2536

app/upgrade: Do not upgrade if updates driver registered

---

rust/libdnf-sys/cxx/libdnf.hxx
src/app/rpmostree-compose-builtin-rojig.cxx
src/app/rpmostree-compose-builtin-tree.cxx

compose: Add missing #include <optional>
This only fails on newer gcc/libstdc++ apparently in current
Fedora rawhide: https://kojipkgs.fedoraproject.org//work/tasks/4372/62164372/build.log
---
libdnf-sys: Include gio.h before libdnf.h
See https://github.com/coreos/rpm-ostree/pull/2562/commits/b77f710cfb45279262144a02208781c94269ed25
Alternative fix to rpm-software-management/libdnf#1139
aka https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1935
This way libdnf's `extern "C"` over the glib headers doesn't apply
because we already processed that header.
---

Two rawhide build fixes

---

rust/src/cxxrsutil.rs
rust/src/lib.rs
src/libpriv/rpmostree-util.cxx
src/libpriv/rpmostree-util.h

When we started using cxxrs, most of the glib-rs objects like
`OstreeRepo`/`OstreeSysroot` were owned by C++ and passed
down into Rust.  That motivated the addition of the special
bridging infrastructure to re-create a glib-rs wrapper
type from what cxxrs wants (a `Pin<&mut T>`).
But now that we're adding more in Rust, we have the need
to pass these objects back into C++.  In fact this will
hopefully soon because the default case as more of the
binary entrypoint becomes Rust.
Add another trait with a method `gobj_rewrap()` that converts
in the other direction.  This implementation took me a number
of tries before I finally settled on simply using `mem::transmute()`.
There are a *lot* of caveats listed on the docs for that function,
but I think it really is what we want here.  See the link …

Add gobj_rewrap() API to pass glib-rs objects back to C++

---

ci/prow/Dockerfile
ci/prow/fcos-e2e.sh

Our "CoreOS CI Jenkins" flow is great, but the reliability/debuggabilty
of the system isn't the best.  This is an experient to *add* another e2e CI
flow that can be run in Prow too.
I'd like to at least have a basic e2e (compose tree, run client tests)
flow that can operate in Prow so that if CoreOS CI Jenkins is down or
flaky, we at least have some confidence in our commits.
Longer term I think we can figure out how to better share CI flows
across these:
https://github.com/coreos/fedora-coreos-tracker/issues/263#issuecomment-772903759

ci: Add Prow e2e testing

---

rust/src/daemon.rs
rust/src/lib.rs
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-os.cxx
src/daemon/rpmostreed-sysroot.cxx

daemon: Refactor deployment variant generation code
Changes to this ad-hoc `a{sv}` code have been scattered
around over time.  Move the "core" bits to the top of
the function, then have the more complex stuff that depends
on the origin (and refspec/layering status) later.
Prep for further cleanups.
---
Add daemon.rs with one helper function, use it from C++
Trying to port to use origin Rust code, I think actually
it gets simpler if we move more to Rust to start.
---

Minor deployment status oxidation

---

src/app/rpm-ostree-countme.timer

Set `Persistent=yes` in the timer unit to make sure that systems that
are not running 24/7 gets counted when they wake up if they missed the
previous timer run / counting window.
This is mostly for Fedora Silverblue like systems as Fedora CoreOS
systems usually run 24/7.
See https://www.freedesktop.org/software/systemd/man/systemd.timer.html#Persistent=

countme: Persist last timer trigger for Silverblue-like systems

---

Makefile-libpriv.am
Makefile-rpm-ostree.am
rust/src/lib.rs
rust/src/live.rs
src/app/rpmostree-builtin-applylive.cxx
src/app/rpmostree-builtin-ex.cxx
src/app/rpmostree-ex-builtins.h
src/daemon/rpmostreed-os-experimental.cxx
src/daemon/rpmostreed-transaction-applylive.cxx
src/daemon/rpmostreed-transaction-types.h
src/libpriv/rpmostree-diff.cxx
src/libpriv/rpmostree-diff.hpp
src/libpriv/rpmostree-output.cxx
src/libpriv/rpmostree-output.h

Depends https://github.com/coreos/rpm-ostree/pull/2574
---
app: Rename livefs.cxx → apply-live.cxx
Continuing the renaming.
---
daemon: Rename transaction_livefs → transaction_apply_live
Continuing the renaming.
---
Add a C++ rpmdb-diff API wrapping the C one, bind in Rust
I'd like to compute diffs in apply-live to differentiate
between "pure layering" versus modifications/removals.
---
Fix progress API to have "output message" separate from task
A lot of our output is outside of a "task"; the Rust binding
incorrectly made it a method on `Progress`.  This is really
just a `println!()` that is backed by our dispatch system.
---
apply-live: Move client-side finish to Rust
Now that we have an RPM diff+printing binding, we can
move the client side postprocessing for `apply-live`
to Rust.
---

More apply-live cleanups and oxidation

---

build.rs
ci/codestyle.sh
rust/libdnf-sys/build.rs
rust/rpmostree-client/src/lib.rs
rust/rpmostree-client/tests/parse.rs
rust/src/client.rs
rust/src/cliwrap.rs
rust/src/cliwrap/cliutil.rs
rust/src/cliwrap/dracut.rs
rust/src/cliwrap/grubby.rs
rust/src/cliwrap/rpm.rs
rust/src/core.rs
rust/src/countme.rs
rust/src/countme/cookie.rs
rust/src/countme/repo.rs
rust/src/cxxrsutil.rs
rust/src/fedora_integration.rs
rust/src/history.rs
rust/src/includes.rs
rust/src/initramfs.rs
rust/src/main.rs
rust/src/nameservice/group.rs
rust/src/nameservice/mod.rs
rust/src/nameservice/passwd.rs
rust/src/ostree_utils.rs
rust/src/passwd.rs

It turns out we accidentally added GPL'd code into the Rust
side, which wasn't intentional on my part and I think it's since
been copied around.
Honestly I think half of the problem is the gigantic
"blah blah blah GNU General blah blah" just makes people's eyes
glaze over.  In contrast the `SPDX-License-Identifier` is short
and obvious.
So let's validate that in CI.
This follows a similar change in ostree:
https://github.com/ostreedev/ostree/pull/1439
If we merge this I'll do the C/C++ side too after that.

rust: Add SPDX-License-Identifier and validate it in ci/codestyle.sh

---

ci/codestyle.sh
rust/src/daemon.rs

This adds a missing `SPDX-License-Identifier` tag, fixing CI.

rust: add missing SPDX-License-Identifier tag

---

rust/src/cxxrsutil.rs
rust/src/daemon.rs
rust/src/lib.rs
src/daemon/rpmostreed-deployment-utils.cxx
src/libpriv/rpmostree-cxxrs-prelude.h

More prep for https://github.com/coreos/rpm-ostree/pull/2388
This was actually also my first time really trying out the
latest gtk-rs `glib::Variant` API, which is one of the major
things we need to use to progress oxidation more.

daemon: Move some "deployment variant" generation to Rust

---

.cci.jenkinsfile
Makefile-tests.am
docs/HACKING.md
tests/common/libvm.sh

Now that `cosa build-fast` writes to `.cosa`, teach our
test suite to pick that up by default.  We don't anymore
support non-CoreOS (i.e. non-Ignition) hosts for our test
suite, so making this more CoreOS specific is fine.
Then use the "standard" COSA_DIR as a way to find the target
cosa dir in the e2e CI.

ci: Drop tests/vmcheck/image.qcow2, use COSA_DIR/.cosa

---

rust/src/lib.rs
rust/src/live.rs
rust/src/ostree_utils.rs
src/daemon/rpmostree-sysroot-core.cxx
tests/kolainst/nondestructive/misc.sh
tests/vmcheck/test-layering-local.sh

Came out of discussion in #2581
around some racy code for checking for the live commit object.
The reliability of apply-live depends on the
underlying commits not being garbage collected.  Our diff logic
is in terms of ostree commits, not the physical filesystem (this
allows us to make various optimizations too).
Ultimately I think we should drive some of the live-apply
logic into libostree itself; we can more easily have an atomic
state file instead of the two split refs.
(Or perhaps what we should add to ostree is like a refs.d model
where a single atomic file can refer to multiple commits)
For now though let's rework the code here to write refs.  We
retain the file in `/run` as just a "stamp file" that signals
that a deployment has had `apply-live` run.

 apply-live: Rework to use refs to store state

---

docs/architecture-core.md

This is long overdue.  Some of this came up in recent
conversation.  Let's keep up some continual background
momentum on documentation, just like CI.

docs/architecture-core.md: New file

---

src/app/rpmostree-builtin-deploy.cxx
src/app/rpmostree-builtin-rebase.cxx
src/app/rpmostree-builtin-status.cxx
src/app/rpmostree-builtin-upgrade.cxx
src/app/rpmostree-dbus-helpers.cxx
src/app/rpmostree-dbus-helpers.h
src/app/rpmostree-libbuiltin.cxx
src/app/rpmostree-libbuiltin.h
tests/vmcheck/test-misc-2.sh

Follow up to #2566.
Error out if users try to manually do a deploy/rebase if an updates
driver is registered. Provide `--bypass-driver` option to proceed
anyway.

app/{deploy,rebase}: Do not deploy/rebase if updates driver registered

---

rust/src/passwd.rs
rust/src/treefile.rs

This adds default-aware getters for `check-passwd` and `check-groups`.
/cc @jlebon

treefile: add getters for check-passwd and check-groups

---

rust/src/lib.rs
rust/src/passwd.rs
src/libpriv/rpmostree-passwd-util.cxx

This ports to Rust the logic for checking whether a directory tree
contains content owned by a given UID/GID.

libpriv/passwd: move UID/GID checker to Rust

---

src/daemon/rpmostree-sysroot-upgrader.cxx
tests/vmcheck/test-pinned-commit.sh

The refspec code really needs to be cleaned up and oxidized (and
unit tested more).
The intention is that if you're pinned to a commit, we say
"No upgrade available" but we were crashing if one (understandably)
rebased to the combination of `remote:checksum` instead of just `checksum`.
Fix the classifer code to say this is a `CHECKSUM` case, and
fix the upgrader to skip the pull path.
Closes: https://github.com/coreos/rpm-ostree/issues/2603

daemon: Fix crash on upgrade with remote:checksum

---

src/app/libmain.cxx
src/app/rpmostree-builtin-applylive.cxx
src/app/rpmostree-builtin-cancel.cxx
src/app/rpmostree-builtin-cleanup.cxx
src/app/rpmostree-builtin-db.cxx
src/app/rpmostree-builtin-deploy.cxx
src/app/rpmostree-builtin-finalize-deployment.cxx
src/app/rpmostree-builtin-initramfs-etc.cxx
src/app/rpmostree-builtin-initramfs.cxx
src/app/rpmostree-builtin-kargs.cxx
src/app/rpmostree-builtin-rebase.cxx
src/app/rpmostree-builtin-refresh-md.cxx
src/app/rpmostree-builtin-reload.cxx
src/app/rpmostree-builtin-reset.cxx
src/app/rpmostree-builtin-rollback.cxx
src/app/rpmostree-builtin-status.cxx
src/app/rpmostree-builtin-upgrade.cxx
src/app/rpmostree-builtin-usroverlay.cxx
src/app/rpmostree-builtins.h
src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-dbus-helpers.cxx
src/app/rpmostree-dbus-helpers.h
src/app/rpmostree-override-builtins.cxx
src/app/rpmostree-pkg-builtins.cxx

Instead of passing the pid back up the stack and using a cleanup
function on it to invoke `kill()`, use `PR_SET_PDEATHSIG` which
has the kernel take care of this for us.
(In practice we don't actually use this peer functionality anymore
because all of the client/daemon code kind of requires being run under systemd
on a real system now)
This shrinks the API surface and is much less repetitive in
the codebase.
Prep for moving more of the CLI code to Rust.

client: Remove peer_pid value from option parsing

---

tests/common/libvm.sh

I spent longer than I'd care to admit being confused why my
changes from `cosa build-fast` weren't being picked up.
We need to honor `.cosa` first because the expected case
is you have both set in the `build-fast` case.
Will look at fixing `kola spawn` to handle all this too; the
problem is we haven't taught kola/cosa about `COSA_DIR`.

tests/vmcheck: Use .cosa over COSA_DIR

---

src/app/rpmostree-builtin-ex.cxx

These commands use DBus so fall under the usual polkit usage,
there's no reason to hard require root.  I think this was a copy-pasta.

ex: Drop erroneous REQUIRES_ROOT flag on apply-live, initramfs-etc

---

Cargo.lock
Cargo.toml
rust/src/passwd.rs
rust/src/treefile.rs

This adds treefile support for both `check-passwd` and `check-groups`
entries with "type: data".
/cc @jlebon

rust/treefile: add support for check-passwd/groups data entries

---

rust/rpmostree-client/src/lib.rs
rust/rpmostree-client/tests/parse.rs

Add more metadata that zincati needs, like `base-commit-meta`
which includes the `fedora-coreos.stream` key and the cosa basearch,
etc.
Also `Derive(Debug)` since it's used in a cache struct that also
derives debug, and that's a friendly thing to do in general.

rust/client: Extend with more metadata for zincati

---

rust/rpmostree-client/src/lib.rs
rust/rpmostree-client/tests/parse.rs
rust/src/testutils.rs

rust/client: Add a CliClient with agent ID, require for status
In prep for adding more methods, require the caller to identify
themselves.
For now this is `CliClient` - one could imagine in the future
we actually do direct DBus, but there's a whole other world
of stuff there.
---
rust/client: Add methods to find/require booted deployment
This is a common need.
---
rust/client: Add Deployment/get_base_commit() API
Zincati wants this.
---
client: Add API to fetch base commit metadata
Also desired by Zincati.
---

More client api

---

src/app/rpmostree-override-builtins.cxx

It's always nice when apps provide useful hints about other commands you
may be interested in.
For instance, if they've done `rpm-ostree override replace/remove`,
let's be helpful and tell users that they can use `rpm-ostree override
reset` to unpin packages.

app/override: Hint at `rpm-ostree override reset`

---

rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-tree.cxx
tests/compose/test-basic-unified.sh

In this case, let's default to the tip of the tree ref.
Closes: #2633

compose/extensions: Handle no --base-rev

---

rust/src/daemon.rs
src/daemon/rpmostreed-deployment-utils.cxx

These are "base ostree" things we can move into the Rust
function.

daemon: Move a bit more deployment-variant code to Rust

---

rust/src/lib.rs
rust/src/lockfile.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-core-private.h
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h
tests/compose/test-lockfile.sh

In FCOS, we use "override" lockfiles to pin packages to certain
versions. Right now, we have separate overrides for each base arch we
(eventually want to) support. But that makes maintaining the overrides
cumbersome because of all the duplication.
Let's allow lockfiles to specify only the `evr` of a package, which is
just as good for FCOS, and means that we'll only have to maintain a
single override file for all the architectures.

lockfile: Allow specifying EVR rather than EVRA

---

rust/src/countme/repo.rs
rust/src/cxxrsutil.rs
rust/src/history.rs
rust/src/testutils.rs

Addresses review comment from
https://github.com/coreos/rpm-ostree/pull/2649#discussion_r591784574
and extends it in a few more random places I found that were
using `with_context()`.

rust: Support context attribute on CxxResult, use it more

---

docs/apply-live.md

Continuing the more docs momentum.

docs: Add apply-live

---

rust/src/builtins/apply_live.rs
tests/kolainst/destructive/apply-live

If all we're doing is layering new packages, no need to tell
the admin that things may need restarting.

live: Don't output "services restart" for pure package additions

---

rust/src/daemon.rs
tests/kolainst/nondestructive/misc.sh

It turns out there's a naming clash between `to_string()` here in
Rust *and* introspection is incorrectly associating the method
with `ostree::Deployment` because of the naming prefix.

daemon: Fix serialization of unlocked state

---

rust/src/composepost.rs
rust/src/lib.rs
src/libpriv/rpmostree-postprocess.cxx
src/libpriv/rpmostree-postprocess.h

The ugly C code for this turns into shorter Rust with a unit
test, a lot less allocation (notice how we don't malloc `NUL` terminated
strings in so many places).

Oxidize postprocessing `altfiles` addition to `/etc/nsswitch.conf`

---

rust/src/daemon.rs
rust/src/lib.rs
rust/src/variant_utils.rs
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-util.cxx

Prep for more oxidation work.  One notable improvement here is that about half
of the callers of the mega function `rpmostree_deployment_get_layered_info`
only wanted the base information, not the layered package lists
for example - so we were passing 4 `NULL`s to ignore those.
This Rust API returns a simple shared struct instead for those
cases.  I also changed things so that `base_commit` is always
set, avoiding the callers needing to do that.

Move some small daemon layering lookup into Rust

---

rust/src/composepost.rs
rust/src/cxxrsutil.rs
rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-rojig.cxx
src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-composeutil.cxx
src/app/rpmostree-composeutil.h
src/libpriv/rpmostree-bwrap.cxx
src/libpriv/rpmostree-bwrap.h
src/libpriv/rpmostree-postprocess.cxx

Move high level bwrap postprocess interface to C++
A future patch will then expose this interface via cxxrs, allowing
us to port more of the postprocess.cxx code to Rust.
---
postprocess: Move script execution to Rust
Continuing oxidation.
---
postprocess: Move add-files handling to Rust
Port add-files handling to Rust.
Note that there's one very magical line of diff here worth calling out:
We dropped an interface from the cxxrs bridge, because both sides
are now Rust!  The treefile code can directly return an `&mut File` reference
instead of needing to pass the raw fd as `i32`.
---
postprocess: Move treefile externals sanitycheck to Rust
This code really makes sense as a method on the treefile.
And when that's done, we no longer need to expose
`get_postprocess_script()` via cxx, so we …

Various postprocess oxidation patches

---

rust/src/isolation.rs
rust/src/lib.rs
rust/src/live.rs

I was thinking about privilege separation today with
systemd units, and that led me to the problem of "lifecycle binding".
We really want e.g. `systemctl stop rpm-ostreed` to kill any
separate systemd units we're managing.
systemd already has a mechanism for this with `BindsTo=`.
And then I realized we weren't doing this for the systemd-tmpfiles
invocations in the `live.rs` code.
Generalize this into a small `isolation` module that fixes this
and several other things at the same time.  I'd like to build
on this to further improve our multi-process isolation story
later.
---

rust: Introduce systemd-run based isolation mod, use in live

---

Makefile-daemon.am
Makefile-rpm-ostree.am
packaging/rpm-ostree.spec.in
rust/src/countme.rs
src/daemon/rpm-ostree-countme.service.in
src/daemon/rpm-ostree-countme.timer
src/daemon/rpm-ostree.conf

Remove rpm-ostree sysusers config
---
countme: Refuse to run as root
We do not need root privileges and should only be started via the system
service unit so avoid mistake by verifying that on startup.
---
rpm-ostree-countme.timer: Fix AccuracySec and add OnBootSec
* Use OnBootSec=5m to give a chance for the timer to trigger on the
first week the system is booted up.
* Use '1s' for AccuracySec as this is accurate enough for this use
case.
---
Install a temporary copy of rpm-ostree for unprivileged use
Install a copy of rpm-ostree as rpm-ostree-unpriv to get a `bin_t`
labeled binary as a temporary workaround for:
https://bugzilla.redhat.com/show_bug.cgi?id=1937404
Also modify the rpm-ostree count me service to use that binary.

Fixes for Count Me support

---

.github/workflows/rust-lints.yml
rust/src/ostree_utils.rs
rust/src/variant_utils.rs

I'd like to move `cargo fmt` checking out of Jenkins; among
other things, GH actions are *much* faster and nicer for this.
This leaves Jenkins to be more heavyweight testing.

ci: Add a Github Action for Rust lints

---

rust/src/composepost.rs
rust/src/lib.rs
rust/src/treefile.rs
src/libpriv/rpmostree-postprocess.cxx
tests/compose/test-mutate-os-release.sh

treefile: Add an allow(dead_code)
I assume this will be used soon.
---
compose: Move mutate-os-release string code to Rust
More classic C string manipulation which is much nicer in Rust
---
compose: Move `remove-files` code to Rust
More oxidation.
---

More postprocess rs 3

---

Cargo.lock

To pull in https://github.com/tailhook/openat/pull/36
so we can update libc.

Cargo.lock: Bump openat

---

rust/src/composepost.rs
rust/src/lib.rs
rust/src/treefile.rs
src/libpriv/rpmostree-bwrap.cxx
src/libpriv/rpmostree-bwrap.h
src/libpriv/rpmostree-postprocess.cxx

Required binding a bit more of the bwrap bits.

postprocess: Migrate `mutate-os-release` to Rust

---

rust/ostree-host/Cargo.toml
rust/ostree-host/LICENSE-APACHE
rust/ostree-host/LICENSE-MIT
rust/ostree-host/README.md
rust/ostree-host/src/binding_fixes.rs
rust/ostree-host/src/lib.rs
rust/ostree-host/src/sysroot_ext.rs
rust/src/builtins/apply_live.rs
rust/src/live.rs

rust/ostree-host: Add SysrootExt trait
This currently just adds a reimplementation of a new API that's
already in C upstream, but the plan is to add more Rust-only APIs in
the future here.
---
rust/ostree-host: Add README.md and license files
In preparation for splitting to a new repo.
---

More ostree sys

---

rust/src/lib.rs
rust/src/lockfile.rs
src/libpriv/rpmostree-core.cxx
tests/compose/test-lockfile.sh

Right now if we want to lock e.g. systemd, we need to specify every
subpackage of systemd that we use. This is a lot of duplication because
in the majority of cases, what we really mean is "lock at this build of
systemd".
Since RPMs bake in the source RPM they were built from, we can use this
to lock packages more succinctly. See the testcase and #2676 for
examples of how this looks.
Closes: https://github.com/coreos/rpm-ostree/issues/2676

lockfile: Allow locking by source RPM EVR

---

docs/countme.md

Reword the documentation in light of recent discussions.
I'll open an issue with libdnf for the work to add a way to disable countme support from the API in order to avoid the second issue.

docs: Update instructions to disable countme

---

src/app/rpmostree-clientlib.cxx
tests/kolainst/destructive/apply-live

In general our error handling philosophy is "errors are strings".
Previously (before C++) we were relying on calling this API
to strip out the GDBus remote error message.
In the recent refactoring of clientlib to expose the txn APIs
to Rust via C++, we implicitly lost that because the C++
wrapper API throws an exception.
Add a copy of the remote error stripping here.  Eventually
it will likely make sense for it to *only* be here instead
of also in `main.cxx`, but one thing at a time.

clientlib: Strip GDBus remote error before throwing exception

---

src/libpriv/rpmostree-bwrap.cxx
src/libpriv/rpmostree-bwrap.h
src/libpriv/rpmostree-scripts.cxx

Port away from a generic child setup function towards more standard
APIs for setting up fd streams.  Prep for oxidizing rpmostree-bwrap.cxx
because cxx-rs doesn't support passing callbacks from C++ to Rust.

bwrap,scripts: Add and use cleaner APIs for standard descriptors

---

src/app/rpmostree-compose-builtin-tree.cxx

[As suggested by](https://github.com/coreos/rpm-ostree/pull/2693#discussion_r600839336) @jlebon in #2693 I've updated the man-page entry with the provided diff.

Fix ambigous compose postprocess man entry

---

rust/src/isolation.rs
rust/src/lib.rs
rust/src/utils.rs
src/libpriv/rpmostree-scripts.cxx
src/libpriv/rpmostree-util.cxx
src/libpriv/rpmostree-util.h

Use it instead of detecting the journal; we *could* do that
by checking the `JOURNAL_STREAM` variable:
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#%24JOURNAL_STREAM
But, really none of our code cares about this today;
anyone running `rpm-ostree compose tree` under e.g.
`systemd-run` can keep both pieces.

Add a helper API to detect running in systemd

---

docs/RELEASE.md
packaging/rpm-ostree.spec.in

In the latest release, we should've bumped librepo's requirement. It
doesn't use symbol versioning, so we don't automatically get this. At
release time at least, we should just peek at the spec we're baking in
and pick up from that.
Clearly the updated deps are in the buildroot if CI is green, so this
should mostly be a matter of bumping to versions which are already
shipped in Fedora.
See: https://github.com/rpm-software-management/libdnf/pull/1128
See: https://github.com/coreos/rpm-ostree/pull/2644
See: https://bugzilla.redhat.com/show_bug.cgi?id=1943773

RELEASE: Add step to update libdnf's deps

---

src/app/rpmostree-compose-builtin-tree.cxx

I did at one point look at converting this stuff into a C++
object but that led in to a whole rathole around a C++ `GObject<>`
smart pointer like glibmm has.  But that would take over the code
and it's better to just port to Rust.

compose: Fix leak of Rust treefile object

---

rust/src/core.rs
rust/src/lib.rs
src/daemon/rpmostree-sysroot-upgrader.cxx
src/libpriv/rpmostree-postprocess.cxx
src/libpriv/rpmostree-postprocess.h

Since it's called from both client and compose side, it should be
in core.  Migrate to Rust too.

Migrate `depmod` helper to core.rs

---

src/libpriv/rpmostree-json-parsing.cxx
src/libpriv/rpmostree-json-parsing.h

This removes some JSON-handling helper methods which are not used
anymore. All the consumers have been moved to directly use the
treefile logic in Rust in the meanwhile.

libpriv/json-parsing: remove dead code

---

rust/src/lib.rs
rust/src/utils.rs
rust/src/variant_utils.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-db-builtin-diff.cxx
src/app/rpmostree-db-builtin-list.cxx
src/daemon/rpmostreed-deployment-utils.cxx
tests/compose/test-basic-unified.sh

There are a lot of use cases for this, notably:
- This allows us to display advisories without fetching updateinfo
metadata in the pure OSTree case.
- It allows pipelines to fetch and display this information to
sanity-check builds (and then into user-facing release notes).
- It makes it much easier to fix the "intermediate CVEs" issue described
in https://github.com/coreos/rpm-ostree/issues/1696#issuecomment-443861107.
This patch just adds the advisory information to the commit metadata.
There's follow-up work to make the client-side of rpm-ostree use this
data. Also, for pipelines, we leave it to higher level tools like cosa
to calculate the "advisory diff" like it does for the package diff for
example.
Closes: #1696

Bake advisory information into commit metadata

---

rust/src/composepost.rs
rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-composeutil.cxx
src/libpriv/rpmostree-postprocess.cxx
src/libpriv/rpmostree-postprocess.h

Previously we carefully ported functionality bit by bit here.
Now take the last step and move it all in to Rust.
A reason I didn't do this in one go before is around the
incredibly twisted handling of the `/etc` vs `/usr/etc`.
I think longer term we should aim to basically have all
of our code keep it as `/etc` up until the very end.  For
now we just do a rename dance around some of the add/remove
files code.

postprocess: Move more code into Rust

---

Makefile-tests.am
tests/check/test-lib-introspection.sh

Even more fallout of the buildroot change to stop deriving from
cosa.  The new buildroot doesn't have `pygobject3`.
We could convert this to an installed test but...blah.
Not worth it.

tests: Stop running test-lib-introspection.sh

---

rust/rpmostree-client/src/lib.rs
rust/src/testutils.rs

In trying to use the API in ostree's tests, this feels like an obvious
change.

rust/client: Make status be a method

---

src/app/libmain.cxx

Let's make this more obvious - in particular today I ran
a command in the wrong terminal and the error made me pause
for a second.

client: Provide more useful error if we're in a container

---

src/libpriv/rpmostree-postprocess.cxx

Remove the unnecessary builder causing memory leaks like this one:
Direct leak of 8 byte(s) in 1 object(s) allocated from:
#0 0x7f60bd2fe3cf in __interceptor_malloc (/lib64/libasan.so.6+0xab3cf)
#1 0x7f60bca6cbb8 in g_malloc (/lib64/libglib-2.0.so.0+0x5bbb8)
#2 0x7f60bcaa54f2 in g_variant_type_copy (/lib64/libglib-2.0.so.0+0x944f2)
#3 0x7f60bcaa3384 in g_variant_builder_init (/lib64/libglib-2.0.so.0+0x92384)
#4 0x55e5bb3120d3 in filter_xattrs_cb src/libpriv/rpmostree-postprocess.cxx:1493
#5 0x7f60bc89cb38  (/lib64/libostree-1.so.1+0x49b38)
#6 0x7f60bc8a5e1a  (/lib64/libostree-1.so.1+0x52e1a)
#7 0x7f60bc8a622b in ostree_repo_write_dfd_to_mtree (/lib64/libostree-1.so.1+0x5322b)
#8 0x55e5bb307e6e in write_dfd_thread src/libpriv/rpmostree-postprocess.cxx:1551
#9 0x7f60bca92401 …

libpriv: Remove unnecessary builder causing memory leak

---

rust/src/treefile.rs
src/libpriv/rpmostree-core.cxx

core: Fix the "is_system" variable
The intention here was to distinguish between server composes
and client side layering.  But that doesn't work today because
we we call`_new_system()`; probably a result of refactoring.
Doesn't matter too much because we only checked it to
throw an error if we failed to load the policy.
And now add a check for `is_system` instead of checking whether
a treefile is present.
This is prep for converting the origin to a treefile and
using that as our standard format.
---
treefile: Make all members pub(crate)
We've been doing this piecemeal so far, let's do it all at once
now.  Prep for converting origin files to treefiles in `origin.rs`.
---
treefile: derive(Default)
So that it's easy to construct without deserializing.  Prep
for converting from origins.
---

Treefile client prep

---

src/libpriv/rpmostree-postprocess.cxx

This adds support for a treefile "xattr-translation" dictionary, and
will then translate extended attributes when they are committed into the
ostree commit.
This can be used for example to translate "user.ima" (which is a common
attribute used by for example ima-evm-utils) to "security.ima", which
would require root permissions to write to during compose. Add the
following to a treefile to achieve this:
```
xattr-translation:
user.ima: security.ima
```
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

Support xattr translation

---

rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-composeutil.cxx
src/app/rpmostree-composeutil.h
src/libpriv/rpmostree-core-private.h
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h

Related to https://github.com/coreos/rpm-ostree/issues/2665
By getting rid of the "treespec" we remove one of our intermediate formats in favor of the treefile.
Depends https://github.com/coreos/rpm-ostree/pull/2737

Patches to drain treespec -> treefile

---

src/app/rpmostree-compose-builtin-rojig.cxx
src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-ex-builtin-rojig2commit.cxx
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h

core: Rename context_new_system() to context_new_client()
Makes the intention clearer.
---
core: Rename context_new_tree() to context_new_compose()
Makes the intention clearer.
---

core: Two minor API cleanups

---

Makefile.bindings

We need to do the same `cmp` dance for the generated `.cxx` file
as for the source, because `make` only works on timestamps.
Currently every time one edits the rust code and types `make`
we end up re-building that object, which also forces a re-link
of the `librpmostreeinternals.la` library.

build-sys: Avoid re-building + re-linking cxx-rs C++ bits each build

---

.gitignore

And roughly split the file into build system things and "owned" test
things.

.gitignore: add compose-{cache,logs} dirs

---

docs/countme.md
src/libpriv/rpmostree-core.cxx

Make sure that we do not use the internal Count Me logic in DNF in
rpm-ostree as we have our own external implementation that is aware of
the different behavior regarding repo handling.
See also the discussions in:
- https://github.com/rpm-software-management/libdnf/issues/1174
- https://github.com/rpm-software-management/libdnf/issues/1068
- https://github.com/coreos/rpm-ostree/pull/2671

countme: Force disable Count Me logic in DNF

---

src/app/rpmostree-compose-builtin-rojig.cxx
src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-ex-builtin-rojig2commit.cxx
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h

A further cleanup, I noticed these functions never throw an
error, and we weren't consistently checking for one anyways.

core: Remove cancellable/error from context creation APIs

---

rust/src/daemon.rs
tests/kolainst/nondestructive/misc.sh

It's an important property, and it's more self-documenting if we
always emit the value rather than only when it's `true`.

daemon: Always write `staged` JSON field

---

rust/src/passwd.rs

We need to handle the case where no previous commit exists. This is
expressed from the C side by passing the empty string.
We're currently not testing this, though... AFAIK no distro uses this
right now anyway and hopefully we simplify a lot of this when we move to
systemd-sysusers!
Fixes: #2580
Fixes: #2769

rust/passwd: Fix handling of `previous` mode

---

rust/src/bwrap.rs
rust/src/core.rs

bwrap: Fix selftest to be truly immutable
We should never have any effect on the host system, so let's
use the more direct APIs which allow us to use the immutable
flag, don't mount `/var` etc.
Crucially this also avoids us running through the tempetc
guard which would try to rename `usr/etc` which can trigger
on an ostree based host.
Closes: https://github.com/coreos/rpm-ostree/issues/2771
---
core: Fix tempetc guard to be no-op if /etc exists
This is further hardening to prevent a situation like
https://github.com/coreos/rpm-ostree/issues/2771
where we would crash on an ostree-based host that has both
`/etc` and `/usr/etc` as physical directories.
That shouldn't happen after the bwrap fix, but we might
as well be more correct here.
---

Two bwrap /etc fixes

---

rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-rojig.cxx
src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-ex-builtin-rojig2commit.cxx
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h

Since in the future we'll operate on a treefile, move the callers
still using treespecs to an explicit API.  This is also clearer
because about half the callers were passing `NULL` for this anyways.

core: Split off a method to set the treespec

---

tests/compose/libbasic-test.sh

This adds some integration tests, covering symlinks injection logic.

tests/compose: check symlinks injected into the rootfs

---

src/app/rpmostree-builtin-kargs.cxx
src/daemon/rpmostreed-transaction-types.cxx
tests/vmcheck/test-kernel-args.sh

add them to the variant in rpmostree_builtin_kargs
update a condition to include the new switches

kargs: add CLI switches --append-if-missing and --delete-if-present

---

rust/src/bwrap.rs
rust/src/composepost.rs
rust/src/lib.rs

Followup to https://pagure.io/fedora-infrastructure/issue/9909
In the refactor we were passing `unified_core: true` unconditionally which was wrong,
as that implies using fuse.  Anyways what we really want here is an immutable bwrap
and not `rofiles-fuse` annyways.  So refactor things to use that.
From https://kojipkgs.fedoraproject.org//work/tasks/7579/66867579/runroot.log
```
fuse: device not found, try 'modprobe fuse' first
fuse: device not found, try 'modprobe fuse' first
bwrap: execvp realpath: No such file or directory
fusermount: failed to unmount /tmp/rpmostree-rofiles-fuseAAphRY: Invalid argument
fusermount: failed to unmount /tmp/rpmostree-rofiles-fuseSCLs24: Invalid argument
error: Updating os-release with commit version: Running realpath: bwrap(realpath): Child process killed …
```

Fix bwrap usage for mutate-os-release

---

rust/src/composepost.rs

The `AT_SYMLINK_NOFOLLOW` flag for chmod was not implemented in glibc
until very recent releases (v2.32 in 2020-08).
Before that version, passing this flag will always result in `ENOTSUP`.
Refs:
* https://github.com/bminor/glibc/blob/glibc-2.31/sysdeps/unix/sysv/linux/fchmodat.c#L36
* https://github.com/bminor/glibc/blob/glibc-2.32/sysdeps/unix/sysv/linux/fchmodat.c

composepost: fix fchmod flags for tmpdir (glibc compat)

---

src/app/rpmostree-compose-builtin-tree.cxx

The goal is to make this increasingly annoying until consumers port.

compose: Bump timeout for non-unified-core to 10s

---

src/lib/rpmostree-package.c
tests/vmcheck/test-db.sh

`rpmvercmp()` doesn't properly compare full EVR. It needs to
be given the Version and Release separately in order to do
a comparison. For example `rpmVersionCompare()` first calls
`rpmvercmp()` to compare the Version and then checks the Release
in a second call to `rpmvercmp()`.
https://github.com/rpm-software-management/rpm/blob/35739c2a2298e61caacb45157706bf342ffcd20e/lib/headerutil.c#L434-L440
Let's just use `rpmverCmp()` instead, which can do the full
EVR comparison.
Fixes: https://github.com/coreos/rpm-ostree/issues/2668

lib/package: Fix rpm version comparison

---

src/daemon/rpmostreed-daemon.cxx

This slightly reduces DBus traffic on nodes as we don't really need
to update systemd status more often than that.

daemon: Only update idle status every 10 seconds

---

rust/src/composepost.rs
rust/src/lib.rs
src/libpriv/rpmostree-postprocess.cxx

This ports the timestamp updating logic which serves as a workaround
for SELinux leaking host details.

composepost: move SELinux workaround logic to Rust

---

rust/src/composepost.rs
rust/src/lib.rs
src/libpriv/rpmostree-postprocess.cxx

This ports the rpmdb hardlinking logic which serves to maintain
a coherent single source of truth across tools.

composepost: move rpmdb linking logic to Rust

---

docs/treefile.md
rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-core.cxx
tests/compose/test-basic-unified.sh
tests/compose/test-basic.sh

This addresses the server compose side of
#2584.
One tricky bit is handling overrides across included treefiles (or
really, even within a single treefile): as usual, higher-level treefiles
should override lowel-level ones. Rust makes it pretty nice to handle.
For now this just supports a `repo` field, but one could imagine e.g.
`repos` (which takes an array of repoids instead), or e.g.
`exclude-repos`.
The actual core implementation otherwise is pretty straightforward.
This should help a lot in RHCOS where we currently use many `exclude=`
directives in repo files to get it to do what we want.
This is also kind of a requirement for modularity support because as
soon as rpm-ostree becomes modules-aware, modular filtering logic will
break composes which assume rpm-ostree treats modular and …

treefile: Add new `repo-packages` field for pinning packages to repos

---

Cargo.lock
Cargo.toml
rust/src/composepost.rs
rust/src/initramfs.rs

ostree hard requires UTF-8 paths (and really we should
never have any non-UTF-8 paths in the OS in general).  The
camino library has types that are both `Path` and `&str` and
has a convenient `try_into()` too to avoid us duplicating
the error handling.

Add and use the `camino` library for UTF-8 paths

---

rust/src/treefile.rs

We're using `kebab-case` so serde translates capitalized letters like
`BDB` as `b-d-b`, which is not what we want here.

treefile: Fix rpmdb backend casing

---

Makefile-rpm-ostree.am
src/daemon/rpm-ostree-countme.service.in

The SELinux policy change has been merged and released upstream.
This reverts: 5d5ccf01 Install a temporary copy of rpm-ostree for unprivileged use
I need to check if we should keep this for RHEL while the policy gets updated.

countme: Drop SELinux workaround/unpriv copy of rpm-ostree

---

rust/src/lockfile.rs

This field will allow humans to shove additional structured metadata
into lockfiles which could then be used by higher-level tools.
See: coreos/fedora-coreos-config#965

lockfile: Allow `metadata` field in locked packages

---

src/app/rpmostree-builtin-deploy.cxx
src/daemon/org.projectatomic.rpmostree1.xml
src/daemon/rpmostreed-transaction-types.cxx
tests/vmcheck/test-misc-2.sh

In Fedora CoreOS, updates are driven by Zincati and we thus completely
trust the information it gives us. The branch validation rpm-ostree does
is thus not necessary. It's also harmful in the case where the node is
extremely out of date because it may not be able to GPG verify the
commit at the tip of the branch (because the GPG key isn't yet in the
tree).
See: https://github.com/coreos/fedora-coreos-tracker/issues/749

app/deploy: Add --skip-branch-check

---

configure.ac
packaging/rpm-ostree.spec.in

This is mostly a bugfix release, with a few new user-facing features.
Kernel arguments can now be updated in an idempotent fashion, via the new `kargs` flags `--append-if-missing` and `--delete-if-present`.
It is now possible to skip on-branch checks when deploying a specific revision by commit hash. This will be used by Zincati in Fedora CoreOS.
The Count Me feature from DNF is now fully disabled by default in all repo queries and will only be triggered by the corresponding `rpm-ostree-countme.timer` and `rpm-ostree-countme.service` units. See https://coreos.github.io/rpm-ostree/countme/ for details.
Among notable changes, the post-processing logic now understands the IMA extended attribute `user.ima`. When such xattr is found, it is automatically translated to `security.ima` in the …

Release 2021.5

---

rust/src/passwd.rs
tests/compose/libbasic-test.sh

This matches the default from the RPM, and we don't want
the file to be writable if an admin adds a user to the `root`
group.  (Which IMO is just a bad idea, but
for historical reasons OpenShift suggests this for
images
https://docs.openshift.com/container-platform/4.7/openshift_images/create-images.html#images-create-guide-openshift_create-images
for example)

passwd: Make default perms 0644

---

Cargo.lock
Cargo.toml
rust/src/container.rs
rust/src/lib.rs
rust/src/main.rs
tests/kolainst/destructive/ex-container

This new `rpm-ostree ex-container` CLI is just code copied
from the `ostree-ext-cli container` binary code.  In the future
I may just add the CLI code as a library API too to simplify this.
For now, I don't want to try to add a new Rust CLI as an RPM
package for example.  This exposes it via rpm-ostree, and
in the future rpm-ostree may have some layering on top of this
anyways.

Update to ostree-ext v0.1.2, add new `ex-container` command

---

src/daemon/rpmostreed-daemon.cxx
src/daemon/rpmostreed-daemon.h
src/daemon/rpmostreed-sysroot.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/daemon/rpmostreed-utils.cxx
src/daemon/rpmostreed-utils.h

Alternative to https://github.com/coreos/rpm-ostree/pull/2845
which moved the `reboot` invocation into the client (which I think
still makes sense in some cases).
Previously we were starting the reboot before we're returned
a success reply to the client, so it could see the daemon killed
by `SIGTERM` and hence emit a spurious error.
(Really in this case any 3 of the calling process, the client
binary or the daemon could be killed in any order, so it's messy
but this just closes one race)
For cleanliness we reject starting any new transactions after the daemon has
started a reboot.
Closes: https://github.com/coreos/rpm-ostree/issues/1348

daemon: Make actually initiating reboot asynchronous

---

configure.ac
rust/src/lib.rs
rust/src/origin.rs
rust/src/treefile.rs
src/app/rpmostree-builtin-rebase.cxx
src/app/rpmostree-builtin-status.cxx
src/app/rpmostree-compose-builtin-tree.cxx
src/daemon/rpmostree-sysroot-core.cxx
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-core-private.h
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h
src/libpriv/rpmostree-importer.cxx
src/libpriv/rpmostree-importer.h
src/libpriv/rpmostree-origin.cxx
src/libpriv/rpmostree-origin.h
src/libpriv/rpmostree-rpm-util.cxx
src/libpriv/rpmostree-rpm-util.h

importer: Remove rojig bits
---
core: Remove rojig bits
Nothing uses this code now.
---
daemon/sysroot: Replace some rojig code with g_assert_not_reached()
Prep for removing the APIs entirely.
---
origin: Remove rojig bits
Nothing calls these now.
---
rust/origin: Remove rojig bits
Has never been used.
---
util: Remove rojig cache branch mapping functions
Not used.
---
rust/treefile: Remove rojig spec writing
One thing I realized is we need to keep the `rojig:` bit
in the treefile because we're (ab)using it in coreos-assembler
for image naming.
But we don't need the spec file generation bits, so that can go.
---
tree-wide: Remove (almost) all remaining rojig bits
The only part left that we will need to keep ~forever is
the treefile parsing `rojig:` because it's used by coreos-assembler. …

tree-wide: Remove (almost) all remaining rojig bits

---

rust/src/builtins/apply_live.rs
rust/src/testutils.rs
rust/src/variant_utils.rs

Trying to deduplicate this stuff there.

rust: Port some bits to new ostree_ext::variant_utils

---

ci/composepost-checks.sh
packaging/rpm-ostree.spec.in
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-postprocess.cxx
tests/kolainst/destructive/layering-local

I planned to use this as part of doing live diffs, e.g. to
notice the kernel changed between commits.
But also, at some point I'd like to add `ostree.architecture`
there to obsolete the cosa-specific `coreos-assembler.basearch`
so that multiple buildsystems and consumers can use that.
(That said, they can also just use `$(arch)` today)

Use new `ostree_commit_metadata_for_bootable()` API

---

Makefile-lib.am
configure.ac
packaging/rpm-ostree.spec.in
src/lib/rpmostree-package.c
src/lib/rpmver-private.c
src/lib/rpmver-private.h

This adds an internal temporary copy of the rpm version comparison
logic from librpmio (LGPL).
It allows relaxing the minimum library version to >= 4.14.
Ref: https://github.com/coreos/rpm-ostree/pull/2856#issuecomment-848785984

lib: temporarily fork rpmver logic

---

Cargo.lock
rust/src/container.rs

The new CLI-as-library lets us avoid reimplementing the CLI.

Update to ostree-ext 0.1.3

---

Makefile-lib.am

This excludes C source files (instead of headers) from the list of
source files scanned by gir.
It fixes the following error:
```
src/lib/rpmver-private.c:27: Error: RpmOstree: identifier not found on the first line:
* Split EVR into epoch, version, and release components.
```

makefile/lib: filter out private sources from gir list

---

rust/libdnf-sys/Cargo.toml
rust/libdnf-sys/build.rs

```
This tries to gracefully handle environments where gpgme
library cannot be directly discovered via pkg-config.
Older gpgme versions (including 1.13) do not provide a
.pc file, so in that case the build-script attempts to
fallback to hardcoded library flags.
```
---
```
This adds an optional dependencies on the `zck` library (zchunk),
and automatically forwards it to libdnf configuration.
It allows to gracefully degrade in older environments where zchunk
is not present, and also matches autoconf behavior.
```

libdnf-sys/build: compatibility fixes

---

src/daemon/rpmostreed-daemon.cxx
src/daemon/rpmostreed-daemon.h
src/daemon/rpmostreed-transaction-types.cxx
src/daemon/rpmostreed-utils.cxx
src/daemon/rpmostreed-utils.h
tests/common/libvm.sh
tests/vmcheck/test-misc-2.sh

Today, non-interactive processes, including rpm-ostree, are not
inhibited by systemd inhibitor locks. systemd 248 added the
`--check-inhibitors` option to `systemctl` commands, which can be
used to make non-interactive proccesses check for shutdown/sleep
inhibitors. However, it also checks for `delay` mode inhibitors,
which isn't what we want. Replicate this logic prior to reboots,
but ignore `delay` mode inhibitors.

daemon: Respect systemd inhibitor locks

---

rust/src/utils.rs
src/libpriv/rpmostree-util.cxx

util: Fix missing error in decompose_sha256_nevra
We can't just `return FALSE` here, we need to set an error.
Noticed by code inspection.
---
rust/utils: Fix ordering of decompose_sha256_nevra
The C API returns effectively a tuple in (nevra, sha256) order,
so let's have the Rust API do the same to avoid confusion.  Also
fix the broken test.
---

Two small sha256-nevra fixes

---

rust/src/isolation.rs

We expect to be able to re-run them.  This fixes an issue
where if `systemd-tmpfiles` failed, further `apply-live` invocations
would also fail.
Closes: https://github.com/coreos/rpm-ostree/issues/2877

daemon/isolation: Clean up failed units too

---

docs/CONTRIBUTING.md
docs/HACKING.md
docs/RELEASE.md
docs/apply-live.md
docs/architecture-core.md
docs/architecture-daemon.md
docs/architecture.md
docs/compose-server.md
docs/compose.md
docs/countme.md
docs/extensions.md
docs/index.md
docs/repo_structure.md
docs/treefile.md

This keeps the focus on user CLI docs first, then how to build images,
then how rpm-ostree works under the hood and finally how to contribute.
Preview at https://travier.github.io/rpm-ostree/compose/

docs: Split pages into three main categories

---

src/app/rpmostree-clientlib.cxx
src/daemon/rpmostreed-transaction-types.cxx

daemon/transaction: perform upfront null check on upgrader
This moves a null check on an sysroot upgrader instance, in order
to check pointer validity before dereferencing it.
The issue was detected by covscan.
---
app/clientlib: initialize bus_name
This initializes a string pointer which could otherwise be left
floating and passed around uninitialized.

Misc fixes for defects detected by static analysis

---

Cargo.lock
Cargo.toml
rust/src/fedora_integration.rs
tests/kolainst/destructive/layering-fedorainfra

Clément commented here:
https://github.com/fedora-infra/bodhi/issues/4175#issuecomment-765278242
but I missed it originally.  The Rust XML-RPC bindings
are pretty sane, just took some time reverse engineering what's
happening in the `koji download-build` code.

Drop use of koji redirector, use XML-RPC API

---

src/libpriv/rpmostree-origin.cxx
tests/vmcheck/test-layering-basic-2.sh

The idea originally was that we'd switch to `baserefspec` when
performing changes such that `ostree admin upgrade` would no longer
work.  But that has long since been buggy since the introduction
of things like `rpm-ostree initramfs --enable` etc.
The only goal of this PR is to avoid "leaking state" across
origin switches, so that the work to map origin ⇔ treefile
can also (correctly) be stateless.

origin: Switch baserefspec → refspec when de-layering

---

rust/src/cliwrap.rs
rust/src/cliwrap/yumdnf.rs
tests/kolainst/destructive/cliwrap

I've come to the conclusion that we need to be friendlier
to people who are transitioning from existing `yum/dnf`
systems.  Just saying `yum: command not found` is harsh.
And moreover, there are some things that IMO *should* work.
Let's take as an example: https://tailscale.com/download/linux/fedora
This is exactly an operating system extension; it doesn't
make sense in `toolbox` or `flatpak`.  (It *could* be containerized
but...let's leave that aside)
So following that, this provides a useful bit of information for
the `dnf install tailscale` part that will point people instead to
`dnf install-osextension tailscale`.  I think the basics of `dnf config-manager` should be
implemented here too.
Obviously, there's a *lot* more that could be done (and changed) here.  This
is just an initial …

cliwrap: Add initial yum/dnf wrapper

---

src/daemon/rpmostreed-transaction-types.cxx
tests/vmcheck/test-override-local-replace.sh

Now override replace <package> automatically resets the previous override for <package> and adds the new one in one transaction.
Closes #2828

daemon/deploy: Allow replacing existing overrides without first resetting

---

rust/src/composepost.rs
rust/src/daemon.rs
rust/src/lib.rs
src/daemon/rpmostreed-sysroot.cxx
tests/kolainst/nondestructive/misc.sh

Came out of seeing discussion from a non-public proprietary chat
system where a build system was incorrectly generating ostree commits
and had an empty `/var/lib/rpm`.
Without this the error is much less obvious, we end up triggering
an assertion failure due to an empty rpmdb.

daemon: Die if /var/lib/rpm exists and is not a symlink

---

src/libpriv/rpmostree-core.cxx

I'm currently getting an error from trying to run
`sudo env TMPDIR=/var/tmp TESTS=installroot ./tests/compose.sh` like:
`installroot: error: While applying overrides for pkg shadow-utils: xattrs: fsetxattr(security.selinux): Operation not supported`
And here it'd be useful to know which file it was.  This adds
error prefixing in both the actual error path as well as the path I thought it was.

core: Add error prefixing when applying rpmfi overrides

---

rust/src/core.rs
rust/src/lib.rs
src/libpriv/rpmostree-core.cxx

This fixes the immense spam of errors from `useradd` trying
to refresh the sssd cache in an `rpm-ostree compose tree`.
It doesn't work when sssd isn't running (as it won't be in a non-systemd container).
xref https://pagure.io/SSSD/sssd/pull-request/3959
I named the struct generically as I'd like in the future to
generalize this code to also do the systemctl wrapper, etc.

core: Neuter /usr/sbin/sss_cache during compose/layering

---

docs/administrator-handbook.md

- Drop Atomic Host reference, it's obsolete.
- Clarify `upgrade` semantics a bit more.

docs: Minor admin-handbook tweaks

---

rust/src/cliwrap/cliutil.rs
rust/src/cliwrap/yumdnf.rs

cliwrap/yumdnf: Indent rpm-ostree install info
So the text is clearly associated.
---
cliwrap: Unify yum/dnf+rpm message about ostree
This way we only have one message printed in both cases.
---
cliwrap/yumdnf: Remove duplicated print of IMAGEBASED
---
cliwrap/yumdnf: Fix up indentation
Old:
```
[root@cosa-devsh ~]# dnf install cowsay
Note: This system is image (rpm-ostree) based.
error: Note: This system is image (rpm-ostree) based.
Before installing packages to the host root filesystem, consider other options:
- `toolbox`: For command-line development and debugging tools in a privileged container
- `podman`: General purpose containers
- `docker`: General purpose containers
- `rpm-ostree install`: Install RPM packages layered on the host root filesystem.
Consider these "operating system …
```

Yumdnf tweaks

---

rust/src/core.rs
rust/src/lib.rs
src/libpriv/rpmostree-core.cxx

Right now we're just making filesystem changes if we're going
to be running scripts, so move the bits that temporarily remove
`sss_cache` into the conditional for (if layering).
And move the systemctl wrapper bits fully into Rust, which cleans
up the code too.

 core: Move systemctl interception into Rust, fix wrapping only for scripts

---

rust/src/composepost.rs
rust/src/lib.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h
src/libpriv/rpmostree-postprocess.cxx
src/libpriv/rpmostree-rpm-util.cxx

This is meant to address https://github.com/coreos/rpm-ostree/issues/2904, although completely fixing that bug also requires a patched libdnf.
---
builtin/tree: inject _dbpath macro file in postprocessing step
This wires the _dbpath macro injection logic to `compose postprocess`,
in order to make sure that the rpm configuration in the commit
matches the location of the rpmdb database.
---
libpriv/core: set _dbpath macro in dnf context
This ensures that the `_dbpath` macro is always in all dnf contexts,
in order to use the rpmdb under /usr.
Setting it explicitly makes sure that there is no logic implicitly
relying on host configuration. This is particularly relevant in
server-side compose cases, which are more likely to be running in
an environment without rpm-ostree macro file.
--- …

builtin/tree: misc fixes related to rpmdb location

---

tests/kolainst/Makefile
tests/kolainst/kolainst-build.sh

```
commit 29aa02449df38cc0e0974a66b0b983138dbfe328
Date:   Fri Jun 18 13:53:09 2021 -0400
tests/kolainst: Copy to rpm-repos/ last
Otherwise, if we fail to build e.g. an RPM because of some typo in the
script, `make` won't know to rerun it on the next invocation.
```
```
commit ea376f150900b6b5add5b8fb289be598bba1df3e
Date:   Fri Jun 18 13:54:52 2021 -0400
tests/kolainst: Add `make localinstall`
When hacking and testing locally with `cosa build-fast` and `kola run`,
I don't want to have to `sudo make install` the kola tests when e.g. I
didn't even e.g. `sudo make install` the built rpm-ostree. That way,
iterating doesn't touch the build environment and doesn't involve root
at all.
```

tests/kolainst: Various tweaks

---

rust/src/builtins/compose/commit.rs
rust/src/builtins/compose/mod.rs
rust/src/builtins/mod.rs
rust/src/lib.rs
src/app/rpmostree-compose-builtin-tree.cxx

This moves the commit-id writing logic to Rust, as a small incremental step
in porting the `compose` builtin.

builtin/compose: move commit-id write logic to Rust

---

rust/src/passwd.rs

This collapses the logging of new user/group entries into a single
message, in order to reduce the amount of log lines that are
emitted at compose time.
This is especially relevant for scratch composes, where all user and
group entries are net-new ones and in aggregate may result in a wall
of text.
It also fixes a typo for group entries, which were previously miscategorized.

passwd: reduce the amount of log messages for new entries

---

docs/HACKING.md
tests/vm.sh

This is a helper script I've had locally for a while that I cleaned up a
bit. It duplicates `cosa run` and some of `libvm.sh` which is originally
why I didn't push it. It sets up e.g. the SSH config and SSH keys just
right so that one can `make vmsync` afterwards.
Long-term I think we should fold that special sauce in `cosa run` with
switches and then wrap it around `make vmsync SPAWN=1` or something. But
for now, this should be helpful for other contributors.

tests/vm.sh: New script to make spawning test VMs easier

---

src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-postprocess.cxx

This introduces a couple of context prefixes in order to make some
error paths/outputs more useful to human readers.

compose: add some error prefixes

---

rust/src/cxxrsutil.rs
rust/src/lib.rs
rust/src/origin.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/libpriv/rpmostree-cxxrs-prelude.h
src/libpriv/rpmostree-origin.cxx
tests/compose/test-basic-unified.sh

The goal here is to move away from "origin" files and
centralize on "treefile" YAML as our standard declarative
representation.
To do this, add the key "derivation" fields to the treefile,
but error out if they're actually used on the compose side for now.
Eventually of course...there's nothing stopping us from supporting
`from:` on the compose side too.  But one step at a time.
---

Add derivation fields to treefile, map origin → treefile

---

packaging/rpm-ostree.spec.in

We hit "LLVM ERROR: out of memory" with LTO on 32 bit.
https://bugzilla.redhat.com/show_bug.cgi?id=1974927

spec: Disable LTO on 32 bit architectures

---

rust/src/cxxrsutil.rs
rust/src/lib.rs
src/libpriv/rpmostree-cxxrs-prelude.h

This adds bidirectional binding for `OstreeRepoTransactionStats`.
As this type is a plain C struct (not wrapped by GObject), it
also requires tweaking the auto-binding macro.
In particular, the intermediate pointer is now "const" in order
to cover this kind of cases which lack interior mutability. The
qualifier is anyway discarded by the final transmute.
Ref: https://github.com/coreos/rpm-ostree/pull/2928#discussion_r658332461

cxxrs: bind OstreeRepoTransactionStats

---

rust/src/cxxrsutil.rs
rust/src/importer.rs
rust/src/lib.rs
src/libpriv/rpmostree-cxxrs-prelude.h
src/libpriv/rpmostree-importer.cxx

This groups all the mode-tweaking logic in the importer, and moves
it to Rust.
---
Context: I'm trying to unify more of this logic with the server-side composing one. Currently hoping to meet in the middle in gio+rust land.

libpriv/importer: move mode-tweaking logic to Rust

---

src/app/rpmostree-builtin-start-daemon.cxx

This is a much smaller patch related to
https://github.com/coreos/rpm-ostree/pull/2932
which is about ensuring the client gets the actual errors instead
of generic DBus activation failure.
The obvious step then would be to have the client ask systemd
for the status text, but that's slightly messy right now and
I think I'd anyways prefer to go the socket route.
But I think this is a useful pattern; basically systemd's `StatusText`
facility is useful.

daemon: If we encounter a startup error, set it as our unit status text

---

rust/src/importer.rs
rust/src/lib.rs
src/libpriv/rpmostree-importer.cxx
tests/vmcheck/test-layering-basic-1.sh

This splits importer logic concerning path-filtering from the
one doing tmpfiles.d translation. The former is moved to Rust,
while the latter is left untouched here but could be later
unified with similar server-side composing logic already in Rust.
---
Context: I'm trying to unify more of this logic with the server-side composing one. Currently hoping to meet in the middle in gio+rust land.

libpriv/importer: move filtering logic to Rust

---

src/app/rpmostree-clientlib.cxx

Should pacify coverity thinking this is an infinite loop.
I believe this code was correct before - coverity just can't see the
indirect function call happening from `g_main_context_iteration()`.
By using atomics we're telling it another thread could be modifying
the value.

clientlib: Use atomics for mainloop completion

---

rust/src/origin.rs
rust/src/treefile.rs
tests/compose/test-basic-unified.sh

This clears the `from` keyword for containers as a base, and
aligns the treefile term more closely with the existing
origin field.

treefile: Rename `from` to `base_refspec`

---

rust/src/builtins/apply_live.rs
rust/src/lib.rs
src/app/rpmostree-clientlib.cxx
src/app/rpmostree-pkg-builtins.cxx
src/daemon/org.projectatomic.rpmostree1.xml
src/daemon/rpmostreed-transaction-types.cxx

Since we stabilized the CLI interface `rpm-ostree install -A`, we need
to stabilize the DBus interface as well.  This hence
Closes: https://github.com/coreos/rpm-ostree/issues/2875
Further, by moving this to one transaction we can drop the
incorrect "Run systemctl reboot" line.  While we have the patient
open, also change it to clarify in the non-live case that the
changes are queued.

Stabilize `apply-live` flag for deploy, use in `rpm-ostree install -A`

---

rust/src/client.rs
rust/src/lib.rs
src/app/rpmostree-clientlib.cxx
tests/kolainst/nondestructive/misc.sh

This is a hackier an alternative to https://github.com/coreos/rpm-ostree/pull/2932
that we can ship immediately because we won't block on SELinux policy.
For historical reasons, the daemon ends up doing a lot of
initialization before even claiming the DBus name.  For example,
it calls `ostree_sysroot_load()`.  We also end up scanning
the RPM database, and actually parse all the GPG keys
in `/etc/pki/rpm-gpg` etc.
This causes two related problems:
- By doing all this work before claiming the bus name, we
race against the (pretty low) DBus service timeout of 25s.
- If something hard fails at initialization, the client can't
easily see the error because it just appears in the systemd
journal.  The client will just see a service timeout.
By explicitly using `systemctl start …

client: Explicitly `systemctl start rpm-ostreed` if root, dump status

---

Cargo.lock
Cargo.toml
rust/src/composepost.rs
rust/src/importer.rs
rust/src/lib.rs
rust/src/utils.rs
src/app/libmain.cxx
src/app/rpmostree-builtin-status.cxx
src/libpriv/rpmostree-importer.cxx
src/libpriv/rpmostree-util.cxx
src/libpriv/rpmostree-util.h

This deduplicates the low level tmpfiles.d translation logic
between client- and server-side codepaths, moving it to Rust
and using gio helpers.

importer: unify tmpfiles.d translation logic

---

rust/src/composepost.rs
rust/src/importer.rs
src/libpriv/rpmostree-importer.cxx

This adds some unit tests for tmpfiles.d translation logic, and
moves newline handling to the calling sites.
Ref: https://github.com/coreos/rpm-ostree/pull/2942#discussion_r661844890

importer: add unit tests for tmpfiles.d translation

---

rust/src/lib.rs
rust/src/treefile.rs
src/daemon/rpmostree-sysroot-upgrader.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h

Part of https://github.com/coreos/rpm-ostree/issues/2947
This makes the core code temporarily uglier, but when we
remove treespec all the conditionals and duplication drop out.

Use treefile instead of treespec for local layering

---

src/libpriv/rpmostree-core.cxx

core: Remove ignore-scripts check
This hasn't been used since 325ee354e9b88c62322949bea14f679dc76164f6 ("core/scripts: Drop support for ignore-scripts")
from `CommitDate: Tue Jul 18 19:21:15 2017 +0000`.
---
core: Remove skip-sanity-check treespec support
As far as I can tell, nothing ever actually set this.  I think
I added it out of an excess of conservatism, perhaps intending
that the flag could be set somewhere.
But because the treespec is an internal only API, it can't be
set.
We really do always want these checks, so just delete the code
that tries to support disabling them.
---

Drop dead treespec bits

---

rust/src/lib.rs
rust/src/treefile.rs
src/libpriv/rpmostree-util.h

treefile: Add an API to generate an empty config
Prep for switching the core over to treefile only.  Today
we use "empty treespec", after this we'll use "empty treefile".
---
util: Add an API to convert `char **` → `rust::Vec<rust::String>`
Since this occurs a fair bit in our code.
---

two minor prep patches for treespec removal

---

rust/src/extensions.rs
rust/src/lib.rs
rust/src/treefile.rs

Prep for dropping treespec.  This way we can just pass
down the config we need to the core.
Currently the C++ extensions code hand rolls this basically.

extensions: Add a method to convert to treefile

---

src/app/rpmostree-composeutil.cxx
src/libpriv/rpmostree-core.cxx

Part of removing the treespec: https://github.com/coreos/rpm-ostree/issues/2947

compose,core: Read exclude-packages directly from treefile

---

src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h

The extensions code is doing something that's not a compose or
a client operation (i.e. it's not doing treefile -> ostree commit).
Another way to look at it is it's using this as a thin wrapper
on top of raw libdnf.
Split off a low level API to create a context and separately
set the cachedir.
This is prep for removing treespec.

core: Split out low level creation method

---

src/daemon/rpmostreed-os.cxx
src/daemon/rpmostreed-transaction-types.cxx

Set transaction titles before setting `rpmostreed_sysroot_set_txn()`
so that we don't display a spurious `(null)` transaction if a the
current transaction title is queried before the current transaction
actually executes; for example, if a second transaction is attempted
immediately after starting the first transaction, previously,
rpm-ostree will print `error: Transaction in progress: (null)`.

daemon: Set transaction title earlier

---

src/daemon/rpmostreed-os.cxx
src/daemon/rpmostreed-sysroot.cxx
src/daemon/rpmostreed-sysroot.h

This is a follow up cleanup commit to
https://github.com/coreos/rpm-ostree/pull/2973.

os: Factor out `rpmostreed_sysroot_set_txn_and_title()`

---

rust/src/lib.rs
src/app/rpmostree-builtin-rebase.cxx
src/app/rpmostree-builtin-status.cxx
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h
src/libpriv/rpmostree-origin.cxx
tests/kolainst/nondestructive/misc.sh
tests/vmcheck/test-pinned-commit.sh

This mainly undoes
https://github.com/coreos/rpm-ostree/commit/2c270a6644810c9fb5956b02a74abc4ef277ef74,
and follows up on https://github.com/coreos/rpm-ostree/pull/2842/.
Also serves as some cleanup to make way for the introduction of a
new `container-image-reference` refspec type.
We no longer have any use for `ostree://` or `rojig://`-style
prefixes in the refspecs. There had been efforts to "canonicalize"
refspecs to always include such prefixes into the code internally,
but that hasn't gotten too far. Crucially, since such prefixes were
never introduced to libostree, the refspecs in the origin file
were never meant to contain such prefixes anyway.

rebase: Remove support for providing prefixes

---

rust/src/lib.rs
rust/src/treefile.rs
src/libpriv/rpmostree-core.cxx

In Fedora 34+ librpm can no longer write bdb, so we fail
to build RHCOS.  But the error for this is obscure.  Make
this an obvious, up front error.
This relies on the implicit "sqlite default == fedora34+ == rpm without bdb write".
xref https://github.com/openshift/os/issues/552
xref https://bugzilla.redhat.com/show_bug.cgi?id=1938928

Error out if sqlite is default, but configured for something else

---

rust/src/lib.rs
rust/src/origin.rs
src/libpriv/rpmostree-origin.cxx

Alternative to https://github.com/coreos/rpm-ostree/pull/2956
We are tripping up on `refspec/baserefspec` and need to dedup
things more.  For now just make this a debug message.

Demote origin roundtrip warning to a debug message

---

rust/src/treefile.rs

We messed up the naming here.  In order to allow
https://github.com/openshift/os/pull/577
to work with both old and new rpm-ostree, let's parse
the old name too.

treefile: Parse `rpmdb: b-d-b`

---

src/libpriv/rpmostree-core.cxx

I'm trying to debug a failure building RHCOS where no packages
are found.  I wanted the `n_solvables()` from the repos, which
I got via adding a debug print, but let's surface this information
by default.
Note to do this we need to move the printing to after we've loaded the sack.
This code also duplicates `journal_rpmmd_info()` but that's not
a new problem.

core: Log repository solvables

---

src/app/rpmostree-compose-builtin-tree.cxx

Software engineering in a nutshell: While trying to debug
something, discovering the mechanism
added a while ago to debug things itself broke silently a while
ago.
(The addition of C++ exceptions to the mix means the `failed`
variable wasn't set if one was thrown)

compose: Fix RPMOSTREE_PRESERVE_TMPDIR

---

rust/src/origin.rs
src/daemon/rpmostree-sysroot-upgrader.cxx
src/libpriv/rpmostree-origin.cxx
src/libpriv/rpmostree-origin.h

This is is part of reducing internal complexity - in particular
our "representations of state".  The code here is basically
printing a warning if a requested package is already in the base
tree, and avoid passing that package down to the core.
To accomplish this original code here was doing:
origin -> (computed state) -> treespec
Now that we dropped treespec in a recent PR, it's going:
origin -> (computed state) -> treefile
Instead of having anonymous (computed state) we can
just make that a new (filtered) origin file.  IOW
we now do:
origin -> origin -> treefile
This is easier to understand and debug.  Note
how duplication around checking "requires local
assembly" between the upgrader and origin code
just drops out!

upgrader: Generate "computed" origin

---

rust/src/composepost.rs
rust/src/lib.rs
rust/src/treefile.rs
src/libpriv/rpmostree-core.cxx

This is a key bit to resolve https://github.com/openshift/os/issues/552
(But we'll close that issue when the PR to use cosa master lands)
We want to support "cross building" where e.g. a Fedora 34+ host
(or container) is generating a RHEL8 ostree commit.  The
status quo right now is that F34+ librpm supports read/write
of sqlite and just reading bdb.  And rhel8 librpm only supports
read/write of bdb.
To deal with this, detect if the input manifest specifies an rpmdb format
(namely `bdb`) that is not the current default (namely `sqlite`
in Fedora 34+/RHEL9+) and if so, fork of the *host* rpm to export
the database we wrote back into memory, and then pass that
down to a bwrap container with the *target* rootfs `rpm`.

compose: Support writing rpmdb with target rootfs to support RHEL8+bdb

---

rust/src/importer.rs
tests/vmcheck/test-layering-basic-1.sh

Do not merge: I'd like to see CI results here first to double-check my current understanding.
---
This simplifies the RPM importing logic by dropping some unused code
for handling the /opt hierarchy.
There is no need to handle this case in the filtering callback, as
paths under /opt have been translated to /usr/lib/opt before
reaching this point.
My understanding is that there was an absolute-vs-relative mixup in
the original implementation, which has been fixed when porting to
Rust. This conditional case was thus left behind but unreachable.

importer: drop some unreachable logic for /opt handling

---

Cargo.lock
Cargo.toml
rust/src/failpoint_bridge.rs
rust/src/lib.rs
rust/src/main.rs
src/app/rpmostree-clientlib.cxx
src/daemon/rpmostreed-transaction.cxx
tests/kolainst/nondestructive/misc.sh

Add generalized "debugpoint" via RPMOSTREE_DEBUG
This is the inevitable application-specific, ad-hoc, informally-specified
reimplementation¹ of a tiny subset of BPF+tracepoints.
One way to view this is similar to `strace` + optional fault injection.
The existing `RPMOSTREE_GDB_HOOK` becomes `RPMOSTREE_DEBUG=main=sigstop`.
But one can pair arbitrary debugpoints with a set of arbitrary actions,
e.g. `RPMOSTREE_DEBUG=main=exit` will exit immediately after main instead
of stopping (not that that's very useful, but it illustrates the mechanism).
A bit more useful, I added a new debugpoint just after client transaction
connect to help reliably trigger a bug:
`env RPMOSTREE_DEBUG=client::connect=exit`.
(OK but wait, why not use tracepoints/BPF?  It'd be cool but I
don't want to actually try …

daemon: Correctly abort not-started transactions after client exit

---

rust/src/main.rs
tests/kolainst/nondestructive/misc.sh

The default Rust API for this panics.  Let's provide a clean
error.
Implementation note: Since argument gathering now returns a `Result<>`,
move it into `inner_main()`.
Closes: https://github.com/coreos/rpm-ostree/issues/2943

main: Cleanly error out on arguments that are not valid UTF-8

---

rust/src/initramfs.rs
tests/kolainst/destructive/initramfs-etc

Otherwise the kernel will just silently skip over files in the CPIO
which are missing an already extracted parent dir.
It's nice anyway since this also verifies that the path is fully
canonicalized.
There's a minor optimization possible here I didn't feel was worth
doing, which is to pass down `path` into `list_files_recurse` and using
it as a buffer to save a few allocations.
Closes: #2944

rust/initramfs: Include parent directories in initramfs-etc overlay

---

rust/rpmostree-client/src/lib.rs
rust/src/core.rs
rust/src/lib.rs
rust/src/origin.rs
rust/src/sysroot_upgrade.rs
src/app/rpmostree-builtin-rebase.cxx
src/app/rpmostree-builtin-status.cxx
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h
src/libpriv/rpmostree-origin.cxx
src/libpriv/rpmostree-origin.h
tests/kolainst/destructive/container-image

**UPDATED**:
We can now do e.g. 
```
$ booted_commit=$(rpm-ostree status --json | jq -r '.deployments[0].checksum')
$ sudo rpm-ostree ex-container export --repo=/ostree/repo ${booted_commit} containers-storage:localhost/fcos
$ sudo rpm-ostree rebase containers-storage:localhost/fcos:latest --experimental
$ rpm-ostree status
State: idle
Deployments:
containers-storage:localhost/fcos:latest
Version: v2021.6-27-g279ff28768+dirty (2021-06-30T21:49:22Z)
* c57a5d1d1e22c79f4a85187f959d9a16c189f8352b840c9f3d40c55a47d3dc24
Version: v2021.6-27-g279ff28768+dirty (2021-06-30T21:49:22Z)
fedora:fedora/x86_64/coreos/testing-devel
Version: 34.20210623.dev.0 (2021-06-23T18:16:51Z)
Commit: a59d1ad617e0fd0690e3f00d1f7e0fc7c2c18ad887e0bd57ceee3a9a03119672
GPGSignature: (unsigned)
$ sudo reboot
...
$ …
```

Allow rebase to OSTree commits in container images

---

configure.ac
docs/RELEASE.md
packaging/rpm-ostree.spec.in

While we're here, mechanize the libdnf dep updating process a bit more.
And by doing that, we drop the swig build dep at least.

Release 2021.7

---

rust/src/main.rs

Followup to previous patch; there's no real reason to have
some stuff in `main()` and some stuff in `inner_main()`.  Move
everything except error formatting into the latter.

rust/main: Move all real logic into inner_main()

---

Cargo.lock
Cargo.toml
rust/src/lib.rs
rust/src/main.rs
src/app/libmain.cxx
src/app/rpmostreemain.h

Propagate exceptions from the C++ `rpmostree_main()` to the
Rust `main` as a `Result`.
Add a depenency on `termcolor` (also used by `cargo`).
Drop the C code to print colored errors, and move it to Rust
using `termcolor`.  (Which, wow is that not ergonomic, but
hey it's more Rust and less C)

Move all error printing into Rust

---

docs/cliwrap.md
docs/experimental.md
rust/src/main.rs

main: Add comment noting to use inner_main()
---
docs: Add experimental/cliwrap
Let's start documenting our experimental features too.  Motivated
by having something to link for the "documentation" section
in a Fedora Change for this.
---

docs: Add experimental/cliwrap

---

src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-transaction-types.cxx

upgrader: Inline the check for local assembly
Just a minor cleanup, we don't need a separate function for this
anymore.
---
transactions: Only open up sepolicy once when importing
I randomly noticed we were loading the selinux policy for
each RPM, which is a bit inefficient.
---

two small patches

---

src/daemon/rpmostree-sysroot-upgrader.cxx
tests/kolainst/destructive/container-image

Ideally we expose full progress messages, but right now one
could say "It's quiet...too quiet."

upgrader: Print messages when we're fetching container bits

---

src/app/rpmostree-builtin-status.cxx
src/daemon/rpmostreed-deployment-utils.cxx
tests/kolainst/destructive/container-image

I think an important part of this story will be that people
will use the `@sha256:` digested container image references
as a way to track operating system snapshots.  The container
image version isn't always useful because not everyone will
make a container tag for every image.  The ostree commit
hash isn't useful because we can't look it up from the registry.
So let's show the digest front and center.

Add container image digest and print it in status

---

rust/src/daemon.rs
rust/src/origin.rs
src/daemon/rpmostreed-deployment-utils.cxx

Part of https://github.com/coreos/rpm-ostree/issues/2326
which is trying to orient rpm-ostree more strongly around treefiles.
Move the C/C++ code which is mapping the origin file into
the deployment variant into Rust, using the code which maps
from origin files to treefile.

daemon: Move more deployment-variant bits to Rust using treefile

---

rust/src/builtins/compose/mod.rs
rust/src/lib.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-composeutil.cxx
src/app/rpmostree-composeutil.h

This ports the legacy (non unified core) logic for creating /dev
entries to Rust.

builtins/compose: move /dev preparation to Rust

---

rust/src/lib.rs
rust/src/treefile.rs
rust/src/utils.rs
src/app/rpmostree-compose-builtin-tree.cxx

This moves the treefile JSON pretty-printing logic to Rust.
It also avoids redundant steps in retrieving host basearch, by
using the internal Rust build-arch mapping and caching the value
upfront.

builtins/compose: move basearch and pretty-print logic to Rust

---

src/app/rpmostree-compose-builtin-tree.cxx

This moves the logic for setting input-hash early on, so that a
meaningful value is always returned even in case of early returns
(e.g. dry runs or no changes).
---
Context: the surrounding code seems to assume this value is always populated, but there are conditional early returns in the middle of this function which can leave it NULL. While I think NULL-dereferencing cases aren't currently reachable, it doesn't hurt making sure the value is populated before any of the possible early returns.

builtins/compose: always return computed input-hash

---

src/app/rpmostree-compose-builtin-tree.cxx
src/lib/rpmostree-db.c
src/libpriv/rpmostree-editor.cxx

compose: Add error prefixing when writing compose JSON
This ends up doing some nontrivial work in e.g. `db diff` and
I want to see if an error trace is happening from there.
xref https://github.com/openshift/os/issues/594
---
db: Prefix error when we fail to load the rpmdb
Also add a missing `:` in the editor code.
xref https://github.com/openshift/os/issues/594
---

Two error prefixing patches

---

src/app/rpmostree-compose-builtin-tree.cxx

This moves an error prefix from an automatic function-wide macro
to an explicit wrapping at the calling site. The function is only
called in a single place anyway, and using an explicit wrapper
will make Rust porting easier later on.

builtins/compose: drop an automatic-error-prefix macro

---

src/daemon/rpmostreed-daemon.cxx
src/daemon/rpmostreed-daemon.h
src/daemon/rpmostreed-os.cxx
src/daemon/rpmostreed-sysroot.cxx
tests/kolainst/nondestructive/misc.sh

os: Minor code style cleanup
Just return early here if we detect the session bus case.
Prep for further work which will add another early return
case.
---
daemon: Authorize uid 0 when polkit is not available
I did an RHCOS build that didn't contain polkit, and noticed
rpm-ostree no longer worked.
But we should work in this scenario.  While zincati currently
relies on this, we should support custom builds that don't
have polkit.
---

 daemon: Authorize uid 0 when polkit is not available

---

docs/treefile.md
rust/src/daemon.rs
rust/src/lib.rs
rust/src/main.rs
rust/src/modularity.rs
rust/src/origin.rs
rust/src/treefile.rs
rust/src/utils.rs
rust/src/variant_utils.rs
src/app/libmain.cxx
src/app/rpmostree-builtin-status.cxx
src/app/rpmostree-compose-builtin-tree.cxx
src/daemon/org.projectatomic.rpmostree1.xml
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-os.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-origin.cxx
src/libpriv/rpmostree-origin.h
src/libpriv/rpmostree-util.cxx
src/libpriv/rpmostree-util.h
tests/common/libtest.sh
tests/compose/test-basic-unified.sh
tests/kolainst/Makefile
tests/kolainst/destructive/layering-modules
tests/kolainst/kolainst-build.sh

Add support for composing with modules and for package layering modules
on the client-side.
This doesn't support modules in `rpm-ostree compose extensions` yet,
which is relevant for RHCOS. We can look at adding that in a follow-up.

Add support for modules

---

.cci.jenkinsfile
.copr/Makefile
Makefile.bindings
ci/coreosci-rpmbuild.sh
ci/installdeps.sh
ci/libbuild.sh

ci: Install system deps before cxxbridge
To ensure we have `jq` which we need; and this is required for COPR.
---
build-sys: Install cxxbridge in target/
Since the binary needs to be version locked with our `Cargo.lock`,
let's move the helper binary into our `target/` directory.  This
should help with the COPR build which doesn't set `$PATH`.
---
Add .copr/Makefile
Prep for re-introducing a coreos/continuous build.
---

build-sys: Rework cxxbridge and add .copr integration

---

rust/src/composepost.rs
rust/src/lib.rs
src/libpriv/rpmostree-postprocess.cxx

We're getting a weird OOM issue in RHCOS builds:
https://github.com/openshift/os/issues/594
which looks like:
`fstatat(92/4682a3540a7d5f834f5159c024f412ff528600f8a683116ce99a1832251b67.filez): Cannot allocate memory`
Reading some code here I noticed that the "open directory" call
could follow symlinks when it shouldn't.  Let's just RIIR and
make this code more explicit - e.g. we ignore symlinks.
I'm pretty sure this is a no-op, but let's harden the code.
---

postprocess: Oxidize directory size counting

---

src/app/rpmostree-builtin-shlib-backend.cxx
src/app/rpmostree-builtin-status.cxx
src/app/rpmostree-clientlib.cxx
src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-db-builtin-diff.cxx
src/daemon/rpmostree-sysroot-core.cxx
src/daemon/rpmostree-sysroot-upgrader.cxx
src/daemon/rpmostreed-deployment-utils.cxx
src/daemon/rpmostreed-os.cxx
src/daemon/rpmostreed-sysroot.cxx
src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-importer.cxx
src/libpriv/rpmostree-kernel.cxx
src/libpriv/rpmostree-postprocess.cxx
src/libpriv/rpmostree-scripts.cxx
src/libpriv/rpmostree-util.cxx
src/libpriv/rpmostree-util.h

We can use the `decltype` built-in to avoid having to pass the type.

src: Simplify CXX_TRY_VAL macro

---

src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-origin.cxx

Part of reducing lines of code that need to be added when
adding new origin functionality.
The goal is to saturate `changed` to `TRUE`, so change the
change handling inside the origin to do that where it's
more convenient.   Then we can drop all of the other
booleans.

origin: Change change handling to saturate at `TRUE`

---

rust/src/builtins/compose/commit.rs
rust/src/lib.rs
src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-composeutil.cxx
src/app/rpmostree-composeutil.h

This refactors the JSON summary logic in order to make it more
explicitly scoped and decoupled from the rest of the surrounding
commit steps. In particular with this:
* the whole logic is skipped if the JSON summary is not requested
* the GVariant builder is scoped within the summary logic
* transaction stats are printed as soon as available, through a
Rust helper

compose/commit: decouple JSON summary logic, move stats to Rust

---

rust/src/core.rs
rust/src/lib.rs
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-kernel.cxx

I'm hitting an issue trying to override the kernel in C9S,
and I wanted to trace through things a bit more.
Let's start using the tracing crate more.  One benefit of
this over `g_debug()` is that we avoid calling any of the code
(in this case the creation of the JSON string) unless the log
level is enabled.

Add some more debugging bits when replacing kernel

---

src/libpriv/rpmostree-core.cxx
tests/compose/libbasic-test.sh
tests/compose/test-basic-unified.sh

Let's be strict and not enable/install any modules by default.  Instead,
we require all module requests to be done explicitly. Note this is
slightly different from dnf, where it automatically enables modules if
trying to install a modular package (e.g. `podman` in RHEL8).
This is also required for proper `repo-packages` handling.
Early iterations of the modularity patches used to have something
similar but it got lost somewhere along the way.
Related: https://github.com/coreos/rpm-ostree/issues/3035

core: Disable all modules upfront

---

src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-origin.cxx

deploy: Only hold local variant pointer, not in struct
This is part of reducing the number of places that need to
be touched when adding new API.  There's no good reason to parse
the options variant into a struct member; we can just keep
it as a local variable.
---
origin: Make some package/module mutation functions no-ops for NULL
Rather than having the caller do conditionals for `NULL`, do it
inside the function.  This simplifies the control flow and avoids
duplication.
---

deploy: Only hold local variant pointer, not in struct

---

src/daemon/rpmostreed-transaction-types.cxx
src/libpriv/rpmostree-origin.cxx

daemon: Move more deploy transaction init into execute()
---
deploy: Move local_repo_remote_dfd into function scope
---
deploy: Move install_local_pkgs into function scope
---
deploy: Move package overrides into function scope
---
origin: Change add_packages to ignore NULL
For symmetry with previous commits, even though this won't be
used right now.
---

More txn cleanup

---

src/libpriv/rpmostree-core.cxx

Our submodule has the new `dnf_context_module_disable_all` API now.
Ref: https://github.com/rpm-software-management/libdnf/pull/1303

core: Use new API for disabling all modules

---

src/app/rpmostree-clientlib.cxx

This adds a bunch of explicit error contexts in the codepaths
handling a local repo as a remote.
It also drops a leftover comment which does not apply anymore
to the current code.
Ref: https://github.com/coreos/rpm-ostree/pull/1794/commits/4469ec59e31073cb7e9ba24f6ae0a82709978e90
---
Context: This showed up in MCO logs as a bare `error: opendir(/srv/repo): No such file or directory`. While the root problem is outside of rpm-ostree, having a bit more error context would be good.

clientlib: add more error contexts

---

rust/src/builtins/apply_live.rs
rust/src/lib.rs
rust/src/live.rs
src/libpriv/rpmostree-diff.cxx
src/libpriv/rpmostree-diff.hpp

This adds opt-in support for cases where there is no rpmdb available
for diffing. It enhances the C++ wrapper in order to cover more usecases,
helping further Rust porting.

libpriv/diff: allow missing rpmdb

---

src/daemon/rpmostreed-transaction.cxx

daemon: Inline variable declarations for txn progress
Reduces lines-of-code.
---
daemon: Inline parsing of ostree progress
No need to declare variables for each item, just convert
them to variants directly.
General code cleanup in prep for further work.
---
daemon: Fix elapsed_secs
Due to redeclaring this variable we were always emitting zero.
It's not used, I just noticed this while cleaning up the code.
---

Txn progress cleanup

---

Cargo.lock
rust/libdnf-sys/Cargo.toml

I noticed we were compiling glib 0.10 *and* glib 0.14, and
this is the reason why.  Since we're not actually using glib
at all, just drop it for now.
---

libdnf-sys: Drop glib dependency

---

docs/treefile.md
rust/src/lib.rs
rust/src/main.rs
rust/src/modularity.rs
rust/src/treefile.rs
src/app/libmain.cxx
src/app/rpmostree-builtin-ex.cxx
src/app/rpmostree-compose-builtin-tree.cxx
src/app/rpmostree-ex-builtins.h
tests/kolainst/destructive/layering-modules

On the client side, we were requiring `--experimental` on the CLI,
though to be clear and consistent, let's instead move it under
`rpm-ostree ex` just like what we usually do with every other new
experimental commands.
On the compose side, move the associated documentation to the
experimental section.

More clearly mark modularity support as experimental

---

Makefile.bindings
rust/src/lib.rs
rust/src/sysroot_upgrade.rs
src/daemon/rpmostree-sysroot-upgrader.cxx

container: Accept an ostree::Repo directly
We don't do anything with the sysroot, so just pass the repo
which we already have.
Prep for using this code on the compose side.
---
build-sys: Don't leave empty file on error
---

container: Accept an ostree::Repo directly

---

rust/src/failpoint_bridge.rs
rust/src/lib.rs
src/app/rpmostree-clientlib.cxx
tests/common/libtest.sh
tests/kolainst/nondestructive/misc.sh

tests/misc: Only validate remote if we have one
I'm trying to run this with `cosa build-fast`, and the test
fails because there wasn't a remote configured to start.
---
Change our failpoint to `return Err` instead of panic
Part of looking at https://github.com/coreos/rpm-ostree/issues/3075
I thought there was an issue with us not catching a panic and
the core dump handler being called before stderr was flushed.
In the end, that wasn't the bug, but I think it's just cleaner
for us to return an error rather than panic.
---
tests/misc: Poll journal for error message
We could race in having the client error out and try querying the journal
before the daemon had written the error message.
Closes: https://github.com/coreos/rpm-ostree/issues/3075
---

Fix disconnected test flake

---

rust/src/container.rs
rust/src/lib.rs
rust/src/main.rs
rust/src/sysroot_upgrade.rs
rust/src/tokio_ffi.rs
src/daemon/rpmostreed-transaction.cxx

Each entrypoint to the container bits sets up a tokio runtime,
which is inefficient and duplicative.  We're also likely
to start using Rust async in more places.
Instead, create a Tokio runtime early in our `main`, and
change the CLI entrypoint to be an `async fn`.
The other setup of a runtime we have is deep inside the
sysroot upgrader bits, also for the container.  In this
case we actually have another thread (distinct from the main one
where we set up Tokio) created by C/C++, so we need to pass
a `tokio::runtime::Handle` across, and call `enter()` on it
to set up the thread local bindings to access tokio async
from there.
I was initially looking at properly handling `GCancellable`
with tokio and wanted to clean this up first.

Set up Tokio runtime in main()

---

rust/src/client.rs

I noticed in gnome-terminal at the default tiny 80x24 size, when
we hit this case `systemctl` will spawn a pager because the status
is too long.  This is confusing and unexpected - I have learned
`systemctl` and `journalctl` may (for the latter, usually) spawn a pager
but I don't expect it from random commands like this.

client: Use `--no-pager` for `systemctl status`

---

rust/src/lib.rs
rust/src/sysroot_upgrade.rs
rust/src/utils.rs
src/daemon/rpmostree-sysroot-upgrader.cxx

There may be a better way to bridge `GCancellable` into tokio.
I still need to join the gtk-rs Matrix chat so I can ask questions.
Anyways, this wasn't really hard to put together in the end.
What took me a while actually was that one can't use `tokio::sync::oneshot`
from a `Fn` (needed in `cancellable_connect()` and instead we need
to use this notify thingy that's threadsafe/`Send` etc.).
---

upgrader: Make container pulls cancellable

---

Cargo.lock
rust/src/daemon.rs
rust/src/live.rs

In favor of the new upstream API methods.  A bit less ergonomic
since we need to `map_err()`, but I think this is cleaner.

rust: Drop use of ostree-rs-ext VariantDictExt, bump glib

---

src/libpriv/rpmostree-scripts.cxx

glibc-gconv-extra uses lua scripts in post as of https://src.fedoraproject.org/rpms/glibc/c/ca0613665ce6e1b4e92dadd3660ad39cf3dc5f3e?branch=main
The post script is the same as glibc, which was previously worked around in https://github.com/coreos/rpm-ostree/commit/d04e946dd4f813716e7bac7f0f3eff6ade590bc6

scripts: Ignore glibc-gconv-extra lua script in %post

---

rust/src/treefile.rs

It warned about the pattern of `.collect().into_iter()`.
This should be more efficient too.

treefile: Fix a clippy lint

---

rust/src/cliwrap.rs
rust/src/composepost.rs
rust/src/countme.rs
rust/src/countme/repo.rs
rust/src/daemon.rs
rust/src/history.rs
rust/src/initramfs.rs
rust/src/live.rs
rust/src/lockfile.rs
rust/src/origin.rs
rust/src/passwd.rs
rust/src/treefile.rs

Tempting to just allow this tree wide since it's harmless, but
fixing this isn't too hard and helps us see the actually important
clippy lints/errors.

rust: Fix clippy lint for extra `&`

---

.cci.jenkinsfile
Makefile-tests.am
ci/build-check.sh
ci/coreosci-rpmbuild.sh
configure.ac
packaging/rpm-ostree.spec.in
rust/src/lib.rs
rust/src/testutils.rs
src/app/libmain.cxx
src/app/rpmostreemain.h
src/daemon/rpmostreed-utils.cxx
src/libpriv/rpmostree-util.h

We lost C unit tests with the Rust-as-main massive buildsystem
rework.
But we're not going to RIIR tomorrow, and there's definitely
a need to continue unit testing directly some of the C/C++
code.
Add a new buildsystem option `--enable-bin-unit-tests` and
turn it on for CI (but not production builds) *or*
when compiling in `--debug` mode.
This basically compiles the unit testing code into the main
binary.  It's hooked up to `make check` too.

Add --enable-bin-unit-tests

---

rust/src/builtins/compose/mod.rs
rust/src/client.rs
rust/src/cliwrap.rs
rust/src/composepost.rs
rust/src/daemon.rs
rust/src/extensions.rs
rust/src/fedora_integration.rs
rust/src/lib.rs
rust/src/live.rs
rust/src/main.rs
rust/src/origin.rs
rust/src/treefile.rs
rust/src/utils.rs

rust: Fix misc clippy lints
No major problems here.
---
rust: Fix two clippy errors
These are marked as errors, and while they're not important bugs
let's fix them.
---
rust: Fix more clippy lints
All low priority stuff
---
rust: Allow a few clippy lints
I think the vec pattern is fine.  And we want lifetimes in the cxxrs code.
---
rust: Fix a clippy lint about manual `strip_prefix()`
Man, clippy is smart.
---

Fix remaining clippy lints

---

tests/kolainst/destructive/layering-modules

That way we exercise the modular bits with a real module instead of only
the synthetic ones we create. `cri-o` is of special relevance for FCOS
so choose that.

tests/kolainst: Check layering of `cri-o:1.20/default`

---

tests/vmcheck/test-misc-2.sh

This was correctly fixed by
https://github.com/ostreedev/ostree/pull/2425

tests/misc: Update regexp to match fixed ostree error

---

Cargo.lock
Cargo.toml
rust/src/core.rs
rust/src/cxxrsutil.rs
tests/kolainst/destructive/container-image

We now support GPG (and signapi) signatures when rebasing to ostree-containers.
We also no longer carry heuristics in our code to distinguish between
ostree remote:ref and container image references - ostree-rs-ext
defines an unambiguous schema for the latter.
Also, we drop the direct dependency on `ostree-sys` since we now
have https://github.com/ostreedev/ostree-rs/pull/25
Closes: https://github.com/coreos/rpm-ostree/issues/3126

Bump to ostree-rs-ext 0.3

---

src/app/rpmostree-override-builtins.cxx
src/daemon/org.projectatomic.rpmostree1.xml
src/daemon/rpmostreed-os-experimental.cxx
src/libpriv/rpmostree-types.h
src/libpriv/rpmostree-util.cxx
src/libpriv/rpmostree-util.h
tests/kolainst/destructive/override-pinning

`override replace --experimental` allows experimental options from and
freeze.
`override replace --from` query and fetch for the lastest version of
a package from specified repo, instead of just enabled repos.
`override replace --freeze` pin the overrided package avoiding updates.
Adapt `ex-pin-from-repos` syntax to `--experimental --freeze`

override replace: add experimental options

---

Cargo.toml

This has been extensively discussed elsewhere; this tweak
is in the official docs:
https://doc.rust-lang.org/cargo/reference/profiles.html
Basically among other things, at the default `opt-level=0` almost
no inlining occurs, and Rust *heavily* depends on inlining.
So we're trading off some debuggability for much improved debug
build performance.
The release profile uses LTO right now which takes 2.5 minutes
on my workstation, which seriously hampers iteration time.
For another random link, e.g:
https://erasin.wang/books/bevy-cheatbook/pitfalls/performance.html

rust: Use `opt-level=1` for default `dev`

---

docs/extensions.md
rust/src/extensions.rs
rust/src/treefile.rs

While we support arch-specific extensions today, the state of
repos and modules are global.  Which means if a module-using
extension is only available on one architecture (as is the
case in RHEL8/OCP with the `av` module) then it's not
possible to build on other architectures.
The most powerful mechanism here is the `arch-include` design
that we have in the treefile, but...since we already have
an architecture filter per extension, it's easier to add
repos and modules per extension.
Note that the repos and modules are still *global* state, so
we're not supporting actively conflicting extensions right now
still.
Closes: https://github.com/coreos/rpm-ostree/issues/3150

extensions: Add support for per-extension repos and modules

---

src/app/rpmostree-builtin-rebase.cxx
tests/vmcheck/test-upgrades.sh

We did this in the past, I don't think it was truly intentional.
But, let's continue to support it since it turned out
gnome-software used it:
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1463

rebase: Parse `ostree://` prefix again

---

rust/src/main.rs

main: Remove pointless `async { ... }` + `.await` pair
---
main: Remove lots of `Some` matching
Destructure first, then match to avoid repetition.
---

Two minor bits for main.rs

---

configure.ac
packaging/rpm-ostree.spec.in

This release contains mostly bugfixes and UX enhancements.
Some changes were made to help with reproducible builds. For example, rpm-ostree now passes the `SOURCE_DATE_EPOCH` to scripts during composes. Also, the `lstchg` timestamp field is now scrubbed from shadow files, and the content of generated `tmpfiles.d` fragments is sorted. #3163 #3174
A notable improvement for users is related to RPM packages with overlapping files color/disposition (i.e. multilib support), which are now properly handled at install time. This used to be a blocker for `unixODBC.i686`, a dependency of `wine`. #3125
A new `rpm-ostree install --force-replacefiles` flag allows overriding files without replacing the package. This may be useful in "quick testing" or hotfix scenarios. #3125
This release now …

Release 2021.13

---

src/app/rpmostree-builtin-rebase.cxx
src/daemon/rpmostreed-transaction-types.cxx

Follow-up to df8315a262 (#3157).
GNOME Software uses the D-Bus API directly, not the CLI. So let's move
handling of `ostree://` there.
The test added in #3157 will verify that we're parsing it correctly.
Closes: #3192

Move `ostree://` parsing to daemon

---

src/libpriv/rpmostree-core.cxx
tests/kolainst/destructive/layering-modules
tests/vmcheck/test-override-kernel.sh

In 11aeb825d2cb ("core: Handle RPM file colors more efficiently"), we
added an early exit in `handle_file_dispositions` on arches which don't
use colours. However, this is incorrect because that function does more
than just colour handling; it also handles files shared between RPMs.
Fix this and expand the function's docstring.
We have tests for this, but it passed through because CI runs on x86_64.
But this would matter or i686 or armhfp (which is relevant for Fedora
IoT).

core: Fix minor regression on colorless arches

---

src/app/rpmostree-builtin-kargs.cxx

This rewords the prefacing help message for the kargs editor.
Among the fixes, it includes:
* fix a missing `\n` on the first sentence
* drop a spurious leading empty line
* add an empty trailing line between instructions and current kargs
* mention that empty lines are ignored
* remove kargs key=value format (full kernel parsing description
is complex, and this margin too narrow to contain it)

builtins/kargs: reword editor instructions

---

src/daemon/rpmostree-sysroot-upgrader.cxx
src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-core.h

This fixes the case of doing cliwrap *and* local package layering,
which ended up wrapping twice, causing an infinite exec loop.
Closes: https://github.com/coreos/rpm-ostree/issues/3184
A lot of history here.  Originally the cliwrap code was duplicated
on the client side (origin files) and the server side (treefiles).
Then lately we've been trying to unify them, which happened via:
https://github.com/coreos/rpm-ostree/pull/2743
I think (but didn't verify) that it was that PR that introduced
this double wrapping.  Basically since we're now passing a synthesized
treefile into the core, it enables cliwrap there too.
However, it's the sysroot upgrader that has the tricky logic right now
around "only invoke libdnf/rpm when necessary" around things like
fetching repodata.  We should drive that …

Unify cliwrap handling into core

---

src/daemon/org.projectatomic.rpmostree1.xml

Add an initial set of simple annotations to help with interface code generation for Qt base applications.

DBus description: Add annotations for Qt support

---

tests/compose.sh
tests/kolainst/destructive/container-image

Fedora 33 packages have been untagged from the pool so CI will start
failing on the next repo regen. Let's just bump to a recent f35 commit.
See: https://github.com/coreos/fedora-coreos-tracker/issues/884

tests/compose.sh: Bump frozen FCOS commit for f35

---

src/libpriv/libsd-time-util.c
src/libpriv/libsd-time-util.h

Notably this fixes proper (non-)pluralization of timestamps.

libpriv: Update libsystemd copy of `format_timestamp_relative`

---

src/app/rpmostree-builtin-kargs.cxx
src/daemon/org.projectatomic.rpmostree1.xml
src/daemon/rpmostreed-transaction-types.cxx
tests/common/libvm.sh
tests/vmcheck/test-kernel-args.sh

This reworks the `kargs --editor` flow, fixing an existing regression and
adding support for `--unchanged-exit-77` too (for the sake of easier
testing).
Closes: https://github.com/coreos/rpm-ostree/issues/3182

builtin/kargs: fix editor flow

---

Cargo.toml

A release build takes four minutes here, which...is just too much.
`lto = "thin"` is much faster, a no-op change on the C/C++ side is
~35s, a 4x reduction.
Eventually thin LTO is going to be equivalent to full LTO:
https://clang.llvm.org/docs/ThinLTO.html

`Cargo.toml`: Switch to `lto = "thin"`

---

src/app/rpmostree-compose-builtin-tree.cxx

Otherwise, we can get log messages like:
> Regex version mismatch, expected: 10.37 2021-05-26 actual: 10.32 2018-09-10
when building RHCOS, which is a new log message from libselinux:
https://www.spinics.net/lists/selinux/msg37626.html.
I think previously it was just silently falling back to re-parsing the
text file which is why we didn't notice this? (Possibly all the way
since the introduction of unified core.)
Closes: https://github.com/openshift/os/issues/669

compose: Apply SELinux regex timestamp hack before reloading policy

---

src/app/rpmostree-builtin-status.cxx

Created this PR as a first step towards fixing #1613.
Fixed issues:
- By using the existing `print_packages()` for RemovedBasePackages and ReplacedBasePackages multiple package groups are no longer started in the same line if the next package/package group would not fit into the same starting line.
- `print_packages()` creates a `packages_sorted` array, but never actually sorts the package list.
- RemovedBasePackages and ReplacedBasePackages do no longer use the comma separator. Package groups are now either nice and short (in which case it's okay to print two in the same line), or new package groups start in a new line - which obsoletes the comma separator.
Open points:
- I removed the `rpmostreecxx::maybe_shell_quote (pkg)` call in `print_packages()` as it introduced quotes for package …

Sort and indent packages/package groups in rpm-ostree status

---

src/daemon/rpm-ostreed.service.in

This is a weaker version of https://github.com/coreos/rpm-ostree/pull/3239
that helps ensure that host updates can't interfere with
application containers (and vice versa).

daemon: Add `InaccessiblePaths=/var/lib/containers`

---

src/libpriv/rpmostree-core.cxx
tests/vmcheck/test-override-replace-2.sh

It's auto-generated by rpm-ostree, but it's associated with the package.
Otherwise, it's possible that the new package will fail to checkout a
different auto-generated dropin.
Someone hit this internally when trying to override openvswitch:
```
sh-4.4# rpm-ostree override replace openvswitch2.15-2.15.0-51.bz1944550.6.el8fdp.x86_64.rpm
Checking out tree a654ec9... done
No enabled rpm-md repositories.
Importing rpm-md... done
Resolving dependencies... done
Applying 1 override
Processing packages... done
error: Checkout openvswitch2.15-2.15.0-51.bz1944550.6.el8fdp.x86_64: Hardlinking 40/4a5bddb5292f74e4a679f4e93c11d13e6097d69d1f0806ed59200398e7d2a8.file to pkg-openvswitch2.15.conf: File exists
```
```
$ diff <(rpm -q --dump -p openvswitch2.15-2.15.0-38.el8fdp.x86_64.rpm | grep /var) <(rpm -q …
```

core: Nuke auto-generated tmpfiles.d when removing packages

---

tests/common/libvm.sh
tests/vmcheck/test-layering-basic-2.sh

This is a workaround for a change of behavior that happened in ostree-2021.06 (possibly in https://github.com/ostreedev/ostree/pull/2486), related to specifying a custom `--repo` which happens to be on a ready-only sysroot.
We should fix `ostree` to detect this case and behave in a better way, but the broken tests here are also quite hackish so let's improve these first.

tests/vmcheck: tweak some hackish direct access to /ostree

---

man/rpm-ostree.xml

* Remove duplicated section for the `override` subcommand.
* Fix typos.

docs: fix minor bugs in rpm-ostree manpage

---

Cargo.lock

To pick up build+runtime fixes for RHEL8.

Bump to ostree-ext 0.5.1 and containers-image-proxy 0.3.1

---

src/daemon/rpm-ostree-countme.timer

The current timer will trigger weekly with a potential delay of a week,
which means that if the delay is big enough, an entire week will be
skipped and we will miss counting.
Instead, let's trigger on boot and every three days with a random delay
of one day so that we are sure that we at least trigger once per
counting window.
This does not introduce the risk of over counting as the logic for that
check is in rpm-ostree itself.

countme: Trigger on boot and bi-weekly with random delay

---

packaging/rpm-ostree.spec.in

It seems to exist in source:
https://gitlab.com/redhat/centos-stream/rpms/zchunk/-/blob/c9s/zchunk.spec
Yet there's no package, and libdnf at least has this same conditional.
Dunno what's going on there; I assume there's some other git repo
removing it from a build list or something.

packaging: Don't use zchunk on RHEL9 either

---

tests/compose.sh

Since it's not officially in FCOS, it's not in the pool. But it's
subject to version binding with `glibc-common`. Let's just add the
`updates-archive` repo to the compose to fix this.
Fixes: #3217 (6b0d4f280bec)

tests/compose: Add updates-archive repo for glibc-all-langpacks

---

src/libpriv/rpmostree-core.cxx

Detected by a RHT-internal proprietary static analyzer.

core: Fix memory leak for colorless files

---

rust/src/cxxrsutil.rs
rust/src/history.rs
rust/src/lib.rs
rust/src/treefile.rs
rust/src/utils.rs

Deny missing `Debug` impls by default, add more of them
Came out of discussion in https://github.com/ostreedev/ostree-rs-ext/pull/178
---
lib: Add `unsafe_op_in_unsafe_fn` lint
But allow it in the cxxrs-generated code.
---

More lints

---

docs/HACKING.md

Stuff is scattered here; just trying to get my current workflow
written down.
It'd clearly be nice to better optimize the `cosa build-fast`
flow to somehow also include external associated tests or so.

HACKING.md: Document iteration on kola external tests

---

rust/src/client.rs

Fixes #2893 by checking for src.rpm on the client code.

rust/src/client: detect src.rpms

---

.cci.jenkinsfile

The `ext.*` glob was selecting all external tests, instead of just the
rpm-ostree specific ones we just built, which I think was the intent
here.

ci: Only run our own external tests

---

rust/src/importer.rs

This is a build-side fix for systemd shipping a non-canonical symlink;
see:
https://github.com/ostreedev/ostree-rs-ext/pull/182
I'll copy/paste that commit message:
In https://github.com/ostreedev/ostree we generate a cryptographic
checksum over files and symlinks, and directories.
ostree does not currently perform any canonicalization on symlinks;
we'll respect and honor whatever bytes we're provided as input,
and replicate that on the target.
We're using the Rust tar crate to do tar serialization,
which has so far worked fine...except, I hit this corner case:
```
[root@cosa-devsh ~]# rpm -qf /usr/lib/systemd/systemd-sysv-install
chkconfig-1.13-2.el8.x86_64
[root@cosa-devsh ~]# ll /usr/lib/systemd/systemd-sysv-install
lrwxrwxrwx. 2 root root 24 Nov 29 18:08 …
```

importer: Canonicalize symlink targets

---

src/app/rpmostree-override-builtins.cxx

For the same reason we have it elsewhere.  Fetching the repomd
is a fine default, but e.g. someone may want to try overriding
using a local package that doesn't need any dependencies when
the machine is offline, or for some reason the rpm-md repositories
aren't accessible.
Motivated by trying to work around an OpenShift MCO issue where
it only provisions an rpm-md repo transitively.

override: Add --cache-only flag

---

Cargo.lock
Cargo.toml

Updating ostree-ext to pick up: 
https://github.com/ostreedev/ostree-rs-ext/pull/186
https://github.com/ostreedev/ostree-rs-ext/pull/190
https://github.com/ostreedev/ostree-rs-ext/pull/191
Which are needed for: #3280

Cargo.toml: Update ostree-ext to use main branch code

---

Makefile-rpm-ostree.am
Makefile.bindings

Joseph just hit the trap of https://github.com/coreos/rpm-ostree/pull/3274 landing, but it means that the bindings currently need to be regenerated manually.  This also hit me in the past.  The very broken thing here is we need to remove the generated bindings in `make clean`.
---
build-sys: Remove generated bindings in `make clean`
This was a double trap because they become invalid when `cxxbridge`
is updated.
---
build-sys: Ensure bindings depend on cxxbridge binary
This way if it's updated, the bindings will be regenerated.
---

two build system fixes for bindings

---

rust/src/client.rs
rust/src/lib.rs
src/app/libmain.cxx
src/app/rpmostree-pkg-builtins.cxx

proof of concept, current version works. Example Dockerfile:
```
FROM localhost/myfcos
RUN mkdir /tmp
ADD rpm-ostree /usr/bin/
RUN rpm-ostree install htop
RUN rpm-ostree install zsh strace
```

rust/src/client: Use microdnf when installing pkgs on a container

---

rust/src/cxxrsutil.rs
rust/src/lib.rs

Came up in review of
https://github.com/coreos/rpm-ostree/pull/3285#pullrequestreview-836664044

rust: Add some more comments around cxx.rs, particularly `Result<T>`

---

Makefile-rpm-ostree.am
rust/src/main.rs
tests/kolainst/nondestructive/misc.sh

This installs the `ostree-container` multicall binary as an
hardlink to the existing `rpm-ostree` one.
It also adds a kola tests to make sure it is actually working
at runtime.
Ref: https://github.com/coreos/rpm-ostree/pull/3281

make: install ostree-container as a multicall hardlinked binary

---

src/libpriv/rpmostree-core.cxx

I think perhaps due to the complexity of the `find_locked_packages`
function it doesn't see that the variable really is always non-`NULL`.
Let's add an assertion to help.

core: Add an assertion to silence clang-analyzer

---

src/daemon/rpmostreed-os-experimental.cxx

This drops a bunch of goto codepaths from the DBus DownloadPackages
handler.

dbus/download-pkgs: remove some goto statements

---

rust/src/daemon.rs
rust/src/lib.rs
src/daemon/rpmostreed-os-experimental.cxx
src/libpriv/rpmostree-types.h
src/libpriv/rpmostree-util.cxx
src/libpriv/rpmostree-util.h

This gets rid of the C logic for parsing override sources, moving
to a safe string parser in Rust. It also adds some basic unit tests.

daemon: port the override-source string parser to Rust

---

rust/src/cliwrap/yumdnf.rs
rust/src/countme/repo.rs
rust/src/normalization.rs

Newer rust warns about these by default.  For most of them
I just chose to `#[allow(dead_code)]` because these structs
are intended to mirror external things, and it just happens
that we're not reading all of the fields right now.

Fix or quiet unused field warnings

---

Cargo.lock
Cargo.toml

Now that there's an official release of the crate, let's switch
to it.

rust: Switch to ostree-rs-ext 0.6.0 release

---

configure.ac
packaging/rpm-ostree.spec.in

Various smaller bugfixes, but also an update the ostree 2022.1 stack,
support for "multicall", support for `rpm-ostree install` inside
a container (with microdnf).

Release 2022.1

---

Cargo.lock
Cargo.toml
rust/src/capstdext.rs
rust/src/composepost.rs
rust/src/ffiutil.rs
rust/src/lib.rs
rust/src/utils.rs

This will be nontrivial churn with no immediate obvious end user
value.  But, long term, the "cap-std ecosystem" of crates has *much*
more momentum than openat.  (Really, it's mostly just Dan Gohman
right now but his code is really, really good; and we can contribute)
There are a few concrete improvements from this; see
https://github.com/bytecodealliance/cap-std#similar-crates
I have to emphasize this bit:
> However, cap-std uses RESOLVE_BENEATH-style resolution where absolute paths are considered errors,
This is a big deal - a while ago I accidentally created an absolute
path in some of the code, and I only noticed it in review.
And related to this, openat's `open()` path does not follow symlinks
by default, which is a huge ergonomic hit when one *does* want to do
so, as I did in a …

Start using cap-std/rustix instead of openat/nix

---

rust/src/bwrap.rs
rust/src/client.rs
rust/src/cliwrap/cliutil.rs
rust/src/composepost.rs
rust/src/countme.rs

Part of porting to cap-std/rustix.

tree-wide: Replace `nix::get*[ug]id` with rustix equivalents

---

rust/src/composepost.rs
src/libpriv/rpmostree-scripts.cxx

Half of it is an upgrade hack that is incompatible with rpm-ostree
model; we always generate a fresh root.  Just touch the stamp
file so that authselect knows to rerun.
---

scripts: Replace `authselect-libs` prein

---

src/libpriv/rpmostree-core.cxx

I apparently forgot to `git commit` these additional tweaks.
- Make brace usage consistent
- it's useful to also see the reponame

core: Small tweaks for non-matching package output

---

rust/src/client.rs

I was writing a test against a FCOS base that doesn't have `microdnf`
and was getting:
```
STEP 4/6: RUN rpm-ostree install ./bar-1.0*.rpm
error: No such file or directory (os error 2)
```
This confused me because I thought it was talking about `bar.rpm`.
Add an error context for clarity.

client: Add context to microdnf failure to exec

---

.cci.jenkinsfile

So we can start using it in our own CI.

ci: Try using next so we pick up `microdnf`

---

ci/prow/fcos-e2e.sh
tests/kolainst/destructive/container-image

I think this needs to gate our CI.
Blocks on getting `microdnf`; I think I'll look at changing
our CI to operate on next-devel maybe?  Although that will
likely unveil its own dragons around the buildroot too.

container-image: Test installs in a container

---

src/daemon/rpmostreed-os-experimental.cxx

This fixes a buggy error return expression. Due to a "throw vs prefix"
mixup, in this case the function was wrongly returning with a `NULL`
error. It does now correctly generate and return a proper error value.
Fixes: https://github.com/coreos/rpm-ostree/issues/3344

daemon/donwload-pkgs: fix a wrong error return

---

docs/layering.md

- Call out that building the custom FCOS image is done on the local system
- Correct `strace --version` command and output
- Add a note about Quay marking repositories as private by default
- Fix the `rpm-ostree status` output given the Zincati service has been stopped

docs: clarify layering tutorial

---

src/app/libmain.cxx
src/app/rpmostree-builtin-initramfs-etc.cxx
src/app/rpmostree-builtins.h
tests/kolainst/destructive/initramfs-etc

This command has been released for a while now and apart from a few bugs
fixed early on, there hasn't been issues. I'd like to start recommending
it more often, and we have lots of experimental commands, so let's
promote this one.
Keep the old command working for now, but print a deprecation message.

Stabilize `initramfs-etc`

---

docs/container.md
docs/ex-replace.md
docs/experimental.md

docs: Match title and link for ex-container page
---
docs: Add page for `override replace --experimental`
Fixes: https://github.com/coreos/rpm-ostree/issues/3342

docs: Match title and link for ex-container page

---

Makefile-libpriv.am
Makefile-rpm-ostree.am
rust/src/client.rs
rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-builtin-cleanup.cxx
src/app/rpmostree-builtin-ex.cxx
src/app/rpmostree-builtin-rebuild.cxx
src/app/rpmostree-ex-builtins.h
src/app/rpmostree-pkg-builtins.cxx
src/libpriv/rpmostree-container.cxx
src/libpriv/rpmostree-container.h
tests/kolainst/destructive/container-image
tests/kolainst/kolainst-build.sh

This command reads treefile dropins in `/etc` and applies it to the
system. Only the OSTree container flow is supported for now. For the
client-side flow, see coreos#2326.
In the container flow, only `packages` is currently supported. But this
paves the way for supporting more derivation fields as well as making
currently "base" fields only become valid derivation fields too (by
promoting it from the `BaseComposeConfigFields` struct to
`TreeComposeConfig`).
What we're doing here is providing a "container" backend for derivation
treefiles, but coreos#2326 will provide a "client" backend which uses the core
more fully. But the inputs themselves are the exact same, hence
providing symmetry between the two flows. (See also discussions about
this in coreos/fedora-coreos-tracker#1054).
This …

Add `rpm-ostree ex rebuild` command

---

Makefile-libpriv.am
Makefile-rpm-ostree.am
rust/src/client.rs
rust/src/composepost.rs
rust/src/dirdiff.rs
rust/src/lib.rs
rust/src/main.rs
rust/src/sysroot_upgrade.rs
rust/src/treefile.rs
src/app/rpmostree-builtin-cleanup.cxx
src/app/rpmostree-builtin-ex.cxx
src/app/rpmostree-builtin-rebuild.cxx
src/app/rpmostree-ex-builtins.h
src/app/rpmostree-pkg-builtins.cxx
src/libpriv/rpmostree-container.cxx
src/libpriv/rpmostree-container.h
tests/kolainst/destructive/container-image
tests/kolainst/kolainst-build.sh

And then pass through `cargo fmt`.

rust: Fix `cargo clippy` warnings

---

docs/treefile.md
rust/src/lib.rs
rust/src/treefile.rs
src/libpriv/rpmostree-core.cxx

In some cases the usual mechanisms libdnf uses to establish the platform ID, and thus the platform module, fail. To cater for
this circumstance, and for any case where a user may want to override it, allow the platform module to be specified in the Treefile.
The specific case here is that Oracle Linux currently has the `system-release` and `base-module(platform:el8)` Provide entries on different packages. This has been raised with them and discussion is ongoing. The upshot though is that in a compose scenario we can't establish the platform ID from the package provides and we also lack `/etc/os-release` and `/usr/lib/os-release` and so the fallback mechanisms fail.

Allow the platform module to be specified in the Treefile.

---

packaging/rpm-ostree.spec.in

The container functionality is optional, but we might as well
be nice to people and add a recommendation.
Closes: https://github.com/coreos/rpm-ostree/issues/3286

packaging: Add `Recommends: skopeo`

---

.cci.jenkinsfile
ci/prow/fcos-e2e.sh

We only did the `next/next-devel` switch to pull in microdnf,
which is no longer needed.
At the current moment `next` is broken, and it's good we found
that, but let's be consistent with other things and build/test
against `testing-devel.

ci: Switch back to `testing-devel`

---

README.md

I'm actually doing this to sanity check the state of CI, but
hey I think we should mention the container stuff in the main
README.md now.

README.md: Link to ostree native container change

---

Cargo.lock
Cargo.toml
rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-builtin-rebuild.cxx

This is prep for work on https://github.com/coreos/rpm-ostree/issues/3364
---
treefile: Don't bail out if `/etc/rpm-ostree` doesn't exist
As it doesn't by default today, even in a container.
---
ex-rebuild: Print something in the case where we found no files
Now clearly we should have *much* more useful information here,
but this is a start.
---
treefile: Fix parsing of derived config fields
There may be a serde bug going on here.  But I think this is
fallout from https://github.com/coreos/rpm-ostree/pull/3341/commits/72a6a77640c70de0d2a7845b4816727356877bea
Basically we have `#[flatten]` in 3 places; in both the `base`
and `derive` structs, *and* the `base` struct has the `extra` member.
It seems that order matters here.  In order to parse the derive
config fields, it needs to be earlier …

Prep patches for supporting container overrides

---

docs/container.md

We've moved into a (somewhat more) official image location,
also start using `ostree container` instead of `rpm-ostree ex-container`
etc.

docs/container: Update for recent changes

---

rust/src/treefile.rs

I just changed a single use as a demo, but if we decide
to merge this I can do more of them.  (I want to avoid a conflict
fest though)
This will make it easier to migrate fields between the two structs.
Now, I think what we *really* want here is to flip everything around
here so that we have `DeriveTreefile` and `ComposeTreefile` that
include the base, and deref to that.
But that would be a much larger churn.
The status quo means we can't implement `Deref` to the derive.

treefile: Use `Deref` trait for something like inheritance

---

rust/src/composepost.rs
rust/src/cxxrsutil.rs

This is a followup to https://bugzilla.redhat.com/show_bug.cgi?id=2034360
The existing code that checks for `OSTREE_VERSION` has (I believe)
never actually worked at `compose tree` time because the version
mutation happens after the altfiles bits.
We recently started adding `/run/ostree-booted` in the legacy
compose path to try to aid this too.
But the code in the authselect `%post` for this is not really
less ugly or more maintanable than us doing the mutation too.
I think it *would* be cleaner if authselect's upstream code base
handled this by default.  But that seems like a more invasive
fix that requires some design changes.

composepost: Do replace `altfiles` in `/etc/authselect/nsswitch.conf`

---

src/libpriv/rpmostree-container.cxx

We added support for `repo-packages`, and it's only passing CI
because the test case *also* included `packages`.
I want to extend the declarative model to support more, so lift
this restriction.

`ex rebuild`: Drop check gating on `packages` key

---

ci/prow/Dockerfile.containerci
ci/prow/test-container.sh

This parallels our cosa build (which does a VM flow) and instead
directly overlays the production FCOS container image.
I am sure we are going to be doing more of this type of thing
as we adapt more of our CI to be really "container native".
My immediate motivation is being able to turn this on in Prow.
(That said...we do want to avoid building our binary twice, because
it's a bit expensive.  I need to investigate
https://docs.ci.openshift.org/docs/architecture/ci-operator/#building-artifacts
perhaps?

Add a `Dockerfile.containerci`

---

rust/src/composepost.rs

This reverts commit 769e688a1b600a6ce06deb0b1dc964559cfff63c.
Don't need this because the spec file will be fixed.

Revert "composepost: Do replace `altfiles` in `/etc/authselect/nsswitch.conf`

---

Cargo.lock
Cargo.toml
rust/src/bwrap.rs
rust/src/capstdext.rs
rust/src/client.rs
rust/src/cliwrap/cliutil.rs
rust/src/composepost.rs
rust/src/countme.rs
rust/src/ffiutil.rs
rust/src/utils.rs

And cap-std 0.24 and rustix 0.33.  Both of those are now
consistently imported via the re-export from cap-std-ext to
avoid version duplication/tearing.

Bump to cap-std-ext 0.24

---

rust/src/treefile.rs

treefile: Also error if derive is nonempty for client side
We don't support e.g. `override-remove` there...yet.
---
treefile: Fix naming of `assert_empty()`
The `non` part looks like a nonsequitur.
---

treefile: Two small patches

---

tests/kolainst/destructive/container-image

Older podman found in RHEL8 blows up without /etc/resolv.conf
which happens in our qemu path.
(I am running this test manually today; we do still need to pursue
at some point the model of running upstream tests in both FCOS
and RHCOS main CI too)

tests/container-image: Support old rhel8 podman

---

Cargo.lock

This avoids having two cap-std (important!) and gets a fix for
rhel8.

Bump to ostree-ext 0.6.3

---

docs/countme.md

- Update link to official DNF Configuration Reference documentation.
- Mention that the timer is now triggered on boot after 5 minutes and
then bi-weekly, with a random delay in both cases.
See: https://github.com/coreos/rpm-ostree/pull/3041

docs/countme: Update doc links and trigger frequency

---

src/libpriv/rpmostree-core.cxx
src/libpriv/rpmostree-importer.cxx

This contains two minor enhancements for the logic handling `/var`:
* when preparing scripts environment, stop relying on an implicit `/var/lib`
* when importing package content, log a debug message if spurious content is encountered/skipped

var: minor enhancements

---

rust/src/composepost.rs

Rawhide has moved the rpmdb to `/usr/lib/sysimage/rpm`, which is great!
FCOS composes started breaking because rpm now creates that directory:
https://github.com/coreos/rpm-ostree/issues/3397
We should be able to eventually flip our `_dbpath` macro with this (and
eventually much later once it hits RHEL, stop overriding the macro at
all). This will require some careful changes and testing.
But anyway we probably don't want to do this yet on f35 to match Fedora,
so we will want a transition mechanism; e.g. a `rpmdb-in-sysimage`
treefile knob.
For now just to unblock rawhide changes, let's remove the empty dir so
we can symlink and keep `/usr/share/rpm` as canonical. We'll rework once
we have the permanent solution.

composepost: Remove /usr/lib/sysimage/rpm dir before symlinking

---

configure.ac
packaging/rpm-ostree.spec.in

Various smaller bugfixes, but also adds `rpm-ostree ex rebuild` which is a step towards a declarative way to define packages to be layered on the OS.

Release 2022.2

---

docs/treefile.md
rust/src/lib.rs
rust/src/treefile.rs
src/app/rpmostree-compose-builtin-tree.cxx
tests/compose/test-misc-tweaks.sh

Builds on https://github.com/ostreedev/ostree-rs-ext/pull/235
Part of https://github.com/coreos/coreos-assembler/issues/2685
Note making use of this will require bumping ostree-ext here.

treefile: Add `container-cmd`

---

rust/src/lib.rs
rust/src/testutils.rs
src/daemon/rpmostree-package-variants.cxx
src/daemon/rpmostree-package-variants.h
src/lib/rpmostree-package-priv.h
src/lib/rpmostree-package.c
tests/kolainst/nondestructive/misc.sh

Prep for using this for ostree layer splitting work.

Add internal API to expose package variant list to Rust

---

src/libpriv/rpmostree-scripts.cxx
tests/kolainst/destructive/layering-local

This is an ugly bug; I noticed while doing an `ostree diff`
between two commits that `/run/ostree-booted` had been added.
This was because bwrap `--ro-bind-data` writes a persistent file,
and we weren't mounting `/run` as a tmpfs.
In general we've been potentially leaking state from any scripts
into the persistent commit!
We should change ostree to perhaps error out on this if `--bootable`
is specified or so.

scripts: Use a tmpfs for /run

---

src/libpriv/rpmostree-scripts.cxx
tests/kolainst/kolainst-build.sh
tests/vmcheck/test-layering-scripts.sh

The previous commit was not correct.  While we're here, add
a much stronger test that explicitly verifies the non-persistence
for `/run`, `/tmp`, and `/var/tmp`.

scripts: Fix tmpfs for `/run`

---

src/libpriv/rpmostree-rpm-util.cxx

`db version`: Switch to using SHA-256
Motivated by a RHEL-initiated effort to change or drop code using
SHA-1.
This code is old, has no unit tests, and I am not aware of anything
actually using it.  We could probably just delete it.
That said, let's take a middle ground of changing it to use SHA-256.
I believe the higher level logic here duplicates that of libdnf;
xref https://github.com/rpm-software-management/libdnf/issues/1373
We should be using that API anyways; but that's a larger change,
I'm just trying to get SHA-1 out for now.

`db version`: Switch to using SHA-256

---

src/app/rpmostree-builtin-cleanup.cxx

Return after cleaning up or we go back to try using D-Bus which fails in the container.
closes https://github.com/coreos/rpm-ostree/issues/3416

src/app/rpmostree-builtin-cleanup: return after cleaning up repo cache

---

rust/src/daemon.rs

It's more succinct and fixes the fact that we're not using `write_all`.
Fixes: #3406

rust/daemon: Use `replace_contents_with_perms`

---

Cargo.lock
rust/src/cliwrap.rs

Bump to cap-std-ext 0.24.1
Has the `O_TMPFILE` fallback we need.
---
cliwrap: Port to cap-std
Ongoing cleanup that helps me at least get a PR or two out
per day so I signal my continued existence.
---

Bump to cap-std-ext 0.24.1 && cliwrap: Port to cap-std

---

Cargo.lock
rust/src/initramfs.rs

The `subprocess` crate I think doesn't hold up to its weight.
In particular, I'd like to do more with cap-std, and our cap-std-ext
crate better integrates with the `std::process::Command`.
While here, I simplified things by having `bash` make the pipeline.
We aren't really gaining anything by avoiding it; there's no
command line args to worry about quoting.
What we really want is to factor this out into a crate, or maybe
just lower it to ostree-rs-ext.

initramfs: Port to cap-std, drop `subprocess` dependency

---

rust/src/bwrap.rs
rust/src/composepost.rs
rust/src/lib.rs
src/libpriv/rpmostree-importer.cxx
src/libpriv/rpmostree-postprocess.cxx
src/libpriv/rpmostree-scripts.cxx
src/libpriv/rpmostree-util.cxx
tests/compose/libbasic-test.sh

This reworks the exsisting workarounds for '/var/lib/alternatives'
and '/var/lib/vagrant', making the symlink generation conditional.
The 'alternatives' and 'vagrant' packages currently ship
some content under /var.
A proper ostree commit should come with a basically empty /var,
thus rpm-ostree needs to apply some ad-hoc tweaks here.
For these specific cases, workarounds are performed in two steps:
* their '/var/lib/foo' path-prefixes are translated to
'/usr/lib/foo'.
* '/var/lib/foo -> /usr/lib/foo' symlink entries are put in place
for compatibility purposes.

var: enhance workarounds for 'vagrant' and 'alternatives'

---

rust/src/bwrap.rs
rust/src/composepost.rs
tests/compose/libbasic-test.sh

Minor followup to https://github.com/coreos/rpm-ostree/pull/3387.

var: minor cleanup and basic checks for iptables alternatives 

---

rust/src/countme/cookie.rs
rust/src/live.rs
rust/src/utils.rs

utils: varsubst: Allocate initial string to around expected capacity
Just a drive by minor commit.
---
live: A bit of porting to cap-std
There's more here, just trying to keep up momentum.
---
countme: Port to cap-std
Keeping up porting momentum.
---

A few minor patches
